### ISSUE TITLE
Is possible to make SDL one header file and one source file?

### ISSUE THREAD

**Issue by bovacu** [libsdl-org/SDL#10024]
Hello, what I'd like to achieve is compressing all of the SDL header files into one header file and all of the source files into one source file, basically SDL.h and SDL.c and thats about it. The idea is to make it easier to integrate into an existing code base and compile everything together, no linked SDL lib, SDL to be compiled along side the other source code.

I've seen [this issue](https://github.com/libsdl-org/SDL/issues/9580) but I don't think we want exactly the same, and the comments are on a different line of what I want to achieve.

Is this possible or there is someone who knows how this could be achieved?

Thanks!

**Comment by madebr** [comment]
Creating a single header is possible, the current `SDL.h` does that in a way by including all other headers.

But combining all `.c` sources in a single `SDL.c` is (currently) not possible.
The various sources sometimes define conflicting static functions or types that have the same names.
C does not support anonymous C++ namespaces.

Configuring SDL with `-DCMAKE_UNITY_BUILD=ON`, you get an idea how big the problem is.

**Comment by bovacu** [comment]
Thank you so much for the answer. As you said "currently", does that mean there is a future plan on solving this problem?

**Comment by madebr** [comment]
No, there is no current plan.
But we have it in the back of our head to find out a good approach.
[Grouping sources by id](https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD_MODE.html) might be a good middle ground.
