### ISSUE TITLE
SDL 2.30.4 breaks Steam Deck gamepad on Arch Linux

### ISSUE THREAD

**Issue by sealedgo** [libsdl-org/SDL#10073]
Upon updating Arch Linux sdl2 package from 2.30.3 to 2.30.4 the Steam Deck gamepad no longer behaves properly, for example the KDE System Settings Game Controller page no longer displays activity and controller input inside Wine (Lutris build) games no longer work. The release notes say 2.30.4 is a stable bugfix release so I assume this is unexpected behaviour from commit 361cae0. I've downgraded back to 2.30.3 as a workaround.

If there are any issues with this bug report, or if more information is needed, please let me know.

**Comment by slouken** [comment]
@smcv, any ideas?

**Comment by smcv** [comment]
I don't have a Steam Deck, so I am not the right person to debug this.

The most relevant change in 2.30.4 is likely to be 361cae087495653286c523d664d2031e2f0dafe7, which fixes a known regression since 91f8b4de (between 2.28.x and the 2.29.1 prerelease), ValveSoftware/steam-for-linux#9571. My understanding of the regression is that when using Steam Input, Steam creates a virtual Xbox 360 controller (device ID 28de:11ff) corresponding to each physical controller that is being managed by Steam Input, and then instructs SDL and Proton (Steam's version of Wine) to ignore the physical controllers and read from the virtual controllers instead. Steam assigns controller names that encode the "slot" number, based on its UI for reordering controllers, and Proton parses the name to figure out how to assign the virtual controllers to the expected XInput slot.

This particularly matters for local multiplayer games that only support the 4 controllers in the first 4 XInput slots: if players have connected 4 external USB/Bluetooth gamepads (Xbox, Playstation, Switch) and do not want any player to be using the Deck's built-in gamepad, then they need to tell Steam to reorder the controllers so that the Deck's built-in gamepad is in slot 5 or later.

**Comment by smcv** [comment]
> the Steam Deck gamepad

With SDL 2.30.3, were you using the physical gamepad device directly; or were you running Steam in the background and letting it map the gamepad to a Steam Input virtual gamepad, and then having KDE System Settings talk to that?

If you have Steam installed (it doesn't need to be *running* for this, only *installed*), then running its diagnostic tool is likely to be helpful:

```
~/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-input-monitor --once
```

This enumerates all the raw HID and evdev input devices that SDL could potentially access, together with the information that SDL would use to identify them. Run this in the same situation where you were trying to use game controllers in KDE System Settings and Wine, whatever that is (but please also clarify what that situation is!)

It might also be helpful to compile SDL 2's `test/testgamecontroller.c` and try running that, to compare SDL's view of the game controllers with the diagnostic tool's. In some distributions this is packaged into a separate installable package (for example in Debian/Ubuntu, it can be found in `/usr/libexec/installed-tests/SDL2` if you install the `libsdl2-tests` package) but I think in Arch you would have to compile it yourself.

Wine is very complicated, and I don't know what patches (if any) Lutris applies to it, so it would be better to eliminate Wine from consideration to start with, and get the controller working with native Linux software first.

**Comment by smcv** [comment]
This could perhaps indicate that one build is accessing the device via raw HID, and the other is accessing it via evdev?

**Comment by smcv** [comment]
If it's that, then 793a0681 might be another commit to look at.

**Comment by slouken** [comment]
Can you build SDL3 and check what the output of testcontroller is? Switching from USB to hidraw shouldn't prevent the controller from working.

**Comment by slouken** [comment]
Actually, since this is SDL2, using test/testgamecontroller from 2.30.4 is probably an easier way to verify using the system installed SDL.

**Comment by slouken** [comment]
Oh, the USB driver is not used by default to prevent applications locking exclusive access to USB devices. If you want to override that behavior, try setting the environment variable SDL_HIDAPI_LIBUSB_WHITELIST=0

**Comment by slouken** [comment]
Okay, it sounds like it's working as intended. Thanks!
