### ISSUE TITLE
Compiling SDL on SPARC platform with GNU toolset should target correct CPU by default

### ISSUE THREAD

**Issue by joncox123** [libsdl-org/SDL#10098]
By default, when compiling SDL on a SPARC processor using the GNU toolset (e.g. gcc), it does not properly target the processor. For CISC processors like x86, it doesn't make a big difference whether the compiler specifically targets the architecture, but for true RISC processors like the UltraSPARC, it makes an enormous difference--like 10 to 100x, typically. By default GCC is so slow on SPARC that its virtually unusable. 

I suggest that this be handled in a couple ways. Keep in mind, I think this issue effects most true RISC processors (perhaps not Apple's ARM64 since its new enough and common enough that GCC probably specifically handles this situation under the hood. Also, most apps use XCode to compile for Apple chips). 

First, some sort of warning message should be written in `configure` or `CMake` when the Solaris platform is detected. For example, in SDL2-2.30, [Line 23](https://github.com/libsdl-org/SDL/blob/f08f458896d99f63b829c994623f8b9701d7eaf9/cmake/sdlplatform.cmake#L23) and an additional check and message that warns the user if compiling with GCC/GNU and not on an x86 platform. 

Second, if compiling with GCC/GNU and not on an x86 platform, add the following flag to CFLAGS by default: `CFLAGS="-mcpu=ultrasparc"`. This is documented in the [GCC manual](https://gcc.gnu.org/onlinedocs/gcc/SPARC-Options.html).

I suggest using the ultrasparc option, combined with a warning message, because realistically, nobody is likely to run SDL on anything older than an UltraSPARC from the 1990s. It is possible to use `-mcpu=native` instead, which tries to autodetect the architecture, but the library won't be as portable and the detection is likely to fail, according to the documentation.

**Comment by madebr** [comment]
Adding hardware specific flags like `-mcpu=...`, `-march=...`, `-mtune=...` does not belong in a build system.
In autotools land, users should configure their CFLAGS/CPPFLAGS correctly.
In CMake land, users should use an appropriate CMake toolchain file (and don't worry about `-mcpu=...` at all)

In the same vain I also don't think we should print a warning when no `-mcpu=...` command can be found in the CFLAGS.
It does not scale to other projects. You can't expect every OSS project to do these checks.

I think extending system-wide autotools/cmake rules makes more sense.

**Comment by smcv** [comment]
> Adding hardware specific flags like `-mcpu=...`, `-march=...`, `-mtune=...` does not belong in a build system.

I agree. With my Debian hat on, we have recurring problems with upstream projects (in the same position as SDL) saying something like "well *obviously* nobody will run my software on an x86 without SSE" or "well *obviously* nobody will run my software on an ARM without NEON" and hard-coding their own `-mcpu` or `-march` which is higher than the baseline that Debian has chosen to make its minimum for a particular architecture, resulting in binaries that crash with an illegal instruction on baseline CPUs.

Choosing the baseline is something to be done by OS builders, not by individual upstream projects that become part of your OS or are compiled as addons to your OS. It should be possible to configure gcc *at the time that you build gcc* to have a particular baseline of your choice (definitely true on x86 and ARM, probably equally true on SPARC), so that all software that you build with that gcc binary will automatically assume that baseline unless forced to behave otherwise by options like `-march`. I would suggest doing that.

**Comment by icculus** [comment]
Sounds like this is a WONTFIX. Those that are building can configure/cmake with CFLAGS="-mwhatever" and get what they want.
