### ISSUE TITLE
Some notes on recent keyboard changes

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10165]
Just copying this in here so it isn't lost; we can't reopen a merged PR. It can be closed one way or another once @slouken has considered it.

--ryan.

> I would like to discuss the commit f78779024 of two days ago.
>
> Although it broke some code in Exult, it presented a consistent picture of providing a single `event.key` value for the various mod states of the alphabetic ( but NLS compliant ), numeric ( including numeric keypad ), arrow and page movements, insert, suppress and return keys, that is, the keys essential to any game. It was sensitive to NumLock, that is fine.
>
> Thus Exult received SDLK_4 when I pressed the 4 key either on the main keyboard or on the numlocked numeric keypad, Exult received SDLK_M when I pressed the M key ( right of L on a french keyboard ), whatever mod key I may been holding.
>
> - So I find somewhat pitiful that you reverted to handling the numeric keypad separately by > yesterday's commit b948d1446.
> - I have another problem, the single `event.key` value regardless of the mod keys does not work ( in both commits ) on the main numeric keys on my french keyboard. I get `event.key` as SDLK_2 when I press the main 2 key, but `é` when Shift is held ( which is by the way the _opposite_ of the entered characters ). I should get SDLK_2 whether or not Shift is held, correct ? Here is a trace of a ( slightly enhanced ) `checkkeys` :
>
> When I press unshifted main 2, I get the correct SDLK_2 `event.key` :
> ```
> INFO: Key pressed :  raw 0x03, scancode 31 = 2, keycode 0x00000032 = 2, shifted keycode 0x000000E9 = é, modified keycode 0x000000E9 = é,  modifiers: (none)
> INFO: INPUT Text (\xc3\xa9): "é"
> ```
> When I press shifted main 2, I get the unexpected `é` `event.key` :
> ```
> INFO: Key pressed :  raw 0x03, scancode 31 = 2, keycode 0x000000E9 = é, shifted keycode 0x00000032 = 2, modified keycode 0x00000032 = 2,  modifiers: LSHIFT
> INFO: INPUT Text (\x32): "2"
> ```
> In these messages,
> - the `shifted keycode` come from `SDL_GetKeyFromScancode(event->scancode, SDL_KMOD_SHIFT & event->mod)`,
> - the `modified keycode` come from `SDL_GetKeyFromScancode(event->scancode, event->mod)`.
>
> If I prevent SDL to handle the french numkeys with `SDL_KEYCODE_OPTIONS=none`, I get `keycode 0x000000E9 = é` when I press the main 2 key with or without Shift.

_Originally posted by @Dragon-Baroque in https://github.com/libsdl-org/SDL/issues/10156#issuecomment-2205783573_

**Comment by slouken** [comment]
@Dragon-Baroque, I'm glad you like the direction we were going with the new keyboard changes!

That the French numeric keycode changed based on shift state was a bug, fixed in 61441c2be.

The keyboard event keycodes are defined as the character generated by pressing the key with no modifiers. Changing that definition caused issues with a number of applications that needed that behavior.

It sounds like you want the behavior where the keycode is the character that is generated by the pressing the key, including modifiers, and mapping the numpad into the main keyboard. That can easily be added in your application by setting SDL_HINT_KEYCODE_OPTIONS to "hide_numpad" and then calling SDL_GetKeyFromScancode() in your event handler:
```c
SDL_SetHint(SDL_HINT_KEYCODE_OPTIONS, "hide_numpad");
...
switch (event.type) {
    case SDL_EVENT_KEY_DOWN:
    {
        SDL_Keycode key = SDL_GetKeyFromScancode(event.key.scancode, event.key.mod);
        ...
    }
    break;
}
```
The ability to do this is a new feature in SDL3, and I'm glad it's useful to you in Exult.
