### ISSUE TITLE
Vulkan Renderer on Android

### ISSUE THREAD

**Issue by captain0xff** [libsdl-org/SDL#10208]
Please add support for the SDL_renderer vulkan backend on android. Currently, if I try to use the vulkan renderer on android (by patching the cmake file), it gives `Failed to create renderer: vkCreateAndroidSurfaceKHR failed: VK_ERROR_NATIVE_WINDOW_IN_USE_KHR`.

**Comment by icculus** [comment]
I'm assuming we set this up for OpenGL ES by default, which is causing the problem. @1bsyl, do you happen to know? And if you know, do you happen to know if the fix is easy?

**Comment by captain0xff** [comment]
Most probably no. I will try with it and report back.

**Comment by captain0xff** [comment]
I can try to attach a debugger and find the exact function causing the crash but I am not using android studio so not sure how to debug from the commandline.

**Comment by slouken** [comment]
@danginsburg, any idea why VULKAN_AllocateDescriptorSet() would crash on Android?

**Comment by danginsburg** [comment]
> @danginsburg, any idea why VULKAN_AllocateDescriptorSet() would crash on Android?

Running with Vulkan validation should hopefully reveal what the issue is.  Off the top of my head, I don't know.  Maybe vkCreateDescriptorPool failed first?  Although if that it happened this should also occur:

```
SDL_SetError("[Vulkan] Unable to allocate descriptor pool vkCreateDescrptorPool: %s", SDL_Vulkan_GetResultString(result));
```
Maybe we are hitting some limit on the implementation with descriptor counts in a descriptor pool?  You could try setting `SDL_VULKAN_MAX_DESCRIPTOR_SETS` to 1 or some other low number, although I'm not aware of an implementation with such low limits.

**Comment by flibitijibibo** [comment]
On the subject of `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR` we ran into this with SDL_gpu, since the window won't necessarily know what backend is being used the default check here is causing problems:

https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L260

Should it be more like the Metal check below where `Vulkan && Android` assumes Vulkan by default?

**Comment by captain0xff** [comment]
@danginsburg that patch fixed the issue. Thank you everyone for looking. Now, both the GPU api and the renderer vulkan backend are working on Android. 
@slouken So, can I create a PR with that patch and the other required changes to enable the backend on Android?

**Comment by slouken** [comment]
> @danginsburg that patch fixed the issue. Thank you everyone for looking. Now, both the GPU api and the renderer vulkan backend are working on Android.

Great!

> @slouken So, can I create a PR with that patch and the other required changes to enable the backend on Android?

Yes, but please don't change the default. OpenGL ES is still more widely supported on mobile devices than Vulkan.

Thanks!
