### ISSUE TITLE
SDL_Log does not write to Emscripten console

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10410]
It will write to the JavaScript console, but not the actual text area that displays stdout and is visible by default with the standard index.html template.

**Comment by Semphriss** [comment]
I believe I found the issue: the Module JS object in the Emscripten HTML template separates stdout and stderr on the JS side; stdout is the `print`  kew and stderr is `printErr`. Since I believe SDL_Log always prints to stderr, and the Module object in template.html only has a `print` and no `printErr`, everything sent to stderr is dropped.

For SuperTux, I made it so stdout shows in white and stderr shows in red; I'll do something similar for the recently-merged template file in a PR shortly.
