### ISSUE TITLE
SDL_CopyDirectory, SDL_RenameDirectory

### ISSUE THREAD

**Issue by luppichristian** [libsdl-org/SDL#10507]
On win32 the current file system seems to not support copying and renaming of directories.
These functions would be very useful in a filesystem.

**Comment by luppichristian** [comment]
Also functions names in the filesystem are kinda misleading because some functions are called SDL_##Path but only work on files.

I think the following naming convention would be better:
- SDL_###Path if the function works both on directories and files
- SDL_###File if the function only works on files.
- SDL_###Directory if the function only works on directories.

**Comment by slouken** [comment]
> Also functions names in the filesystem are kinda misleading because some functions are called SDL_##Path but only work on files.
> 
> I think the following naming convention would be better:
> 
> * SDL_###Path if the function works both on directories and files
> * SDL_###File if the function only works on files.
> * SDL_###Directory if the function only works on directories.

I think that's the intent. Which functions don't follow this convention?

**Comment by icculus** [comment]
> I think that's the intent. Which functions don't follow this convention?

I rechecked all the existing functions and I think we're solid on this (please reopen if I'm wrong!).

SDL_RenamePath _will_ rename directories, if it doesn't, it's a bug. SDL_CopyDirectory isn't something we're going to add, because it's a whole can of worms, and apps that want to do it can do it with the existing APIs.
