### ISSUE TITLE
SDL3 Request: SDL_LogOutputRaw (fputs equivalent)

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#10603]
For custom log formatting, one can use `SetLogOutputFunction`. However, after creating the log string, there is still the question of actually outputting it. SDL currently has no function to simply send the data to the right stream (`stdout`, `stderr`, or `OutputDebugString`) without modifying it. This means the application has to rewrite the same logic all over again (check `IsDebuggerPresent()`, convert to UTF-16, etc.).

The closest alternative is to use `SetLogPriorityPrefix` to remove prefixes, and then get the function pointer to `SDL_LogOutput` through `GetLogOutputFunction`. But this function modifies the input by [adding a newline at the end of the string](https://github.com/libsdl-org/SDL/blob/5dc5b4b83c57b88963e4087435da3451b830f3fb/src/SDL_log.c#L582). And this workflow is not very intuitive, to say the least.

What can be done is add a function `SDL_LogOutputRaw` (similar to [`SDL_LogOutput`](https://github.com/libsdl-org/SDL/blob/5dc5b4b83c57b88963e4087435da3451b830f3fb/src/SDL_log.c#L526)) that takes only a string as argument, and outputs it to the appropriate stream without any modification (besides unicode conversion). 

```c
void SDL_LogOutputRaw(const char *message)
```

The `SDL_LogOutput` function can simply be rewritten to use `SDL_LogOutputRaw` to prevent code duplication. This will also separate out the code responsible for formatting from code responsible for outputting.

**Comment by slouken** [comment]
So I went through several iterations of this, and it turns out that depending on the platform, the output messages might have to be self-contained, so treating them as separate lines of text is the correct cross-platform way to treat output messages. I implemented SDL_OutputDebugString(), which turned out to be entirely redundant to SDL_LogDebug(), since the default prefix is the empty string.

In the end, I just added a function to make it easy to get the default output function so you can use it from your own logging functions.

**Comment by slouken** [comment]
> Now, the issue (as I understand it) is that some platforms don't do logs in the traditional "single-buffer-of-text" way. I'm myself not sure what the right way is to deal with this situation (as evident by my cludgy PR).

That's correct. One some platforms (Apple, Android, etc.) you can't build up a message as you send output. The right way to do this is to build up the message in the app, and then send it all at once.
