### ISSUE TITLE
GPU Metal: Remove calloc usages

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL#10655]
calloc doesn't work correctly with ARC so we'll have to manually initialize struct fields on the Metal backend.

**Comment by TheSpydog** [comment]
To correct my hastily-written statement while I was out of the office: I actually don't know for certain if calloc works as expected.

Objective-C ARC [is complicated](https://clang.llvm.org/docs/AutomaticReferenceCounting.html). It tries to automatically insert calls to `objc_retain`/`objc_release`, but in my experience that's not 100% reliable for ids contained in structs. Having been bit by this in the past, I tend to opt for explicit `whatever->myID = nil` calls, but that may not be strictly necessary.

If anyone reading this is more familiar with the particulars of how ARC deals with `id<>` handles in structs, I'm all ears.

(cc @jansedivy)

**Comment by TheSpydog** [comment]
In light of https://github.com/libsdl-org/SDL/commit/8edb901724a8b22f244a26d787a6a0e1778c4eff which adds calloc calls to fix a variety of crashes due to ARC releasing references on garbage struct memory, I'm closing this.

In general, we should avoid memset/memcpy and friends that directly modify the bits without the compiler explicitly knowing to insert objc_retain/release calls, but calloc is an exception since it's just zero-initializing -- nothing exists to retain or release.
