### ISSUE TITLE
SDL_GetGPUDriver should return a string

### ISSUE THREAD

**Issue by TheSpydog** [libsdl-org/SDL#10682]
Currently `SDL_GetGPUDriver` returns an enum for the driver. We should change that to a `const char *` to match the other `SDL_Get*Driver` functions.

**Comment by Akaricchi** [comment]
`SDL_GetGPUDriver` is very handy in a switch() to determine which shader format to use. Having to match strings in order to do that would kind of suck. If we want to make that change, I think there should be something like `SDL_GPUShaderFormat SDL_GetShaderFormatsForGPUDevice(SDL_GPUDevice *device)`

**Comment by slouken** [comment]
> If we want to make that change, I think there should be something like `SDL_GPUShaderFormat SDL_GetShaderFormatsForGPUDevice(SDL_GPUDevice *device)`

I think that's a great idea. We should add SDL_GetNumGPUDrivers() and SDL_GetGPUDriver(int index) as well.

**Comment by flibitijibibo** [comment]
Agreed - that makes it a lot easier to check for supported drivers rather than having to map the enum to another enum manually.
