### ISSUE TITLE
No way to set function to use for aligned allocations, and arguments for free

### ISSUE THREAD

**Issue by maia-s** [libsdl-org/SDL#10680]
`SDL_stdinc.h` provides the `SDL_Get[Original]MemoryFunctions` and `SDL_SetMemoryFunctions` to get and set the functions SDL calls for `malloc`, `calloc`, `realloc` and `free`, and it also provides `SDL_aligned_alloc` and `SDL_aligned_free` to allocate and free explicitly aligned memory, but there's no way to get/set what's used for the aligned alloc/free. `SDL_aligned_alloc` uses `SDL_malloc` internally and manually overallocates to provide the required alignment, but a custom allocator may have a more efficient way to do this.

Also, it would be helpful for some allocators if the free functions also took the allocated size as an argument (and the alignment, for aligned free), but I understand that's a departure from the way standard C does things (and allocators that need this can work around it by storing the size and alignment as part of the allocation, at the cost of some extra memory). I wanted to mention it though. (In Rust, allocators equivalents of the free and realloc functions take an argument containing the size and alignment of the allocation)

**Comment by slouken** [comment]
Is this a requirement for your use case or just a nice to have? I'd like to avoid blowing out the memory functions with lots of variations that might need to be considered by people replacing allocators.

**Comment by maia-s** [comment]
It's just a nice to have.

**Comment by slouken** [comment]
Okay, I'll mark it as not-planned for now. Let me know if it becomes important.

**Comment by supahero1** [comment]
Bump. I have an allocator that by default guarantees all allocations be aligned to the power of 2 greater to or equal to the allocation size. This means aligned allocations are extremely easy to write. Moreover, getting rid of the "size" argument in free() is devastating in results - all allocations would need to be twice as big, and smaller ones (1, 2, 4 bytes) even larger (eg. for 1 byte it would need to allocate 16, reserve 8 for size and keep the 1 byte of data). I would love to use it with SDL.

Rust is an interesting topic, because they have the new, "good" (I would say) style of allocations, but it's only possible to use them and use your own allocator with them in the rust programs that you compile. You can't recompile the compiler with it, which is a bummer, because LLVM still has the old memory functions, without realloc/free with size. I guess they have a massive infrastructure and changing free calls everywhere would be an actually insane thing to do and would surely cause an outage and introduce bugs, but here I don't think it would be that big of a problem. I would be willing to volunteer some.
