### ISSUE TITLE
Remove UWP support

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL#10724]
As per this discussion: https://github.com/libsdl-org/SDL/pull/10717#issuecomment-2332274919

UWP was deprecated 4 years ago and UWP submissions are no longer supported on any platform. The toolchain is actively bitrotting. I don't think it's a good idea to continue supporting it.

**Comment by sezero** [comment]
Yes please. See, e.g. [my original comment in #6570](https://github.com/libsdl-org/SDL/issues/6570#issuecomment-1325572169)

**Comment by icculus** [comment]
If nothing is using it in general and publishing with it is becoming impossible, I say let's dump it.

I will definitely say that for every subsystem we added in SDL3, I would look into how to do something with Win32, and then find out you had to do a totally different way, in a weird variant of C++, with WinRT, so I won't miss it _at all_.

**Comment by icculus** [comment]
I've started working on a PR for this.

**Comment by icculus** [comment]
There are like a million things like this:

```c
#if defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINRT) || defined(SDL_PLATFORM_GDK)
```

...can these just be `#ifdef SDL_PLATFORM_WINDOWS` now?

**Comment by thatcosmonaut** [comment]
GDK is still used to deploy on Xbox.

**Comment by icculus** [comment]
Yeah, but doesn't it define the generic SDL_PLATFORM_WINDOWS macro, too?

**Comment by icculus** [comment]
Oh, it _doesn't_!

**Comment by slouken** [comment]
Yes, it does.

**Comment by slouken** [comment]
```c
#if defined(_WIN32) || defined(SDL_PLATFORM_CYGWIN)
#define SDL_PLATFORM_WINDOWS  1    /* Win32 api and Windows-based OSs */

/* Try to find out if we're compiling for WinRT, GDK or non-WinRT/GDK */
#if defined(_MSC_VER) && defined(__has_include)
#if __has_include(<winapifamily.h>)
#define HAVE_WINAPIFAMILY_H 1
#else
#define HAVE_WINAPIFAMILY_H 0
#endif

/* If _USING_V110_SDK71_ is defined it means we are using the Windows XP toolset. */
#elif defined(_MSC_VER) && (_MSC_VER >= 1700 && !_USING_V110_SDK71_)    /* _MSC_VER == 1700 for Visual Studio 2012 */
#define HAVE_WINAPIFAMILY_H 1
#else
#define HAVE_WINAPIFAMILY_H 0
#endif

#if HAVE_WINAPIFAMILY_H
#include <winapifamily.h>
#define WINAPI_FAMILY_WINRT (!WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP))
#else
#define WINAPI_FAMILY_WINRT 0
#endif /* HAVE_WINAPIFAMILY_H */

#if HAVE_WINAPIFAMILY_H && HAVE_WINAPIFAMILY_H
#define SDL_WINAPI_FAMILY_PHONE (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)
#else
#define SDL_WINAPI_FAMILY_PHONE 0
#endif

#if WINAPI_FAMILY_WINRT
#define SDL_PLATFORM_WINRT   1
#elif defined(_GAMING_DESKTOP) /* GDK project configuration always defines _GAMING_XXX */
#define SDL_PLATFORM_WINGDK 1
#elif defined(_GAMING_XBOX_XBOXONE)
#define SDL_PLATFORM_XBOXONE    1
#elif defined(_GAMING_XBOX_SCARLETT)
#define SDL_PLATFORM_XBOXSERIES 1
#else
#define SDL_PLATFORM_WIN32      1
#endif
#endif /* defined(WIN32) || defined(_WIN32) || defined(SDL_PLATFORM_CYGWIN) */

/* This is to support generic "any GDK" separate from a platform-specific GDK */
#if defined(SDL_PLATFORM_WINGDK) || defined(SDL_PLATFORM_XBOXONE) || defined(SDL_PLATFORM_XBOXSERIES)
#define SDL_PLATFORM_GDK    1  <--- These are all defined inside the WIN32 block above
#endif
```

**Comment by icculus** [comment]
Lack of indentation on these things kills me. So we _should_ change these to just check for SDL_PLATFORM_WINDOWS then.

**Comment by slouken** [comment]
Yeah, I think that's a new thing for SDL3 that hasn't been rolled through yet.

**Comment by icculus** [comment]
PR is live. I'm going to bed, so I'll leave y'all to push the merge button if you want.

**Comment by edo9300** [comment]
For what I know uwp is still the only real way the Xbox homebrew scene is still actively producing programs, I don't know if the things changed on that end

**Comment by icculus** [comment]
I don't know if they have other options, but we're going to leave it in SDL2 in any case.

**Comment by Sergio0694** [comment]
I know it's a bit late now (only saw this now), but the arguments for making this PR were completely misguided, and based on information that is entirely incorrect:
- UWP in general is **not** deprecated
- There are no plans to ever deprecate it
- UWP support specifically on Xbox is **only** deprecated for GDK
- UWP apps and games on Xbox are still fully supported when targeting the System partition (ie. non GDK).
- The Microsoft Store also still accepts UWP submissions targeting Xbox as well

UWP still is and will continue to be by far the easiest way for indie devs to publish games on Xbox (as you don't need an NDA nor the GDK at all), and it's the only way to publish apps on Xbox. And yes you can use DX12 on UWP on Xbox just fine, both for UWP apps and games, it's fully supported.

It's really sad to see all of this being removed just based on some comments repeating inaccurate information found who knows where. Even the official Microsoft docs still say that UWP is fully supported for production.

**Comment by icculus** [comment]
Okay, how did we get from "submissions are no longer supported on any platform" and "the toolchain is actively bitrotting" to "this platform is alive, supported and vital"?

I don't like supporting UWP for several technical reasons, but if it's still a serious going concern, we should revert all of this and also figure out what bugs we closed as WONTFIX because of this.

If it's not, I'm fine with leaving it alone.

**Comment by Perksey** [comment]
I probably wouldn't say it's a vital platform, but it's certainly one for which there will be interest (Xbox Creators Program still has no pathway outside of UWP, and while ID@Xbox is the normal route for publishing on Xbox, getting concept approval may be prohibitive/a deterrent for hobbyists).

UWP is still getting security updates and some QoL improvements (just a couple of months ago Microsoft officially ported .NET 9 to work on UWP, which while not relevant here does show that there is non-trivial work being done in orbit of the UWP space). It is true that MS are trying to move people off UWP, with the official Microsoft position being:
- For GUI apps, UWP will be supported forever but you should use WPF or WinUI3 where possible (both of which Win32 toolchains, obviously this bullet point isn't relevant here but I'm including it for completeness)
- For Xbox games, UWP is community-supported only in the context of GDK but remains acceptable for submissions targeting the system partition and remains the **only officially supported target** for Xbox Creators Program.

Public GDK is not intended for production use (at least as per its "no license required for learning" language), and GDKX obviously requires licensing that UWP does not, which is why it can't be used for the Xbox Creators Program - a license-free program. It is highly likely that the Xbox Creators Program will be disbanded before it ever gets a non-UWP development story (as it stands, neither are happening).

I agree, UWP is not the easiest to support and likely does create lots of awkward maintenance issues. It is possible that the backend can be ported to e.g. WRL or whatever the most recommended way to use WinRT is these days (cc @ahmed605) to try and cut as much of the problematic bits out as possible. I appreciate as I'm typing out that sentence I realise why there may be distain for investigating further support, but ultimately it's just down to whether the valid scenarios for it are worth supporting.

Just want to make sure those decisions are being made for the right reasons with the most up-to-date information :)

**Comment by SternXD** [comment]
> I know it's a bit late now (only saw this now), but the arguments for making this PR were completely misguided, and based on information that is entirely incorrect:
> 
> * UWP in general is **not** deprecated
> * There are no plans to ever deprecate it
> * UWP support specifically on Xbox is **only** deprecated for GDK
> * UWP apps and games on Xbox are still fully supported when targeting the System partition (ie. non GDK).
> * The Microsoft Store also still accepts UWP submissions targeting Xbox as well
> 
> UWP still is and will continue to be by far the easiest way for indie devs to publish games on Xbox (as you don't need an NDA nor the GDK at all), and it's the only way to publish apps on Xbox. And yes you can use DX12 on UWP on Xbox just fine, both for UWP apps and games, it's fully supported.
> 
> It's really sad to see all of this being removed just based on some comments repeating inaccurate information found who knows where. Even the official Microsoft docs still say that UWP is fully supported for production.

Yeah, my comment is also a bit late. And this really hurts my development of apps and now recently my fork of PCSX2 for the Xbox One/Series X|S.
