### ISSUE TITLE
SDL3: Mutex seems to be broken

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10754]
I am getting a hang and an assertion failure when starting my application (see appended screenshot). I did not see this problem before.

<img width="1773" alt="mutex" src="https://github.com/user-attachments/assets/6979d84d-a966-4775-8d11-6db08f49bf4e">

Update: Only happens when building with debug enabled

**Comment by dimhotepus** [comment]
The problem here is that when background mutex lock fails in DEBUG mode SDL shows assertion UI dialog.
But it means UI API call which is not allowed in background mode and catched by your Main Thread Checker.

I think in Release mode mutex lock fails, too. You just do not see the error, so need to fix anyway.

See https://github.com/libsdl-org/SDL/blob/1ba99c53d48ec1f1f7c58b20326fc0c964ce5aa2/src/thread/pthread/SDL_sysmutex.c#L79-80:
```
const int rc = pthread_mutex_lock(&mutex->id);
SDL_assert(rc == 0);  // assume we're in a lot of trouble if this assert fails.
```

Without actual error code ```rc``` hard to tell what's going wrong. Let's go to https://linux.die.net/man/3/pthread_mutex_lock for pthread_mutex_lock error codes:
```
EINVAL
The mutex was created with the protocol attribute having the value PTHREAD_PRIO_PROTECT and the calling thread's priority is higher than the mutex's current priority ceiling.

EINVAL
The value specified by mutex does not refer to an initialized mutex object.

EAGAIN
The mutex could not be acquired because the maximum number of recursive locks for mutex has been exceeded.

EDEADLK
The current thread already owns the mutex.
```

Guess you get either ```EAGAIN``` or most likely ```EDEADLK```. Could you check thread doesn't acquire mutex recursively?

**Comment by andreasgrabher** [comment]
Thank you very much for the explanation! It was EINVAL caused by using the mutex after destroying it. There was bad order in the un-initialisation routine.
