### ISSUE TITLE
GPU: User Clip Planes? (gl_ClipDistance / SV_ClipDistance)

### ISSUE THREAD

**Issue by rabbit-ecl** [libsdl-org/SDL#10814]
User clipping has uses for cut-through views, planar mirrors, planar portals, etc.
Always supported by D3D11+ & Metal. Requires shaderClipDistance on Vulkan, which is not always supported on Android.
Optional feature in WebGPU.
Relevant WebGPU discussion: https://github.com/gpuweb/gpuweb/issues/390

**Comment by TheSpydog** [comment]
This is tricky because we currently don't have (and don't really _want_) a system for handling optional hardware features. If SDL_GPU supports a feature, it should be universally supported across all backends. At least within reason; e.g. texture format support varies wildly so we do have queries for that.

In this particular case, though, since we don't control the shader format, there's nothing we can really do to stop clients from using SV_ClipDistance and friends on non-Vulkan backends, making it a bit of a portability footgun.

I suppose we could require the `shaderClipDistance` feature for Vulkan, but that cuts down the supported percentage of Android devices down to ~66% just for the sake of allowing you to use a particular feature in your shaders. Seems like not a great tradeoff? Would need to do some more investigation on the devices that lack support for this feature. If it's only old devices, then I think it'd be acceptable. But if it's affecting even recent devices from a particular hardware vendor, that might be problematic.

**Comment by rabbit-ecl** [comment]
Looking over gpuinfo a bit, it looks like Mali GPUs have really poor support, but Adreno & PowerVR always support this. So the distinction isn't so much old-vs-new but vendor-vs-vendor, which is a bit unfortunate.

**Comment by thatcosmonaut** [comment]
Supporting Android is so fun!

**Comment by rabbit-ecl** [comment]
Yeah the Android graphics stack has been kind of a disaster since forever.

**Comment by thatcosmonaut** [comment]
I'm always basically one bad day away from saying we don't support Android with SDL GPU since I imagine terrible broken drivers are going to cause us lots of pain anyway.
