### ISSUE TITLE
SDL_GetUserFolder path separator

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#10956]
This note in SDL_GetUserFolder's docs:

```
 * The returned path is guaranteed to end with a path separator ('\\' on
 * Windows, '/' on most other platforms).
```

Should we drop this and say "the path separator is always '/', which happens to also work on Windows" and change the implementation?

It seems unlikely we're ever going to see a new path separator on some future platform; macOS Classic used ':' but this seems settled at this point...?

**Comment by slouken** [comment]
100% yes.

**Comment by Semphriss** [comment]
IIRC, I deliberately decided to use the platform-native separator, because Windows returns its paths with backslashes and I thought that mixing forward slashes and backslashes would be poor practice if consistency or OS-native notation is expected.

Since appending the path separator is done on platform-specific implementations, it is neither more nor less complex to use a forward slash or a backslash; only the character itself must be changed at `src/filesystem/windows/SDL_sysfilesystem.c:337`.

I'm not sure what would be gained using a forward slash (given that there are backslashes elsewhere in the path anyways), but the only potential loss is ease of use with theoretical, deprecated APIs that still don't support forward slashes, so I don't really lean one way or the other.

**Comment by slouken** [comment]
Good point, I forgot that we return paths with backslashes in them. That means we probably want to support either.

**Comment by icculus** [comment]
If we were to do this, we would have the Windows-specific code convert the entire path to use '/' before returning it, not just the last character.

The benefit is that a cross-platform app that uses this API can then take the string and append more paths that use '/' to it on any platform, and SDL can continue not to have an API or macro to tell you the platform's path separator character.

Although, now that I'm thinking about it, it's not like win32 can't mix and match '/' and '\\' in a single path, so the app can probably just append '/' paths regardless of platform.

Okay, I talked myself out of it, we can close this.  :)

**Comment by quimmedes** [comment]
Hi, I just would like to add that windows also use "/" forward slash as flags like chkdsk.exe /r /f /b and for example a path with C:/Windows/System32/chkdsk /r /f will not work in prompt command but works in windows PowerShell. sorry if it's not useful;

**Comment by icculus** [comment]
Yeah, let's just leave this alone.
