### ISSUE TITLE
SDL3, macOS: Mouse events have wrong coordinates

### ISSUE THREAD

**Issue by andreasgrabher** [libsdl-org/SDL#10978]
With the recent revision of SDL3 mouse coordinates are no longer reported correctly on my Retina display. I am using `SDL_ConvertEventToRenderCoordinates()`. This worked correctly until recently.

**Comment by slouken** [comment]
@icculus, related to the logical size changes?

**Comment by paked** [comment]
Yes, noticed this behaviour changed yesterday when I re-built SDL3 from master yesterday. I think.

My flow is this, on Mac OS 14.6.1, Macbook Pro 14 inch:

1. Create window with SDL_WINDOW_HIGH_PIXEL_DENSITY
2. SDL_SetRenderScale(4)
3. When an event fires...
4. Before updating to yesterdays main: `SDL_ConvertEventToRenderCoordinates` seems to represent coordinates within my scaled window size (no additonal processing needed to render a point onto the screen in the correct place)
5. After updating to yesterdays main: I need to divide `SDL_ConvertEventToRenderCoordinates` by my scale factor (4) in order to have the event coordinates match the effective mouse position.

To be honest, I'm not actually sure I'm even doing this flow right!

**Comment by slouken** [comment]
Yeah, this is a bug, we’ll fix it!

**Comment by icculus** [comment]
I intentionally took the scale out of this calculation, since this is meant to be used for changing how drawing is done and might be changed multiple times during a frame, as opposed to logical presentation, which is meant to change how the view is perceived.

I can put this back if this was a wrong choice on my part. @slouken, which do you think?

@andreasgrabher, is this what you're seeing too? Is it a scale issue for you, too?

**Comment by andreasgrabher** [comment]
Without taking the scale into account this function is useless for me. I would replace it by this (which unfortunately does not seem to work while in fullscreen):

```
static void SDLGui_ScaleMouseButtonCoordinates(SDL_MouseButtonEvent *event)
{
	int width, height;
	SDL_GetWindowSize(sdlWindow, &width, &height);

	event->x *= pSdlGuiScrn->w / width;
	event->y *= pSdlGuiScrn->h / height;
}

```

**Comment by icculus** [comment]
I'm not confident this API _should_ take into account viewport and scale, but I don't feel strongly about it.

#11043 restores the previous behavior of these APIs, and documents what states it operates on.
