### ISSUE TITLE
GPU: Don't rely on SDL_GetWindowSizeInPixels() for swapchain size 

### ISSUE THREAD

**Issue by Akaricchi** [libsdl-org/SDL#10982]
#10958 removed the width and height out parameters from `SDL_AcquireGPUSwapchainTexture()`. IIRC the arguments for removal were:

* Out parameters are ugly.
* The size should always match `SDL_GetWindowSizeInPixels()`, so clients can just query that.
* It incidentally fixed #10924. `SDL_AcquireGPUSwapchainTexture()` would sometimes report 0-size with a non-null texture, which broke the Render backend's faux backbuffer creation logic.

However, I don't think this is a good solution for a few reasons:

* `SDL_GetWindowSizeInPixels()` has some limitations. In particular, it must be called on the main thread on macOS (see #10977). Clients can theoretically work around this by handling the `SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED` event and caching the size. However, it is not obvious why that should be done, and it unnecessarily complicates the application logic.
* `SDL_GetWindowSizeInPixels()` doesn't have direct access to the pixel size on some backends and must infer it from the logical window size and content scale. This affects at least Windows, X11, macOS, and Emscripten. Notably, the generic fallback code (used by X11) and Emscripten's implementation disagree on the rounding method (`ceilf` vs `lroundf` respectively), which may be a bug in either of those.
* It makes sense to return the size from `SDL_AcquireGPUSwapchainTexture()` as it should have direct access to that information. It can even be used in a test to validate that it does indeed match `SDL_GetWindowSizeInPixels()`.

To reduce the number of out parameters, I propose to make `SDL_AcquireGPUSwapchainTexture()` fill out a struct like this:

```c
typedef struct SDL_GPUSwapchainTextureInfo {
    SDL_GPUTexture *texture;    // may be NULL due to backpressure
    Uint32 width;
    Uint32 height;
} SDL_GPUSwapchainTextureInfo;
```

However, we should definitely fix the root cause of it sometimes reporting 0 size, or at least work around it. The workaround may be as stupid and simple as discarding the texture in `SDL_gpu.c` if the reported size is bad — at the very least, it makes sense to validate it there.

**Comment by flibitijibibo** [comment]
Trying to think of reasons it would return 0 for swapchain size and the best that I can remember is when a window is minimized, but I don't think that returns a texture at all... we should try to determine the cause of that before doing anything else.

**Comment by flibitijibibo** [comment]
Ran through everything in Discord and we can avoid this by using the renderer's existing cached sizes:

https://github.com/libsdl-org/SDL/blob/main/src/render/SDL_render.c#L2553

SDL_Render shouldn't have to query the display for this. That should avoid the issues outlined above and also fix #10977.

**Comment by Akaricchi** [comment]
> Ran through everything in Discord and we can avoid this by using the renderer's existing cached sizes:

Looks like that function spoofs `renderer->main_view.pixel_[wh]` with the 'logical' size? I'm not sure I understand that code correctly, but if I do, we can't use that for the backbuffer. We want the *actual* swapchain size there.

Besides, this only fixes Render. If the main author of SDL_GPU managed to make this mistake, then clients inevitably will, too. I still believe this is a footgun design. At the very least SDL should validate that `SDL_GetWindowSizeInPixels()` is called from the main thread only, due to the macOS limitations, or work around the macOS issue by caching the values.

We went over this on discord already, but I remain unconvinced that `SDL_GetWindowSizeInPixels()` is *necessarily guaranteed* to match the real swapchain size. The Vulkan backend [seems to clamp it to implementation limits](https://github.com/libsdl-org/SDL/blob/d2094bd0a248d03384b9fe01b09456cb6f063272/src/gpu/vulkan/SDL_gpu_vulkan.c#L4496), and D3D11 and Metal use neither `SDL_GetWindowSizeInPixels()` nor the `SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED` values when creating their swapchains. I don't understand the opposition to returning the size at all.

**Comment by thatcosmonaut** [comment]
In my opinion, out params should be for data that is expected to actually vary on every call. Yes, the window technically can change size whenever, but in normal application scenarios the swapchain will not be changing sizes constantly and I don't think we should imply that it does. The swapchain _only_ resizes when the window resizes, and SDL already informs the client when this occurs. The client is expected to handle window size changes appropriately everywhere else in their application so I'm not sure why we should make an exception for GPU. Presumably the client could want to make all kinds of changes on window resize, like recreating render textures, and it's awkward to defer those changes to swapchain acquisition time anyway.

@slouken Any thoughts?

**Comment by flibitijibibo** [comment]
As far as bugs go this is now good; we now do what we _should_ do which is use events for size, only falling back to SizeInPixels as a last resort. Both are functional and their limitations are documented.

The only detail left is whether we want to hand values back from the swapchain API. I'm torn, personally: apps should really _really_ handle size events but it's not a guarantee, and SizeInPixels is potentially expensive compared to just returning swapchain extent values. Both are valid arguments for/against so really it's down to which is _safer_, and I couldn't say whether it's better or worse.

**Comment by thatcosmonaut** [comment]
> As far as bugs go this is now good; we now do what we _should_ do which is use events for size, only falling back to SizeInPixels as a last resort. Both are functional and their limitations are documented.

Slight correction - the events are watched by the backend to know that the swapchain should be recreated - it then uses GetWindowSizeInPixels to determine the new size.

> The only detail left is whether we want to hand values back from the swapchain API. I'm torn, personally: apps should really _really_ handle size events but it's not a guarantee, and SizeInPixels is potentially expensive compared to just returning swapchain extent values. Both are valid arguments for/against so really it's down to which is _safer_, and I couldn't say whether it's better or worse.

All we're doing right now is just calling SizeInPixels anyway. The best practice is for the client to handle the size change event and update their render state accordingly.

**Comment by kg** [comment]
Thorny potential issue that came up while looking at this, maybe someone knows for certain whether it's not a possibility:

Window resizing and size queries are very complex on each operating system, often involving modal loops, synchronous RPCs to a window manager, etc.

If a game spends 16-33ms waiting for a swapchain image acquire to complete (feasible with vsync active; iirc Vulkan allows these operations to block and they can block on D3D too), it seems possible to me that when you finally get your swapchain image back, its size will not match the size of the actual window, if the user is currently resizing it with their mouse or other input device.

The window manager will have sent you resize messages, but SDL's event pump won't have seen them yet.

Is SDL designed to prevent this hazard by reporting the 'most recent observed size based on messages that have flowed through the event loop', so that SizeInPixels will report the size that was last seen by the backend and thus the size of the swapchain image? Or is it possible that SizeInPixels will report the *current* size of the window, perhaps by querying the window manager and getting an immediate response? I dug around and can't find any firm assertions that i.e. Win32's APIs for querying window dimensions are based on the last processed sizing message or not.

This potential hazard only comes up with swapchain textures since their size is controlled by the internals, and it can get out of sync with the claimed window, and to me it suggests an outparam that reports how big the swapchain texture is. The size being wrong would normally only produce a frame of glitched rendering, but if there are i.e. backing arrays or mapped/locked surfaces, it could lead to user code dereferencing an invalid pointer/otherwise overrunning a buffer.

If not for this issue the worst case outcome is just single-frame glitches during resize due to the swapchain being 'out of date', and when I last tested this, vulkan and dxgi presentation handle this more or less adequately (you get some garbage pixels in the empty space or the swapchain texture gets stretched to the window dimensions).

**Comment by thatcosmonaut** [comment]
I hadn't really considered the case where Acquire is blocking for a significant amount of time, which as pointed out is very likely to happen in VSYNC present mode. The swapchain texture is the only one that the client doesn't control directly so I'm starting to think @Akaricchi is right and we should just hand the size back to the client in the acquire call.
