### ISSUE TITLE
SDL3: The "SDL_VIDEODRIVER" environment variable should be supported as a fallback

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/SDL#11115]
Users are trained to use `SDL_VIDEODRIVER=wayland` for native Wayland support.
Renaming that env var to `SDL_VIDEO_DRIVER` breaks this.
As SDL3 is ABI-stable now it's probably too late to undo the renaming, but if the `SDL_VIDEO_DRIVER` env var isn't set it could (should!) still fall back to `SDL_VIDEODRIVER`.

Probably same for SDL_AUDIODRIVER/SDL_AUDIO_DRIVER.

I briefly looked at the code and am not sure how to best implement this: Hardcode the case in `SDL_Get_Hint()` and friends (`if(result == NULL && strcmp(name, SDL_HINT_VIDEO_DRIVER) == 0) result = SDL_getenv("SDL_VIDEODRIVER");`), or somehow handle this in the callers of `SDL_GetHint(SDL_VIDEO_DRIVER)`?
The latter is probably harder to do correctly if I want to respect hint priorities..

By the way, the (public) Hint API is missing a getter for a hints priority.

**Comment by DanielGibson** [comment]
Implementation of this: https://github.com/libsdl-org/SDL/pull/11120

Not 100% sure if this is the best way to implement this, but I think doing this at all (before the first official) SDL3 release *does* make a lot of sense, and at least my solution is simple ;)

**Comment by p2ndemic** [comment]
The old environment variables SDL_VIDEODRIVER and SDL_AUDIODRIVER, even for someone like me without programming experience, look ugly and annoying. That’s why I don’t mind if they are completely removed in SDL3. Sooner or later, users and developers will adopt the new variables - the key point is to create a dedicated section in the documentation for SDL3 environment variables, so that search engines and AI can properly index it.

At the moment, if you search in google for "sdl environment variables", the very first result still points to the SDL 1 documentation:
[https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html?utm_source=chatgpt.com)

Thank you

**Comment by icculus** [comment]
(The above comment has moved to #13827, where we will track the issue.)
