### ISSUE TITLE
SDL3 Ray Tracing API

### ISSUE THREAD

**Issue by Qubrick** [libsdl-org/SDL#11147]
I think there should be a single API for hardware-accelerated ray tracing on all hardware ray tracing supported platforms.

The idea might similar to The-Forge Ray Query API.
https://github.com/ConfettiFX/The-Forge/blob/master/Common_3/Graphics/Interfaces/IRay.h

For shader, they put all states in a single compute shader file. This is only possible for their own cross-platform shader language called FSL.
https://github.com/ConfettiFX/The-Forge/blob/master/Examples_3/Unit_Tests/src/16_Raytracing/Shaders/FSL/RayQuery.comp.fsl

**Comment by flibitijibibo** [comment]
The policy for GPU is that features that do not already exist in the API were intentionally omitted due to heavy fragmentation in the current landscape of platform implementations - pull requests implementing support for all supported backends (including console but excluding D3D11) will be considered, otherwise the answer will be "no."
