### ISSUE TITLE
Simple Window on iMac 27" not working

### ISSUE THREAD

**Issue by rcman** [libsdl-org/SDL#11307]
Hello,
I know this is not a show stopper. I'm running Ubuntu 24.10 on my 27" iMac and also on my PC. I have the code creating a basic window. It works on the PC but not on the iMac. There error is it can't open the display on the iMac. 

I've compiled SDL3 on both systems. 
Thanks
Franco

**Comment by icculus** [comment]
I would recommend:

- Try one of the example apps, since most are 50 to 150 lines of code for a complete program, and see if it works on the iMac. I'd try `examples/renderer/01-clear/clear.c`.
- If it does work, then post your code here, if you can, and we'll see if there's an issue we can notice in it.
- If it doesn't work, it might be helpful to use a prebuilt SDL and see if it works better. If so, somehow your copy of SDL was misbuilt in some way or another, and we can help track that problem down.
- If we're still stuck at that point, explicit error messages (like, "I called SDL_GetError() right after this SDL function returned a failing result and _this is the exact string it gave me_") can be very helpful, because we can usually look at the exact detail that failed inside SDL with that info.

**Comment by rcman** [comment]
Well, unfortunately my iMac Died. So sorry to say I will not be able to give you more info.
Thanks for getting back to me.
RC

**Comment by icculus** [comment]
Okay, I'm closing this for now, but if the Mac comes back from the dead, let me know!
