### ISSUE TITLE
compilation errors if include *<SDL3/SDL_vulkan.h>* before *<vulkan/vulkan.hpp>*

### ISSUE THREAD

**Issue by feelamee** [libsdl-org/SDL#11328]
The problem in compilation errors if  *<SDL3/SDL_vulkan.h>* was included before *<vulkan/vulkan.hpp>*.
It reproducing only with vulkan C++ api, but not C.
<details>
  <summary>compilation output</summary>

  ```cpp
  In file included from /home/missed/code/sdl-bug-with-vulkan-cpp-api/build/_deps/vulkan-headers-src/include/vulkan/vulkan.hpp:8681,
                 from /home/missed/code/sdl-bug-with-vulkan-cpp-api/build/_deps/vulkan-headers-src/include/vulkan/vulkan_raii.hpp:11,
                 from /home/missed/code/sdl-bug-with-vulkan-cpp-api/main.cpp:3:
  /home/missed/code/sdl-bug-with-vulkan-cpp-api/build/_deps/vulkan-headers-src/include/vulkan/vulkan_handles.hpp:2613:46: error: conversion from ‘int’ to ‘VkSurfaceKHR_T*’ in a converted constant expression
   2613 |   struct CppType<VkSurfaceKHR, VK_NULL_HANDLE>
        |                                              ^
  /home/missed/code/sdl-bug-with-vulkan-cpp-api/build/_deps/vulkan-headers-src/include/vulkan/vulkan_handles.hpp:2613:46: error: could not convert ‘0’ from ‘int’ to ‘VkSurfaceKHR_T*’
   2613 |   struct CppType<VkSurfaceKHR, VK_NULL_HANDLE>
        |                                              ^
        |                                              |
        |                                              int
  ```
</details>

As I explored, `VK_NULL_HANDLE` defined to `0` insted of `nullptr` in *<vulkan/vulkan_core.h>*
```cpp
#ifndef VK_DEFINE_NON_DISPATCHABLE_HANDLE
    #if (VK_USE_64_BIT_PTR_DEFINES==1)
        #if (defined(__cplusplus) && (__cplusplus >= 201103L)) || (defined(_MSVC_LANG) && (_MSVC_LANG >= 201103L))
            #define VK_NULL_HANDLE nullptr
        #else
            #define VK_NULL_HANDLE ((void*)0)
        #endif
    #else
        #define VK_NULL_HANDLE 0ULL
    #endif
#endif
#ifndef VK_NULL_HANDLE
    #define VK_NULL_HANDLE 0
#endif
```
Because *<SDL3/SDL_vulkan.h>* defined `VK_DEFINE_NON_DISPATCHABLE_HANDLE`.

I also made a [repo](https://github.com/feelamee/sdl-bug-with-vulkan-cpp-api) with minimal repoducible example.

So, I'm not sure that this is an SDL bug. But, probably, we need to provide workaround for this.
I'm ready to make PR, if someone will guide me to right solution/fix.

**Comment by Dv-Senna** [comment]
The issue is due to `VK_NULL_HANDLE` being defined to `0`, which can't be implicitly converted to a pointer in C++. By looking at the way `VK_NULL_HANDLE` is defined, you have to not define `VK_DEFINE_NON_DISPATCHABLE_HANDLE` before including `vulkan/vulkan_core.h`, or else, `#define VK_NULL_HANDLE 0` is forced. The issue is that `SDL_vulkan.h` need `VK_DEFINE_NON_DISPATCHABLE_HANDLE` and define it itself, but it's never undef. In #11361 , I added an `#undef` at the end of `SDL_vulkan.h` for `VK_DEFINE_NON_DISPATCHABLE_HANDLE` and one for `VK_DEFINE_DISPATCHABLE` (didn't check if it can work without the second one, but it's safer to add it anyway).

**Comment by Dv-Senna** [comment]
After check, `#undef VK_DEFINE_DISPATCHABLE` is not necessary to allow it to compile with gcc 14.2.1
