### ISSUE TITLE
In-tree builds don't work

### ISSUE THREAD

**Issue by godofecht** [libsdl-org/SDL#11360]
Surely there's a way to get this working... could I get some guidance?

I and my users require in-tree building for portability and convenience.

```
if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_CURRENT_BINARY_DIR)
  message(FATAL_ERROR "Prevented in-tree build. Please create a build directory outside of the SDL source code and run \"cmake -S 
```

**Comment by icculus** [comment]
We could probably add a flag to override that, but it just means it should be built in a subdirectory, or an external build directory, not the root of the SDL source tree.

**Comment by madebr** [comment]
I think in-tree builds were forbidden as a safety precaution.

You can build your project with an in-source build, and still build SDL3 as an out-of-tree build
[`add_subdirectory`](https://cmake.org/cmake/help/latest/command/add_subdirectory.html)

by doing the following:
```cmake
add_subdirectory(external/SDL3 external/SDL3-build)
```

The first argument is the path to the (relative) source tree, the second argument is the (relative) binary tree

**Comment by godofecht** [comment]
Gotcha. I ended up doing exactly that.

**Comment by madebr** [comment]
f543faf83 allows in-tree builds again.
But please try to avoid doing it.

**Comment by slouken** [comment]
Why are we enabling in-tree builds again?

**Comment by madebr** [comment]
Why was it disabled in the first place?

I modified the cmake script such that it will not overwrite SDL's source files,
and added `.gitignore` rules such that generated files will not be marked untracked.

CMake always generates a `CMakeCache.txt` and `CMakeFiles`, even when the build fails. So you cannot do an out-of-tree build after doing an in-tree build because CMake sees the `CMakeCache.txt` in the SDL source tree.
This confuses beginners.

**Comment by slouken** [comment]
Hmm, it looks like it was that way to mirror the automake build system. That was done that way because building for different architectures would pick up old cache values from previous builds. I imagine this would have the same problem, without the ability to easily remove the build directory to start fresh?

**Comment by madebr** [comment]
Cleaning up from an in-tree build of SDL2 (where it is forbidden) is easy: just remove `CMakeCache.txt` and the `CMakeFiles` directory.

In current SDL3, it will be a bit harder.
Cleaning up from a downloaded SDL3 archive will be hard. But I think that's not a problem: just remove everything and extract the SDL3 source archive again.

Cleaning up from an in-tree git SDL3 build, can be done by running `git clean`.
Eventually add `-n` to do a dry run, add `-i` for interactive mode, and add `-x` to also remove files present in `.gitignore`.
