### ISSUE TITLE
Erroneous relative mouse input injected when alt tabbing

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#11422]
Observed in CS2, reproduced in a modified version of WoodenEye 008. 

Not sure what is the root cause of this, but when alt tabbing SDL seems to inject a large sum of relative motion from mouse id 0, resulting in you ending up aiming at the floor or turning horizontally 90 degrees after alt tabbing.

**Comment by Slartibarty** [comment]
Just a heads up, this may be a regression that was introduced recently because I've been running my game on a 6+ month old version of SDL3 for a long time, and only after updating a few weeks ago did this start happening to me, it might be worth tracking down the original commit that caused this before merging the PR.

**Comment by slouken** [comment]
> Just a heads up, this may be a regression that was introduced recently because I've been running my game on a 6+ month old version of SDL3 for a long time, and only after updating a few weeks ago did this start happening to me, it might be worth tracking down the original commit that caused this before merging the PR.

Can you git bisect it?

**Comment by Slartibarty** [comment]
> @Slartibarty could it be this one?

Yep that's it, reverted back to the commit before this one and it's fine again.
