### ISSUE TITLE
SDL audio and Emscripten

### ISSUE THREAD

**Issue by viglietta** [libsdl-org/SDL#11435]
The default audio buffer sizes computed by the function GetDefaultSampleFramesFromFreq in SDL_audio.c seem to be too small for Emscripten apps. For example, with a sample fequency of 22050 Hz, the default audio buffer has 512 frames, which causes noticeable occasional audio stuttering even in the simplest Emscripten app. Doubling or even quadrupling this buffer size greatly reduces the stuttering.

(Also, keep in mind that if the ScriptProcessorNode interface is being used, the number of sample frames of the buffer must be a power of 2 in the range 256--16384.)

**Comment by icculus** [comment]
Are you actually seeing SDL3 choose 512 sample frames? Since Emscripten doesn't specify the audio device format during init, SDL gives it a default sample rate of 44100, so it won't get less than 1024 frames.

I _do_ need to add code to deal with the sample rate being unexpectedly high when we finally discover it during device open, but I'm just making sure there isn't a code path that results in 512 frames that I'm misunderstanding.
