### ISSUE TITLE
SDL_StopTextInput crashes on macOS when called from another thread

### ISSUE THREAD

**Issue by squidbus** [libsdl-org/SDL#11447]
Using SDL 3, calling `SDL_StopTextInput` from another thread causes the following crash on macOS:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[HIRunLoopSemaphore wait:] has been invoked on a secondary thread; the problem is likely in a much shallower frame in the backtrace'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff808cc6f4e __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff8087b0f12 objc_exception_throw + 62
	2   Foundation                          0x00007ff809ca6c41 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 362
	3   HIServices                          0x00007ff80f4d993a -[HIRunLoopSemaphore wait:] + 400
	4   HIToolbox                           0x00007ff814884580 __62-[IMKInputSessionXPCInvocation_Modern invocationAwaitXPCReply]_block_invoke + 100
	5   HIToolbox                           0x00007ff8148850fc +[IMKInputSession_Modern withActivity:performActions:] + 934
	6   HIToolbox                           0x00007ff814886a56 -[IMKInputSession_Modern deactivate] + 1118
	7   HIToolbox                           0x00007ff814816180 IMKInputSessionDeactivate + 36
	8   HIToolbox                           0x00007ff81481567a DeactivateInputMethodInstance + 58
	9   HIToolbox                           0x00007ff8147ffd88 utDeactivateAllSelectedIMInDocIterator + 82
	10  CoreFoundation                      0x00007ff808c1aba8 CFArrayApplyFunction + 62
	11  HIToolbox                           0x00007ff8147ffd27 utDeactivateAllSelectedIMInDoc + 132
	12  HIToolbox                           0x00007ff8147fb25f MyDeactivateTSMDocument + 381
	13  HIToolbox                           0x00007ff8147fb399 DeactivateTSMDocument + 75
	14  AppKit                              0x00007ff80c6b6c02 -[NSTextInputContext deactivate] + 246
	15  AppKit                              0x00007ff80c4dff2d +[NSTextInputContext currentInputContext_withFirstResponderSync:] + 357
	16  AppKit                              0x00007ff80c4f107b -[NSView _setWindow:] + 711
	17  AppKit                              0x00007ff80c51c774 -[NSView removeFromSuperview] + 212
	18  shadps4                             0x0000020000a41d0f Cocoa_StopTextInput + 127
	19  shadps4                             0x0000020000a01c7b SDL_StopTextInput_REAL + 75
	20  shadps4                             0x0000020000013974 _ZN5ImGui3SdlL18PlatformSetImeDataEP12ImGuiContextP13ImGuiViewportP20ImGuiPlatformImeData + 84
	21  shadps4                             0x00000200006c5795 _ZN5ImGui8EndFrameEv + 597
	22  shadps4                             0x00000200006c70d7 _ZN5ImGui6RenderEv + 55
	23  shadps4                             0x0000020000010d59 _ZN5ImGui4Core6RenderERKN2vk13CommandBufferEPN6Vulkan5FrameE + 41
	24  shadps4                             0x00000200005f75dc _ZN6Vulkan14RendererVulkan7PresentEPNS_5FrameE + 156
	25  shadps4                             0x00000200004279cf _ZN9Libraries8VideoOut14VideoOutDriver4FlipERKNS1_7RequestE + 47
	26  shadps4                             0x000002000042840b _ZN9Libraries8VideoOut14VideoOutDriver13PresentThreadENSt3__110stop_tokenE + 379
	27  shadps4                             0x00000200004291a1 _ZNSt3__114__thread_proxyB8ne180100INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Libraries8VideoOut14VideoOutDriverC1EjjE3$_0NS_10stop_tokenEEEEEEPvSD_ + 81
	28  libsystem_pthread.dylib             0x00007ff808b73253 _pthread_start + 99
	29  libsystem_pthread.dylib             0x00007ff808b6ebef thread_start + 15
)
libc++abi: terminating due to uncaught exception of type NSException
```

Would like to ask for one of the following:
* For SDL to handle dispatching the appropriate calls to the main thread to avoid these issues.
* For SDL to document that this function (and possibly related input functions) should be called from the main thread.

**Comment by slouken** [comment]
@ocornut, it's true that the text input enable/disable calls can only be made on the main thread. Is this an expected use case for imgui?

**Comment by ocornut** [comment]
Core Dear ImGui itself doesn't have any restrictions, but I assume that selected backends may do (I don't think it has been researched exhaustively).
The SDL3 backend also uses `SDL_SetClipboardText()`/`SDL_GetClipboardText()` which also has requirement of being called from main thread.

---

My intuition given the callstack and the fact that clipboard function may already be called anytime by dear imgui, is that @squidbus is already running **a vast majority of imgui code in the main thread**, and intuitively wanted to call `Render()` in their "render thread" (and that one calls `EndFrame()` as a convenience if it hasn't been done previously).

`Render()` really doesn't do much, it just bundle some mostly-ready internal CPU-side data and would be perfectly fine and logical to call it in the main thread when you are done with your imgui stuff. So you can call `EndFrame()` and `Render()` in main thread imho. It is probably your actual "submit to gpu" processing that you want to keep in your render thread, but that's not what ImGui::Render() does.
(either way, if you hypothetically called Render() in your render thread, which is frankly not super valuable for imgui but may be ok, you would need some sync or swap so that the ImDrawData being prepared then submitted to GPU isn't overwritten by next frame ImGui code.).

---

I don't know how many SDL calls are constrained to main thread.
In the event we wanted to support running ImGui with SDL backend in a different thread (which is not what OP needs I believe) we could probably come with convoluted workarounds in the backend, e.g. querying clipboard ahead of time in main thread if there isn't a SDL provided by SDL. But both SDL and GLFW have that that specific restriction for clipboard functions and nobody really reported it or seemed to care in a decade.

FYI a vast majority of backend/platform specific stuff called by Dear ImGui are done in NewFrame()/EndFrame() calls, the exception being currently:
- io.Platform_GetClipboardTextFn(), io.Platform_SetClipboardTextFn() (for which SDL3 has a threading requirement)
- io.Platform_OpenInShellFn() (which is has a default impl by core imgui and doesn't has threading requirement)
- io.Platform_OnChangedViewport() (which is user hook to detect DPI change when appending to a window in a different monitor, rarely used and if ever does processing that doesn't interact with the OS/platform).

Everything else is done in NewFrame/EndFrame/Render functions, so I think the user can manage.

**Comment by squidbus** [comment]
Reading through your explanation, I think its reasonable enough to require to run these things on the main thread, what I would ask then is just on the SDL and ImGui side that it be more documented what should be run on the main thread.

**Comment by slouken** [comment]
I've documented the main thread requirements of SDL video and input functions and added SDL_RunOnMainThread() so you can easily run code on the main thread.

@ocornut, the patch @squidbus made seems reasonable, generalized to use SDL_RunOnMainThread() on all platforms.
