### ISSUE TITLE
Remove GPU renderer?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#11468]
We’ve used the GPU renderer as a smoke test of the API, and a way to get testing coverage across lots of different systems, and that has gone well, however there are some downsides that make me wonder if we should remove it or make it non-default before release.

1. GPU has removed D3D11 support. We switched to the D3D11 renderer by default in SDL3 because there were performance issues with D3D12 and D3D11 gave us the widest coverage on customer systems.
2. The GPU renderer has bugs that would need to be fixed before shipping and it seems like nobody is interested in fixing them. YUV support and Vulkan orientation come to mind offhand.
3. Another reason we switched to D3D11 for the renderer is that it’s needed for transparent window support. That turns out to be a popular feature and it’s not available in the GPU renderer.
4. Anyone wanting to ship anything on Android using the 2D renderer is going to want to use the OpenGL ES renderer for better customer device coverage.
5. In the future the GPU API is likely to be less stable than the existing, basically frozen, renderers, making it more risky to ship as the default renderer. As an anecdote we had to disable the GPU renderer in Steam because it was crashing on some customer systems during initialization.
6. If we have a GPU renderer, people will continually be asking to expose more advanced features in the 2D API, and as @thatcosmonaut  is fond of saying, you can write a better sprite batcher in an afternoon and a cup of tea using the GPU API.

Right now we’re in this halfway point where people want to use the 2D API plus shaders, and it feels like that’s a great project but would be better done starting fresh and targeting just the GPU API.

@libsdl-org/a-team, thoughts?

**Comment by Akaricchi** [comment]
I'm willing to add the missing features e.g. YUV and fix some bugs if it's going to accelerate a stable SDL3 release, but I don't mind the renderer being outright removed. The only reason I wrote it was because it was a requirement to upstream GPU, and I wanted to help make it happen faster. I don't care about the 2D renderer API at all; in fact I kinda wish it didn't exist.

> Another reason we switched to D3D11 for the renderer is that it’s needed for transparent window support. That turns out to be a popular feature and it’s not available in the GPU renderer.

This would be nice to have as a feature of GPU in general. It has been implemented for Vulkan in #10654, but @thatcosmonaut didn't want to merge it until it works on all backends.

> GPU has removed D3D11 support. We switched to the D3D11 renderer by default in SDL3 because there were performance issues with D3D12 and D3D11 gave us the widest coverage on customer systems.

For what it's worth, D3D11 has been removed because the vast majority of systems has Vulkan drivers these days, so maybe that coverage should be re-evaluated. In my opinion the GPU renderer over Vulkan is currently in much better standing than the Vulkan renderer. The latter had serious rendering bugs in render target tests last time I tried it, and is significantly slower. The Vulkan backend is also much faster than D3D12 and the old D3D11 backend, which is why it's preferred on Windows.

> If we have a GPU renderer, people will continually be asking to expose more advanced features in the 2D API, and as @thatcosmonaut is fond of saying, you can write a better sprite batcher in an afternoon and a cup of tea using the GPU API.

> Right now we’re in this halfway point where people want to use the 2D API plus shaders, and it feels like that’s a great project but would be better done starting fresh and targeting just the GPU API.

The bit about the sprite batcher is true, but what constitutes a good sprite batcher is also very use-case-specific. A generic solution will always be flawed. In my opinion, people who want to use shaders should really just use the GPU API directly.

**Comment by icculus** [comment]
I don't want it _removed_ but it's fine with me if it isn't the default at this point.

We aren't there yet for several reasons, but eventually I would like to remove the Metal, D3D12 and Vulkan backends in favor of the GPU backend, as a massive simplification.

**Comment by flibitijibibo** [comment]
I'm also in favor of moving it to the bottom of the bootstrap list - a lot of the problems listed aren't fundamental flaws as much as they are features we just haven't gotten to yet; it should be possible for GPU to support transparent windows, YUV support, fast D3D12 support, and so on, but they got put to the side while we focused on the core stuff that _every_ application was going to need.

The FNA team finished what they set out to do, and we're hoping it's a good enough foundation for other SDL stakeholders to make use of it, invest in it, and add what they need so that Render (for example) doesn't have to do effectively the same work FNA3D and others were for the same (or worse) results.

**Comment by slouken** [comment]
> I don't want it _removed_ but it's fine with me if it isn't the default at this point.
> 
> We aren't there yet for several reasons, but eventually I would like to remove the Metal, D3D12 and Vulkan backends in favor of the GPU backend, as a massive simplification.

Since we're ABI locked, this would involve having the GPU renderer expose the device and texture interop features that are currently supported by the respective renderers. I'm all for that, but it sounded like that wasn't likely to happen.

**Comment by icculus** [comment]
> Since we're ABI locked, this would involve having the GPU renderer expose the device and texture interop features that are currently supported by the respective renderers. I'm all for that, but it sounded like that wasn't likely to happen.

This (and Andreas's multithreading concerns) are both examples of what I mean, plus just a lot of stress testing. We'll (probably) get there eventually, and if we do, we can yank the duplicates, but that's distant future stuff atm.
