### ISSUE TITLE
Missing gameinput.h header while compiling on Windows (Github CI specific)

### ISSUE THREAD

**Issue by coornio** [libsdl-org/SDL#11487]
Likely a side-effect of the last few updates going on, and someone will likely patch it soon, but in case it went unnoticed, here's an excerpt from github ci:

```
  ...
  SDL_gameinputjoystick.c
  SDL_dinputhaptic.c
...project-path...\build\_deps\sdl-src\src\joystick\gdk\SDL_gameinputjoystick.c(29,10): error C1083: Cannot open include file: 'gameinput.h': No such file or directory [...project-path...\build\_deps\sdl-build\SDL3-shared.vcxproj]
  (compiling source file '../sdl-src/src/joystick/gdk/SDL_gameinputjoystick.c')
```

**Comment by slouken** [comment]
How are you building SDL_gameinputjoystick.c on Linux? That's not supposed to be included in the build.

**Comment by coornio** [comment]
I'm.. not. I don't use anything gamepad related in my project. Some other file likely is including it. My cmakelist basically has the user check out the latest branch (my attempt a specific commit was failing in a prior attempt, may well have been a config error, but I digress) and compile it along with my project. 
Here's the full log from github's ci on the linux build in case you'd like to have a wider look:
[logs_30989057505.zip](https://github.com/user-attachments/files/17792303/logs_30989057505.zip)

**Comment by slime73** [comment]
That log looks like a Windows build, in which case it's probably this CI issue: https://github.com/actions/runner-images/issues/10980 & https://github.com/actions/runner-images/issues/10978

**Comment by coornio** [comment]
Oh my, I must have been tired indeed yesterday, having clicked the same link so many times and my brain just assumed "Linux" for some reason ... I will update the title/comments accordingly, my bad :(

**Comment by ChillerDragon** [comment]
I was playing around with a github pipeline a bit and at some point it started failing with this error

```
    SDL_xinputjoystick.c
    Generating Code...
    Compiling...
    SDL_gameinputjoystick.c
    SDL_dinputhaptic.c
  C:\setupsdl\16eb5b3e346096a6b19ce66a13b7e1ed19bdccf05d6144aace18b2c8fbb98373\source\src\joystick\gdk\SDL_gameinputjoystick.c(29,10): error C1083: Cannot open include file: 'gameinput.h': No such file or directory [C:\setupsdl\16eb5b3e346096a6b19ce66a13b7e1ed19bdccf05d6144aace18b2c8fbb98373\build\SDL3-shared.vcxproj]
    (compiling source file '../source/src/joystick/gdk/SDL_gameinputjoystick.c')
```

Using this https://github.com/libsdl-org/setup-sdl

To be precise I was playing around with [this](https://github.com/libsdl-org/SDL_image/blob/b1c8ec7d75e3d8398940c9e04a8b82886ae6163d/.github/workflows/main.yml) and removed a few things. Which uses setup-sdl and that one failed for **Windows (MSVC)** while **Windows (mingw64)** was still passing.

The rename commit https://github.com/libsdl-org/SDL/commit/b5b868044fedc83959626fc433aa1a74e2c60200 should not be problematic right? Because windows is supposed to be case insensitive.

It is a bit annoying to debug because you never know what the github actions black box provides you with. And some [caching](https://github.com/libsdl-org/setup-sdl/blob/c1e5c0a9e419019e8408c4588c9fe931a626c1c7/src/main.ts#L644) also trolled me. But maybe we can just wait this out and microsoft will fix it on their end :shrug:
The include should just work on any windows machine thats running [May 2019 update or newer](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/input/overviews/input-overview).

**Comment by madebr** [comment]
The actions log of https://github.com/libsdl-org/SDL/issues/11487#issuecomment-2481539175 contains the following lines, so [the `gameinput.h` test succeeds](https://github.com/libsdl-org/SDL/blob/aa352837d55405fee45fa9cb308f1239990cb4a3/CMakeLists.txt#L1899-L1904)
```cmd
-- Performing Test HAVE_GAMEINPUT_H
-- Performing Test HAVE_GAMEINPUT_H - Success
```
So it's very weird it fails to include `"gameinput.h"`.
```cmd
D:\a\CubeChip-SDL\CubeChip-SDL\build\_deps\sdl-src\src\joystick\gdk\SDL_gameinputjoystick.c(29,10): error C1083: Cannot open include file: 'gameinput.h': No such file or directory [D:\a\CubeChip-SDL\CubeChip-SDL\build\_deps\sdl-build\SDL3-shared.vcxproj]
```

We've also seen an issue with the latest windows-2022 update on GitHub Actions (related to ARM32) (version 20241113.3.0). We worked around it by [using an older Windows SDK](https://github.com/libsdl-org/SDL/commit/bd57cfdb55c70c7f3eda5673f0255c54b695ca3c).

Perhaps our preseeded MSVC cache is invalid? Does anything change by adding `-DSDL_PRESEED=OFF` to the `cmake-arguments` input of `libsdl-org/setup-sdl`?

**Comment by ChillerDragon** [comment]
> Perhaps our preseeded MSVC cache is invalid? Does anything change by adding `-DSDL_PRESEED=OFF` to the `cmake-arguments` input of `libsdl-org/setup-sdl`?

I am not sure if I understood the caching yet. But turning off pre seed fixes the build. But that might also be caused by it having no cache for the preseed cmake argument.

https://github.com/ChillerDragon/SDL_image/commits/chiller_test/

![image](https://github.com/user-attachments/assets/df255fbb-63da-4eb7-b9d1-9e7c877ff889)

**Comment by ChillerDragon** [comment]
> [MSVC succeeded](https://github.com/ChillerDragon/SDL_image/actions/runs/11927512772/job/33242991330) because you are using an [older Windows runner image](https://github.com/ChillerDragon/SDL_image/actions/runs/11927512772/job/33242991330#step:1:9): 20241021.1.0 You need 20241113.x (or newer). Restart the job until you get the newer one.

Indeed. I refreshed that very job until I hit Image: windows-2022 Version: 20241113.3.0 and then [it failed](https://github.com/ChillerDragon/SDL_image/actions/runs/11927512772/job/33271138264#step:1:8).

**Comment by madebr** [comment]
https://github.com/actions/runner-images/issues/10980#issuecomment-2513163023

> I think there's something wrong with either the MSBuild files or the CMake Visual Studio generator on the runner image.
Switching to the Ninja CMake generator does not cause a gameinput.h error.

**Comment by kingofknights** [comment]
any update on this issue,
still getting in ci / cd windows-latest

**Comment by madebr** [comment]
The resolution of https://github.com/actions/runner-images/issues/10980 was to use windows-2025
