### ISSUE TITLE
SDL_RenderCopyF copies outside of its source texture?

### ISSUE THREAD

**Issue by Legaliz3Nukes** [libsdl-org/SDL#11493]
Hello,

Recently I created a tiled based game where I had all the textures in a texture atlas. To render the player for an example I had to copy a portion of this atlas onto the renderer using SDL_RenderCopyF. I used this function instead of the SDL_RenderCopy because I liked the sub-pixel precision it gave me. But I noticed sometimes when the player walked that the border color that surrounded the textures in the atlas came with it. This only happened when the destination Rect argument in SDL_RenderCopyF had a position with a decimal of exactly .5(or **very** close to it). So I develop a quick test with SDL where I loaded a texture that had one pixel border in it. Then I used the the function to only copy the texture without the border and then render it to the screen. Then once again I could see the border become visable when the destination had a x value of .5, when the x value didn't have decimal of .5 the border went away and I got the texture that I wanted.

I used this texture: 
![test](https://github.com/user-attachments/assets/1ff7f11a-28e8-499d-8ae2-bc098c6cb4ea)
The texture is 16x16(without border) but the whole image is 18x18(with the border)
This is what it shows when the decimal is not .5:
![test1](https://github.com/user-attachments/assets/f6390c04-8b31-4a7c-87a1-9c64f60088d9)
This is what it shows when the decimal is very close to .5:
![test2](https://github.com/user-attachments/assets/6d2b5fdb-aacd-42ee-8e66-6a1d21a51f65)

I used this code to test this:

```
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>

#define WIDTH 500
#define HEIGHT 500

int main(int argc, char **argv)
{
	if (SDL_Init(SDL_INIT_VIDEO) < 0)
		exit(1);

        SDL_Window *window;
	SDL_Renderer *renderer;

	if (SDL_CreateWindowAndRenderer(WIDTH, HEIGHT, 0, &window, &renderer))
		exit(2);

	SDL_Surface *surface = IMG_Load("test.png");
	if (!surface)
		exit(3);
	SDL_Texture *texture = SDL_CreateTextureFromSurface(renderer, surface);
	SDL_FreeSurface(surface);
	if (!texture)
		exit(4);

	while (1) {
		SDL_Rect source = (struct SDL_Rect){
			.x = 1,
			.y = 1,
			.w = 16,
			.h = 16
		};
		SDL_FRect dest = (struct SDL_FRect){
			.x = 16.5f, /* no issue when it's not .5 */
			.y = 16.0f,
			.w = 16.0f,
			.h = 16.0f
		};

		SDL_RenderCopyF(renderer, texture, &source, &dest);
	
		SDL_RenderPresent(renderer);
	}

	SDL_DestroyTexture(texture);
	SDL_DestroyWindow(window);
	SDL_DestroyRenderer(renderer);

	SDL_Quit();

	return 0;
}
```

I used SDL2 on Linux - if that helps, Thanks

**Comment by sridenour** [comment]
This is because the default texture filtering mode, bilinear filtering, tells the GPU to blend the surrounding texels together. It isn't really a bug/issue with SDL, it's just something inherent to using the GPU to draw stuff that every game has to deal with.

There are a few ways around this:
1) Use nearest-neighbor filtering instead, by calling `SDL_SetTextureScaleMode(texture, SDL_ScaleModeNearest)` to just do it for that texture, or by calling `SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "0")` before you create the renderer.
2) Leave a 1 pixel border of empty space around each sprite/tile/whatever in your texture atlas.
3) Similar to 2, but instead of empty space, make each border a repeat of the tile's edge pixels. There are programs out there that will do this for you, like [TexturePacker](https://www.codeandweb.com/texturepacker).
4) Always make sure you're drawing on whole number (aka integer) coordinates.

For a pixel art game, Option 1 is probably what you want anyway. Otherwise, most people use Option 2.

**Comment by Legaliz3Nukes** [comment]
Thanks but the first option didn't work. Looks like I just have to stick with option 2 or 3 then.

**Comment by sridenour** [comment]
Since it looks like you're doing some kind of pixel art game, option 4 would also make sense.
