### ISSUE TITLE
GPU Docs: SDL_GPUSwapchainComposition seems to have a typo

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#11530]
On the [SDL_GPUSwapchainComposition](https://wiki.libsdl.org/SDL3/SDL_GPUSwapchainComposition) wiki page, it describes both `SDR` and `SDR_LINEAR` with the same description:
> Pixel values are in nonlinear sRGB encoding.

which seems like a typo.

Additionally, it might be better to document these in terms of input and output (i.e., what format should be written to the swapchain by the shader, what format is shown on display, and what format is [read back](https://wiki.libsdl.org/SDL3/SDL_DownloadFromGPUTexture)).

**Comment by icculus** [comment]
Actually...  @thatcosmonaut, @TheSpydog, what _should_ this say? I assume that `SDL_GPU_SWAPCHAINCOMPOSITION_SDR` should say "Pixel values are in nonlinear sRGB encoding." and  `SDL_GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR` should be the same text, except "linear" instead of "nonlinear" ... but they're both sRGB, right?

@namandixit's other point is good, too, about inputs/outputs/readback. Tell me the bullet points, I'll write it up.

**Comment by thatcosmonaut** [comment]
I agree that this is confusing. The gist of it is that SRGB texture types are linearized inside the shader but are still stored non-linearly in memory.
