### ISSUE TITLE
X11 mouse position has subtle issues

### ISSUE THREAD

**Issue by niconii** [libsdl-org/SDL#11646]
[Here's a YouTube video](https://www.youtube.com/watch?v=t6oV-bnGB-s) showcasing the below code. `driver` is the current video driver, `mouse` is the position from the latest mouse motion event, and `gmouse` is the position from `SDL_GetGlobalMouseState`.

It's hard to pin down exactly what's wrong, but you can see instances where `mouse` seems to lag behind `gmouse`, instances where the mouse cursor visibly moves a pixel but this isn't reflected in SDL, and so on.

As best as I can tell, `SDL_VIDEO_DRIVER=wayland` doesn't have these issues.

```c
#include <SDL3/SDL.h>

#define SDL_MAIN_USE_CALLBACKS
#include <SDL3/SDL_main.h>

SDL_Window *window;
SDL_Renderer *renderer;

float mouse_x = 0;
float mouse_y = 0;
float gmouse_x = 0;
float gmouse_y = 0;

SDL_AppResult SDL_AppInit(void **appstate, int argc, char **argv) {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_CreateWindowAndRenderer("Test Window", 320, 240, 0, &window, &renderer);
  
  return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppIterate(void *appstate) {
  char *text = NULL;
  
  SDL_SetRenderDrawColor(renderer, 0, 0, 255, 255);
  SDL_RenderClear(renderer);

  SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);

  SDL_asprintf(&text, "driver %s", SDL_GetCurrentVideoDriver());
  SDL_RenderDebugText(renderer, 0, 0*8, text);
  SDL_free(text);

  SDL_asprintf(&text, " mouse x=%11.6f y=%11.6f", mouse_x, mouse_y);
  SDL_RenderDebugText(renderer, 0, 1*8, text);
  SDL_free(text);

  SDL_GetGlobalMouseState(&gmouse_x, &gmouse_y);
  SDL_asprintf(&text, "gmouse x=%11.6f y=%11.6f", gmouse_x, gmouse_y);
  SDL_RenderDebugText(renderer, 0, 2*8, text);
  SDL_free(text);

  SDL_RenderPresent(renderer);

  return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppEvent(void *appstate, SDL_Event *event) {
  switch (event->type) {
    case SDL_EVENT_QUIT: {
      return SDL_APP_SUCCESS;
    }

    case SDL_EVENT_MOUSE_MOTION: {
      mouse_x = event->motion.x;
      mouse_y = event->motion.y;
      break;
    }
  }

  return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void *appstate, SDL_AppResult result) {
  SDL_DestroyRenderer(renderer);
  SDL_DestroyWindow(window);
}
```

**Comment by Kontrabant** [comment]
For clarification, are you seeing this behavior on a real X11 session,  when running via XWayland, or both?

**Comment by niconii** [comment]
I've tested this in GNOME on Arch Linux, in both Wayland and X11. It happens on both a real X11 session and Xwayland, but doesn't happen running natively on Wayland. @12Me21 and @y-ack were both able to reproduce this on their computers. @y-ack has also confirmed this doesn't happen on Windows.

I'd like to provide more videos, but while recording I discovered a bug in OBS preventing me from accurately recording the mouse position, so now I'm investigating that too. In the meantime, adding this code to `SDL_AppIterate` before `SDL_RenderPresent` makes the problem a bit easier to see:

```c
  SDL_SetRenderDrawColor(renderer, 0, 255, 0, 128);
  SDL_RenderLine(renderer, SDL_floorf(mouse_x), 0, SDL_floorf(mouse_x), 240);
  SDL_RenderLine(renderer, 0, SDL_floorf(mouse_y), 320, SDL_floorf(mouse_y));
```

**Comment by Kontrabant** [comment]
This seems like a mismatch between the coordinates provided by XInput and XQueryPointer. XInput does provide the root coordinates in motion events, so that should be used if a window has focus to avoid possible relative/global mismatches.

Can you test this branch and see if it fixes your issue: https://github.com/Kontrabant/SDL/tree/x11_coordinate_mismatch

**Comment by niconii** [comment]
https://github.com/libsdl-org/SDL/blob/5608bf5866ee2b6749990f0e2b70026c0e43b3e5/src/video/x11/SDL_x11xinput2.c#L451-L454

Commenting out these lines fixes the bug, though I don't know why.

**Comment by Kontrabant** [comment]
On my system, which is a standard desktop with one mouse, XInput exposes these pointer devices:

- Virtual core pointer
- Virtual core XTEST pointer
- xwayland-pointer:18
- xwayland-relative-pointer:18
- xwayland-pointer-gestures:18

The virtual core pointer is a master device, while the others are slaves.

Each movement of the mouse triggers two XI_Motion events: one from xwayland-relative-pointer, followed by one from the Virtual core pointer. With very small pointer movements, I'm occasionally seeing the coordinates delivered by these two devices going out of sync, with the xwayland-relative-pointer slave device lagging behind the virtual core pointer. In both cases the sourceid of the event is the id for xwayland-relative-pointer, so events from the virtual core pointer device are being dropped in that conditional, which is why removing it fixes the issue.

That conditional was added as part of the early pen code, so it could probably be moved into the pen path (I don't have a pen to test)? We might also just want to listen to the master pointer device for non-relative motion, as SDL doesn't distinguish between pointers for non-relative motion anyways.

This could also be a bug somewhere in the X stack, as it doesn't seem to make sense that the slave device lags behind the master, when according to the source id of the event, the slave device is the originator of the motion to begin with.

**Comment by Kontrabant** [comment]
Just to note, on real X11 the listed devices other than "Virtual core *" are different, but everything else still applies.

**Comment by slouken** [comment]
> We might also just want to listen to the master pointer device for non-relative motion, as SDL doesn't distinguish between pointer devices for non-relative motion anyways.

This is a good idea. We need to distinguish pointer devices for relative motion, that's how we implement multi-mouse support, but if there's a bug in the X11 stack we can definitely listen to the master device for absolute motion.

**Comment by Kontrabant** [comment]
@niconii can you confirm that the pull request fixes this on your end?

**Comment by niconii** [comment]
@Kontrabant Yes, it does.

**Comment by Kontrabant** [comment]
Thanks for confirming; the fix is merged.
