### ISSUE TITLE
Wayland `SDL_GetDisplayContentScale` returns wrong values

### ISSUE THREAD

**Issue by GoaLitiuM** [libsdl-org/SDL#11775]
Wayland backend seems to report the display content scale as 1.0 with 125% scaled monitor, whereas X11 returns 1.25 as expected for the same monitor. There also seems to be some inconsistencies between X11 and Wayland when querying the window size with `SDL_GetWindowSizeInPixels`.

Value returned from `SDL_GetDisplayContentScale(SDL_GetPrimaryDisplay())`:
- Wayland display content scale for primary monitor: **1.0 (expected: 1.25)**
- X11 display content scale for primary monitor: 1.25 (expected: 1.25)

Creating a window with requested size of 500x170 (no Hi-Dpi flag):
- Wayland `SDL_GetWindowSize(...)`: 500x170
- Wayland `SDL_GetWindowSizeInPixels(...)`: 500x170
- Wayland `SDL_GetWindowDisplayScale(...)`: **1.0 (expected 1.25)**
- X11 `SDL_GetWindowSize(...)`: 500x170
- X11 `SDL_GetWindowSizeInPixels(...)`: 500x170
- X11 `SDL_GetWindowDisplayScale(...)`: 1.25 (expected 1.25)

Creating a window with requested size of 500x170 (with Hi-Dpi flag):
- Wayland `SDL_GetWindowSize(...)`: 500x170
- Wayland `SDL_GetWindowSizeInPixels(...)`: **625x213**
- Wayland `SDL_GetWindowDisplayScale(...)`: 1.25 (expected 1.25)
- X11 `SDL_GetWindowSize(...)`: 500x170
- X11 `SDL_GetWindowSizeInPixels(...)`: 500x170
- X11 `SDL_GetWindowDisplayScale(...)`: 1.25 (expected 1.25)

The end result for Wayland is that the window looks much blurrier than X11 window when the backbuffer for the window is sized based on the returned `SDL_GetWindowSizeInPixels` values.

**Comment by GoaLitiuM** [comment]
The only way I can get perfectly scaled image from Wayland backend is to enable `SDL_HINT_VIDEO_WAYLAND_SCALE_TO_DISPLAY` hint, but that hint also makes the window not resizable at all.

**Comment by Kontrabant** [comment]
In short, Wayland and X handle scaled desktops completely differently.

Scaled Wayland desktops work in scaled points, like on Mac, so the display scale is always 1.0, and the content scale is 1.0 on non-DPI aware windows, since Wayland will scale up the output.

With the DPI-aware flag set, Wayland is giving you a window that is 500x170 _points_ in size with a 625x213 _pixel_ backbuffer that will give you 1:1, non-blurred output on the scaled desktop.

The window display scale is what UI elements should be scaled by to be the correct size on scaled desktops, so it's 1.25 on a DPI-aware window, since the client app is expected to handle the scaling, and 1.0 on a non-DPI-aware window since Wayland scales up the final output for you at the cost of being blurry.

X is always 1:1, and the display scale is just a suggestion.

>The only way I can get perfectly scaled image from Wayland backend is to enable SDL_HINT_VIDEO_WAYLAND_SCALE_TO_DISPLAY hint, but that hint also makes the window not resizable at all.

That's a clamping bug in the min/max size code that will be fixed momentarily.

**Comment by Kontrabant** [comment]
Reading it over, I think the documentation on the content scale functions can be improved a bit as well, as it is really just a recommendation for how content such as text and UI elements should be scaled, and doesn't necessarily correlate with backbuffer sizes, as accessibility options may also affect it (e.g. on X it is the desktop scale multiplied by the text scale).

**Comment by GoaLitiuM** [comment]
Thanks. Fixing the hint in # looks good enough for my use-case. We probably want to refactor the application to handle the scaling independently for each window in the future, but this is good enough for now.

Fixed by 8cc4735d74a1ce89c5fceb48b021872c8c563174

**Comment by Kontrabant** [comment]
Thank you actually, as your reports shook out bugs that my own checks missed, and avoided future issues for everyone 🙂.
