### ISSUE TITLE
Need a RWops-like way to get Directory listings

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1214]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2013-11-14 05:05:52 +0000, Mike Kasprzak wrote:

> This is mainly necessary for Android.
> 
> The SDL_RWFromXX (RWops) family of function can be used to read files stored in an Android APK file. The APK is like (is) as ZIP file though. Typical directory listing functions are of no use here. SDL_GetBasePath() is also not helpful here.
> 
> 
> Some Starting Points:
> 
> On Linux/Mac(?) you use opendir, dirent* types, readdir, and closedir.
> 
> On Windows you use _findfirst (with *.*), _finddata_t types, _findnext, and _findclose.
> http://msdn.microsoft.com/en-us/library/kda16keh.aspx
> 
> Not sure about WinRT, but it's probably different.

On 2017-08-15 04:44:32 +0000, Sam Lantinga wrote:

> Yes please!

**Comment by icculus** [comment]
Tossing this into 2.0.20 to explore, but might bump out later.

**Comment by circl-lastname** [comment]
Related to #4989

**Comment by 1bsyl** [comment]
Should we add something in SDL3, to list directories ? 

in the same way that we enumerate joystick, so that we don't need any locking API ?

**Comment by slouken** [comment]
Yes.

**Comment by icculus** [comment]
I'm wondering if an iterator, like what opendir() returns, makes sense for filesystems in ways it doesn't for the list of joysticks.

Joysticks are likely to be a handful of results, each a single integer, returned quickly from internal memory. File systems might give you thousands of results of variable length strings, depending on the directory.

**Comment by slouken** [comment]
Yes, good point. It also maps more cleanly to what the OS APIs return, probably for the same reason.

**Comment by ericoporto** [comment]
When browsing inside an Android asset package, it has these APIs that may be useful to take a look 

- [`AAssetManager_openDir`](https://developer.android.com/ndk/reference/group/asset#group___asset_1gab5b57ff012d6d1024d8bf5d30aedced4)
- [`AAssetDir_getNextFileName`](https://developer.android.com/ndk/reference/group/asset#group___asset_1ga4703b9f7baa3daeba248b6547de6b9b0)
- [`AAssetDir_rewind`](https://developer.android.com/ndk/reference/group/asset#group___asset_1ga45db6d19ad5e1c0f9b2e6b4059da14b3)

**Comment by nfries88** [comment]
> * difference of behavior compared to various platform

considering [the C++ standard library](https://en.cppreference.com/w/cpp/filesystem/directory_iterator) went with the iterator pattern here and both POSIX and Windows use an iteration pattern for their interfaces, I'm not sure how valid that concern is.

> * having Lock api for whatever reason.
> * does it reflect file removed/renamed in the mean times.

These are kind-of the same problem three times from where I sit (if your not removing or renaming files and directories, you don't need a lock)

While it wouldn't be at all inappropriate for SDL to offer an APi to delete or rename files, I don't think it would be particularly valuable, so that leaves other programs modifying directories while you're iterating them. It is a problem, but it's also a problem with using the system level APIs to begin with.

> * is the previous iterator still valid.

again referring to std::filesystem::directory_iterator, operator++ is specified to invalidate previous iterators, and while it's been a long time since I've used the system-specific APIs I'm pretty sure both readdir and FindNextFile naturally require such behavior. So I think the choice is pretty obvious here.

I also don't think there's a fully satisfactory alternative - could treat an "open directory" like a file and have the caller read out "directory entry" structures into caller-supplied buffers until they get EOF, or a Win32-style enumeration function taking a callback, but they both still have some of these problems

**Comment by 1bsyl** [comment]
I meant the OS/AnotherApp/User maybe deleting/creating the file while your are looking at the directory.
All platform should be coherent of that, and provide the same behavior.

The *sdl* previous iterator should also be valid (or invalid whatever you choose), and be coherent across all platform I guess.

You can have a locking API, to request that the list won't reflect untimely listing changes.
(the lock/unlock for joystick was also thread safety, but that can probably ignored here)

If the API starts by foreseeing a lock/unlock api, that already a bad step i think.

@nfries88 Feel free to propose an API proposition + test case of your suggestion to see where it goes

**Comment by icculus** [comment]
Moving this over to #8129 for concrete API discussion.
