### ISSUE TITLE
Unable to create GL context for external window

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1717]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2014-12-11 10:54:46 +0000, David Pickering wrote:

> hello
> 
> i appear to be unable to call SDL_GL_CreateContext() [SDL_Video.c:2882] on a window that was created/acquired with SDL_CreateWindowFrom() [SDL_Video.c:1308]. 
> 
> this appears to be because the flags variable for the external window (that is checked in SDL_GL_CreateContext()) does not contain the SDL_WINDOW_OPENGL flag.
> 
> error message received: "The specified window isn't an OpenGL window".
> 
> many thanks

On 2014-12-12 19:27:29 +0000, Philipp Wiesemann wrote:

> In some cases the hint SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT [1] needs to be configured before using SDL_CreateWindowFrom().
> 
> [1] https://wiki.libsdl.org/SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT

On 2016-07-15 01:36:49 +0000, sage wrote:

> hello
> 
>   i have face the same problem too. i work with MFC, can't use SDL_CreateWindow to  
> create a window with SDL_WINDOW_OPENGL, so can't set the hint  SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT , int the end , i can't use SDL_GL_CreateContext().
> 
> many thanks

On 2017-08-14 01:08:57 +0000, Sam Lantinga wrote:

> We've discussed adding a new API for this, and we could also create a hint that would affect the existing API. I'm inclined toward the latter since it would allow people to affect how the SDL window will be created in more flexible ways over time.

**Comment by madscientist42** [comment]
Going to resurrect interest in this one.  As described in the bug, it's a laudable thing to be as hands-off as is possible with a foreign window.  That being said, the framework really ought to have a hook/means to tell the rest of the framework, "No, no...act like you created it when it comes to GL setup, etc. because that's OK."   Same goes for EGL.  There's interesting and relevant (Sorry, can't say...NDA involved) use cases wherein you need to be able to do that...and not just the ones mentioned in the old discussion threads talked to in the ticket.

I'm leaning towards additional hints that pass select flag overrides into the framework as you create the Windows off of the externals.  This would be quite a bit simpler if I could just hand a hint in to tell SDL to act as if the window is a GL capable one we otherwise asked for.  Well, however it needs to be for GLX and EGL...

**Comment by slouken** [comment]
Yes, I think a more robust system to describe how to handle foreign windows would be great for SDL 3.0. I know you're probably doing other things, but if you have a patch set that you'd like to contribute, I'd love to see it.

**Comment by slouken** [comment]
This is fixed in https://github.com/libsdl-org/SDL/commit/1c4723ac66363c1b0dd08f2095869b810bfd16ec, where you can set properties indicating that the external window is used for OpenGL, as well as set the window that you'll share the pixel format with if needed.
