### ISSUE TITLE
OpenGL compability

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2288]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Windows 7, x86_64

# Comments on the original bug report:

On 2016-10-25 20:49:05 +0000,  wrote:

> Header SDL_opengl.h has declarations of functions from OpenGL 1.3
> which are not supported by import library opengl32.lib on operating systems
> like Windows 7 and older windows systems.
> 
> So you have to achieve addresses of these functions during runtime.
> 
> However you can't load declared extern pointers named as these functions during application runtime because this names has already been declared in SDL_opengl.h
> which doesn't make sense because opengl32.lib doesn't have declaration of them.
> 
> SDL version 2.0.3 had macro GL_GLEXT_PROTOTYPES which prevented declaration
> of functions from OpenGL 1.3

On 2017-08-11 20:29:07 +0000, Sam Lantinga wrote:

> Ryan, can you review this?

**Comment by icculus** [comment]
Reading this again, the request is to be able to declare a post-1.1 entry point as a function pointer, which he can't because SDL_opengl.h (_correctly_) declares them as actual functions.

He absolutely shouldn't do this; pick a different symbol instead. `pglBindBuffer` instead of `glBindBuffer` or whatever.
