### ISSUE TITLE
-lmingw32 and -lSDL2main are not required for building libraries, only applications.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2779]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.7
**Reported for operating system, platform:** Windows 10, x86

# Comments on the original bug report:

On 2018-01-07 23:38:31 +0000,  wrote:

> Unsure how one would handle this correctly, but the only time
> (on mingw-w64, at least) one needs to link libSDL2main.a and
> libmingw32.a (and possibly the -mwindows flag) is when you're
> building an actual 'application', that is, something that starts
> executing at main().
> 
> There should be a way to make sdl2-config or pkg-config and friends
> differentiate between 'linking to sdl2 to make a library (like SDL2_ttf)'
> and 'linking to sdl2 to make a game/executable'.

**Comment by madebr** [comment]
For sdl2-config, this is possible with refactoring.
But since it's deprecated and sdl3-config does not exist, this will never happen.

Current sdl3 git provides cmake config files + pkg-config files, which provide the same information as `sdlX-config`.
SDL3 also does not need libSDL3main.a anymore (with accompanying -lmingw32 -mwindows), so that simplified things a lot.
