### ISSUE TITLE
Mouse position changes while in relative mouse mode SDL_SetRelativeMouseMode

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3087]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2018-12-01 16:40:22 +0000,  wrote:

> From https://wiki.libsdl.org/SDL_SetRelativeMouseMode :
> "Only relative motion events will be delivered, the mouse position will not change."
> 
> After disabling the relative mouse mode and moving the mouse, the cursor is in a different position than where it was before enabling the mode.
> 
> Example C program: https://pastebin.com/a2JNrMT8
> 
> Windows 7 32-bit, MinGW-w64 GCC 7.3.0, SDL 2.0.9

On 2018-12-01 16:55:59 +0000,  wrote:

> (In reply to ihcusk from comment # 0)
> > From https://wiki.libsdl.org/SDL_SetRelativeMouseMode :
> > "Only relative motion events will be delivered, the mouse position will not
> > change."
> > 
> > After disabling the relative mouse mode and moving the mouse, the cursor is
> > in a different position than where it was before enabling the mode.
> > 
> > Example C program: https://pastebin.com/a2JNrMT8
> > 
> > Windows 7 32-bit, MinGW-w64 GCC 7.3.0, SDL 2.0.9
> 
> Sorry, I meant:
> After disabling the relative mouse mode, the cursor is in a different position than where it was before enabling the mode and moving the mouse.

On 2018-12-01 17:22:22 +0000,  wrote:

> (In reply to ihcusk from comment # 0)
> > From https://wiki.libsdl.org/SDL_SetRelativeMouseMode :
> > "Only relative motion events will be delivered, the mouse position will not
> > change."
> > 
> > After disabling the relative mouse mode and moving the mouse, the cursor is
> > in a different position than where it was before enabling the mode.
> > 
> > Example C program: https://pastebin.com/a2JNrMT8
> > 
> > Windows 7 32-bit, MinGW-w64 GCC 7.3.0, SDL 2.0.9
> 
> There is an error in the example program. Again, sorry.
> Correct version: https://pastebin.com/hLQnkkRP

**Comment by qiyidian** [comment]
This same bug happens on macOS Big Sur 11.6.2 and SDL 2.0.18. 

Setting `SDL_SetRelativeMouseMode(SDL_TRUE)` still allows the mouse to be moved within the borders of the window (which can be seen using `SDL_GetMouseState` or, when the window is in its own Space (maximized), activating "hot zones" near the top and bottom of the screen that annoyingly cause the menu bar and task bar to appear when the mouse is nearby).

This bug seems to have existed on macOS for a while, and was brought up in issue #1116. This bug is particularly troublesome for any applications involving a camera that can be turned freely and infinitely, like FPS games as referenced in 1116.
