### ISSUE TITLE
Vulkan Window Slow to Show

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3088]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.9
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2018-12-01 20:14:35 +0000, Diego wrote:

> I'm testing on MacOS 10.14.1 using testvulkan.c. After the window is created, if it is moved completely behind another window and then brought back to the front again (such as by command-tabbing), sometimes it is very slow to show. 
> After pressing command-tab or clicking on the applications icon in the dock it can take several seconds before the window is actually shown. This doesn't seem to be the case if the window is not completely hidden behind another window. I could not reproduce this with MoltenVK's demoes. They showed promptly.

On 2019-06-24 00:43:42 +0000, Ryan C. Gordon wrote:

> 
> I haven't looked into this further than throwing some SDL_GetTicks() calls in there, but the reason this happens is the vkWaitForFences() call, which blocks about 16 milliseconds normally (for vsync?), but in the background waits 1500 milliseconds.
> 
> I _presume_ this is a MoltenVK bug (or possibly intentional feature...?) and that the MoltenVK demos just don't wait on a fence.
> 
> I'll look a little further, but I don't think this is an SDL bug at the moment.
> 
> --ryan.

On 2019-06-24 04:11:50 +0000, Diego wrote:

> Thanks for taking a look! It could be a MoltenVK bug but that wasn't my initial feeling. The LunarG/MoltenVk demo cube.c does use fences and vsync. I can't get my SDL window to show promptly from the background whether or not I'm using vsync, or using fences or just waiting for queue idle.
> 
> https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/demos/cube.c

**Comment by ellipticaldoor** [comment]
It looks like this issue happens because the window stops waiting for the vsync when the window gets hidden and the high amount of produced fps throttles the thread.

Right now I listen for the window event `SDL_WINDOWEVENT_FOCUS_LOST` and then I sleep in the in render loop for 1000 / 60 seconds. This seems to make the window focus responsive again.

It seems like this was fixed previously for OpenGL https://github.com/libsdl-org/SDL/commit/13869f194c5b975aefac6517e58998f11108d722 but I can't see this fix on the `SDL_cocoavulkan` implementation

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
