### ISSUE TITLE
SDL_GetDisplayDPI returns incorrect result on MacOS with retina screens

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3446]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.10
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2019-11-11 15:19:50 +0000, Rokas Kupstys wrote:

> On MacOS with retina screens we have double pixel density. Interesting detail is that OS reports window size in uniform units as if it was on 96 DPI display (unsure about terminology here). Simply put - whatever window size reported it will cover twice as many pixels in each dimension.
> 
> SDL_GetDisplayDPI() in this setup reports 54.5 DPI.
> 
> Correct DPI scale (which is 2.0f in this case) can be obtained form NSScreen::backingScaleFactor https://developer.apple.com/documentation/appkit/nsscreen/1388385-backingscalefactor
> 
> SDL should return 96.f * NSScreen::backingScaleFactor

On 2019-12-04 17:22:59 +0000, Ryan C. Gordon wrote:

> 
> Pushed a fix for this in https://hg.libsdl.org/SDL/rev/3b03741c0095 ...someone should check my math (should we scale before doing the diagonal DPI math, etc?), and see if there's a better way to get an NSScreen from a CGDirectDisplay, maybe, but it finds the correct scaling factor on my retina macbook.
> 
> Reopen the bug if there's still a problem, please!
> 
> --ryan.

**Comment by vkedwardli** [comment]
Since `backingScaleFactor` is "locked" to `1.0` / `2.0` / `3.0`, it does not reflect the actual resolution scaling.

E.g. on MBP 16", the native resolution is 3072x1920 with 226 dpi.

With the current implementation, the DPI is fluctuating:

For scaled resolution 1792x1120, `SDL_GetDisplayDPI` returns `ddpi=264.279755`

For scaled resolution 2048x1280, `SDL_GetDisplayDPI` returns `ddpi=302.000000`

For scaled resolution 3072x1920, `SDL_GetDisplayDPI` returns `ddpi=226.279556`

I would suggest to calculate the DPI by `Native Resolution (px) / Physical size (mm) * 25.4f` like the following:
https://github.com/flyinghead/flycast/blob/master/shell/apple/emulator-osx/emulator-osx/osx-main.mm#L179-L195

**Comment by vkedwardli** [comment]
pinging @icculus

**Comment by slajerek** [comment]
This is still not fixed and I need to add a workaround on macOS:

```
#if __APPLE__
		monitor.DpiScale = MACOS_GetBackingScaleFactor(n);
#else
        float dpi = 0.0f;
        if (!SDL_GetDisplayDPI(n, &dpi, NULL, NULL))
            monitor.DpiScale = dpi / 96.0f;
#endif

// workaround for SDL 2.0.10 bug: https://bugzilla.libsdl.org/show_bug.cgi?id=4856
// based on: https://github.com/ocornut/imgui/commit/a843af4306e0d786fec5394bba07fd5067384661
float MACOS_GetBackingScaleFactor(int screen)
{
	if (screen >= [NSScreen screens].count)
		return 1.f;
	return static_cast<float>([[NSScreen screens][static_cast<NSUInteger>(screen)] backingScaleFactor]);
}
```

This above seems to be working OK in most cases, but some external monitors do not properly return `SDL_GetGlobalMouseState(&xPos, &yPos);` (i.e. the global mouse position is wrong and not correct, probably due to dpi/scaling problems).
