### ISSUE TITLE
Add @Keep to JNI methods to preserve them during proguard obfuscate/shrink

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3563]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Android (All), All

# Comments on the original bug report:

On 2020-02-24 18:34:17 +0000, Anthony @ POW Games wrote:

> At present, the only way to build a successful APK with proguard is to add the following line to the rules:
> 
> -keep public class org.libsdl.app.** { public *; }
> 
> This works, but leaves the entire Android SDL Java code unoptimised. 
> 
> I've found the @Keep keyword (import android.support.annotation.Keep;) works really well to preserve the methods for JNI. If we add them to all the JNI methods, it should allow us to run a full proguard optimization.
> 
> Not vital - but very useful for developers wanting to reduce their APK size.

On 2020-02-24 18:35:52 +0000, Anthony @ POW Games wrote:

> Another alternative is to list every JNI in proguard-rules.pro, but there are a lot of them and it'd be something more to manage (and maybe forget to update).

On 2020-03-02 23:17:04 +0000, Sam Lantinga wrote:

> Can you provide a tested patch? I'd like to add that for 2.0.13.
> Are there any build environment dependencies?
> 
> Thanks!

On 2020-03-06 11:09:40 +0000, Sylvain wrote:

> I wonder whether adding "import android.support.annotation.Keep;" would increase size.
> 
> Does it need to add some gradle dependency ?
> 
> Do you have an example of a proguard line to keep the method ?

**Comment by AntTheAlchemist** [comment]
Bump! I've just tried this and it works well, so I would still like it to be added if possible. I'm still not sure how to do a pull or commit, but I can tell you exactly how to implement this.

This import is needed:
` import androidx.annotation.Keep; `

And then a `@Keep` placed before every JNI method:
`@Keep public static void pollInputDevices() { mJoystickHandler.pollInputDevices(); }`

And before every C native declaration:
`@Keep public static native int nativeRemoveHaptic(int device_id);`

There's quite a lot of methods to tag across a few .java files. 

The import shouldn't add any bulk to the apk since it's a build-time thing? Unfortunately I don't have a bare-bones set up to easily test if it adds dependencies. Test it on just one JNI method to see if it coughs anything up?

This allows proguard to do a full optimization, shrink & obfuscate pass and reduces the APK massively, which will please a lot of people. Without adding `@Keep` to SDL I had to add this line to proguard `#-keep public class org.libsdl.app.* { public static *; }` which effectively prevents it from doing much.

I am no expert, so hopefully someone else can chip in with pros / cons, otherwise I think this is a safe and positive thing to add.

**Comment by slouken** [comment]
This seems like a good idea, can you create a PR for this?

**Comment by slouken** [comment]
Added, thanks!

BTW, let me know if you'd like me to walk you through the process of making a PR? It's fairly easy and would definitely help us process patches more safely and efficiently.
