### ISSUE TITLE
MinGW sdl2-config.cmake produces bogus Makefiles

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3665]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.12
**Reported for operating system, platform:** Windows (All), All

# Comments on the original bug report:

On 2020-04-28 16:21:35 +0000, Ethan Lee wrote:

> When using SDL2-devel-2.0.12-mingw with CMake, builds will fail to start, only producing a mysterious "*** target pattern contains no '%'.  Stop."
> 
> I found out that the "if(NOT TARGET SDL2::SDL2)" block added in 2.0.12 is the root cause. Deleting this entirely gets builds to work again.
> 
> You can test this with both FAudio and FNA3D:
> 
> https://github.com/FNA-XNA/FAudio
> https://github.com/FNA-XNA/FNA3D
> 
> Both builds are as simple as `mingw32-cmake .. && mingw32-make`, they should depend on nothing more than SDL2. I tested this on CentOS with the files provided by libsdl.org as well as Fedora's built-in mingw32/64-SDL2 packages.

**Comment by DanielGibson** [comment]
(pinging @flibitijibibo has he originally reported this)

I could reproduce this on Windows, it happens if you build SDL2 itself with mingw+autotools and then try to build your application with mingw as well (ok, it's not like you have a choice, SDL2 built with mingw doesn't generate the .lib files needed to use it with MSVC).
More details about the problem:
```
$ make VERBOSE=1
...
-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/sdl-cmake-test/build-mingw
"/C/Program Files/CMake/bin/cmake.exe" -E cmake_progress_start /D/dev/sdl-cmake-test/build-mingw/CMakeFiles /D/dev/sdl-cmake-test/build-mingw/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/d/dev/sdl-cmake-test/build-mingw'
make -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/depend
make[2]: Entering directory '/d/dev/sdl-cmake-test/build-mingw'
CMakeFiles/SDL2Test.dir/build.make:83: *** target pattern contains no '%'.  Stop.
```
`CMakeFiles/SDL2Test.dir/build.make` around line 83 looks like:
```
SDL2Test.exe: CMakeFiles/SDL2Test.dir/main.cpp.obj
SDL2Test.exe: CMakeFiles/SDL2Test.dir/build.make
SDL2Test.exe: SDL2::SDL2-NOTFOUND
SDL2Test.exe: d:/dev/sdl2inst-autotools/lib/libSDL2main.a
SDL2Test.exe: CMakeFiles/SDL2Test.dir/linklibs.rsp
...
```
Yes, line 83 is the one with `SDL2::SDL2-NOTFOUND` - that explains it, of course.

The problem is that `sdl2-config.cmake` doesn't add an `IMPORTED_IMPLIB` property in `set_target_properties(SDL2::SDL2 PROPERTIES ...` - on Windows that is supposed to specify the .lib (maybe .dll.a for mingw?) file used for linking against a DLL.
Adding `IMPORTED_IMPLIB "${exec_prefix}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2${CMAKE_SHARED_LIBRARY_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}"` below the `IMPORTED_LOCATION ...` line gets us a step further, that part of `CMakeFiles/SDL2Test.dir/build.make` now looks like:
```
SDL2Test.exe: CMakeFiles/SDL2Test.dir/main.cpp.obj
SDL2Test.exe: CMakeFiles/SDL2Test.dir/build.make
SDL2Test.exe: d:/dev/sdl2inst-autotools/lib/libSDL2.dll.a
SDL2Test.exe: d:/dev/sdl2inst-autotools/lib/libSDL2main.a
SDL2Test.exe: CMakeFiles/SDL2Test.dir/linklibs.rsp
...
```
Now compiling gets further, but linking fails:
```
[ 50%] Linking CXX executable SDL2Test.exe
"/C/Program Files/CMake/bin/cmake.exe" -E remove -f CMakeFiles/SDL2Test.dir/objects.a
/C/yq2buildenv/mingw32/bin/ar.exe cr CMakeFiles/SDL2Test.dir/objects.a @CMakeFiles/SDL2Test.dir/objects1.rsp
/C/yq2buildenv/mingw32/bin/g++.exe    -Wl,--whole-archive CMakeFiles/SDL2Test.dir/objects.a -Wl,--no-whole-archive  -o SDL2Test.exe -Wl,--out-implib,libSDL2Test.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/SDL2Test.dir/linklibs.rsp
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x39): undefined reference to `SDL_calloc'
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x60): undefined reference to `SDL_wcslen'
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x83): undefined reference to `SDL_iconv_string'
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0xb0): undefined reference to `SDL_ShowSimpleMessageBox'
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0xd8): undefined reference to `SDL_SetMainReady'
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x10a): undefined reference to `SDL_free'
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x118): undefined reference to `SDL_free'
```
`CMakeFiles/SDL2Test.dir/linklibs.rsp` looks like:
`d:/dev/sdl2inst-autotools/lib/libSDL2.dll.a d:/dev/sdl2inst-autotools/lib/libSDL2main.a -lmingw32 -lSDL2main -mwindows -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32`

(putting `libSDL2main.a` before libSDL2.dll.a`` doesn't help)

I'm not sure what to do about this, but at least we're one step further with this bug now.

Note however that when using `target_link_libraries(SDL2Test ${SDL2_LIBRARIES})` instead of `target_link_libraries(SDL2Test  SDL2::SDL2main SDL2::SDL2)` in the test projects CMakeLists.txt, it does build - in that case `CMakeFiles/SDL2Test.dir/linklibs.rsp` looks like:
` -Ld:/dev/sdl2inst-autotools/lib  -lmingw32 -lSDL2main -lSDL2 -mwindows -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32`

And when building SDL2 with MSVC (and CMake), building works with `SDL2::SDL2main SDL2::SDL2` passed to `target_link_libraries()` - in that case `CMakeFiles/SDL2Test.dir/linklibs.rsp` looks like:
` D:/dev/sdl2inst/lib/SDL2.lib D:/dev/sdl2inst/lib/SDL2main.lib -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32`
(apparently MinGW is able to use the .lib files)

(BTW: I have no idea where all those system libs linked against there come from, CMake must add them by default)

**Comment by DanielGibson** [comment]
Ok, WTF: If I manually edit `CMakeFiles/SDL2Test.dir/linklibs.rsp` to look like:
```
-lmingw32 d:/dev/sdl2inst-autotools/lib/libSDL2main.a d:/dev/sdl2inst-autotools/lib/libSDL2.dll.a -mwindows -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
```
i.e. pull the `-lmingw32` to the front, remove the (superfluous) `-lSDL2main`, make sure the other SDL2main entry is before the SDL2 entry, it works (when also adding `IMPORTED_IMPLIB "${exec_prefix}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2${CMAKE_SHARED_LIBRARY_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}` to `SDL2::SDL2`'s properties, as described above).

I'm unsure if/how that `SDL2::SDL` or `SDL2::SDL2main` library definitions in `sdl2-config.cmake` would have to be massaged to get `-lmingw32` in front - as far as I can tell, it always starts with the entry from `IMPORTED_IMPLIB` and puts the `INTERFACE_LINK_LIBRARIES` behind that.

I fucking hate computers.

**Comment by DanielGibson** [comment]
https://github.com/libsdl-org/SDL/pull/4320 should fix this (but is still WIP)
