### ISSUE TITLE
Wayland: cannot paste text copied from within the application itself

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3725]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2020-06-09 10:40:58 +0000, Ivan Molodetskikh wrote:

> hg revision 71c13a6765a9405927a5bf0aaf1471f4dabb3b01, also SDL 2.0.12 and earlier
> 
> Run test/testdropfile, press Ctrl-C to copy, press Ctrl-V to paste, it says Clipboard empty. Pasting works fine if the text was copied from another application.

**Comment by flibitijibibo** [comment]
I've started looking at this and I've at least fixed the _worst_ of this via #4295, but the Wayland clipboard implementation is kind of a train wreck.

With the patchset mentioned above, the checklist is as follows:
- [x] Copy from SDL, Paste to elsewhere
- [x] Copy from elsewhere, Paste to SDL
- [ ] Copy from SDL, Paste to SDL

That last one not only stalls on a pipe read, but also trips a million Valgrind warnings and causes an infinite loop in the application's event loop (!!!!!). Let's get into why, shall we...

The Wayland clipboard system has what appears to be 2 different ways of getting clipboard data: offers and sources (though the comments in datamanager.h would suggest otherwise):

https://github.com/flibitijibibo/SDL/blob/9ff5f869843e6bfdacece1d36ab5cc850da6ccbd/src/video/wayland/SDL_waylandclipboard.c#L77-L89

https://github.com/flibitijibibo/SDL/blob/9ff5f869843e6bfdacece1d36ab5cc850da6ccbd/src/video/wayland/SDL_waylandclipboard.c#L111-L120

You will notice that these samples come from GetClipboardText and HasClipboardText... what about SetClipboardText?

https://github.com/flibitijibibo/SDL/blob/9ff5f869843e6bfdacece1d36ab5cc850da6ccbd/src/video/wayland/SDL_waylandclipboard.c#L42-L53

Okay, so we're just using the source API which makes sense, but this variable worries me a ton, mainly because all of the Valgrind errors point right here:

https://github.com/flibitijibibo/SDL/blob/9ff5f869843e6bfdacece1d36ab5cc850da6ccbd/src/video/wayland/SDL_waylandclipboard.c#L43

There's a really bad use-after-free in here, but there's just too much indirection for me to figure out what's really happening here.

**Comment by flibitijibibo** [comment]
Turns out all the explosions were from read_pipe/write_pipe having an absurd timeout of a whole second for clipboard activity, which was causing PumpEvents to fire unnecessarily and, under the right circumstances, retread events that freed data that was already freed. This is now fixed by #4295.
