### ISSUE TITLE
[Patch] Enable pthread support for Emscripten

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3795]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Emscripten pthread patch (emscripten_pthreads.diff, text/plain, 2020-08-15 03:13:07 +0000, 1319 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4437)

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Other, x86

# Comments on the original bug report:

On 2020-08-15 03:13:07 +0000, Caleb Cornett wrote:

> Created attachment 4437
> Emscripten pthread patch
> 
> This patch enables building SDL2 for Emscripten with pthread support. This allows the SDL_Thread API to work in the browser, for recent versions of Chrome and Firefox. Of course, threading support is still totally optional and can be disabled by passing --disable-threads to the configure script.

**Comment by icculus** [comment]
This still needs a cmake equivalent and I feel like emscripten pthreads have burned me before, but I'll try to poke at this for 2.0.16.

**Comment by icculus** [comment]
Okay, it looks like threading is still not widely enabled in browsers at the moment, and the problem is that if you try to run an app with pthreads support on one of those, it won't even start up, even if your app doesn't make any pthreads calls. The emscripten developers currently recommend you make two builds of your app and load the right one with some Javascript based on what you see supported on the user's browser.

Since you not only need two separate builds, but one of them has to do everything single-threaded, it makes sense to just avoid pthreads for now. This will definitely change as SharedArrayBuffer support is widespread (and _enabled_, which is the real problem here), or if the Emscripten team finds a workaround that lets you do one build.

So I'm going to put the hooks into configure.ac and CMakeLists.txt so people can _enable_ support, but it's going to be disabled by default for now.
