### ISSUE TITLE
Sizes should be Uint32 (no int32)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3804]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2020-08-24 16:26:33 +0000,  wrote:

> It is only one bit, but it will allow 2x larger size. That is not real problem, but it's unnecessary. Also, it will disallow programmers to put negative value to it.

**Comment by 1vanK** [comment]
If size is unsinged, then if user write `size1 - size2`, then overflow occurs if size1 < size2.
Those, sizes still need to be converted to int before being used in calculations, and user can easily forget about it

Cycle `for (unsigned i = 9; i >= 0; i--)` will never stop, because `i >= 0` is always true.
User can workaround this in many ways, but why? Again, this is an additional source of error.

Scott Meyers recommeds use signed types in interfaces https://www.aristeia.com/Papers/C++ReportColumns/sep95.pdf

Bjarne Stroustrup recommeds use signed types for sizes: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1428r0.pdf

C# uses int for sizes https://docs.microsoft.com/en-us/dotnet/api/system.array.length?view=net-6.0

Bullet uses int for capacity & size & indices https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/Bullet/src/LinearMath/btAlignedObjectArray.h

**Comment by 1vanK** [comment]
> Also, it will disallow programmers to put negative value to it.

No. This will allow programmers to put negative value to it. Negative values will be automatically converted to big unsigned, and it will be more difficult for the user to find the source of the problem
