### ISSUE TITLE
0 alpha size setting not respected on EGL (Wayland)

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3919]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Other, Other

# Comments on the original bug report:

On 2020-12-11 18:07:30 +0000,  wrote:

> In sdl_egl, EGL_ALPHA_SIZE is only set if gl_config.alpha_size is "true" (non-zero):
> 
> http://hg.libsdl.org/SDL/file/6044f03a6809/src/video/SDL_egl.c#l711
> 
> But it should always be set!
> 
> On Wayland, having alpha is the default. SDL users expect no alpha to be the default – it is even mentioned in https://wiki.libsdl.org/SDL_GL_SetAttribute that SDL_GL_ALPHA_SIZE defaults to 0. But this if condition breaks that by interpreting *that* zero as "just use platform default", so there's basically no way to create an SDL window without transparency on Wayland.

**Comment by flibitijibibo** [comment]
I was able to test this and confirm that this report is invalid; not only does eglChooseConfig specifically state that the default is 0...

https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglChooseConfig.xhtml

... but I was able to fix a transparency issue in FNA because this feature works correctly:

https://github.com/FNA-XNA/FNA3D/commit/7942d736b4cd85d84979f7fcc4a21d8a503edfd6

**Comment by flibitijibibo** [comment]
In addition to the EGL spec noting that ALPHA_SIZE is zero, this turned out to be just a general EGL design issue that is being addressed via an extension. If you _really_ wanted to fix this it would have to be in Mesa or the NVIDIA EGL implementation since the implementation decides whether to prioritize RGBA over RGBX; SDL is doing what it's supposed to be doing here.

EGL_EXT_present_opaque should fix this for good, but it's still being drafted. We'll integrate it as soon as it's ready.
