### ISSUE TITLE
SDL_Init fails on iOS due to removed code from SDL_uikitappdelegate.m

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3941]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.15
**Reported for operating system, platform:** macOS 10.15, ARM

# Comments on the original bug report:

On 2020-12-26 08:58:58 +0000, Steve Robinson wrote:

> When building SDL2-static from 2.0.14 source and using it with the 'Rectangles' example, SDL_Init failed due to SDL_MainIsReady being false. The identical set up with 2.0.12 worked fine.
> 
> Adding the following lines from src\video\uikit\SDL_uikitappdelegate.m in 2.0.12 fixed the problem:
> ```
> #if defined(SDL_MAIN_NEEDED) && !defined(IOS_DYLIB)
> /* SDL is being built as a static library, include main() */
> int main(int argc, char *argv[])
> {
> 	return SDL_UIKitRunApp(argc, argv, SDL_main);
> }
> #endif /* SDL_MAIN_NEEDED && !IOS_DYLIB */
> ```
> Environment:
> CMake: 3.19.2
> Xcode: 12.3
> macOS: 11.1

On 2020-12-26 12:52:29 +0000, Ozkan Sezer wrote:

> Removal commit is https://hg.libsdl.org/SDL/rev/6c2bbcfc3940

On 2020-12-28 19:59:02 +0000, Sam Lantinga wrote:

> Hey Ryan, I think you broke this. What were you fixing with that commit?

**Comment by sezero** [comment]
You may want to handle this in 2.0.16

**Comment by slouken** [comment]
Yep, thanks!

**Comment by icculus** [comment]
oh, I'll look at that real fast.

**Comment by icculus** [comment]
So this code is _also_ in a legit SDLmain library for iOS:

https://github.com/libsdl-org/SDL/blob/main/src/main/uikit/SDL_uikit_main.c

So it's likely that the app needs to link with SDLmain. I can put that code back, but this is closer to how we do it on every other platform, unless I'm misunderstanding the problem.

**Comment by slime73** [comment]
> the app needs to link with SDLmain.

Is that change documented anywhere? I imagine I'd figure this out pretty quickly after I update SDL myself, but I don't remember hearing about that behaviour change before if apps using SDL's main on iOS now need to link with two libraries instead of just one.

Also (if I'm interpreting that correctly, not having tested myself) it sounds like the iOS test apps all need to be updated for that change?

**Comment by slime73** [comment]
Reading the original commit, there's a new comment as part of the commit which makes it sound like the extra library link is only meant to be needed when using SDL as a dynamic library on iOS. Whereas the bug report says the problem is happening when using SDL as a static library.

**Comment by slouken** [comment]
In general we're trying to eliminate the need for the SDLmain library on all platforms, however SDL shouldn't conflict with an application that provides their own main function. I _think_ what we're trying to do here will work, where the application code will use main() if provided, and will use SDL's main otherwise.

Ryan, did you actually run into problems with that code being in there, or was it a speculative change?

**Comment by icculus** [comment]
> Ryan, did you actually run into problems with that code being in there, or was it a speculative change?

I triggered this issue in the iOS build of DragonRuby Game Toolkit last time we upgraded our internal SDL builds. Prior SDL revisions had separate Xcode files for iOS and macOS, and right before my change, that was replaced with a unified Xcode project, which was when we suddenly had a build with two copies of main().

I don't feel strongly about how this should be handled; one can avoid having a separate SDLmain library but iOS still needs us to supply main() at this moment, regardless of where it is supplied. I think it would be more incorrect to delete SDLmain in this case, but less surprising to projects.

**Comment by TheSpydog** [comment]
This change is causing problems for FNA apps as well, since we already have a main() implicitly defined by the C# runtime via Xamarin.iOS. Having SDL contain a main function that can't be removed via preprocessor defines means that we have to [patch the SDL source](https://github.com/TheSpydog/fnalibs-ios-builder/blob/master/sdl2_fna_ios.patch#L45) as part of the iOS build process. This isn't too inconvenient but is still less than ideal, especially when the code from the OP used to work for us out of the box.

For what it's worth, having the main function live exclusively in a separate standalone SDLmain lib would also work for our purposes, since we could just not link with that library and the problem would solve itself.

**Comment by icculus** [comment]
> preprocessor defines means that we have to patch the SDL source as part of the iOS build process. This isn't too inconvenient but is still less than ideal, especially when the code from the OP used to work for us out of the box.

To be clear, you're patching that out of the SDLmain library, so the right thing to do is just not link with it, since you're supplying your own entry point and apparently taking steps to deal with that.

**Comment by TheSpydog** [comment]
> > preprocessor defines means that we have to patch the SDL source as part of the iOS build process. This isn't too inconvenient but is still less than ideal, especially when the code from the OP used to work for us out of the box.
> 
> To be clear, you're patching that out of the SDLmain library, so the right thing to do is just not link with it, since you're supplying your own entry point and apparently taking steps to deal with that.

As far as I can tell, there is no SDLmain library for iOS currently. There is only the one "Static Library-iOS" target in Xcode, which is the one that I'm linking with. It includes this SDL_uikit_main file, so there is no way to work around this other than patching it out of the source.

**Comment by icculus** [comment]
Oh, hmm, I could swear this was separated out. Let me check that today.

(The original issue--we had two copies of this function--still stands, though, so this might be a separate issue.)

**Comment by slouken** [comment]
@TheSpydog, in commit https://github.com/libsdl-org/SDL/commit/3a4b217d6c26df04f4afe05d5f0eec5edd14afef, I added SDL_MAIN_HANDLED which you can define in the SDL project if you provide your own main()
If you do that, you should make sure that you either instantiate SDL's application delegate another way, or have all the functionality that it provides covered by your application delegate.

**Comment by slouken** [comment]
For people linking with the dynamic library or Framework, I added targets to build libSDLmain.a for iOS and tvOS in https://github.com/libsdl-org/SDL/commit/3e76646cc6415a918f7635e8c9671ea8233d05e7

I also tried to reproduce the original issue, but since we include SDL_uikit_main.c in libSDL2.a, it seems like that is taken care of now.
