### ISSUE TITLE
iOS: SDL_Metal/Vulkan_GetDrawableSize returns non-retina dimensions

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3980]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.15
**Reported for operating system, platform:** iOS (All), x86

# Comments on the original bug report:

On 2021-01-10 23:32:59 +0000, Caleb Cornett wrote:

> If the Metal drawable size is queried before creating a Metal view, the non-retina dimensions will be returned instead of the full high-dpi drawable size.
> 
> This also applies to Vulkan since they share the GetDrawableSize implementation on UIKit.

On 2021-01-11 22:31:03 +0000, Alex Szpakowski wrote:

> Already fixed
> 
> *** This bug has been marked as a duplicate of bug 5431 ***

On 2021-01-11 22:32:50 +0000, Alex Szpakowski wrote:

> Oh, this is the iOS version of that other bug report, I see

**Comment by slime73** [comment]
Hi @TheSpydog (I think it was you who created this bug report on Bugzilla - if not, apologies).

Now that I've taken the time to think about this behaviour, I don't think changing it to what you suggest is correct.

It just happened to incidentally work on macOS+OpenGL because of a quirk in the implementation of OpenGL window surfaces. But getting the size of a metal or opengl or vulkan drawable surface doesn't make logical sense until the drawable surface is created. The current behaviour of SDL_GL_GetDrawableSize and SDL_Metal_GetDrawableSize on iOS reflects that fact – ie it doesn't return the size of the GL or Metal drawable before creating one, because there is no GL or Metal drawable to query the size of.

**Comment by flibitijibibo** [comment]
We ended up nixing this anyhow - turns out it's actually a better idea to query drawable size later anyhow since multimonitor DPI support requires checking the scale on device changes.

I wonder if this is worth documenting, since we can't return an error code like we'd want to.

**Comment by slime73** [comment]
`SDL_GetWindowSizeInPixels` can be used instead now, which works even before a graphics surface has been created for a window (and the other GetDrawableSize APIs are removed in SDL3), so this can be closed now I think.
