### ISSUE TITLE
Creating a fullscreen desktop window goes windowed temporarily

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3991]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** macOS 10.14, x86_64

# Comments on the original bug report:

On 2021-01-17 02:55:20 +0000, Emily Pasfield wrote:

> When I make a fullscreen desktop window, it goes fullscreen for a split second, before going windowed quickly, then back fullscreen and continues running the program normally.
> 
> I make the window with this code:
> > SDL_Renderer *renderer;
> > SDL_Window *window;
> > SDL_CreateWindowAndRenderer(1440, 900, SDL_WINDOW_FULLSCREEN_DESKTOP, &window, &renderer);

On 2021-02-02 06:37:20 +0000, Sam Lantinga wrote:

> This was caused by trying to us a Metal renderer on an OpenGL window and SDL trying to recreate the window with the new parameters. It turns out we don't need to do that, at least on macOS 10.15.
> 
> This is fixed, thanks!
> https://hg.libsdl.org/SDL/rev/79c03aa2d7a8

On 2021-02-02 20:03:34 +0000, Sam Lantinga wrote:

> And now closed.

**Comment by slime73** [comment]
Hi @slouken , the commit that went in to fix this stops testsprite2 (and probably other programs that use SDL_Render) from choosing a Metal renderer by default.

Because the window isn't recreated with the correct flags anymore, `METAL_CreateRenderer`'s call to `SDL_Metal_CreateView` fails (since CreateView checks the window's flags). In testsprite2's case it ends up falling back to the OpenGL backend.

I'm not sure what the best fix for this would be. SDL adds the `SDL_WINDOW_OPENGL` flag to all SDL windows on macOS, but it doesn't do the same with `SDL_WINDOW_METAL` - according to a comment _METAL and _VULKAN flags are mutually exclusive? I don't understand that code enough to say if/why that's true.
