### ISSUE TITLE
[cmake] SDL2Config and SDL2Target not exporting SDL2_INCLUDE_DIRS

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4004]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2021-01-19 23:45:51 +0000, Parker Reed wrote:

> When using the newer SDL2Config.cmake vs the sdl2-config.cmake, SDL2_INCLUDE_DIRS is not being set
> 
> Referencing
> 
> https://github.com/dhewm/dhewm3/issues/340
> 
> System: Arch Linux with sdl2 2.0.14-1 and cmake 3.19.3-1

**Comment by DanielGibson** [comment]
related to this (describing the whole problem in more detail): https://discourse.libsdl.org/t/how-is-sdl2-supposed-to-be-used-with-cmake/31275

**Comment by DanielGibson** [comment]
To be honest, SDLs CMake support (for users who want to link SDL, no idea about building SDL with CMake) is a mess right now and using it creates more problems than it solve (at least if you want your code to be easy to build on different Linux distros and operating systems in general).

(This is both a condensed and enhanced version of the discussion in [the SDL discourse](https://discourse.libsdl.org/t/how-is-sdl2-supposed-to-be-used-with-cmake/31275)).

Depending on whether SDL2 has been built with autotools (./configure) or CMake it creates/installs either `sdl2-config.cmake` or `SDL2Config.cmake` (+ `SDL2Target.cmake` etc) - and both variations behave differently:

`SDL2Config.cmake` / `SDL2Target.cmake` (generated/installed by CMake):
* Defines CMake libraries `SDL2::SDL2` **and** `SDL2::SDL2main` and `SDL2::SDL2-static), with `add_library(SDL2::SDL2 ...)`
* Sets both `$prefix/include` and `$prefix/include/SDL2` as include directories for `SDL2::SDL2*`
* `SDL2::SDL2` does **not** implicitly link `libSDL2main` (I think this is useful!) - if you want libSDL2main, you gotta add both `SDL2::SDL2` and `SDL2::SDL2main` to your `target_link_libraries(YourApp ...)` call
* Links against libs by passing the full path to the .lib/.so/.a to the linker (and on Linux it uses `libSDL2-2.0.so.0.14.0` instead of `libSDL2.so` - yikes!)
* (On Windows, as far as I can tell) does **not** set additional linker flags (like `-lmingw32 -mwindows`)
* Does not hardcode its installation directory, paths seem to be relative to the position of `SDL2Config.cmake`
* Does **not** provide `SDL2_LIBRARIES`, `SDL2_INCLUDE_DIRS`, `SDL2_PREFIX` etc

`sdl2-config.cmake` (generated/installed when building SDL2 with autotools):
* Only defines `SDL2::SDL2*` since SDL2 2.0.12 (not useful right now, many Linux distros incl. Ubuntu 20.04 LTS and Debian/Raspbian stable ship older versions)
  - Apparently the `SDL2::SDL2` definition is also (sometimes?) broken, see #3665
* Only sets `$prefix/include/SDL2/` as include directory (=> the commonly used `#include <SDL2/SDL.h>` only works if the include directory is in the compilers standard search path anyway)
* `SDL2::SDL2` (if available at all) **does** implicitly link `libSDL2main`, and so does `SDL2_LIBRARIES` (=> no way to only link against `SDL2` itself - what if I want to link it to a library?)
* Links against libs by setting the include dir and the lib separately, like `-L${SDL2_LIBDIR}  -lSDL2main -lSDL2`
    - that syntax is GCC-(like-)specific though, while the full paths (as set by `SDL2Config.cmake` work with both GCC/mingw/clang and MSVC)
* (On Windows) it **does** set additional linker flags (`-lmingw32 -mwindows` and, as mentioned before, `-lSDL2main`) - both for `SDL2_LIBRARIES` and for `SDL2::SDL2`
* **Does** hardcode the installation directory/prefix
* Does provide `SDL2_LIBRARIES` etc (and before 2.0.12 that's all it provided)

Most Linux distros I checked (and FreeBSD) ship `sdl2-config.cmake`; Arch Linux (and derivatives) ship `SDL2Config.cmake` and so does vcpkg.
The official SDL2-devel-2.0.14-VC.zip doesn't include anything to use it with CMake.
In the official [SDL2-devel-2.0.14-mingw.tar.gz](https://www.libsdl.org/release/SDL2-devel-2.0.14-mingw.tar.gz) ships `sdl2-config.cmake` but it's useless because it hardcodes `/opt/local/x86_64-w64-mingw32` as prefix.

<br>

One step to make the whole situation a bit better would be to make `SDL2Config.cmake` also provide `SDL2_LIBRARIES` and `SDL2_INCLUDE_DIRS`; but that's not necessarily trivial (I have a half-finished solution I'll link later).

Another small thing would be fixing the paths in the `sdl2-config.cmake` of the official MinGW binaries by using `${CMAKE_CURRENT_LIST_DIR}/../../..` as `prefix` and make all other exported variables use that prefix instead of a hardcoded path - kinda like [this example](https://github.com/dhewm/dhewm3-libs/blob/master/i686-w64-mingw32/lib/cmake/SDL2/sdl2-config.cmake).  
However, this should only be done in those release binaries, not in `sdl2-config.cmake.in` in the repo, because not all platforms use the same (relative) paths, see e.g. `$prefix/lib/x86_64-linux-gnu/` instead of just `$prefix/lib/` on some Linux distros.

But apart from those fixes we'd need to define what behavior we even expect/want:
* Should SDL2main always be implicitly linked (on platforms that "need" it like Windows)?
  - IMHO: NO, but then we should probably have a mechanism for not doing this when using `sdl2-config` or `pkg-config` as well, and introduce one for the "classic" CMake `SDL2_LIBRARIES`
  - The old FindSDL.cmake (shipped with CMake for SDL1.2) allowed you to do `set(SDL_BUILDING_LIBRARY TRUE)` before calling `find_package(SDL REQUIRED)` and if which case it'd only link `libSDL` itself, not libSDLmain or libmingw32 or whatever
* Should `$prefix/include` be exported as an include directory, or only `$prefix/include/SDL2`?
   - IMHO: Exporting that would be a good idea - while I think it has been suggested to use `#include <SDL.h>` instead of `#include <SDL2/SDL.h`, AFAIK the latter is quite common and I'm not even sure if that suggestion was officially and prominently documented

**Comment by DanielGibson** [comment]
https://github.com/DanielGibson/SDL/tree/improve-cmake-configs has some code to set `SDL2_INCLUDE_DIRS` etc, windows-only so far

**Comment by DanielGibson** [comment]
See https://github.com/libsdl-org/SDL/pull/4320 for work in progress to address at least some of the aforementioned issues

**Comment by DanielGibson** [comment]
Additional fun: When building SDL2 for Windows with MinGW and CMake (so SDL2Config.cmake and SDL2Target.cmake are installed), linking applications against SDL with `target_link_libraries(SDL2Test  SDL2::SDL2main SDL2::SDL2)` doesn't work, because `SDL2::SDL2*` don't have the correct link order - `-lmingw32` must be first but SDL2main and SDL2 are linked first and libmingw32 seems to *implicitly* be linked statically at the end instead, which results in the following error:
```
/C/yq2buildenv/mingw32/bin/g++.exe    -Wl,--whole-archive CMakeFiles/SDL2Test.dir/objects.a -Wl,--no-whole-archive  -o SDL2Test.exe -Wl,--out-implib,libSDL2Test.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/SDL2Test.dir/linklibs.rsp
C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/yq2buildenv/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o): in function `main':
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
```
`CMakeFiles/SDL2Test.dir/linklibs.rsp` looks like:
`D:/dev/sdl2inst-mingw-cmake/lib/libSDL2main.a D:/dev/sdl2inst-mingw-cmake/lib/libSDL2.dll.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32`

I have no good idea how to fix this, as SDL2Targets.cmake and SDL2Targets-*.cmake are generated by CMake, apparently from the normal library definition used by CMake to build it, so I can't just hack around it like [I did for sdl2-config.cmake](https://github.com/libsdl-org/SDL/pull/4320/commits/8dde07fc120036b65d7c514b1b05ad7f7f163fc4).

By the way, consequently this means that my `SDL2_LIBRARIES` generated by SDL2Config.cmake on Windows (if SDL2 is built with MinGW+CMake) doesn't work either; though hacking this (by special casing `WIN32 AND NOT MSVC` or something like that) might be feasible, but ugly.

Ok, even uglier possibility would be to also special case SDL2::SDL2 and SDL2::SDL2main for those cases and practically replace the ones generated in SDL2Targets.cmake with hardcoded ones in SDL2Config.cmake (that only use the original ones to fetch the right paths; kinda like I already do in sdl2-config.cmake) when building with MinGW.. :vomiting_face: :vomiting_face: :vomiting_face:

**Comment by DanielGibson** [comment]
BTW, https://github.com/libSDL2pp/libSDL2pp/issues/66#issuecomment-177171413 has an explanation why -lmingw32 must be linked before SDL2main.
In short, it's because libmingw32 tries to call `WinMain()`, which is defined in libSDL2main. But as this the `ld` linker, it has already thrown the `WinMain()` symbol from libSDL2main away if `-lSDL2main` is before `-lmingw32` (if `-lmingw32` is not explicitly set, it's implicitly linked last).
Apparently `ld` handles static libs (like libSDL2main) differently from the object files created from your own source - otherwise a simple non-SDL program that defines `WinMain()` wouldn't work either.

What's extra weird: If I build SDL2 and SDL2main with CMake+MSVC, but my test app with MinGW, for some reason compiling works *without* explicitly linking against `-lmingw32` first. No idea why - *could* be that .lib static libs (as created by MSVC but supported by MinGW) are handled differently than .a static libs and that the linker then doesn't discard the `WinMain()` from SDL2main..

**Comment by DanielGibson** [comment]
#4320 should now be ready to be reviewed and merged.

Also, Hot Take: SDL2main should be a single header library instead of a static lib - that would completely resolve all the linking order problems discussed earlier, and would make choosing whether to use it easier (and transparent).

Using it would be as simple as `#include <SDL_main_impl.h>` (or just `#include <SDL_main.h>` if you don't mind changing its semantics and stop automatically including it in other SDL headers).
It could do all the things `SDL_main.h` does **and** provide an inline implementation of the real main (`WinMain()` or whatever) that calls `SDL_main()`.

And if you don't want to use it (it's not strictly needed on most or even all platforms, right?), you don't include that header which is much easier than trying to filter it out of the output of `sdl2-config` or `pkg-config` or CMake's `SDL2_LIBRARIES`.

**Comment by madebr** [comment]
Hello!
I created https://github.com/libsdl-org/SDL/pull/5727 which keeps `SDL2Config.cmake` compatible with autotools' `sdl2-config.cmake` and, at the same time, greatly simplifies it. 

In short, I could avoid the requirement of adding mingw32 to the link libraries by using `-Wl,--undefined,_WinMain@16`/`-Wl,--undefined,WinMain` for respectively 32/64-bit mingw.
I also kept `SDL2::SDL2main` and `SDL2::SDL2` completely separate (no linking is done between both).

This is done because for cli win32 sdl2 applications, you don't need a `WinMain`.

The intended CMake usage would then become:

Use in a gui application:
```cmake
find_package(SDL2 REQUIRED)
add_executable(main_gui WIN32 main_gui.c)
if(TARGET SDL2::SDL2main)
    target_link_libraries(main_gui PRIVATE SDL2::SDL2main)
endif()
target_link_libraries(main_gui PRIVATE SDL2::SDL2)
```

Use in a cli application:
```
find_package(SDL2 REQUIRED)
add_executable(main_cli main_cli.c)
target_link_libraries(main_cli PRIVATE SDL2::SDL2)
```

The only issue people might be having is that `SDL2::SDL2main` MUST be linked to BEFORE `SDL2::SDL2`.
Otherwise, there will appear warnings about missing `SDL_*` symbols in e.g. [`main_getcmdline`](https://github.com/libsdl-org/SDL/blob/847539afebe1019c2e1320eccfbe2334d30a2bcc/src/main/windows/SDL_windows_main.c#L41).
This is in line with [the comment(s) above](https://github.com/libsdl-org/SDL/issues/4004#issuecomment-821921466).

It would be nice to receive feedback from the people in this thread, since you look like cmake experts.

**Comment by slouken** [comment]
> > (...) This is done because for cli win32 sdl2 applications, you don't need a WinMain.
> 
> Keep in mind that SDL2main (on Windows) does more than just providing a standard-C `int main(argc, argv)` for Windows GUI applications - it _also_ translates the commandline arguments it passes to the users main() to UTF-8. In your CLI example, the users main() would be called by Microsofts runtime directly, and the `argv` strings would be in the system encoding (like Windows-1252).

If I remember right, we always link SDLmain on Windows unless the application is specifically handling WinMain() themselves. In that case, they define SDL_MAIN_HANDLED in preprocessor defines. Maybe we should have a similar CMake variable that omits SDLmain and adds that preprocessor define?

**Comment by DanielGibson** [comment]
> If I remember right, we always link SDLmain on Windows unless the application is specifically handling WinMain() themselves.

No, even before my changes a year ago, linking SDL2::SDL2 did not imply linking SDL2main (at least when SDL2Config.cmake, which is generated when building SDL2 itself with CMake, is used).

`SDL2_LIBRARIES` on the other hand *did* always link both.

**Comment by DanielGibson** [comment]
(it's all super messy, and I kind of want to say "don't touch anything in the cmake stuff, except to duct-tape obvious bugs, until SDL3 - then breaking backwards compat doesn't matter and it can all be done properly and unified".. but OTOH no idea when SDL3 is due and maybe rewriting it like this really makes things better until then and doesn't add too many new bugs)

**Comment by madebr** [comment]
> Keep in mind that SDL2main (on Windows) does more than just providing a standard-C `int main(argc, argv)` for Windows GUI applications - it _also_ translates the commandline arguments it passes to the users main() to UTF-8. In your CLI example, the users main() would be called by Microsofts runtime directly, and the `argv` strings would be in the system encoding (like Windows-1252).

Thanks for the reminder. I am focusing on the build system here, so am ignoring any side effects.

> `SDL2_LIBRARIES` on the other hand _did_ always link both.

I restored this behavior.
As a result, the cli test with variables will fail to link on mingw because it cannot find the `SDL_main` symbol.


> (it's all super messy, and I kind of want to say "don't touch anything in the cmake stuff, except to duct-tape obvious bugs, until SDL3 - then breaking backwards compat doesn't matter and it can all be done properly and unified".. but OTOH no idea when SDL3 is due and maybe rewriting it like this really makes things better until then and doesn't add too many new bugs)

I am not going to deny the current cmake config is super messy :).

Using this build script (to be placed in the root of `SDL`): [build_all.sh.zip](https://github.com/libsdl-org/SDL/files/8820421/build_all.sh.zip),
I compared the behavior between current master and this pr (it builds SDL2 6 times autotools+cmake and using native+mingw32+mingw64)

This [`cmake/test/CMakeLists.txt`](https://github.com/libsdl-org/SDL/files/8820453/CMakeLists.txt) is capable to build against current master.
Because the CMake generated SDL2Config.cmake from current master does not support MinGW, I had to disable a few combinations (+ a segfault in the linker).

 For SDL3, I propose to get rid of all exported variables and only export targets.

**Comment by madebr** [comment]
Fixed in current main.

**Comment by DanielGibson** [comment]
> Also, Hot Take: SDL2main should be a single header library instead of a static lib - that would make choosing whether to use it easier (and transparent) and it'd solve both the linking order issues mentioned earlier, and the issue that you can't link a (static) SDL2main created with MinGW with Visual C++ (because MinGW doesn't seem to support SAFESEH; you _can_ link a SDL2.dll created with MinGW as long as you create a SDL2.lib with VC++'s `lib.exe`, but AFAIK static libs are just incompatible).
> 
> Using it would be as simple as `#include <SDL_main_impl.h>` (or just `#include <SDL_main.h>` if you don't mind changing its semantics and stop automatically including it in other SDL headers). It could do all the things `SDL_main.h` does **and** provide an inline implementation of the real main (`WinMain()` or whatever) that calls `SDL_main()`.
> 
> And if you don't want to use it (it's not strictly needed on most or even all platforms, right?), you don't include that header which is much easier than trying to filter it out of the output of `sdl2-config` or `pkg-config` or CMake's `SDL2_LIBRARIES`.

And now I did this, for SDL3: https://github.com/libsdl-org/SDL/pull/6750 - testing and review is welcome! :)
