### ISSUE TITLE
Android black screen on resume using OpenGL ES 2.0

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#4041]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Android (All), ARM

# Comments on the original bug report:

On 2021-02-02 22:01:29 +0000, Vitaly Novichkov wrote:

> Hello!
> 
> I found that the bug against the black screen on resuming got back, it happens on various devices:
> - Open the game
> - Switch to another application, try to do anything
> - Try to switch the game back
> - You'll get the black screen
> - However, the game itself will resume its normal work, but a black screen
> - No matter what to draw: textures or color-filled shapes
> - I do render into texture, then into the screen. Also, I draw some shapes on the screen directly.
> This happens on Android 4.1, 5.1, Android 10, also on Android 8 the bug confirmed.
> 
> At the logger I get the next spamming:
> -------------------------------------
> 
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/libEGL: eglMakeCurrent:777 error 3002 (EGL_BAD_ACCESS)
> 02-03 00:55:02.482 3666-3690/ru.wohlsoft.thextech.debug E/EGL_emulation: tid 3690: eglMakeCurrent(1500): error 0x3002 (EGL_BAD_ACCESS)
> 
> -------------------------------------
> If needed, I can try to compose a simple unit test that reproduces this bug

On 2021-02-03 07:21:14 +0000, Sylvain wrote:

> Did you make sure not to call any rendering function between the two events
> SDL_WILL_ENTER_BACKGROUND and SDL_DID_ENTER_FOREGROUND
> 
> see docs/README-android.md

On 2021-02-03 21:50:38 +0000, Vitaly Novichkov wrote:

> Oh, interesting, how I messed this up? Gonna try this out... Thanks for the notice!

On 2021-02-03 22:19:12 +0000, Vitaly Novichkov wrote:

> btw, does that also counting the rendering into the texture too? Okay, I'll check.

On 2021-02-03 23:16:12 +0000, Vitaly Novichkov wrote:

> Nope, that didn't help completely, even I made the strict avoiding of any render functions being called, I still can get the black screen and the EGL_BAD_ACCESS error after I switched application back

On 2021-02-04 07:24:08 +0000, Sylvain wrote:

> that really really is a reason,
> are you depleting the event loop ?
> no multi-threading ?
> 
> really stop using renderer after reading WILL_ENTER_BG, and start again using DID_ENTER_FG.
> 
> are you using the SDL_Renderer or your own context ?

On 2021-02-04 08:02:26 +0000, Vitaly Novichkov wrote:

> > are you depleting the event loop ?
> 
> No, I do call the event loop sequentially
> 
> > no multi-threading ?
> 
> No, single threading
> 
> > really stop using renderer after reading WILL_ENTER_BG, and start again using DID_ENTER_FG.
> 
> Oh, I did a mistake - I used the WILL_ENTER_FG instead of WILL_ENTER_BG event, I should re-try this experiment again.
> 
> > are you using the SDL_Renderer or your own context ?
> 
> I use SDL_Renderer

On 2021-02-04 08:32:58 +0000, Vitaly Novichkov wrote:

> Okay, I really made sure no render will be called between those events, I even added asserts to crash if any of the render calls will be executed after `SDL_APP_WILLENTERBACKGROUND` event, and allow them to be called after `SDL_APP_DIDENTERFOREGROUND` event that unlocks the render.

On 2021-02-04 08:35:03 +0000, Vitaly Novichkov wrote:

> The result is the same, on Android 10:
> - open the game
> - switch another application (my log will print the fact "SDL_APP_WILLENTERBACKGROUND" was coming, I made sure those messages be printed to see the result)
> - All big render calls got blocked by a boolean
> - All small routine render calls got blocked by assert
> - Switch the game back (my log will print the fact of "SDL_APP_DIDENTERFOREGROUND")
> - Black screen

On 2021-02-04 08:41:00 +0000, Vitaly Novichkov wrote:

> I also checked the fact of any attempts to call the render calls, just by spamming of the same message into the log, the spamming is off completely when entering background, and getting on back when entered background.

On 2021-02-04 08:48:27 +0000, Sylvain wrote:

> 
> 
> >> are you depleting the event loop ?
> > No, I do call the event loop sequentially
> 
> before each frame, and also periodically, you must poll all the events.
> 
> 
> Just to make sure, all functions using the SDL_renderer includes: RenderCopy, RenderPresent, CreateTexture, UpdateTexture, ..

On 2021-02-04 08:55:37 +0000, Vitaly Novichkov wrote:

> > before each frame, and also periodically, you must poll all the events.
> 
> Yes, that what I already do, I poll all events in every loop cycle
> 
> 
> > Just to make sure, all functions using the SDL_renderer includes:
> 
> 
> > CreateTexture, UpdateTexture
> I don't call them during the loop except for the lazy-decompression algorithm that gets executed when calling the big render call, I blocked by the boolean
> 
> 
> > RenderCopy, RenderPresent
> Both blocked by the boolean I do set

On 2021-02-04 09:15:34 +0000, Sylvain wrote:

> This look strange ...
> 
> you have recent SDL2 lib + sync'ed java file ?
> 
> you can add trace here:
> http://hg.libsdl.org/SDL/file/1cde3dd0f44d/src/video/android/SDL_androidevents.c
> to backup and restore context
> 
> maybe log the event: SDL_RENDER_DEVICE_RESET
> 
> with those print do you have a full adb log to check ?
> 
> try with a simpler test case ?

On 2021-02-04 09:47:04 +0000, Vitaly Novichkov wrote:

> Closing to the evening (UTC+3) I'll try to compose a simple test program that simulates my and verify the work.

On 2021-02-04 09:52:02 +0000, Vitaly Novichkov wrote:

> Anyway, without of SDL2 patching, I did the tracking of SDL_RENDER_DEVICE_RESET event, and I got next:
> 
> ```
> 02-04 12:50:08.444 2791-2814/ru.wohlsoft.thextech.debug D/TRACKERS: Android: Entering background
> 02-04 12:50:16.879 2791-2814/ru.wohlsoft.thextech.debug D/TRACKERS: Android: Resumed foreground
> 02-04 12:50:19.591 2791-2814/ru.wohlsoft.thextech.debug D/TRACKERS: Android: Entering background
> 02-04 12:50:23.807 2791-2814/ru.wohlsoft.thextech.debug D/TRACKERS: Android: Resumed foreground
> 02-04 12:50:27.021 2791-2814/ru.wohlsoft.thextech.debug D/TRACKERS: Android: Entering background
> 02-04 12:50:32.787 2791-2814/ru.wohlsoft.thextech.debug D/TRACKERS: Android: Resumed foreground
> 02-04 12:50:32.787 2791-2814/ru.wohlsoft.thextech.debug D/TRACKERS: Android: Render Device Reset
> ```
> 
> I had multiple times to go into the background, and then, resume back, but the thing got blacked once SDL_RENDER_DEVICE_RESET was happened at my log

On 2021-02-04 09:54:51 +0000, Vitaly Novichkov wrote:

> So, seems once this event came:
> 
> ---
> SDL_RENDER_TARGETS_RESET
> 	
> 
> the render targets have been reset and their contents need to be updated (>= SDL 2.0.2)
> 
> SDL_RENDER_DEVICE_RESET
> 	
> 
> the device has been reset and all textures need to be recreated (>= SDL 2.0.4)
> ---
> I should reload all the textures again, right?

On 2021-02-04 09:55:33 +0000, Vitaly Novichkov wrote:

> I'll try some in the evening after my workday will finish.

On 2021-02-04 12:26:04 +0000, Sylvain wrote:

> yep, re-create texture once you get the device reset.
> (you don't need to recreate the SDL renderer)

On 2021-02-04 12:53:31 +0000, Sylvain wrote:

> Updated the android README file because this is a recurrent issue
> http://hg.libsdl.org/SDL/rev/8609e27b3eed
> 
> feel free to improve it!

**Comment by Wohlstand** [comment]
Gonna resume the work on this at me. To confirm the solution of this I must implement the textures reloading at me. However, I still have some questions on this:
- Should I destroy all old `SDL_Texture*` objects or they already got self-destroyed and I will have the set of the dead pointers?
- Forgot to tell you that this bug also affects the drawing of texture-less shapes, probably that because the render settings also got been reset too, right?

**Comment by Wohlstand** [comment]
Okay, I did an attempt to handle the `SDL_RENDER_DEVICE_RESET` and reload some of the textures, however, that didn't help:
- Attempt to use SDL_CreateTexture() caused me `E/libEGL: eglMakeCurrentImpl:1321 error 3002 (EGL_BAD_ACCESS)` error
- When I trying to remove an old texture by `SDL_DestroyTexture()`, I get the same.
- Attempt to call `SDL_SetRenderTarget(m_gRenderer, NULL);` have caused the same error
Now I need to try what will happen if I'll re-create the renderer context :thinking:

**Comment by ell1e** [comment]
Usually how this works from my own experience a long while back is that you're basically supposed to not touch the SDL2 graphics API any more in *any* way once SDL_WILL_ENTER_BACKGROUND reached you. This includes destroying textures, or querying them in any way, or doing anything to the renderer (like destroying it). If you have mechanisms that may garbage collect textures while in background you need to queue up the deletions instead and wait to do them until the app returns into foreground. If you still see EGL_BAD_ACCESS, it usually means you forgot some code accessing any texture, any renderer, any OGL context which violated this rule. If you leave everything alone until the app is back it should usually magically "just work." From your description, it seems like you maybe didn't follow this approach so it looks a little like it might be a bug in your code then, not an SDL2 bug.

**Comment by Wohlstand** [comment]
I guess that the whole issue should have the "help wanted" tag rather than "bug".

**Comment by samgubernick** [comment]
I assume the issue I'm having is the same. SDL is apparently not getting the OpenGL context when the app comes back into focus. I posted more about this here: https://discourse.libsdl.org/t/sdl-2-0-14-error-after-reentering-android-activity/28701

I'm not sure how to set break points in Android Studio for SDL, but from what I'm observing, either android_egl_context_restore(SDL_Window *window) or android_egl_context_backup(SDL_Window *window) isn't working correctly. Those are in video/android/SDL_androidevents.c. SDL still has a lock on the context so I can't call SDL_GL_CreateContext() or SDL_GL_DeleteContext(). GetCurrentContext() returns nullptr without an error code, and CreateContext() fails because there's an existing context.

**Comment by Wohlstand** [comment]
@samgubernick, interesting... Initially, I got the guide that I don't need to re-create the context:
> yep, re-create texture once you get the device reset.
    (you don't need to recreate the SDL renderer)

, but that didn't help: re-created textures won't work, and there are even texture-less primitives that won't be drawn.

**Comment by Wohlstand** [comment]
> I'm not sure how to set break points in Android Studio for SDL

You can do that if you build the SDL2 library on your own, simply browse actual source files, open them, and set, them should work. Files must be located at the places where they have placed while the build process.

**Comment by ell1e** [comment]
From when I last tried this you definitely don't need to recreate anything, not the textures either, unless something major changed in the few last SDL2 releases. But you sure would be required to not **touch anything at all in any way** about the textures, the context(!), the renderer, the windows for things like size, or anything which could access the GL context. @samgubernick you also really shouldn't need to modify the SDL2 code to make anything a weak reference. Any specific reason why you did so? Just getting a black screen after resume can also happen due to a lot of reasons, so you may not e having the same issue at all.

Also, if BLOCK_ON_PAUSE is 1 (which used to be the default) then as soon as the app pauses your event loop should freeze anyway. My deepest apologies if that should have changed too, I tried all of this about two years back. But I wouldn't have heard of any changes to this at least.

**Comment by samgubernick** [comment]
Thanks for all that info. Yeah, I tried adding the weak reference because of the suggestion in Android Studio about the memory leak from the static Context, but I took that out and just used the original one from SDL.

So, I tried a few different things to isolate the issue. I haven't had a chance to use breakpoints in SDL but I replaced the entire run() loop with just a basic while(true) and SDL_PollEvent() and I'm still getting an error about the context.

while(true)
{
   SDL_PollEvent();
   if (SDL_GL_GetCurrentContext() != nullptr) // this evaluates to true
   {
      glCheckFramebufferStatus(GL_FRAMEBUFFER); // this is returning GL_FRAMEBUFFER_UNDEFINED
      glClear(GL_COLOR_BUFFER_BIT); // This is getting an "Invalid framebuffer operation" error from OpenGL
   }
}

When that's first running, everything's fine. After switching tasks and then reopening it on my Pixel 3, I start getting errors. For just testing this now, there's no other task running, so nothing should be touching OpenGL after the SDL_APP_WILLENTERBACKGROUND event since the program's just in that above loop. If I try to reinitialize OpenGL after glCheckFramebufferStatus(), I'll get a segmentation fault of some variety on the depth check:

        if (SDL_GL_GetCurrentContext() != nullptr)
	{
		if constexpr (LOG) { msg << "Context is valid--deleting..."; msg.out(LOG_DATA, log::Color::openGl); }
		SDL_GL_DeleteContext(context);
	} // this is running

	initializeAttributes();
	if constexpr (LOG) { msg << "Creating GL context"; msg.out(LOG_DATA, log::Color::openGl); }
	context = SDL_GL_CreateContext(window);
	if (context == nullptr)
	{
		if constexpr (LOG) { msg << "Failed to create GL context: " << SDL_GetError(); msg.err(LOG_DATA); }
	}
	else
	{
		if constexpr (LOG) { msg << "Successfully created GL context"; msg.out(LOG_DATA, log::Color::openGl); }
	} // this is running

	if constexpr (LOG) { msg << "Finished creating GL context"; msg.out(LOG_DATA, log::Color::openGl); }
	{
		auto majorVersion = int{ 0 };
		auto minorVersion = int{ 0 };
		SDL_GL_GetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, &majorVersion);
		SDL_GL_GetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, &minorVersion);

		msg << "OpenGL version: " << majorVersion << "." << minorVersion; msg.out(LOG_DATA, log::Color::openGl);

		msg << "Getting profile mask"; msg.out(LOG_DATA, log::Color::openGl);
		auto profileMask = int{ 0 };
		SDL_GL_GetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, &profileMask);

		msg << "Getting depth size"; msg.out(LOG_DATA, log::Color::openGl);
		auto depthSize = int{ 0 };
		if (SDL_GL_GetAttribute(SDL_GL_DEPTH_SIZE, &depthSize) == 0) // this is causing a segmentation error in SDL_video.c on line 3660: glGetIntegervFunc(attrib, (GLint *) value);
		{
			msg << "Success"; msg.out(LOG_DATA, log::Color::openGl);
		}
	}

I don't want to hijack the original bug report if you don't think this is related to it. Thanks again for all info you posted! It's really helpful to me. I'll see what else I can do to track this problem down.

**Comment by ell1e** [comment]
Are you running `SDL_GL_GetCurrentContext()` after you got `SDL_APP_WILLENTERBACKGROUND`? AFAIK you shouldn't do that either, instead use a global variable where after getting `SDL_APP_WILLENTERBACKGROUND` in `SDL_PollEvent` you skip any OpenGL check (even just if you got a context) entirely until you get `SDL_DID_ENTER_FOREGROUND`. The context never disappears, neither do window, textures, ... but any access while in background will (permanently!) break things.

**Comment by samgubernick** [comment]
Yeah, I replaced the contents of those events with return, so there's nothing touching OpenGL there, either. I'm confident I'm not touching OpenGL after the program starts to enter the background or before it completely comes back. Output from logging that loop:

       loop start
       loop end
       ...
       loop start
       sdlEventAppWillEnterBackground called
       sdlEventAppDidEnterBackground called
       <no output because it's in the background, and then I get this after reopening app>
       Adreno: OverrideNativeWindowFormat: Unable to find a format in sRGB colorspace for EGL format: 518
       Adreno: Create: Initialize failed
       sdlEventAppWillEnterForeground called
       sdlEventAppDidEnterForeground called
       GL_FRAMEBUFFER_UNDEFINED
       glClear: Invalid framebuffer operation
       
       

Do you have a simple OpenGL window program that I can test here? If not, I'll try to separate out my window code and the rest of it into a small repository so you can see exact what's going on. I'd like to contribute to fixing this if that's where the problem is, but I don't know the inside of SDL at all.

**Comment by ell1e** [comment]
I don't understand, your loop does not seem to be checking SDL_PollEvent as I suggested and avoiding any access to the context. As far as I know you can't just poll events and ignore them, you need to track the foreground/background state always.

**Comment by samgubernick** [comment]
Sorry, I oversimplified what I wrote. Yes, while(true) should've been a global called shouldRender in that example, and it only changes on WILL_ENTER_BACKGROUND and DID_ENTER_FOREGROUND. In terms of ignoring the polled events, how would that affect this particular case? After creating the window and the GL context, as long as I'm not touching the OpenGL again, is there something I actually need to handle apart from the filtered events? Plugging it back into my event handler, the only window events I'm seeing are focus lost, minimized, restored, and focus gained, and I'm not seeing any display-related events at all. I'm returning 0 on the filtered events so I wouldn't expect to see those in my event handler (I haven't confirmed that those aren't there).

I've stripped even more out to the point where all that loop is doing is outputting that it's running. No OpenGL checks or anything else. When the app goes into the background, I get log messages from the filtered events (WILL/DID_ENTER_BACKGROUND) and then complete silence. When I reopen it, I get the two Adreno errors:

      I/Adreno: OverrideNativeWindowFormat: Unable to find a format in sRGB colorspace for EGL format: 518
      I/Adreno: Create: Initialize failed

followed by the messages from WILL/DID_ENTER_FOREGROUND. Adding an SDL_Delay(200) to the loop to increment a variable, comparing that variable to 30, and then touching OpenGL, I'm getting the previous error about the invalid framebuffer.

I have to see why I can't get breakpoints in SDL to work in Android Studio. That would help me find what's going on in SDL since I can only follow it abstractly right now.

Thanks again for your help.

**Comment by ell1e** [comment]
> In terms of ignoring the polled events, how would that affect this particular case?

That can affect everything, because that takes one SDL event off the queue and that could be an `SDL_APP_WILLENTERBACKGROUND`. Every event must be checked for this, or you risk getting into an undefined state. So I'm not sure what exactly you're trying to do, but from looking at your code it seems kind of obvious to me that it won't work due to that alone.

> After creating the window and the GL context, as long as I'm not touching OpenGL again, is there something I actually need to handle apart from the filtered events?

But you are touching OpenGL, with `SDL_GL_GetCurrentContext`.

**Comment by samgubernick** [comment]
I understand what you're saying, but I think the confusion is coming from the unclear code that I posted above.

      namespace
         {
            bool shouldRender = false;

            void sdlEventFunctionAppDid...AppWill... // set shouldRender to true or false
            ...
            void customFilter()
            {
            ... // sends the events to the appropriate app event handler
            }
         }

       StartHere::now()
       {
          createWindow(); // this will set shouldRender to true
          SDL_SetEventFilter(customFilter, ptrToResources);
          ...
         auto t =  int{ 0 };
         while (true)
         {
             while (shouldRender)
             {
                logOut("loop start");
                events.checkEventsNoResources(); // handles SDL events, but while (SDL_PollEvent() == 1) would work, too, because of the filter
                
                SDL_Delay(200);
                ++t; // this won't increment while the app is minimized
                
                if (t == 30) // minimize the app before t reaches 30
                {
                   glBindFramebuffer(GL_FRAMEBUFFER, 0);
                   switch (glCheckFramebufferStatus(GL_FRAMEBUFFER))
                   {
                   // invalid framebuffer
                   }
                }
                logOut("loop end");
             }
         }
       }

I added the SDL app events to the event handler and I can confirm that the filter is correctly not sending them to the handler since they're each returning 0. As a note, I'm using the Mercurial build from a week or so ago, but I also had this problem in 2.0.14, which is why I tried upgrading to the development build. I'll see if the problem goes away if I can downgrade to 2.0.12 or even earlier.

When I have some time again, I'll try to get Android Studio to use breakpoints in SDL but I've gotten frustrated when I've tried this before; it just says it isn't part of my project. "This file does not belong to any project target, code insight features might not work properly,"

**Comment by ell1e** [comment]
You still seem to be doing `glBindFramebuffer` unconditionally. Why aren't you checking `shouldRender` before doing that?

**Comment by samgubernick** [comment]
Yeah, I completely get where you're coming from. The SDL documentation is a life saver for that--that was the only way I knew about the app events and the custom filter.

For this test on my phone, it's exactly what I posted apart from a few simplified sections that definitely are not using OpenGL. That was one of the reasons I replaced my own event handler with the dummy one that just pumps through the SDL events without doing anything. The thing with t was my idea to make sure that nothing in that loop wasn't touching OpenGL till well after SDL's sent DIDENTERFOREGROUND and my program handled it. I could post that one file/part of that file to GitHub if it'd help to confirm that I'm not calling any OpenGL function.

**Comment by ell1e** [comment]
I'm not sure I was 100% clear, so just in case I was not: `events.checkEventsNoResources` could mean you're now in the background. Then you'll still unconditionally call `glBindFramebuffer` right after. It just seems like your loop isn't set up right, even with the filter.

**Comment by samgubernick** [comment]
Thanks for the clarification. I copied/pasted this from the main loop:

	int t = 0;
	while (true) // the program should stay in this loop even when minimized
	{
		if constexpr (LOG) { msg << "A start"; msg.out(LOG_DATA); }
		if (!shouldRender)
		{
			//if constexpr (LOG) { msg << "Polling events..."; msg.out(LOG_DATA); }
			while (SDL_PollEvent(&events.sdlEvent) == 1)
			{

			}
			//if constexpr (LOG) { msg << "Finished polling events..."; msg.out(LOG_DATA); }
		}
		while (shouldRender)
		{
			//if constexpr (LOG) { msg << "B start"; msg.out(LOG_DATA); }

			//if constexpr (LOG) { msg << "Polling events..."; msg.out(LOG_DATA); }
			while (SDL_PollEvent(&events.sdlEvent) == 1)
			{

			}
			//if constexpr (LOG) { msg << "Finished polling events..."; msg.out(LOG_DATA); }

            ++t;
            SDL_Delay(200);
            if constexpr (LOG) { msg << "Run count (" << t << ")"; msg.out(LOG_DATA); }

	    if (t == 30 && shouldRender)
	    {
                // bind the framebuffer here
            }
            else if (false)
			{
			    if constexpr (LOG) { msg << "Shouldn't render"; msg.out(LOG_DATA); }
				auto a = 2;
				auto b = a;
			}
			//if constexpr (LOG) { msg << "B end"; msg.out(LOG_DATA); }
		}
		if constexpr (LOG) { msg << "A end"; msg.out(LOG_DATA); }
	}

**Comment by ell1e** [comment]
Yes, that one looks better (if you keep any GL stuff to the `bind the framebuffer here` section). Does that help?

**Comment by samgubernick** [comment]
It's possible the cause of this came from when I first created the context:

	if (SDL_GL_SetAttribute(SDL_GL_FRAMEBUFFER_SRGB_CAPABLE, SDL_ENABLE) != SUCCESS)
	{ // use srgb framebuffer for gamma correction
		if constexpr (LOG) { msg << "SDL error: " << SDL_GetError(); msg.err(LOG_DATA); }
	}

That works fine when I create the context the first time, but when I minimize it and then reenter it, the Adreno drivers fail. Commenting that line out has eliminated all of the Adreno errors in the log from my test code--I'll try reloading the whole game to see if it works correctly.

**Comment by 1bsyl** [comment]
Maybe you're receiving the event: SDL_RENDER_DEVICE_RESET 
see: https://github.com/libsdl-org/SDL/blob/main/docs/README-android.md

**Comment by 1bsyl** [comment]
This is what happens when the event is set:
https://github.com/libsdl-org/SDL/blob/main/src/video/android/SDL_androidevents.c#L68
the device is re-created internally, so you probably only need to get it again.

**Comment by Wohlstand** [comment]
> SDL_GL_GetCurrentContext

That for the case when I do use OpenGL directly, I do use the `SDL_Renderer` context created by the `SDL_CreateRenderer()` call with the `SDL_RENDERER_ACCELERATED` flag. I asked how to revive the context at the `SDL_Renderer`'s backend that I use at my side.

**Comment by Wohlstand** [comment]
Oh, should the `SDL_GetRenderer()` work?

**Comment by 1bsyl** [comment]
if you use SDL_Renderer then you only need to delete, then re-create all the texture you use

**Comment by Wohlstand** [comment]
I did, but the `EGL_BAD_ACCESS` error had occurred in just an attempt to create the texture, and there are even non-textured primitives (color-filled rectangles) that won't render after the RESET event came.

**Comment by 1bsyl** [comment]
Then you've something wrong. Maybe when calling function while in background. I'd suggest to re-start with a plain hello world to figure out.

**Comment by Wohlstand** [comment]
> Then you've something wrong. Maybe when calling function while in background. I'd suggest to re-start with a plain hello world to figure out.

I did the wide check, and the application never calls any render functions while in the background, even I made the protections from off them to avoid any possible render call done in the background. But you right, I should compose the simple application and verify the work of it. In another case, the SDL activity isn't the main activity: it gets open by the separated launcher Java activity (I made it to let the user setup the game before starting the actual game). I'll try to make a similar case but in a form of a dummy application that will be as simple as possible.

**Comment by 1bsyl** [comment]
Just wondering: 
which android device do you use ? does this happen with any device ?
do you use latest SDL2 source ?

If you are not changing the BLOCK_ON_PAUSE feature, you shouldn't even care about using or not the renderer, because the pollEvent call is blocking when the app is in background.

Another thing: can you try to comment out in SDL_renderer, the is a call to "glFinish()"  (src/render/opengles2/SDL_render_gles2.c), which look suspicious because it's called from another thread than the rendering thread.

**Comment by Wohlstand** [comment]
>  which android device do you use ? does this happen with any device ?

I have multiple different devices:
- My SGN9 with Android 10
- My Archos 70c tablet with Android 5.1
- My friend's Retroid Pocket thing that using the Android 8

All those devices have the same behavior

>  do you use latest SDL2 source ?

I do use the 2.0.14 release yet, do you suggest to me try the latest dev version to verify the work?

> BLOCK_ON_PAUSE

I never touched this hint, it works at me in its default value.

> Another thing: can you try to comment out in SDL_renderer, the is a call to "glFinish()" (src/render/opengles2/SDL_render_gles2.c), which look suspicious because it's called from another thread than the rendering thread.

I'll need to try that...

**Comment by 1bsyl** [comment]
Since there is a recent device in the list, I think this ok. 
2.0.14 .. is also recent and should be fine.

- you can try the glFinish, but I don't think this is that, otherwise I would also have such black screen.
- there is  a "debug_enabled" that you can set to SDL_TRUE in opengles2 renderer ...
- maybe this helps, before creating the window:
```
    SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 5);
    SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 6);
    SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 5);
```
- reading the back-log, just to make sure: 
  in your main look, where you check the events, you must poll *all* the events. I mean to deplete the event queue.

**Comment by samgubernick** [comment]
A quick update: SDL_GL_SetAttribute(SDL_GL_FRAMEBUFFER_SRGB_CAPABLE, SDL_ENABLE) was the exact cause of my problem. After removing that (even though SDL's able to create the initial context correctly), I'm able to load data back into the new GL context and run the shader programs. Any chance you're doing something similar?

**Comment by Wohlstand** [comment]
I should try the same...

**Comment by Wohlstand** [comment]
Nope, with the case of SDL Renderer, that didn't help. I have another idea to try. On the side, I have another SDL2-game that doesn't have this bug, I gonna upgrade the SDL2 on it and try to see its behavior... The one difference that I build the SDL2 with the ANDROID.mk via the overlay made at CMake, at this game I do build SDL2 with the CMake build directly.

**Comment by Wohlstand** [comment]
Okay, just now I made the experiment on building the SDL2 through "Android.mk" file, and the result is still be same faulty... However, the difference:
- at my other game I do start the SDL2 activity directly
- at this application I do start the Java-side hand-made activity called "launcher", and then I do start the SDK Activity by the next code:
```java
        Intent myIntent = new Intent(Launcher.this, thextechActivity.class);
        myIntent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
        Launcher.this.startActivity(myIntent);
        Launcher.this.finish();
```
and, when I trying to resume that activity, I get the fault

**Comment by Wohlstand** [comment]
Probably I'll try to compose the simple unit test application that draws simple primitives to verify the thing at all...

**Comment by Wohlstand** [comment]
Okay, just now I made a simple application and I placed it here:
https://github.com/Wohlstand/SDL2-Android-Example

so, I had to implement the same rendering sequence as my game, I did next experiments:
- Simply render color squares: no bug
- Try to draw the same squares on a texture: BUG APPEARS HERE!
- Okay, I also did render of the third square, but drawn on the screen itself, not on the textured surface: BUG STILL APPEARS HERE, and there were no textures loaded, except one created from the scratch for the target rendering.

HOWEVER:

After some tweaks, I finally found the reason for the mess, look:

At my game I did the next:
- After the game loading and initialization of everything, I set `SDL_SetRenderTarget(m_gRenderer, m_tBuffer);`
- Then I draw all stuff on the texture attached
- Then, I do `SDL_SetRenderTarget(m_gRenderer, nullptr);` to draw the texture and on-screen buttons.
- Before doing the `SDL_RenderPresent(m_gRenderer);`, I did `SDL_SetRenderTarget(m_gRenderer, m_tBuffer);`
- Then, wait, and go for the next loop

So, when I accidentally did the experiment, and I had to change the way of texture target:
- After the game loading and initialization of everything, I set `SDL_SetRenderTarget(m_gRenderer, m_tBuffer);`, then, after I'll clean the surface, I do `SDL_SetRenderTarget(m_gRenderer, nullptr);` at final
- At begin of render function, I call `SDL_SetRenderTarget(m_gRenderer, m_tBuffer);`
- Then I draw all stuff on the texture attached
- Then, I do `SDL_SetRenderTarget(m_gRenderer, nullptr);` to draw the texture and on-screen buttons.
- Then, I do the `SDL_RenderPresent(m_gRenderer);`
- Then, wait, and go for the next loop

The way I made had fixed the bug at my demo application, so, gonna try the game itself!

Conclusion: this was a VERY WEIRD bug, and it was MINE, because I messed up with the texture target, and didn't guess that until I built the simple demo application by myself... If the game will get this bug solved, I'll say, please add the note about the rendering into the texture: unplug any texture targets until to do the `SDL_RenderPresent(m_gRenderer);` and never keep the texture target be say forever, plug the texture target in only condition when it's really needed!

**Comment by Wohlstand** [comment]
P.S. To replay the invalid behavior, please comment the `#define TEXTURE_TARGET_ORDER_VALID` line at `main.cpp`, and the buggy behavior will be, otherwise keep it to see the proper work.

**Comment by Wohlstand** [comment]
Okay, so, I refactored my game side to make sure the screen target will be always kept before and after repainting and do set the texture target in the only condition when the in-game world gets rendered.

**Comment by baidwwy** [comment]
me too
I'm not using textures, just fillrect
SDL_RenderClear returns not 0
GetError
Unable to make EGL context current (call to eglMakeCurrent failed, reporting an error of EGL_BAD_ACCESS)

SDL 2.0.18
android 7.1.1

sorry i don't speak english, this is from google translate

**Comment by baidwwy** [comment]
SDL_SetHint(SDL_HINT_RENDER_BATCHING, "1");
after
looks like normal

**Comment by crudelios** [comment]
After two days scratching my head I found this issue and I can confirm that removing the render target does fix the problem.

Note that instead of constantly swapping the render target during normal texture drawing,  an alternative to prevent the black screen is simply to set  the render target to `NULL` on the `WILL_ENTER_BACKGROUND` event, then restore the render target on the `DID_ENTER_FOREGROUND` event.

**Comment by 1bsyl** [comment]
Thanks, I've added a comment, 
let's say this fix the issue ..
