### ISSUE TITLE
CPU_haveARMSIMD() for Linux

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#4095]
SDL_cpuinfo.c:CPU_haveARMSIMD() for Linux case has:
https://github.com/libsdl-org/SDL/blob/main/src/cpuinfo/SDL_cpuinfo.c#L378
```
        Elf32_auxv_t aux;
        while (read(fd, &aux, sizeof aux) == sizeof aux)
        {
            if (aux.a_type == AT_PLATFORM)
            {
                const char *plat = (const char *) aux.a_un.a_val;
```

Do we not need `Elf64_auxv_t aux;` for 64 bit platforms? Because
a_type and a_un.a_val are uint32_t in Elf32_auxv_t, but uint64_t in
Elf64_auxv_t.  E.g.:
```
diff --git a/src/cpuinfo/SDL_cpuinfo.c b/src/cpuinfo/SDL_cpuinfo.c
index 896b4dd..b792ae2 100644
--- a/src/cpuinfo/SDL_cpuinfo.c
+++ b/src/cpuinfo/SDL_cpuinfo.c
@@ -375,7 +375,11 @@ CPU_haveARMSIMD(void)
     fd = open("/proc/self/auxv", O_RDONLY);
     if (fd >= 0)
     {
+#ifdef _LP64
+        Elf64_auxv_t aux;
+#else
         Elf32_auxv_t aux;
+#endif
         while (read(fd, &aux, sizeof aux) == sizeof aux)
         {
             if (aux.a_type == AT_PLATFORM)
```

I don't have anything-arm to test (or compile), however did I notice
this when building SDL-1.2 for x86_64, where CPU_haveARMSIMD() is not
guarded against `__arm__` define (which may be an oversight), and got
a -Wint-to-pointer-cast warning.

**Comment by sezero** [comment]
@bavison: `CPU_haveARMSIMD` was added by you, is the patch above correct?

**Comment by ccawley2011** [comment]
> Do we not need `Elf64_auxv_t aux;` for 64 bit platforms? Because
> a_type and a_un.a_val are uint32_t in Elf32_auxv_t, but uint64_t in
> Elf64_auxv_t.

It shouldn't be neccessary, since SIMD and NEON are always available with AArch64.

> I don't have anything-arm to test (or compile), however did I notice
> this when building SDL-1.2 for x86_64, where CPU_haveARMSIMD() is not
> guarded against `__arm__` define (which may be an oversight), and got
> a -Wint-to-pointer-cast warning.

This is fixed as part of libsdl-org/SDL-1.2#838.

**Comment by bavison** [comment]
It's worth noting that CPU_haveARMSIMD and CPU_haveARMNEON are actually used to activate functions that are currently only available in AArch32 assembly. Therefore, at present, I'd recommend that they return 0 when __aarch64__ is defined. Maybe at some point someone will translate them to AArch64, and at that point the return codes could change again.

I'd further note that CPU_haveARMSIMD is only really useful for distinguishing between different versions of the AArch32 instruction set. The relevant assembly code uses instructions like PKH and SMLAxx for SIMD operations on sub-32-bit data elements within general-purpose registers. There are no equivalent instructions in AArch64 - if you want to work on packed data like that, you're expected to use the NEON registers and instructions. Therefore there is unlikely to ever be a requirement for run-time switching of this feature for AArch64 binaries.

By contrast, there is a (small) chance that run-time switching based on NEON support might be required for AArch64 binaries. The Cortex-R82 (which uses exclusively AArch64) has optional NEON, and ARM's toolchain options imply that some architecture v8.0-A CPUs also omit NEON in AArch64 (though I couldn't tell you which CPUs are in that category).

**Comment by sezero** [comment]
> It's worth noting that CPU_haveARMSIMD and CPU_haveARMNEON are actually used to activate functions that are currently only available in AArch32 assembly. Therefore, at present, I'd recommend that they return 0 when `__aarch64__` is defined. Maybe at some point someone will translate them to AArch64, and at that point the return codes could change again.

OK, reverting the `__aarch64__` parts, like in the following patch,
should do the trick yes?
```
diff --git a/src/cpuinfo/SDL_cpuinfo.c b/src/cpuinfo/SDL_cpuinfo.c
index f0d14e8..e2531d7 100644
--- a/src/cpuinfo/SDL_cpuinfo.c
+++ b/src/cpuinfo/SDL_cpuinfo.c
@@ -340,7 +340,7 @@ CPU_haveAltiVec(void)
     return altivec;
 }
 
-#if (defined(__ARM_ARCH) && (__ARM_ARCH >= 6)) || defined(__aarch64__)
+#if defined(__ARM_ARCH) && (__ARM_ARCH >= 6)
 static int
 CPU_haveARMSIMD(void)
 {
@@ -448,7 +448,7 @@ CPU_haveNEON(void)
 #  endif
 /* All WinRT ARM devices are required to support NEON, but just in case. */
     return IsProcessorFeaturePresent(PF_ARM_NEON_INSTRUCTIONS_AVAILABLE) != 0;
-#elif (defined(__ARM_ARCH) && (__ARM_ARCH >= 8)) || defined(__aarch64__)
+#elif defined(__ARM_ARCH) && (__ARM_ARCH >= 8)
     return 1;  /* ARMv8 always has non-optional NEON support. */
 #elif defined(__APPLE__) && defined(__ARM_ARCH) && (__ARM_ARCH >= 7)
     /* (note that sysctlbyname("hw.optional.neon") doesn't work!) */
```

**Comment by bavison** [comment]
That still looks problematic to me, since __ARM_ARCH will be defined when compiling for AArch64 as well - at least judging from ARM's online Clang documentation and a quick experiment I just did with GCC. For example

Target CPU architecture | Instruction set | `__arm__` | `__aarch64__` | `__ARM_ARCH`
---------------------------------|--------------------|----------------|---------------------|---------------------
ARMv7                            | A32 or T32     | 1                | undefined         | 7
ARMv8                            | A32 or T32     | 1                | undefined         | 7
ARMv8                            | A64                | undefined  | 1                       | 8
non-ARM                         |                       | undefined  | undefined         | undefined

Unfortunately I don't have access to (for example) the Windows ARM compiler to comment on what that does, but I suspect you want something like

```
#if defined(__arm__) && (__ARM_ARCH >= 6)
```

I'd also repeat that the assumption that all architecture 8 ARMs have NEON is arguably not correct. I'd have thought it was safer to assume its absence if there isn't a run-time feature check code block for the system. If someone on an unusual platform notices the loss of performance from not having NEON, they're welcome to submit one.

**Comment by sezero** [comment]
Reopening this.   @bavison: do you have a patch?  @ccawley2011: comments?

**Comment by bavison** [comment]
How about the following (untested)? Elevates the test of `__arm__` to be the first thing tested (apart from the Windows case because Windows compilers just love to be different from everyone else) to ensure both optimizations are disabled for AArch64 builds, and removes the assumption that all ARMv8 CPUs must have NEON.

```
diff --git a/src/cpuinfo/SDL_cpuinfo.c b/src/cpuinfo/SDL_cpuinfo.c
index f0d14e83..50d37d78 100644
--- a/src/cpuinfo/SDL_cpuinfo.c
+++ b/src/cpuinfo/SDL_cpuinfo.c
@@ -340,18 +340,18 @@ CPU_haveAltiVec(void)
     return altivec;
 }
 
-#if (defined(__ARM_ARCH) && (__ARM_ARCH >= 6)) || defined(__aarch64__)
+#if !defined(__arm__)
 static int
 CPU_haveARMSIMD(void)
 {
-       return 1;
+       return 0;
 }
 
-#elif !defined(__arm__)
+#elif defined(__ARM_ARCH) && __ARM_ARCH >= 6)
 static int
 CPU_haveARMSIMD(void)
 {
-       return 0;
+       return 1;
 }
 
 #elif defined(__LINUX__)
@@ -440,7 +440,7 @@ CPU_haveNEON(void)
    query the OS kernel in a platform-specific way. :/ */
 #if defined(SDL_CPUINFO_DISABLED)
    return 0; /* disabled */
-#elif (defined(__WINDOWS__) || defined(__WINRT__)) && (defined(_M_ARM) || defined(_M_ARM64))
+#elif (defined(__WINDOWS__) || defined(__WINRT__)) && defined(_M_ARM)
 /* Visual Studio, for ARM, doesn't define __ARM_ARCH. Handle this first. */
 /* Seems to have been removed */
 #  if !defined(PF_ARM_NEON_INSTRUCTIONS_AVAILABLE)
@@ -448,15 +448,13 @@ CPU_haveNEON(void)
 #  endif
 /* All WinRT ARM devices are required to support NEON, but just in case. */
     return IsProcessorFeaturePresent(PF_ARM_NEON_INSTRUCTIONS_AVAILABLE) != 0;
-#elif (defined(__ARM_ARCH) && (__ARM_ARCH >= 8)) || defined(__aarch64__)
-    return 1;  /* ARMv8 always has non-optional NEON support. */
+#elif !defined(__arm__)
+    return 0;  /* ARM running AArch64 instruction set, or not an ARM CPU at all. */
 #elif defined(__APPLE__) && defined(__ARM_ARCH) && (__ARM_ARCH >= 7)
     /* (note that sysctlbyname("hw.optional.neon") doesn't work!) */
     return 1;  /* all Apple ARMv7 chips and later have NEON. */
 #elif defined(__APPLE__)
     return 0;  /* assume anything else from Apple doesn't have NEON. */
-#elif !defined(__arm__)
-    return 0;  /* not an ARM CPU at all. */
 #elif defined(__OpenBSD__)
     return 1;  /* OpenBSD only supports ARMv7 CPUs that have NEON. */
 #elif defined(HAVE_ELF_AUX_INFO)
```

**Comment by ccawley2011** [comment]
I should point out that the [audio type conversion](https://github.com/libsdl-org/SDL/blob/main/src/audio/SDL_audiotypecvt.c) also uses NEON, which appears to be supported on AArch64, meaning that with this patch, SDL won't use the NEON code on AArch64 (and will likely crash in the absence of the C versions to fall back on). The same thing potentially applies to other applications using SDL, since `SDL_HasNEON()` is part of the public interface. As such, it would be better to support runtime detection on AArch64 as well rather than always returning 1 or 0.

**Comment by bavison** [comment]
In that case, I think another flag bit and corresponding functions are required, so we can switch on either "have NEON and don't care about the instruction set" or "have NEON and is (or isn't) AArch64" so that the best optimization can always be selected. That could be any one of the CPU_haveAArch32NEON, CPU_haveAArch64NEON or CPU_haveAArch32 or CPU_HaveAArch64, where the latter two are tested in combination with CPU_haveNEON. Which way you go is up to taste.

**Comment by sezero** [comment]
@ccawley2011, @bavison:

What #4100 basically did really new was allowing `__aarch64__` to
report having SIMD- and NEON-capable, along with elevating priority
of `!__arm__ -> no NEON` check a little.

So: I we apply the patch from https://github.com/libsdl-org/SDL/issues/4095#issuecomment-782171951
we would practically go back to pre-#4100 state from the point of
allowing ARM SIMD/NEON code. Am I missing anything?  If I am not,
the pre-#4100 state has been there since about at least 13 months
i.e. SDL2-2.0.12, which no one screamed about ARM SIMD/NEON stuff.
So, how about that we remove `__aarch64__` additions of #4100 as
the first thing to do?

**Comment by sezero** [comment]
Another point / solution:

Main concern of @bavison was CPU_haveARMSIMD and CPU_haveARMNEON
activating functions that are currently only available in AArch32,
i.e. the arm blitting code enabled through `SDL_ARM_NEON_BLITTERS`
and/or `SDL_ARM_SIMD_BLITTERS`, yes?  If that's the only issue,
how about restricting the arm asm blit code to 32 bits only, like
adding `!(defined(__aarch64__) || defined(_M_ARM64))` around them?
