### ISSUE TITLE
life is strange uses incorrect pixel bit depth on wayland

### ISSUE THREAD

**Issue by soredake** [libsdl-org/SDL#4132]
With `SDL_VIDEODRIVER=wayland`:
![sway_wayland](https://cloud.githubusercontent.com/assets/5204968/25785812/cfdc1d4c-3378-11e7-936d-d96454620616.png)

With `SDL_VIDEODRIVER=x11`:
![sway_x11](https://cloud.githubusercontent.com/assets/5204968/25785825/f40b3b9e-3378-11e7-95c0-d30271d02457.png)

I've preloaded newer version (2.0.12+dfsg1-4) from ubuntu repos with ` LD_PRELOAD=/usr/lib64/libSDL2-2.0.so.0` but this happens with bundled steam runtime version too.

**Comment by icculus** [comment]
I just tried this with Wayland and it looks alright, but I have to confess that I don't see what's different in those two screenshots either (obviously the logo and text are different, but the color depth seems the same...?)

Can you tell me what part of this looks wrong? Is it obvious and I'm just looking too hard?  :)

**Comment by icculus** [comment]
Oh wait, I see the banding in the sky, nevermind.

**Comment by icculus** [comment]
Okay, this is happening because the game asks for an OpenGL 2.1 context and a 16-bit color depth.

On X11, asking for a 2.1 context will use the legacy glX context creation API, which means your OpenGL context will probably get the (24-bit) color depth of your desktop. A 3.0 context would be able to ask for more specific color depths, but they avoid this path.

On Wayland, there is no such limitation, and it is willing to hand the game a 16-bit surface to draw on, so the game gets exactly what it asks for.

I don't know _why_ it asks for this, but it appears to be hardcoded in the game binary and not some configuration thing. I suspect it was meant to be an attempt to not fail on old hardware but assume modern systems would always give it 24-bit color anyhow.

I bet this is the same bug as #4056, too.

I guess the appropriate thing to do is have our Wayland backend favor 32-bit configurations over 16-bit ones. I could see this causing problems on some embedded device, maybe, but it's probably the right thing to do on desktops.

**Comment by icculus** [comment]
Okay, latest in revision control fixes this problem. Go ahead and update your local build and let me know how it does!
