### ISSUE TITLE
Commit breaks Raspberry Pi compatibility

### ISSUE THREAD

**Issue by vanfanel** [libsdl-org/SDL#4135]
Hi there,

This latest KMSDRM commit breaks Raspberry Pi compatibility:

https://github.com/libsdl-org/SDL/commit/dfa64eadd38a6a8125290dcf121f1bc285e98dad

Video can't be initialized on the Pi with that, so please remove that commit or correct, I don't have the time to dig the problem, but the backend was working when I last I touched it.

Thanks.

**Comment by cgutman** [comment]
Looking into it

**Comment by cgutman** [comment]
Hmm, I'm not able to reproduce that behavior here. I ran a bunch of the SDL tests (`testgl2`, `testgles`, `testgles2`, and `testdraw2`) and they work for me here using KMSDRM in from the console.

The only test that didn't work was `testvulkan` which failed to create a window because "Installed Vulkan doesn't implement the VK_KHR_surface extension". However, I get the same results both with and without https://github.com/libsdl-org/SDL/commit/dfa64eadd38a6a8125290dcf121f1bc285e98dad, so I don't think it's related to that specific issue for me.

I'm testing on a Pi 4 with a single connected display running Raspberry Pi OS with the v5.10.11-v7l+ kernel and SDL main built with `--enable-video-kmsdrm --disable-video-rpi`.

Are you able to reproduce the issue with one of the SDL test binaries?

**Comment by vanfanel** [comment]
@cgutman I can't reproduce it anymore after I update the code to current git.
I guess something fixed it between https://github.com/libsdl-org/SDL/commit/dfa64eadd38a6a8125290dcf121f1bc285e98dad and https://github.com/libsdl-org/SDL/commit/33598563b35067417c2fed8fab03c503438ce6f6, but I can't examine in depth now.

I am closing this for now, but the issue really had to be opened, sorry for not being able to offer better information ATM.
