### ISSUE TITLE
Terrible performance with new Linux gamepad code

### ISSUE THREAD

**Issue by pcercuei** [libsdl-org/SDL#4229]
Running Super Mario 64 PC (https://github.com/JohnnyonFlame/sm64-od-port) on a Anbernic RG-350.

Prior to commit https://github.com/libsdl-org/SDL/commit/345b4d7e14, the intro and gameplay would run at a nice 60fps. After this commit, it's a sluggish 10fps. Still the case in the main branch.

**Comment by cgutman** [comment]
Did you figure out what was causing the excessive calls to `LINUX_JoystickGetGamepadMapping()`?

Searching through the code manually, I found a few functions that would result in one of these calls indirectly (excluding obvious cases like opening a joystick or gamepad):
- `SDL_JoystickGetDeviceType()`
- `SDL_IsGameController()`
- `SDL_GameControllerNameForIndex()`
- `SDL_GameControllerMappingForDeviceIndex()`

None of those seem like functions that should be called each frame in most applications, even `SDL_IsGameController()` which is otherwise a bit insidious.

**Comment by glebm** [comment]
`SDL_IsGameController` is used on every joystick event in many games, which can be quite often if sticks are moving. It is expected to be quite fast.

**Comment by cgutman** [comment]
I guess you might need to call `SDL_IsGameController()` on the `SDL_JOY*` events to distinguish between a game controller and a joystick if you don't keep track of that from when you called `SDL_GameControllerOpen()`/`SDL_JoystickOpen()`. Is that the use-case you're seeing?

If many games are wasting CPU cycles discarding these duplicate joystick events from game controllers, it might be a good idea to provide a hint to turn them off and only send joystick events for things that aren't game controllers.

**Comment by glebm** [comment]
For example Xash3d-FWGS allows controls with both game controllers and non gamecontroller joysticks

I think `SDL_IsGameController` should just be fast, like it used to be, without asking games to do limiting workarounds like the one you're proposing

**Comment by cgutman** [comment]
> I think `SDL_IsGameController` should just be fast, like it used to be, without asking games to do limiting workarounds like that

Oh for sure, we agree on that. I definitely didn't mean that we shouldn't fix it.

I was just thinking if there was a better solution for this particular use case that would both:
- avoid wasting time calling `SDL_IsGameController()` and discarding those events
- simplify game code by being able to rely on receiving either GC or joystick events, but never both for the same device

**Comment by glebm** [comment]
> never both for the same device

For example, DevilutionX port for the Switch handles most events as GC events but there are 2 extra buttons on the Switch controller that it handles as Joystick events.

**Comment by glebm** [comment]
Though it doesn't use `IsGameController` to differentiate these

**Comment by meyraud705** [comment]
> Though it doesn't use `IsGameController` to differentiate these

`IsGameController` take a joystick index, event gives you an instance id, you cannot use `IsGameController` to filter event.  You need to store whether you opened as a joystick or a gamecontroller yourself.

> It is expected to be quite fast.

`IsGameController` is only used when opening joystick, this call being slow should not be a problem.

For Super Mario 64 PC, it checks each frame if a joystick is opened ( https://github.com/JohnnyonFlame/sm64-od-port/blob/od-port-beta/src/pc/controller/controller_sdl.c#L122 ). If no joystick is opened, it calls `IsGameController` and eventually open a joystick. Normally this only happen on the first frame, but because the game never opens a joystick, it calls it every frame.

That make me wonder how the game even work if it never open any joystick.

**Comment by glebm** [comment]
Ah, I forgot that I actually used `SDL_GameControllerFromInstanceID` to differentiate these in xash3d-fwgs (https://github.com/FWGS/xash3d-fwgs/commit/5a36a26dd116bdbddbf8b011f59597eb77e6d4cd)
