### ISSUE TITLE
Android Back Button when pressed the input from softkeyboard/keyboard is not working properly

### ISSUE THREAD

**Issue by rafal1137** [libsdl-org/SDL#4261]
Hi let me go straight to the issue here. I have an Android app that is running a native lib and when I do press Back Button on my Smarphone I cannot enter any letters/numbers except working ```ESC, ENTER```.

Things I added to lib code is to handle it on my lib
```SDL_SetHint(SDL_HINT_ANDROID_TRAP_BACK_BUTTON, "1");```

```SDL_SCANCODE_AC_BACK``` which I did assigned to ESCAPE key

And after I do press Back input is not working properly
I have ```in_keyboardDebug``` to debug keyboard input which shows that keys pressed by softkeyboard are caught by lib but are not lets say generated/printed on screen.

Also I did some changes to my own Activity/Java file to override some functions regarding back button.
```java
    /*
    @Override
    public void onBackPressed() {
        mLayout.requestFocus();
    }*/

    @Override
    public void superOnBackPressed() {
        ETLActivity.onNativeKeyDown(111 );
        ETLActivity.onNativeKeyUp(111);
        this.superOnBackPressed();
    }

    @Override
    public void pressBackButton() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (!isFinishing()) {
                    ETLActivity.this.superOnBackPressed();
                }
            }
        });
    }
```

In which seems like those overrides are getting ignored.

**Comment by slouken** [comment]
That change would make it so all keys would hide the soft keyboard. The way it currently works is that the back key will hide the soft keyboard by default, so maybe that's what @rafal1137 was running into?

Since @rafal1137 has a solution and I am not seeing other related bugs reported, let's go ahead and close this.

Please enter a new bug if you're seeing an issue with 2.0.18 once it's released.
