### ISSUE TITLE
macOS Build: Cross-compiled SDL2 from x86_64 to ARM64 fails to run on target machine

### ISSUE THREAD

**Issue by Wohlstand** [libsdl-org/SDL#4262]
Hello!

Since the recent time I produce builds of my game using SDL2 for ARM64 on macOS. However, I had no way to test it out to verify the result. 

Once upon I found that my [friend](@kode54) has the M1-based Mac. My build didn't work:
- It failed to create the window
- It reported that the SDL2 got built without threading
- etc.

When he locally (on M1 Mac itself) re-built the game, it got worked fine.

My game build process does taking the SDL2 source code (release version 2.0.14) and builds it via the CMake method and Ninja generator (I specified the `-DCMAKE_OSX_ARCHITECTURES="arm64"` build flag) to cross-compile into ARM64 from x86. The build itself was done on macOS 10.15 Catalina.

My friend made an experiment: he built the game on macOS 11 x86_64 with a theory that system libraries on 10.15 aren't universal and that was a source of the problem. However, the new cross-compiled build is also won't work on the M1. Also, no matter which generator (Ninja, Xcode, or Makefiles), the result is the same.

However, natively-built SDL2 on ARM64 itself works perfectly. The problem is getting up when cross-compiling from the x86_64. This case is a big problem for me because the rest of the CI services do run on x86_64 processors only.

**Comment by kode54** [comment]
Friend reporting. On both x86_64 and arm64 machines, this build process's SDLMixerX CMake script fails to find libiconv and fails, unless I use ccmake on its build directory to set the ICONV_LIB variable to something, anything, even a non-existent path.

**Comment by Wohlstand** [comment]
The ICONV_LIB fault is the problem of MixerX's build itself as you have found. I did some fix on that, so, should build now. Please try :fox_face:

**Comment by past-due** [comment]
I can confirm this issue.

**Comment by past-due** [comment]
The issue is in `CheckPTHREAD` in `cmake/sdlchecks.cmake`.

Because of how target architectures are handled by CMake for macOS, `CMAKE_CROSSCOMPILING` may not be defined. Thus, it calls `check_c_source_runs` and attempts to compile + run an ARM64 executable on x64 macOS. Obviously, this fails, and that leads `HAVE_PTHREADS` to be false.

I don't see why this first `check_c_source_runs` is necessary on macOS, so a simple tweak to fix this would be:
```diff
- if(CMAKE_CROSSCOMPILING)
+ if(CMAKE_CROSSCOMPILING OR DARWIN)
```

As a longer-term fix, you may want to examine using CMake's built-in `FindThreads` and `THREADS_PREFER_PTHREAD_FLAG`, but that will obviously require more testing and affect all platforms.

**Comment by Wohlstand** [comment]
I did the build with this fix, and @kode54 had to fix the working of my build, seems this fixes the issue, thank you @past-due!
Gonna make the pull request with this fix...
