### ISSUE TITLE
Wooting 2 always considered an XBox360Controller

### ISSUE THREAD

**Issue by Freso** [libsdl-org/SDL#4271]
Wooting 2 keyboards can be set in a few different "gamepad modes", including one "no gamepad":
![screenshot from Wootility 3.6.15](https://user-images.githubusercontent.com/177659/113476086-a6bf5a00-9468-11eb-9b55-0c71d7a6d2c0.png)

However, regardless of which one it is set to, SDL will always pick it up as an XBox360Controller. I assume due to https://github.com/libsdl-org/SDL/blob/07af9baa86179a719b16c4fd672de78979c88e15/src/joystick/controller_type.h#L184 as the ID will always be `03eb:ff02` regardless of what mode the keyboard is in.

This can block input from an actual controller in some instances where the game can only handle one controller at a time and decides to pick up the W2 as the one (e.g., Yakuza 0 and I believe the other Yakuza Kiwami games too).

I don’t know if there is a way to detect the state from the keyboard to determine whether to broadcast it as an available controller or not, though. Maybe someone from @WootingKb might be able to provide insight?

**Comment by simon-wh** [comment]
In this current version of the Keyboard firmware (v1.30). The "No Gamepad" setting applies these changes which could be used to detect it:
USB Interface 0 becomes a "dummy" HID interface instead of the Xbox controller interface
BCD version is changed: i.e. `0.92` for "Xbox Controller" mode and `0.94` for No gamepad
Serial number prefix is changed i.e. `WOOT_001` for Xbox mode and `WOOT_002` for No gamepad

We plan to slightly alter this however, from the Lekker edition onwards we intend to be using our own Vendor ID as well as slightly different product ids for each gamepad mode setting to make it more easily identified and prevent some issues around controller calibration with DirectInput in Windows

**Comment by Rocky04** [comment]
The problem is that SDL don't really check if the interface is really for a Xbox controller.

Like the xpad code it would need to cross check the interface class, sub class and protocol number. Like `255 / 93 / 1` for a Xbox 360 wired controller and `255 / 93 / 129` for a wireless one.

https://github.com/torvalds/linux/blob/9b1f61d5d73d550a20dd79b9a17b6bb05a8f9307/drivers/input/joystick/xpad.c#L395

**Comment by XDM-Inc** [comment]
same issue here with my wooting 2, steam games ALWAYS sees a device called "Xbox 360 controller :wooting keyboard (xinput) and sometimes tries to use it resulting in my actual controller not working until i switch the priority.
my os is manjaro linux

**Comment by Rocky04** [comment]
That problem should be limited to the older Flaretech keyboards and I think it's caused by an unideal SDL implementation.

Because the Lekker keyboards have different product IDs depending on the analog mode they should not have this problem.

So if the Flaretech keyboards get the update for the newer Wootility the problem should be fixed. But that may take a while. :-(

**Comment by slouken** [comment]
I updated to the latest firmware (1.30.12) and now it shows up on SDL on Windows in "Xbox Controller" mode, but not in "Legacy Controller" or "No Gamepad" mode.

Interestingly it doesn't show up here on Linux as a controller in any mode.

So... it sounds like this is fixed?

**Comment by Rocky04** [comment]
@slouken For Linux you need to use `xboxdrv` in order the Wootings appear as a Xbox controller because the device IDs of the Wooting aren't yet included in `xpad`.

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
