### ISSUE TITLE
Hotplugging on UWP/WinRT broken due to default joystick thread behavior 

### ISSUE THREAD

**Issue by matpow2** [libsdl-org/SDL#4321]
Since `SDL_windowsjoystick.c` now uses device notifications by default, this breaks hotplugging for WinRT/UWP (which does not have an implementation for device notifications).
The workaround for this is to call `SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");` in user code, but maybe a good idea to have hotplugging working by default :)

**Comment by flibitijibibo** [comment]
This hint is only used once, here:

https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/joystick/windows/SDL_windowsjoystick.c#L359

We probably just need to def this whole block on and only use the thread path on WinRT, with a FIXME hoping that they'll add this to UWP later on.

**Comment by DJm00n** [comment]
We can use [CM_Register_Notification](https://docs.microsoft.com/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_register_notification) under WinRT. Example: https://github.com/microsoft/Windows-driver-samples/blob/1fe4cc42bedfccb97a5b2cc169f9e5306d41d0de/general/DCHU/osrfx2_DCHU_base/osrfx2_DCHU_usersvc/DeviceContext.cpp#L826-L856

It have almost same API as usual [RegisterDeviceNotification](https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-registerdevicenotificationw) but win32 window is not needed - it will just call callback func.

Available since Microsoft Windows 8 and can be used in UWP.

**Comment by slouken** [comment]
@DJm00n, any chance you can provide a tested patch using CM_Register_Notification?

**Comment by DJm00n** [comment]
@slouken I can try to do it in spare time.

**Comment by DJm00n** [comment]
@slouken here is related PR that should add hotplug support in hidapi on Windows: https://github.com/libusb/hidapi/pull/299

**Comment by slouken** [comment]
It turns out that we need the notification window for the raw input driver in the non-WinRT case, and the WinRT case is now handled with the joystick thread.

We can come back to CM_Register_Notification() in the future if we end up needing it. Here is the link to the relevant hidapi patch for future reference: https://github.com/libusb/hidapi/pull/299/commits/e91f905453dd516fbbd0f45064cc8a746fb3bdd9
