### ISSUE TITLE
SDL 2.0.14 on macOS ignores SDL_WINDOW_BORDERLESS in SDL_CreateWindow

### ISSUE THREAD

**Issue by frankleonrose** [libsdl-org/SDL#4324]
SDL 2.0.14
macOS 10.15.7 (Catalina)

Passing `SDL_WINDOW_BORDERLESS` to `SDL_CreateWindow` results in a window with a title bar. This used to result in a window with *no* title bar.

Note: subsequently calling `SDL_SetWindowBordered(window, false);` *does* still result in a borderless window.

**Comment by icculus** [comment]
This works correctly (running `testsprite2 --noframe`) on Mojave (10.14), and works on Big Sur with a binary built on Mojave, but since this is likely some OS change gated behind the Xcode used to build the binary, I'll report back when I get Xcode installed on this Big Sur machine.

**Comment by icculus** [comment]
Just tried on Big Sur with latest Xcode and it works, even with the official SDL 2.0.14 release (as opposed to using the latest in revision control).

Is this bug hitting _only_ Catalina?

**Comment by frankleonrose** [comment]
No, @icculus, we saw the problem on Mojave as well. Thanks for looking into it!

**Comment by icculus** [comment]
Hmm, can you send me a compiled build of the app that's doing this, if that's possible?

**Comment by frankleonrose** [comment]
It's the latest version of https://github.com/Genymobile/scrcpy - which has a lot of dependencies (a server app, adb) so maybe not the greatest test app to send.

I did rebuild scrcpy with slightly altered flags - I removed `SDL_WINDOW_RESIZABLE` and now the window appears borderless!

Looking at the SDL Cocoa window source, it appears that an `nswindow` gets created and window flags are reconstructed from it? I don't claim to understand why that needs to happen - though I can guess it's about ascertaining actual window capabilities vs requested capabilities.

Regardless why, it appears that the flags-to-style logic here https://github.com/libsdl-org/SDL/blob/a0a5da5d91b4316c2ca60f5dfce3b5963ef89d24/src/video/cocoa/SDL_cocoawindow.m#L277-L289 is not exactly reciprocal to the style-to-flags logic here https://github.com/libsdl-org/SDL/blob/a0a5da5d91b4316c2ca60f5dfce3b5963ef89d24/src/video/cocoa/SDL_cocoawindow.m#L1414-L1425 

When both flags are set, `(style == NSWindowStyleMaskBorderless)` will never be true. It should be `(style & NSWindowStyleMaskBorderless)` instead.

**Comment by icculus** [comment]
Good catch! I'll take a look at this.

**Comment by icculus** [comment]
Okay, it's more interesting than expected.

First: I suspect the reason it's trying to reconstruct the style flags is because it's rebuilding the window. Almost certainly this is a window that was created with SDL_WINDOW_OPENGL and then used with an SDL_Renderer, right? On the Mac, it sees it's an OpenGL window, tries to use Metal for the renderer, and has to destroy and rebuild the window to make this work.

(At least, in my little test app, this problem goes away if I don't force SDL_WINDOW_OPENGL.)

Second: the reason it's using `==` instead of `&` is because this is the value in NSWindow.h:

```c
    NSWindowStyleMaskBorderless = 0,
```

So I think you're definitely on the right track, but I guess we need to mask out some things to make this work correctly. Working on this now.

**Comment by icculus** [comment]
Okay, should be fixed now. Thanks!
