### ISSUE TITLE
Please mark a release as latest on github

### ISSUE THREAD

**Issue by fundies** [libsdl-org/SDL#4400]
I'm trying to automate updating my dependencies but the github API URL
"https://api.github.com/repos/libsdl-org/SDL/releases/latest" does not work properly because you have no release set as latest or something. I do not have this issue with other github repos eg: "https://api.github.com/repos/g-truc/glm/releases/latest"

**Comment by icculus** [comment]
I think this is a bug in GitHub's importer, since all the existing release tags were there when we pulled in the repository from Mercurial.

I'm putting this request on the 2.0.16 milestone, which we are trying to finish up soon, to see if this fixes itself when we ship it. If not, I'll dig deeper.

**Comment by lethosor** [comment]
The issue is that there are _no_ releases present in this repo. There are tags, presumably imported from Mercurial, but [GitHub "releases"](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases) consist of extra metadata (e.g. release notes) and are not created automatically from tags. For an example, see [the releases page of the repository fundies linked](https://github.com/g-truc/glm/releases), and compare it to [this repo's list of releases](https://github.com/libsdl-org/SDL/releases), which is essentially identical to [this repo's list of tags](https://github.com/libsdl-org/SDL/tags).

Whether it makes sense for SDL to publish releases on GitHub is another matter, however. I don't know whether it would fit well with the existing release process.

@fundies https://api.github.com/repos/libsdl-org/SDL/tags is probably the most complete source of data for this repo at the moment. It appears to sort tags in reverse chronological order, but it's unclear to me whether that's guaranteed from the [API docs](https://docs.github.com/en/rest/reference/repos#list-repository-tags).

**Comment by icculus** [comment]
Oh.

uh, I don’t know, then. I don’t think we are planning to do official releases through GitHub. I’m tossing this one to Sam to consider.

**Comment by Croydon** [comment]
Another pro-point: If you create GitHub releases and upload the official source code downloads you effectively have a free mirror for downloads.

**Comment by slouken** [comment]
We can create a GitHub release, but we'll still host the official archives on libsdl.org

**Comment by slouken** [comment]
It looks like you can grab the previously released archives from here, even if the API doesn't return a release:
https://github.com/libsdl-org/SDL/releases

**Comment by fundies** [comment]
Right, they're already there and I don't see any negatives to marking one as "latest"

**Comment by slouken** [comment]
Done, thanks!

**Comment by Croydon** [comment]
> We can create a GitHub release, but we'll still host the official archives on libsdl.org

Why not both?
