### ISSUE TITLE
SDL_GL_CreateContext fails on MacOS Big Sur

### ISSUE THREAD

**Issue by bobbruce000** [libsdl-org/SDL#4428]
The following code fails on MacOS Big Sur. 
It works on MacOS Catalina and on Ubuntu.

The error msg is:
**"Unable to create context: The specified window isn't an OpenGL window"**

It was compiled with this command:

**clang++ -std=c++17 -O3 -Wall -Wextra -Werror -D_REENTRANT -D_THREAD_SAFE -I/opt/local/include main.cpp -o foo -L/opt/local/lib -lSDL2 -framework OpenGL**

The version information is:
**Compiled SDL version: 2.0.14
Linked SDL version: 2.0.14**

```
#include <stdio.h>
#include <SDL2/SDL.h>

int
main(void)
{
  if (SDL_Init(SDL_INIT_VIDEO) != 0) {
    fprintf(stderr, "Unable to init SDL: %s", SDL_GetError());
    exit(1);
  }
  SDL_version compiled;
  SDL_version linked;
  SDL_VERSION(&compiled);
  SDL_GetVersion(&linked);
  printf("Compiled SDL version: %d.%d.%d\n",
	 compiled.major, compiled.minor, compiled.patch);
  printf("Linked SDL version: %d.%d.%d\n",
	 linked.major, linked.minor, linked.patch);
  SDL_Window *window;
  SDL_Renderer *renderer;
  if (SDL_CreateWindowAndRenderer(400, 400, SDL_WINDOW_OPENGL,
				  &window, &renderer) < 0) {
    fprintf(stderr, "Unable to create window: %s", SDL_GetError());
    exit(1);
  }
  SDL_GLContext context = SDL_GL_CreateContext(window);
  if (context == NULL) {
    fprintf(stderr, "Unable to create context: %s", SDL_GetError());
    exit(1);
  }
  
  // ... do stuff with OpenGL ...
    
  return 0;
}
```

**Comment by icculus** [comment]
So I didn't read this carefully when it was on sdl12-compat's bug tracker. The problem is likely that SDL_CreateWindowAndRenderer is making a window ready to render with _Metal_, but then you are trying to create a GL context on it and it refuses to do so.

More to the point, you shouldn't create an SDL renderer and an OpenGL context. If the renderer uses OpenGL, it will create it for you.

If you didn't want to use the render API but did want to use OpenGL, use SDL_CreateWindow with the SDL_WINDOW_OPENGL instead of SDL_CreateWindowAndRenderer, and then create the GL context as above.
