### ISSUE TITLE
Mac: Window jumps when clicking top bar and changing relative mouse mode immediately afterwards

### ISSUE THREAD

**Issue by samojordan** [libsdl-org/SDL#4469]
We observe the following problem on our Mac with Mac OS 10.15.6: when the user puts the window into background (SDL_WINDOWEVENT_FOCUS_LOST) we disable relative mouse mode and when the window gets focus again (SDL_WINDOWEVENT_FOCUS_GAINED) we enable relative mouse mode. When the window is located behind other windows and we click the top bar, the window jumps to another position (it's officially a window move as confirmed by recieving the SDL_WINDOWEVENT_MOVED event afterwards). This does not happen when we don't modify relative mouse mode. It's 100% reproducible in our application. We currently have no workaround for this problem. We would appreciate if someone could try to reproduce this in a simpler setup.

**Comment by slouken** [comment]
This is fixed by https://github.com/libsdl-org/SDL/commit/88e4755c26d5fd5c9f8da17fb0e1659ff46d9203.

By the way, you shouldn't need to enable/disable relative mode on focus changes. SDL should take care of this automatically. If you have a platform where that's not the case, please report it as a bug and we'll fix that.
