### ISSUE TITLE
Update FlashWindow API

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#4472]
We should simplify the API before 2.0.16 and remove the flash count. For platforms like Windows, we should have a standard flash count that can be adjusted with a hint.

**Comment by slouken** [comment]
@icculus, does the new API in https://github.com/libsdl-org/SDL/commit/f1633127d1c88f33179a5ddc8fae3eed7157b4b1 look good to you?

**Comment by icculus** [comment]
We should probably note that some platforms might not have a lot of control over this (like, it might only be able to _only_ flash indefinitely or briefly, depending on the whims of the OS or window manager), so you might get a successful flashing but not exactly what you expected. But otherwise, looks good to me.

**Comment by slouken** [comment]
The supported platforms all do what you'd expect so far. We can note deficiencies if they come up, but as long as the OS supports some way of alerting the user, we should be able to make this work the way the application expects.

Thanks!
