### ISSUE TITLE
Win: SDL_StartTextInput on by default, produces SDL_TEXTINPUT & SDL_TEXTEDITING from app start

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4491]
As soon as the application starts, I'm getting "1" from a call to SDL_IsTextInputActive(). But on Android I get "0". So on Windows I'm getting SDL_TEXTINPUT events with keyboard events. I also get a blank SDL_TEXTEDITING event at app start. I have to put a SDL_StopTextInput() at the start of main() to fix this.

I'm using the latest 32-bit .dll compiled with VS2019 default settings. Doesn't happen on Android build.

**Comment by sezero** [comment]
Looks like it's intentional? Has been there since SDL2-2.0.0, see `SDL_VideoInit()`:
https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L570
Android seems to send `SDL_TRUE` for `SDL_HasScreenKeyboardSupport()`, so it
should be the reason that it's not enabled for Android at startup.

Others such as @slouken and @icculus may have more to say on the matter.

**Comment by icculus** [comment]
It'a intentional. The keyboard is available by default on a desktop. On Android, we don't show the virtual keyboard unless requested. That's the difference.

**Comment by AntTheAlchemist** [comment]
But does that make sense? I can plug a physical keyboard into an Android and use it as a desktop. And I have a Windows 10 tablet that only has an on-screen tablet. This intentional feature becomes platform dependant rather than what hardware is available.

**Comment by slouken** [comment]
Conceptually, text input events are enabled by default for connected keyboards and disabled by default for on-screen keyboards. I'm fine with moving us closer to that, but nobody has done that work yet.
