### ISSUE TITLE
Will there be support for GDK?

### ISSUE THREAD

**Issue by DoubleBullet** [libsdl-org/SDL#4519]
Microsoft Game Developer Kit (GDK) was just released and announced.
https://developer.microsoft.com/en-us/games/blog/meet-the-microsoft-game-developer-kit-gdk/

Will there be any support for it in the near future?

**Comment by TheSpydog** [comment]
I am currently in the early stages of porting SDL to Xbox via GDK. I plan to open a PR for PC GDK support as well once the implementation is further along.

**Comment by chalonverse** [comment]
@TheSpydog Are you still working on a GDK port?

**Comment by TheSpydog** [comment]
> @TheSpydog Are you still working on a GDK port?

Unfortunately no, I haven't had time to devote to that project recently.

**Comment by chalonverse** [comment]
With the DirectX 12 renderer merged, one piece of eventually supporting Xbox GDK is now in.

The next logical step is to add support for Windows GDK. In theory, Windows GDK should allow all the APIs currently used by the Windows configuration. If this is the case, then I don't think it would be that crazy to add Windows GDK support (famous last words). I think we need:
* Any needed vcxproj/sln changes
* Appropriate checks in `SDL_platform.h` (probably can just look for the  `_GAMING_DESKTOP` define?) and a corresponding new `__WINGDK__` define
* A new `SDL_config_wingdk.h` and a hook for the default `SDL_config.h`
* Fix up any `__WIN32__` and/or `__WINDOWS__` checks to also check for `__WINGDK__` as appropriate
* A new `SDL_wingdk_main.cpp` -- it has to be a .cpp file because I think shipping GDK games need to call `XblInitialize` to initialize the XSAPI and at least get the default user in simplified mode. All of the XSAPI headers require C++ mode.
* A MicrosoftGame.config sample plus one for each test program we want to support

For the vcxproj/solution files, the two options are either we could make a separate set of sln/vcxproj files and put them in a `VisualC-GDK` directory, or we could add GDK as a separate solution configuration and build them out that way. My current thought is to keep it separated out as with WinRT, but if people really want to include it in the existing vcxproj files, we could do that, too.

(As an aside, there is also a [sample](https://github.com/microsoft/Xbox-GDK-Samples/tree/1f44bdabed6e340170e2c7d1007500e4dff897bb/Samples/Tools/CMakeExample) of how to use CMake with GDK, but this seems lower priority).

For the main function, I think essentially the steps would be:
1. Call `XGameRuntimeInitialize` (required)
2. Try to get the Title ID with `XGameGetXboxTitleId` -- if this succeeds, then:
   1. Call `XblInitialize`
   2. Setup an async task queue
   3. Call `XUserAddAsync` with `AddDefaultUserSilently`, which will login the default user (and in the simplified user model, this is guaranteed to happen without any UI)
3. Enter the normal main entry point

If step 2 fails, I believe you could still test running through Visual Studio, but I don't think it would be possible to deploy a package and test locally, because I think the package would be invalid without a title id). AFAIK the function just retrieves the title ID that was specified in the MicrosoftGame.config file.

I'm sure I'm missing something and this will be more complicated than I expect, but that's the starting point I've got.

**Comment by chalonverse** [comment]
Thinking a bit further, I wonder if it would be useful to have a separate `__GDK__` define that's basically an OR of all the different platforms like `__WINGDK__` and a future `__XBOXONE_GDK__` and `__XBOXSERIES_GDK__`. That way we can separate out preprocessor checks that are just "any GDK" (which is going to be most of the checks) versus checks for a specific GDK platform.

**Comment by flibitijibibo** [comment]
GDKX patchset: #5869

**Comment by walbourn** [comment]
Note that ``_GAMING_XBOX``, ``_GAMING_XBOX_XBOXONE``, and ``_GAMING_XBOX_SCARLETT`` are already established preprocessor symbols for the custom "Gaming.Xbox.XboxOne.x64" and "Gaming.Xbox.Scarlett.x64" platforms we define in the Microsoft GDKX. We use them publicly in samples.

"_GAMING_DESKTOP" is used for "Gaming.Desktop.x64" but it is also used for classic "x64" platforms with the Microsoft GDK. In general, there's nothing really that SDL should care about compared to 'stock' DirectX 12 except perhaps GameInput usage.

**Comment by chalonverse** [comment]
Hi Chuck,
Yes, so the way it’s setup right now is we use those platform defines to determine which SDL-specific defines to set, since the general convention is to prefer using SDL-specific defined outside of the platform header:
https://github.com/libsdl-org/SDL/blob/main/include/SDL_platform.h#L172-L181

**Comment by walbourn** [comment]
For the content that is currently checked into main, please change the following:

1. src\SDL.c the platform name should be "Xbox Series X|S"

2. Don't reuse the samples identity for the test MicrosoftGame.config files. Create fresh ones for just the SDL test so the GUIDs are unique.

**Comment by chalonverse** [comment]
@flibitijibibo Do you happen to have a partner account you could use to generate an SDL test product ID for? What did we do for the WinRT test program?

**Comment by icculus** [comment]
Reopening this, since there seems to be some changes to be made.

@walbourn (Apologies for briefly hijacking this thread, but) I just noticed your GitHub bio, and wanted to say we get a _lot_ of requests for an official Xbox port of SDL, but we don't have an SDK to do the work; we've got Nintendo Switch, Sony PS4 and PS5, and Google Stadia forks of SDL, but we haven't managed to get Xbox developer access...if there's some way we could get onto Microsoft's radar about being part of the developer program, I'd love to talk to you about it.

If you can help us get access, can I email/DM you somewhere? No worries if not!

**Comment by walbourn** [comment]
> @flibitijibibo Do you happen to have a partner account you could use to generate an SDL test product ID for? What did we do for the WinRT test program?

For the functionality in the SDL library, you shouldn't need the service-side stuff that's in the sample you copied the MGC from. A freshly generated MGC with the GDK project template with some light editing should do it.

> if there's some way we could get onto Microsoft's radar about being part of the developer program, I'd love to talk to you about it.

I've forwarded your request.

**Comment by slouken** [comment]
@chalonverse, @flibitijibibo, can you make the project changes that walbourn requested?

**Comment by chalonverse** [comment]
Ok, I made the change in #6532 to the config files so it doesn't use the Microsoft sample ones anymore, and instead uses the placeholder ones that are generated when you create a new GDK project from the Visual Studio template.

**Comment by slouken** [comment]
Great, thanks!

**Comment by chalonverse** [comment]
Hi @walbourn I was wondering if you had an opportunity to review the Xbox-specific DirectX files which are posted on the GDK forums here: https://forums.xboxlive.com/questions/130003/

Specifically, I was wondering if we could get approval to add those files to the public SDL repo here rather than needing to maintain it separately? The question comes up because some of the APIs used are *not* in the public documentation but they are used in the official GDK samples produced by your team. So, there is public information about their existence and how to use them but it still is a grey area.

It would be nice if we could include those in this repo just from a maintenance standpoint.

Thanks!
