### ISSUE TITLE
Try AVX512F for 5.1 -> Stereo audio conversion?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4529]
> SSE saves 50% execution time compared to the C code (with the divisions replaced) while AVX only saves about 15% time compared to SSE.
> This is because extracting the interleaved samples requires a lot of shuffles. AVX 256 bit registers are split in two lanes and only a select few instructions can move data between lo and hi.
> AVX512F would help significantly since it can shuffle/permute values across all lanes at latency=1.

_Originally posted by @JoelLinn in https://github.com/libsdl-org/SDL/issues/4436#issuecomment-859967560_

**Comment by slouken** [comment]
@0x1F9F1, does this make sense to do?

**Comment by madebr** [comment]
Would we be fine by adding ispc sources to SDL?
Using those, simd code can be generated for x86/arm.
I suppose 0x1F9F1 is using it to generate the A/V converters.

**Comment by 0x1F9F1** [comment]
So I did slightly improve the AVX code after this issue was created (#4550) though both the SSE and AVX 51toStereo converters were removed when all the channel converters were rewritten. It may be worth revisiting them to see if they can be updated and added back.
Steam hardware survey has AVX512F support at less than 10% so I'm not sure it's worth the effort.

**Comment by slouken** [comment]
I'll go ahead and close this for now. If you find that it's a significant performance improvement feel free to submit a PR for this.
