### ISSUE TITLE
wayland: High CPU usage with v-sync on

### ISSUE THREAD

**Issue by dos1** [libsdl-org/SDL#4609]
Tested on a Librem 5 running phoc.

With SDL 2.0.12, Neverball while in its graphics menu eats about 60-62% of CPU with v-sync off and about 20% with v-sync on.

With SDL 2.0.16, it's slightly better with v-sync off - 55-57%, but with v-sync on it goes up to 100%, constantly eating one whole CPU core - even when the screen is locked and turned off.

Reverting c54c16d353f206162cdbb125c0847b4645e096a3 brings it down to reasonable levels again.

**Comment by cgutman** [comment]
I can confirm this bug locally too with `SDL_VIDEODRIVER=wayland ./testgles2 --vsync`

We're busy looping in:
https://github.com/libsdl-org/SDL/blob/791d9d3ff61db369008d8590ee87340d7074f3c6/src/video/wayland/SDL_waylandopengles.c#L133-L141

There are no blocking function calls in that loop, so it will just busy loop until the compositor is ready for a frame. We should definitely get that fixed.

> With SDL 2.0.16, it's slightly better with v-sync off - 55-57%, but with v-sync on it goes up to 100%, constantly eating one whole CPU core - even when the screen is locked and turned off.

Screen locked and turned off is actually the worst case scenario, since we won't be getting any frame callbacks. We will sit in that loop most of the time and render at 10 FPS.

cc: @flibitijibibo

**Comment by flibitijibibo** [comment]
Ah crap, I knew this would be no good somehow... I think we may just need to yield somewhere? We definitely need an escape route when getting blocked but it probably shouldn't burn as hard. Sleeping is probably too much in the opposite direction though.

Long-term we'll either need to lean heavily on surface suspension or figure out that timeout extension for SwapBuffers (#4306)

**Comment by cgutman** [comment]
@dos1 give this a try, it works for me:

**Comment by icculus** [comment]
Would a small SDL_Delay in there if we aren't the foreground window cover this for now?

**Comment by cgutman** [comment]
> Would a small SDL_Delay in there if we aren't the foreground window cover this for now?

We would still hit 100% of a core while in the foreground and getting frame callbacks :(

Even a foreground window will be subject to this issue, since any time spend waiting for buffer swap in `SDL_GL_SwapWindow()` is going to be a busy wait.

**Comment by dos1** [comment]
@cgutman Much better! The CPU usage with screen locked is still elevated, but that's expected due to forced 10Hz update rate. Otherwise the CPU usage is similar to 2.0.12.

**Comment by cgutman** [comment]
@icculus I put the patch up as a PR. You can merge it for 2.0.16 if you feel comfortable or do something simpler if you want.
