### ISSUE TITLE
CMake < 3.14: set IOS variable to 1?

### ISSUE THREAD

**Issue by SpaceIm** [libsdl-org/SDL#4635]
In CMakeLists, there is a lot of logic based on `IOS` variable, but this variable is never set to 1 when `CMAKE_SYSTEM_NAME` is `iOS`.
CMake does that automatically, but only since 3.14: https://cmake.org/cmake/help/latest/variable/IOS.html

In the meantime, CMake min version in sdl CMakeLists is 3.0.0, so I think that it should still be handled manually in CMakeLists.

**Comment by SpaceIm** [comment]
Maybe something like this, even if it's a little bit cumbersome:

```cmake
elseif(APPLE)
  if(CMAKE_SYSTEM_NAME MATCHES ".*Darwin.*")
    set(DARWIN TRUE)
  elseif(CMAKE_SYSTEM_NAME MATCHES ".*MacOS.*")
    set(MACOSX TRUE)
  elseif(CMAKE_SYSTEM_NAME MATCHES ".*tvOS.*")
    set(TVOS TRUE)
  elseif(CMAKE_SYSTEM_NAME MATCHES ".*iOS.*")
    # could be set unconditionally, it's just a reminder to remove this logic if CMake min version is bumped to 3.14
    if(CMAKE_VERSION VERSION_LESS 3.14)
      set(IOS TRUE)
    endif()
  endif()
```

**Comment by icculus** [comment]
> ```cmake 
> if(CMAKE_SYSTEM_NAME MATCHES ".*Darwin.*")
>    set(DARWIN TRUE)
>  elseif(CMAKE_SYSTEM_NAME MATCHES ".*MacOS.*")
>    set(MACOSX TRUE)
>  elseif(CMAKE_SYSTEM_NAME MATCHES ".*tvOS.*")
>    set(TVOS TRUE)
> ```

...are _all_ of these necessary? If this isn't causing a problem beyond the missing IOS variable, I'd rather not bulk this up as a defensive measure.

(if we _need_ them explicitly set, though, then yeah, let's do it.)

**Comment by okuoku** [comment]
Generally speaking, we should not dispatch platforms inside CMake project since Apple's recommendation is feature detection macros (Macro itself still have versioning issue though: https://github.com/libsdl-org/SDL/issues/4475 ). It seems current SDL2 codebase largely follows this.

> ...are all of these necessary?

`DARWIN`, `MACOSX` and `TVOS` exists current SDL2 codebase. History:

- `DARWIN` and `MACOSX` : These are from day1. https://github.com/spurious/SDL-mirror/commit/7b16b8577cdfa55ee8a4d3e146e60043fdddc5b6 these could be `APPLE` but SDL2 calls these platforms `darwin` so I guess the original author defined `DARWIN` instead. (In 2012, OpenDarwin derived was still there.) [CMake calls darwin as `APPLE` entirely](https://github.com/Kitware/CMake/blob/859241d2bbaae83f06c44bc21ab0dbd38725a3fc/Modules/Platform/Darwin.cmake#L1).
- `TVOS` : was added in https://github.com/libsdl-org/SDL/commit/ec65a34b8ee7f4811d02e809de877d7b590ef508 `TVOS` name is compatible with unofficial CMake iOS support ( https://github.com/leetal/ios-cmake ).

IMHO we should follow CMake upstream thus we can depend on `APPLE` and `IOS`. `DARWIN` and most of `MACOSX` can be safely translated into `APPLE` and some of them might be `if(APPLE NOT IOS)`. Every `TVOS` occurrences can be translated into `IOS`. Since `CMAKE_SYSTEM_NAME` is not utilized in unofficial CMake support (ios-cmake), I don't think it worked CMake prior to 3.14 anyway for iOS/tvOS.
