### ISSUE TITLE
SDL_RenderSetViewport 2.0.16 on 32 bit not correct

### ISSUE THREAD

**Issue by illume** [libsdl-org/SDL#4643]
Hello,

this is a pygame test failure being worked on here with SDL 2.0.16 on windows: https://github.com/pygame/pygame/pull/2670

[SDL_RenderSetViewport](https://wiki.libsdl.org/SDL_RenderSetViewport) with `(0, 0, 1920, 1080)` is successful,
however [SDL_RenderGetViewport](https://wiki.libsdl.org/SDL_RenderGetViewport) then returns `(0, 0, 1917, 1077)`.

Note, this only happens on our 32 bit windows builds on both appveyor and github. I haven't tried it manually on a windows machine yet. This wasn't happening before.

Edit: Well, not just windows... also happening on 32bit linux.

---

https://github.com/pygame/pygame/blob/main/test/video_test.py
```
python -m pygame.tests.video -k test_renderer_set_viewport
```

**Comment by icculus** [comment]
RenderSetViewport:

```c
renderer->viewport.x = (int)SDL_floor(rect->x * renderer->scale.x);
renderer->viewport.y = (int)SDL_floor(rect->y * renderer->scale.y);
renderer->viewport.w = (int)SDL_floor(rect->w * renderer->scale.x);
renderer->viewport.h = (int)SDL_floor(rect->h * renderer->scale.y);
```

RenderGetViewport:

```c
rect->x = (int)(renderer->viewport.x / renderer->scale.x);
rect->y = (int)(renderer->viewport.y / renderer->scale.y);
rect->w = (int)(renderer->viewport.w / renderer->scale.x);
rect->h = (int)(renderer->viewport.h / renderer->scale.y);
```

I haven't tried this, but I could see this dropping some pixels depending on the scale.

**Comment by icculus** [comment]
Ah, as pointed out in #4657, @0x1F9F1 also saw this.

I don't think rounding is right, the comment in #4657 that we just need to store the original value is probably the correct approach here.

**Comment by 1bsyl** [comment]
Whatever the rounding method, there will always ways to have pixels differences. So it seems also an interesting solution to store the user values.

So some starts of patch ...
[SDL_patch_pull_4657.txt](https://github.com/libsdl-org/SDL/files/7576658/SDL_patch_pull_4657.txt)
but there are few sensible places:  when switching the RenderTarget we save viewport and cliprect.
+ there is also a RenderSetScale which change what the viewport size. so there are not original value for that.

other solution maybe:
- use "double" precision internally ?
- use fixed point ?

**Comment by icculus** [comment]
@1bsyl's patch seems to be the right direction, but let's bump this to 2.0.20 so we don't inadvertently break something else with these changes.

**Comment by 1bsyl** [comment]
I have a patch that seems to fit correctly. (almost same as before  + bug fix)
[SDL_patch_pull_4643.txt](https://github.com/libsdl-org/SDL/files/7597046/SDL_patch_pull_4643.txt)

And a wide test suite, with a lot of random fuzzing.
[main_bug_4643_scaling_viewport_cliprect.c.txt](https://github.com/libsdl-org/SDL/files/7597060/main_bug_4643_scaling_viewport_cliprect.c.txt)

If you dump before / after the patch and compare the outputs. it fixes pixels stuffs.

... but, it's not clear to me if the viewport values that look nice are really the one that are correct. for instance if you go from one value to the other. does it fits the screen area. 
   some real testing would be nice.
... after some combination with larger scale, it's also not clear which version is correct.

Then, adding some more variables:
  viewport_user,  viewport_user_backup, clip_rect_userclip_rect_user_backup

to the 
  viewport viewport_backup clip_rect clip_rect_user_backup

with the already existing :
  scale integer_scale logical_w logical_w_backup logical_h logical_h_backup dpi_scale

seem to add more trouble to maintain ...

Another solution I thinking of, (and also the reason of the PR https://github.com/libsdl-org/SDL/pull/5003) is:
makes "renderer->viewport" be the one set by the user.
and scale in place, wherever "viewport" is used.

for the clip-rect, it fits nicely. we just scale before queuing SETCLIPRECT cmd. (instead of RenderSetClipRect)
but the viewport there are more places. 

But it changes the behavior little bit:

SDL_RenderSetViewport() and SDL_RenderScale() can be inversed without any change.

Because currently : 
doing:  
```
SDL_RenderSetViewport()
SDL_RenderScale()
```
would be different from
```
SDL_RenderScale()
SDL_RenderSetViewport()
```

**Comment by 1bsyl** [comment]
There's actually a much better and easier modification to do:
change the internal SDL_Rect viewport to float version: SDL_FRect viewport

here's a patch: 
[SDL_patch_pull_4643____use_FRect.txt](https://github.com/libsdl-org/SDL/files/7603925/SDL_patch_pull_4643____use_FRect.txt)

**Comment by sezero** [comment]
> There's actually a much better and easier modification to do: change the internal SDL_Rect viewport to float version: SDL_FRect viewport
> 
> here's a patch: [SDL_patch_pull_4643____use_FRect.txt](https://github.com/libsdl-org/SDL/files/7603925/SDL_patch_pull_4643____use_FRect.txt)

Is this safe for 2.0.18?

**Comment by 1bsyl** [comment]
I think we need the PR first: https://github.com/libsdl-org/SDL/pull/5003
so that to make sure we don't use the float renderer->viewport in backend, even if it doesn't look crazt, but I haven´t tested the D3D11 windows modification at all.

... is it safe ... maybe. the test case is doing random call. and I compare before/after output. and it look sane at first look.
I haven't tested the SDL_SetIntegerScale API, though, so I can maybe add more stuff to test ...

**Comment by icculus** [comment]
This should still wait for 2.0.20, imho.

**Comment by 1bsyl** [comment]
I've updated the test-case (which was actually broken ! without updating the cliprect)... 
[main_bug_4643_scaling_viewport_cliprect.c.txt](https://github.com/libsdl-org/SDL/files/7604342/main_bug_4643_scaling_viewport_cliprect.c.txt)

I definitively see that it solve pixel size issues.  (most of the time "Set scale / Set Viewport / Get Viewport ")
I see no drawback so far ...

**Comment by 1bsyl** [comment]
ok, np

**Comment by 1bsyl** [comment]
I've added the patch to the PR: https://github.com/libsdl-org/SDL/pull/5003

**Comment by 1bsyl** [comment]
Should we now merge this ? 
can you @illume and @0x1F9F1 try the PR #5003 ?

**Comment by slouken** [comment]
Sure, feel free to merge unless @icculus has any concerns.

**Comment by illume** [comment]
Thanks :) I haven’t tried it, but looks grand to me.

**Comment by 1bsyl** [comment]
ok! so let's merge this !
