### ISSUE TITLE
Difference in handling `CTRL + <KEY>` and `SDL_TEXTINPUT` between the `wayland` and `x11` backend

### ISSUE THREAD

**Issue by ATiltedTree** [libsdl-org/SDL#4695]
On `x11`:

1. `LEFT_CTRL` is pressed.
2. `SDL_KEYDOWN` with `LEFT_CTRL` is sent.
3. `<KEY>` is pressed.
4. `SDL_KEYDOWN` with `<KEY>` is sent.

On `wayland`:

1. `LEFT_CTRL` is pressed.
2. `SDL_KEYDOWN` with `LEFT_CTRL` is sent.
3. `<KEY>` is pressed.
4. `SDL_KEYDOWN` with `<KEY>` is sent.
5. `SDL_TEXTINPUT` with `<KEY>` is sent.

This has been tested with this included example: https://github.com/libsdl-org/SDL/blob/main/test/testime.c

The `wayland` backend probably shouldn't send a `SDL_TEXTINPUT` event as the `x11` backend doesn't do this either.

**Comment by bdach** [comment]
I know this issue is specific to wayland but it seems that even on x11 some key combinations involving <kbd>Ctrl</kbd> will also send `SDL_TEXTINPUT` events, strangely. The three weird cases that I have seen are: <kbd>Ctrl</kbd>+<kbd>0</kbd>, <kbd>Ctrl</kbd>+<kbd>1</kbd> and <kbd>Ctrl</kbd>+<kbd>9</kbd>. Is that intentional? If not, should I open a separate issue for that?

**Comment by Susko3** [comment]
@flibitijibibo this seems to have regressed again, but on X11 this time. See https://github.com/ppy/osu/issues/28212.

From https://github.com/ppy/osu/issues/30703#issuecomment-2484500089, the problematic keybinds also include <kbd>Ctrl</kbd> and <kbd>=</kbd> <kbd>-</kbd> <kbd>1</kbd> <kbd>9</kbd> <kbd>0</kbd> <kbd>,</kbd> <kbd>.</kbd> <kbd>;</kbd> <kbd>'</kbd>
