### ISSUE TITLE
Broken character mapping in `SDL_TEXTINPUT` with `nds_DE` locale

### ISSUE THREAD

**Issue by Noordfrees** [libsdl-org/SDL#4699]
Hi,

I'm using Ubuntu MATE 21.04 with the Low German (nds_DE) system locale. With the default settings for this locale I'm unable to type non-ASCII characters such as äöüß in many applications. Manually setting `LC_CTYPE=de_DE.UTF-8` fixes the problem. 

The only thing that all affected programs have in common afaics is that they use SDL2. I first reported this bug against glibc but they believe it is a bug in the way some other library (which must be SDL then) detects the char mapping, see https://sourceware.org/bugzilla/show_bug.cgi?id=28278.

---

I debugged this in one affected application (https://github.com/FreeRCT/FreeRCT/) and it seems that the `SDL_TEXTINPUT` delivers broken data when pressing such characters. In this code: 
```
	SDL_Event event;
	if (SDL_PollEvent(&event) != 1) return true;

	switch (event.type) {
		case SDL_TEXTINPUT:
			return HandleKeyInput(WMKC_SYMBOL, (const uint8 *)event.text.text);
```
I set a breakpoint to print `event.text.text`. With default locale (`LC_CTYPE=nds_DE`), the result is `"\000"` for <kbd>ä</kbd> and `"\374\000"` for <kbd>ü</kbd> (bug). With `LC_CTYPE=de_DE` I get `"\303\244\000"` and `"\303\274\000"` respectively (correct).

---

My version of `libsdl2-dev` is `2.0.14+dfsg2-3`.
The system locales' char maps are
```
$ LC_ALL=nds_DE locale -k charmap
charmap="UTF-8"

$ LC_ALL=de_DE locale -k charmap
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
charmap="ANSI_X3.4-1968"

$ LC_ALL=C locale -k charmap
charmap="ANSI_X3.4-1968"
```

---

If this is also not the right place to report this bug please feel free to redirect me further on :)

Best regards and thanks in advance

**Comment by icculus** [comment]
I'm going to bump this to 2.0.20, but I'm not confident it's an SDL bug either. It's possible there's an IME misbehaving (if we sent it through fcitx or ibus), or the Xserver itself sent us bogus information.

If you're feeling brave (and/or bored), the next place you'd want to look is here:

https://github.com/libsdl-org/SDL/blob/eda4c40732f788ac06f607c70344f801d2f82454/src/video/x11/SDL_x11events.c#L1000-L1051

And see if the data between where it comes in from the X server and when it gets transformed by the IME looks correct.

Otherwise, I'll probably attempt to put together a MATE system with this locale and check that piece of code for 2.0.20.

**Comment by icculus** [comment]
Kicking this down the line to the next milestone, again. I'll mark it early-in-milestone and spend the time to reproduce it here, though.

**Comment by slouken** [comment]
It turns out with nds_DE we were falling back to an older X11 call that returns Latin-1 text rather than UTF-8 text and then trying to interpret that as UTF-8 with hilarious results.

This was a good find, thanks!
