### ISSUE TITLE
Game window still loses focus while moving mouse on some Windows systems

### ISSUE THREAD

**Issue by rmarquis** [libsdl-org/SDL#4823]
This is potentially the follow up of the recently closed issues #3076, #4293 and #4450.

We recently shipped a new release of our [ET:Legacy](https://github.com/etlegacy/etlegacy) project, an old school FPS based on quake-engine tech, with the latest stable SDL 2.0.16 library. 

However, it was quickly reported by *some* Windows users that the game window keeps losing focus when they move their mouse around, and they can see their mouse cursor appearing, and input to game stops working. The issue happens in windowed, borderless windowed and fullscreen mode.

You can see a video of the issue here: https://streamable.com/zx36y7

And you can see the original ticket here:
* https://github.com/etlegacy/etlegacy/issues/1762

After some investigation, we thought the issue would be related to SDL issues #3076, #4293 and #4450. We tried backporting c542de92135a79f25648e75b1c2ab0fd581e29c0 over SDL 2.0.16 codebase, but without success: the very same issue is still present.

We then tried to compile the project with the very last SDL master version (commit 1b49f092431379d43649d85c5b35b604d977be11) and we can confirm the issue is still present. The same code compiled with SDL 2.0.14 works as expected. As such, it seems the recent SDL fix (c542de92135a79f25648e75b1c2ab0fd581e29c0) either didn't fix all cases, or this bug might be something entirely different.

I personally cannot reproduce the issue on my end (only a few users seem to be affected), but we have a (non-coder) member of the team that might be able to provide requested feedback. Let us know if there is anything we can do to help solve this issue.

**Comment by flibitijibibo** [comment]
Is it uniquely the mouse? I've been seeing similar reports for Streets of Rage 4 on Windows, where most of the input is from a gamepad.

**Comment by DomGries** [comment]
I also noticed that after 4359a47 the clipped mouse cursor can still visibly appear on the window border if your monitor has custom DPI setting (175% in my case) and if your app does not use a manifest to set dpi awareness.

This then after 89b6209 would call `SDL_SetMouseFocus(NULL)` and in turn `SDL_WINDOWEVENT_LEAVE` which the reported app here apparently handles (which from my tests can cause issues and should be ignored in favor of `SDL_WINDOWEVENT_FOCUS_LOST`).

Adding the following manifest to the build process fixes that case (which is a good idea for games to allow custom resolutions to be independent of dpi):
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <asmv3:application>
        <asmv3:windowsSettings>
            <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
            <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">permonitorv2,permonitor</dpiAwareness>
        </asmv3:windowsSettings>
    </asmv3:application>
</assembly>
```

Alternatively adding the following workaround below https://github.com/libsdl-org/SDL/commit/4359a47b3e383de0fe20a98a3cc523ca0e0d8a76#diff-f2ae5c36a8afc0a9a343a6664ab306da2963213e180af8cd97b12397dcbb9ae7R997 also seems to work possibly due to rounding done by `ClientToScreen`.
```c++
rect.left += 1;
rect.top += 1;
rect.right -= 1;
rect.bottom -= 1;
```
Similarly my suggested change in https://github.com/libsdl-org/SDL/issues/4165#issuecomment-939413293 might fix this and other issues at the same time.

**Comment by slouken** [comment]
Please retest using the latest SDL snapshot at commit https://github.com/libsdl-org/SDL/commit/88e9f7765c71156eaa8651b0efa071a7a2f1f247:
http://www.libsdl.org/tmp/SDL-2.0.zip

Thanks!

**Comment by rmarquis** [comment]
@slouken Yes, recent commit c583055acbcae356bc9f1f7d402da98e8bb7ae19 is confirmed to work.

**Comment by slouken** [comment]
Thanks!
