### ISSUE TITLE
[Proposal] New event type `SDL_TextCandidate`

### ISSUE THREAD

**Issue by jai-x** [libsdl-org/SDL#4855]
### Motivation
Consumers of SDL would like to display IME candidate text choices during a text
input context.

This is currently handled by making of use of `SDL_SetTextInputRect` which
indicates to the platform window backend and native IME where to display a
candidate list based on the textbox position.

This method currently does not draw when SDL is used in exclusive fullscreen
mode. Additionally, SDL consumers would like to display the candidate text in a
more integrated way in the window by being able to access and draw the candidate
text directly.

### Proposal

New event type `SDL_TextCandidate`:

| Field        | Datatype | Comment                                                                                          |
|--------------|----------|-------------------------------------------------------------------------------------------|
| `type`       | `Uint32` | `SDL_TEXTCANDIDATE`                                                                       |
| `timestamp`  | `Uint32` | Timestamp of the event                                                                    |
| `windowID`   | `Uint32` | The window with keyboard focus, if any                                                    |
| `candidates` | `char**` | An array of null terminated UTF-8 encoded strings                                         |
| `count`      | `Sint32` | The count of the number of strings in the `candidates` array                              |
| `cursor`     | `Sint32` | The index of which of the strings in the `candidates` array is being selected by the user |

### Feedback and implementation

If there is any feedback to this proposal that would be great.
I would be interested in implementing this myself once appropriate feedback has
been received.

**Comment by jai-x** [comment]
@baidwwy Thanks for the links. I guess these implementations would serve as good reference points for when adding this to SDL.

**Comment by crudelios** [comment]
Also, in platforms like Vita, where the virtual keyboard includes its own input area, it would be nice to have a way to display an initial text.

Rationale: I have a few in-game text inputs, which may already have some text. On other platforms, since SDL's text input events are directly handled by the game, the game's own text inputs get updated.

On Vita (and also on Switch), calling `SDL_StartTextInput` will open the console's own IME dialog, with both a virtual keyboard and an independent text input area, which is empty, regardless of the in- game's text area contents.
