### ISSUE TITLE
[Wayland] Add support for SDL_DISPLAYEVENT_ORIENTATION

### ISSUE THREAD

**Issue by HenkKalkwater** [libsdl-org/SDL#4878]
The value of `SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION` should be allowed to contain multiple values instead of one, since it is supposed to be a set of flags. When multiple content orientations are set for a window and the window is active, the QtWayland server may automatically rotate the system UI between the supported orientations, which at least happens on SailfishOS. 

I'm willing to implement this and create a PR, but I'm not sure wether I should make the multiple hint values space-separated, like the `SDL_HINT_QTWAYLAND_WINDOW_FLAGS` or comma-separated, like all the other hints that support multiple values.

Note: For the automatic rotation to work, `SDL_DISPLAYEVENT_ORIENTATION` should be fired when the orientation of the `wl_output` changes, which currently does not seem to happen at all from quickly reading through the source code, but I'll make a separate issue for that. Additionally, the application developer is still responsible for rotating the video output, as the QtWayland compositor on at least SailfishOS does not do this for them.

**Comment by flibitijibibo** [comment]
This is at risk of being pushed back to 2.0.20 - has this been started yet?

**Comment by HenkKalkwater** [comment]
I've made implemented the multiple content orientations, but I haven't tested it yet properly. SaiflishOS isn't able to run upstream SDL due to `wl_shell_surface` being no longer implemented, so I'll need to correctly apply their patches and then test it. I'll look into that this afternoon.

**Comment by icculus** [comment]
> SaiflishOS isn't able to run upstream SDL due to wl_shell_surface being no longer implemented

https://github.com/libsdl-org/SDL/pull/4323#issuecomment-825374386

...

**Comment by flibitijibibo** [comment]
I looked into it and they've been pretty on top of having an SDL package maintained, so I almost think they were quiet about it on purpose... they're supposed to be updating their compositor according to some meeting notes I found somewhere. They're well aware of the deprecation so I think they're trying to fix this on their end instead of dragging old deps into third party packages.

**Comment by flibitijibibo** [comment]
I've pushed the support for multiple orientation values:

https://github.com/libsdl-org/SDL/commit/63ae103cd184eb46020eb77f5fd49504183296bd

However I'm unable to get my desktop to give me a proper `transform`... in fact I can't even be certain I know the program flow for orientation changes because the protocol doesn't specify it! But to confirm, it _should_ just be a matter of handling a second call to handle_geometry for a given wl_output and resetting the display mode array (which I think Sam just pushed helper functions for the other day?).

Going to repurpose this for the second half of the issue, not sure this will make it into 2.0.18 but if someone has a compositor that sends orientation events I'll get it in ASAP.

**Comment by flibitijibibo** [comment]
@HenkKalkwater, if #4965 looks good to you we'll get this in for 2.0.18!

**Comment by HenkKalkwater** [comment]
Sorry for the late reply, but this I can confirm that #4965 seems to work correctly on SailfishOS.

**Comment by mittorn** [comment]
This breaks fullscreen mode and detecting display mode on sailfishOS
When starting app in landscape mode, it reports landscape display resolution and it's impossible to detect that we should still render in portrait
Moreover, when enabling fullscreen, SDL internally use lanscape display mode and breaks input coordinate scaling.
For example, on my phone it reports 1080x2520 in portrait mode and everything works ok, but when screen is rotated, it starts reporting 2520x1080 and i cannot somehow determine, that i still should render in 1080x2520 window.
Only way to use SDL on SailfishOS with this feature is hardcode portrait mode/resolution somewhere in app, but this mostly makes SDL useless as platform-agnostic toolkit.
Is there any way to detect QTWAYLAND target and native (not rotated) resolution somehow without hard-coding it?
