### ISSUE TITLE
X11 windows cannot be shared in browsers (Firefox, Chromium)

### ISSUE THREAD

**Issue by slash3g** [libsdl-org/SDL#4924]
X11 Windows created using SDL_CreateWindow cannot be shared in browser (see also Genymobile/scrcpy#2640).
The bug has been introduced in b3b4677e3295e49fc37e1400c3b076c4617f162d.
Apparently, both _NET_WM_NAME and WM_NAME need to be set in order for the browser to find the window.

The following (quick and dirty) patch will fix this behaviour:
```diff
diff --git a/src/video/x11/SDL_x11window.c b/src/video/x11/SDL_x11window.c
index 8d81cb055..f083d782b 100644
--- a/src/video/x11/SDL_x11window.c
+++ b/src/video/x11/SDL_x11window.c
@@ -735,6 +735,9 @@ X11_SetWindowTitle(_THIS, SDL_Window * window)
     Atom UTF8_STRING = data->videodata->UTF8_STRING;
     Atom _NET_WM_NAME = data->videodata->_NET_WM_NAME;
 
+    Atom WM_NAME = X11_XInternAtom(data->videodata->display, "WM_NAME", False);
+    X11_XChangeProperty(display, data->xwindow, WM_NAME, UTF8_STRING, 8, 0, (const unsigned char *) title, strlen(title));
+
     status = X11_XChangeProperty(display, data->xwindow, _NET_WM_NAME, UTF8_STRING, 8, 0, (const unsigned char *) title, strlen(title));
 
     if (status != 1) {
```

Moreover, using xdotool to rename (and set both properties of) a window can be used to work around this issue:
```
xdotool selectwindow set_window --name "WindowName"
```

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by morgant** [comment]
Thanks, @slouken! This should fix an issue I'm seeing with @OpenBSD's `fvwm` not being able to match against SDL window names because they're lacking a `WM_TITLE`.

That said, does your fix in [6c56e27](https://github.com/libsdl-org/SDL/commit/6c56e275115fdb5a2fb93d4f6f7459ccb8460151) reintroduce old issues (at least in older window managers that don't support `_NET_WM_NAME`)? I believe, at least according to Issue #35, that `WM_NAME` needs to be a TEXT String, not a UTF-8 String, so should be converted before being set. Such conversion was removed by @ctrlcctrlv's PR #4290.

**Comment by slouken** [comment]
> That said, does your fix in [6c56e27](https://github.com/libsdl-org/SDL/commit/6c56e275115fdb5a2fb93d4f6f7459ccb8460151) reintroduce old issues (at least in older window managers that don't support `_NET_WM_NAME`)? I believe, at least according to Issue #35, that `WM_NAME` needs to be a TEXT String, not a UTF-8 String, so should be converted before being set. Such conversion was removed by @ctrlcctrlv's PR #4290.

Could you provide a PR with a tested patch? I don't have a test environment for this right now.

**Comment by ctrlcctrlv** [comment]
Yes, I removed `WM_NAME` because of its encoding issues, if you'd like to reintroduce it you're going to need to use function `X11_XSetTextProperty` as it was before c5dd9964c1527c26dde57d88b5d9599094a01627

**Comment by ctrlcctrlv** [comment]
Also make sure you test patches against the test case in #4288 which prompted #4290.

**Comment by slouken** [comment]
Is this something you guys can fix for 2.0.18? I'd like to ship without this regression, if possible.

**Comment by morgant** [comment]
@slouken I don't have much availability to work on this except for this coming weekend (2021-11-27 & 28). I see 2.0.18 is already a few days overdue, so I'm not sure if that's soon enough or if there's enough else pending that it'd be okay.

**Comment by slouken** [comment]
There's enough pending that this weekend would be fine.

Thanks!

**Comment by sezero** [comment]
What happened to this one? Still meant for 2.0.18?

**Comment by slouken** [comment]
Yes, morgant is going to get this tested and in for 2.0.18.

**Comment by slouken** [comment]
@morgant, this is the last item going into 2.0.18. Do you have something ready for tomorrow?

**Comment by ctrlcctrlv** [comment]
@slouken I'm not a regular SDL contributor and the patch under discussion is the only one I've ever written. I have time available time going me, but maybe my lack of experience might make you weary of having me try to fix it. Also, you might be able to rightly say I shouldn't fix the mess I made, although I'd say that reliance on `WM_NAME` is a Chrome/FF bug. Nevertheless, I'm willing to help if @morgant can't.

**Comment by ctrlcctrlv** [comment]
I'm looking at the code a little harder and I actually think that the "quick and dirty" patch is really close to being the right one. The previous code only existed to try to run Xorg under a non-Unicode locale. I would say that running Xorg that way is extremely rare these days, probably even non-existent, and likely to cause other issues, but I think I can write a patch pretty quickly here given we know 99% of the problem, I just need to verify some things about Xorg, locales, and whether we should be using `XSetWMName`.

**Comment by slouken** [comment]
Sure, go for it. Can you coordinate with @morgant?
Ryan and I will review it, so you’ve got us as safety net as well.

**Comment by ctrlcctrlv** [comment]
Will do, working on it now.

**Comment by morgant** [comment]
@slouken & @ctrlcctrlv, my apologies for missing your replies yesterday. I have been working on a patch (https://github.com/morgant/SDL/commit/b9b5c04c56fc14382dfb8be6c58a395fd8f41234). I'm still testing as I'm also not a regular SDL contributor.

As for the reliance on `WM_NAME`, it's part of [the spec](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#idm45623294026752) that the client _SHOULD_ set the `_NET_WM_NAME` and the WM should use this in preference to `WM_NAME`, but not all WMs support `_NET_WM_NAME` (yes, even in this day and age, see #4979). Additionally, `WM_NAME` should be a non-UTF-8 string where `_NET_WM_NAME` should always be a UTF-8 string, as far as I understand. So, I don't see this as a bug in Chrome & FF, and believe we should be setting both `WM_NAME` & `_NET_WM_NAME`.

With the aforementioned string encodings in mind, I believe the cause of issue #4288 was that `X11_SetWindowTitle()` was using `SDL_iconv_utf8_locale()` to convert to the UTF-8 title string to the user's locale, but in many (most?) cases is probably still UTF-8.

Also, I believe this same fix needs to be applied to `X11_MessageBoxCreateWindow()` in `https://github.com/morgant/SDL/commit/b9b5c04c56fc14382dfb8be6c58a395fd8f41234`.

**Comment by ctrlcctrlv** [comment]
I'm sorry, I have some thoughts on your patch based on my research.

Firstly, it is wrong to say that WM_NAME should be ASCII. Actually, it should be in the server's locale, and Xorg supplies functions for this. Please see proof at https://tronche.com/gui/x/icccm/sec-2.html#s-2.7.1 , which mentions that the modern encoding for it is COMPOUND_TEXT.

`Xutf8TextPropertyToTextList` is the most commonly used today to get a COMPOUND_TEXT. It is worth noting that the standard for UTF8_STRING in Xorg was approved of 21 years ago: https://www.irif.fr/~jch/software/UTF8_STRING/UTF8_STRING.text . We should be treating non-existence of X_HAVE_UTF8_STRING as a hard error, or at least a warning.

`SDL_iconv_string` is wrong because X11 servers can be remote, so we need to ask X itself for the locale. It's easiest to use `Xutf8TextPropertyToTextList`, because that'll give us back `XLocaleNotSupported` when and where appropriate. I am concerned that your patch might break things by assuming ASCII where we used to assume UTF-8, as ASCII is true for less people.

Also, I think you should consider using the convenience function `XSetWMName` to simplify the code.

**Comment by ctrlcctrlv** [comment]
Also, research showed we're/I'm not the first to assume WM_NAME can finally be done away with, apparently the Qt project assumed the same in 2014 :laughing: https://herbstluftwm.org/archive/msg00459.html

**Comment by morgant** [comment]
@ctrlcctrlv Thanks for the feedback!

Yes, you're correct that I should be using a TextProperty so that it's correctly encoded as STRING, [COMPOUND_TEXT](https://www.x.org/releases/X11R7.7/doc/xorg-docs/ctext/ctext.html) (an implementation of ISO-2022, as I understand it), or C_STRING (for ASCII), based on the locale instead of forcing it to ASCII. I'm updating my implementation & testing now (sorry, my dev machine is a bit slow).

As for assuming `WM_NAME` can finally be done away with, even Qt seems to have [reversed their stance](https://bugreports.qt.io/browse/QTBUG-42209) due to issues in the wild (mainly for MWs that only support the ICCCM features and not EWMH [Extended Window Manager Hints], but also other applications functionality like we're running into w/Chrome/FF).

I do agree that the lack of `X_HAVE_UTF8_STRING` should probably at least be a warning, at this point. There's still a fair amount of use of it throughout the SDL X11 code, so I wanted to be consistent with existing implementation.

**Comment by ctrlcctrlv** [comment]
Heh, here I am removing it everywhere, maybe I should stop.

I rewound an old repository to 2010 to _make absolute sure_ I was using XmbTextListToTextProperty correctly: https://github.com/exg/rxvt-unicode/commit/d7d98751b7385416ad1694b5f1fde6c312ba20d5 just because I saw the CHANGELOG in Google :laughing: 

I'm sorry I messed up the release cycle of such an important project so I'm doing my best to make sure whatever comes next will be as close to perfect as is possible

**Comment by ctrlcctrlv** [comment]
Although in retrospect after writing that I think that a lot of the problems in this codebase are from people trying to maintain consistency with the existing implementation instead of changing what needs to be changed. I just saw `X_HAVE_UTF8_STRING` and `SDL_X11_HAVE_UTF8_STRING` used in _the same function_, seeming to be no rhyme or reason to the choice :dizzy:, so maybe I won't stop, even if my change is too large to be considered this go round

**Comment by morgant** [comment]
Ah, I see you beat me to pretty much the same solution while I was futzing with testing, though you also addressed `X11_MessageBoxCreateWindow()`.

**Comment by ctrlcctrlv** [comment]
I believe I did all the testing I can think of (ran my original example inside `LANG=C Xephyr`, under XWayland, under kwin_x11), but I am sure more is possible. Given how my first patch went, I'd encourage you to throw anything title related you can think of at this one :)

**Comment by morgant** [comment]
I'd be curious what `xprop` shows for `WM_NAME` in the test code from #4288 (whether it's now no longer clipped), but I've unfortunately run out of time to test until Tuesday.
