### ISSUE TITLE
Wayland: Stellaris fullscreen window is 24 pixels too high and input ends up in the wrong place

### ISSUE THREAD

**Issue by ernstp** [libsdl-org/SDL#4932]
If I force Stellaris to SDL_VIDEODRIVER=wayland with the latest libSDL, the fullscreen window will be 24 pixels too high, i.e 3840x2184 pixels. What's worse, the input ends up in the wrong place so the mouse cursor and UI elements no longer align.

Tested with SDL built from master ("Revert "include: Updated SDL_config_emscripten.h from emscripten-ports.""), Ubuntu Wayland session, mutter 40.5-1ubuntu2, mesa 21.3.0~rc4, 5.15.1.

libdecor was enabled version 0.1.0+git2110211017.754432e~i~wayland3

AMDGPU, Radeon 6800 XT.

**Comment by ernstp** [comment]
And this doesn't happen if built without libdecor. :-(
I see the FIXME: We have been explicitly told to respect the fullscreen size ....

**Comment by flibitijibibo** [comment]
As I recall this is unique to Mutter and may actually root from the same bug as GNOME 40.3 and older. If this doesn't happen on Plasma or Sway I would file this as a Mutter issue.

**Comment by ernstp** [comment]
This commit didn't help: https://gitlab.gnome.org/GNOME/mutter/-/commit/d2eec866ed50278965c7136f81f93f92abf6363b

**Comment by flibitijibibo** [comment]
Hm, okay... let's start with libdecor, can you file a report there with the same repro case linking here? One of their maintainers also works on both projects so this just ensures the right people are looking at this. This worked in a previous version and SDL's libdecor work hasn't changed much since 2.0.16 so I suspect a change has happened separately from us.

One more thing that will help diagnose is WAYLAND_DEBUG=1, so we can see exactly what the events are that cause the incorrect window size.

**Comment by flibitijibibo** [comment]
I tested with 2.0.16 to ensure that nothing has regressed on our end - when 2.0.16 was released we were assured that the bugs described in #4603 would be fixed with GNOME 40.4, and they were! So we're almost certainly looking at a desktop regression; libdecor's commit log doesn't show anything new compared to the time 0.1 was tagged.

**Comment by ernstp** [comment]
Created libdecor issue: https://gitlab.gnome.org/jadahl/libdecor/-/issues/28

**Comment by jadahl** [comment]
An update from the libdecor issue:

1)

Stellaris creates requests a "window" size that is derived from some `wl_output` mode that will potentially match the monitor resolution. When in windowed mode, this will result in a too large Stellaris window (it'll be "window title height + shell panel height" too tall, but otherwise work as expected. It's not resizable so it'll always be a region at the bottom that isn't possible to interact with, unless one drags the window to be partially under the shell panel.

In practice this also meant that SDL on behalf of Stellaris created a window that had a minimum size larger than the screen.

In Wayland there is now a thing called "bounds" which is sent when a window is configured that corresponds to the available work area. Any way SDL can make use of this to avoid applications making the wrong sizing decisions?

This reproduces with or without libdecor; with libdecor it'll be both title and panel too tall; without libdecor and without the toplevel decoration protocol it'll be the panel too tall; with the toplevel decoration protocol, I haven't tested.

2)

Mutter did not handle the above situation, since it respected the max size, which was larger than the monitor resolution. https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2234 works around this issue and makes Stellaris work correctly when fullscreen.

3)

Stellaris has a configuration file which contains a size, where it will store the used content size. If one changes this size to something other than what will be decided by Wayland, Stellaris will render incorrectly (too small or too large), until it is restarted, which will correct the issue, as Stellaris will replace the content in the configuration file. What this practically means is that launching Stellaris on a monitor with a different resolution, it will look broken until one restarts it.

This reproduces with or without libdecor.

4)

It appears that `SDL_SetWindowDisplayMode()` will incorrectly resize the window when mode changes. That function lives in the generic layer; how would one best fix that on Wayland, where wl_output modes should practically be ignored for all purposes?

**Comment by flibitijibibo** [comment]
> It appears that SDL_SetWindowDisplayMode() will incorrectly resize the window when mode changes. That function lives in the generic layer; how would one best fix that on Wayland, where wl_output modes should practically be ignored for all purposes?

This is a good question... Ryan or Sam will probably have the best experience at that level since presumably all other backends need this, but I'm surprised it's needed for desktop fullscreen and not just exclusive fullscreen.

**Comment by jadahl** [comment]
> but I'm surprised it's needed for desktop fullscreen and not just exclusive fullscreen.

For Wayland, it's strictly not wanted, as the fullscreen dimension should only come from the configure event. The information about modes and monitors are practically useless for most purposes.

**Comment by flibitijibibo** [comment]
> > but I'm surprised it's needed for desktop fullscreen and not just exclusive fullscreen.
> 
> For Wayland, it's strictly not wanted, as the fullscreen dimension should only come from the configure event. The information about modes and monitors are practically useless for most purposes.

Should have clarified this was in the context of SDL, sorry - I was surprised our desktop fullscreen mode calls SetWindowSize since presumably it should be something closer to a resize event.

**Comment by flibitijibibo** [comment]
So I was _kind of_ right - it only ever makes changes for `FULLSCREEN` (exclusive fullscreen) and not `FULLSCREEN_DESKTOP` (good fullscreen):

https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L1214-L1241

If Stellaris is using the former and not the latter, that can be an application bug; we never actually supported this in Wayland (and we may even need to harden SetWindowFullscreen accordingly). For the latter it should be making no real changes other than the `fullscreen_mode`, which doesn't change anything other than a few int values.

I do recall seeing this very recently with FNA, but I don't recall if it was hardware-specific (i.e. NVIDIA's new GBM support). Let me go check another game real quick, triple-post incoming...

**Comment by flibitijibibo** [comment]
Right, got some `WAYLAND_DEBUG=1` logs of the FEZ Steam beta... this only calls SDL_SetWindowFullscreen so if there's any mess in the common layer it'll be in SDL_video.c's UpdateFullscreenMode:

https://flibitijibibo.com/wl_nv.txt
https://flibitijibibo.com/wl_amd.txt

**Comment by flibitijibibo** [comment]
Found something that might actually fix this, alongside what I found in the above logs:

https://github.com/libsdl-org/SDL/commit/e1b4761c621e9883c3f02971ea74cef14b1d6b87

@ernstp, can you check out the latest SDL revision?

**Comment by ernstp** [comment]
Alright that seems to have done the trick, tested both Stellaris and Jupiter Hell and both seem to behave well with this.

**Comment by flibitijibibo** [comment]
Dang, thanks to both of you for checking this out - that bug's on me then!

**Comment by ernstp** [comment]
That was my last SDL_VIDEODRIVER=wayland + libdecor bug, gonna try it on some more games now.
