### ISSUE TITLE
add SDL_rand() to SDL_stdlib ?

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#4968]
A good public domain implementation can be found e.g. at https://github.com/ppelleti/jsw-libs

**Comment by slouken** [comment]
Maybe, as long as people understand that rand() is not a great source of entropy. Let's consider it for 2.0.20.

**Comment by flibitijibibo** [comment]
This would be nice to have, and having a big note saying "this is not actually 100% random" would be fine for most purposes. We currently use stb_rand in FAudio for example and it's perfectly okay for just picking a number:

https://github.com/FNA-XNA/FAudio/blob/master/src/stb.h

**Comment by sezero** [comment]
The one referred to uses Mersenne twister:
https://github.com/ppelleti/jsw-libs/tree/master/jsw_rand
Its discussion:
https://github.com/ppelleti/jsw-libs/blob/master/Tutorials/jsw_tut_rand.md

**Comment by slime73** [comment]
Pseudorandom number generators are a pretty expansive and researched topic these days - my personal feeling is that the classic C `rand()` API is actually a bad fit for modern use because it has global state, can only return a 32 bit integer, doesn't allow state save/restore, etc. And I don't think any of SDL's internal code needs to call `rand()`, so I don't really like the idea of emulating its API in SDL.

If you do want to, the [PCG](https://www.pcg-random.org/index.html) set of generators are a great modern and flexible choice (even well suited for GPU PRNG and hash use among other use cases, eg [here](https://www.reedbeta.com/blog/hash-functions-for-gpu-rendering/) and [here](https://jcgt.org/published/0009/03/02/)).

**Comment by slouken** [comment]
> If you do want to, the [PCG](https://www.pcg-random.org/index.html) set of generators are a great modern and flexible choice (even well suited for GPU PRNG and hash use among other use cases, eg [here](https://www.reedbeta.com/blog/hash-functions-for-gpu-rendering/) and [here](https://jcgt.org/published/0009/03/02/)).

Agreed, if we do add random numbers to the API, we should add something like this (and possibly a simple SDL_rand() built on top of them.)

**Comment by JKaniarz** [comment]
If global variables are a concern look at the POSIX rand_r interface.

I've been throwing PRNGs against TestU01 lately. 32 bits of output is all you really need, but more than 32 bits of internal state is what really matters. Returning the high 32 bits of a 64 bit LCG is the performance king. PCG32 (which has 64bit internal state) is the knee on the performance/quality curve. And Philox is the quality king (and really fast at that level of quality). One key feature of all of these is small internal state. Mersenne Twister has a huge footprint which isn't justified by the statistical quality.

As much as I personally love PCG, I wouldn't recommend it for SDL. It's not good enough for gambling (to avoid cheating), nor is it fast enough for particle effects (Jonathan Blow complained about this when updating Braid). It's hands down the best the mid-range PRNG, but I think the SDL demographic is going to want one of the two extremes.

**Comment by AntTheAlchemist** [comment]
I'd like to respectfully vote against this on the grounds that it can be easily done front-end and there are many different implementations to choose from which would depend on the use. It comes under bloat that doesn't need to be in SDL.

**Comment by slouken** [comment]
I'm inclined to agree with @AntTheAlchemist and @JKaniarz.

Random numbers are a big space with lots of solutions available. I don't think this needs to be in SDL.

**Comment by slouken** [comment]
Just a thought, should we reopen this for SDL 3.0 and just add SDL_rand() as an easy interface to stb_rand()?
https://github.com/FNA-XNA/FAudio/blob/e57397c24fa12aaca6d3cb8ec6cfa07e36296d22/src/stb.h#L320

**Comment by slouken** [comment]
This has come up often enough that it might be worth adding for demos and quick projects.

**Comment by icculus** [comment]
I personally think it's useful to have it (and have the same warning that every manpage for rand() has: do not use it for cryptography).

**Comment by madebr** [comment]
Perhaps we need to treat rand as the malloc functions and provide a `SDL_SetRandomFunctions` that accepts a `SDL_rand_func` and `SDL_srand_func` function pointer?

**Comment by slouken** [comment]
> Perhaps we need to treat rand as the malloc functions and provide a `SDL_SetRandomFunctions` that accepts a `SDL_rand_func` and `SDL_srand_func` function pointer?

I think that's overkill. If someone has specific requirements for their random number implementation, they should just use that. :)

**Comment by JKaniarz** [comment]
It's not clear to me what the value add is over rand(). Is there that much overlap between the crowd that needs rand() but doesn't link with libc?

An RNG is pretty easy to add, but the hard part is deciding what you want.
* 32 vs 64 bit (or more?) state
* 32 vs 64bit output
* signed vs unsigned output
* global state like rand vs. user state like rand_r vs. thread local global state
* And finally, once the above are decided, which algorithm?

And just to round out the library
* should srand() whiten the seed because users are likely to initialize it with the current time?
* Do you want a uniform random float helper function?
* Do you want a rand in range function? (the naive implementation that user would write themselves is bad)
* Should rand in range take the extra steps to make the probabilities perfectly even?

**Comment by slouken** [comment]
> It's not clear to me what the value add is over rand(). Is there that much overlap between the crowd that needs rand() but doesn't link with libc?
> 
> An RNG is pretty easy to add, but the hard part is deciding what you want.
> 
> * 32 vs 64 bit (or more?) state
> * 32 vs 64bit output
> * signed vs unsigned output
> * global state like rand vs. user state like rand_r vs. thread local global state
> * And finally, once the above are decided, which algorithm?
> 
> And just to round out the library
> 
> * should srand() whiten the seed because users are likely to initialize it with the current time?
> * Do you want a uniform random float helper function?
> * Do you want a rand in range function? (the naive implementation that user would write themselves is bad)
> * Should rand in range take the extra steps to make the probabilities perfectly even?

This is why we didn't put it in, in the first place.

**Comment by JKaniarz** [comment]
Sorry for getting this thread shut down twice. Here's my suggested implementation: https://gist.github.com/JKaniarz/3385b04b7a1abd15f2f78a39ccf9e487

A 32-bit generator is good enough, but 32-bits of internal state isn't. I went with a 64->32bit LCG implementation that is 32-bit arch friendly.
