### ISSUE TITLE
The software renderer always redraws the whole screen every frame

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#4972]
The ability to do partial screen updates would potentially improve performance on slower systems.

**Comment by slouken** [comment]
Go ahead and suggest an implementation?

**Comment by icculus** [comment]
Lowest hanging fruit (for someone else to mess with, I'm just talking out loud here)...

One could use a span buffer and at the end fill in untouched pixels with the clear color, if the app requested a clear, or if not just leave it as-is at the end.

We could also use the command list with a span buffer to decide what can be thrown away: instead of drawing back to front, since we have the whole list of draw commands, we can process it front-to-back and remove any overdraw, as we can know what is completely occluded. This gets a little trickier when we have to blend, but that's solvable too.

And of course, if there's a clear in the middle of the frame, throw every draw command before it away without actually drawing it.

After that: there's likely a bunch of low-level wins in the actual pixel-writing code with SIMD instructions and such that we haven't even begun to look at.

But the question is: how fast does the software renderer need to be, when most things expect a GPU here?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
