### ISSUE TITLE
SDL_filesystem feature request, SDL_CreateDirectory

### ISSUE THREAD

**Issue by ITotalJustice** [libsdl-org/SDL#4989]
Looking at the current filesystem files, seems that for a few platforms, we already have mkdir-like options

vita: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/filesystem/vita/SDL_sysfilesystem.c#L84

emscripten: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/filesystem/emscripten/SDL_sysfilesystem.c#L80

haiku: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/filesystem/haiku/SDL_sysfilesystem.cc#L101

os2: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/filesystem/os2/SDL_sysfilesystem.c#L108

cocoa: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/filesystem/cocoa/SDL_sysfilesystem.m#L123

windows: https://github.com/libsdl-org/SDL/blob/bc7ac134db67392f85ba3dae99c0c191619f4bc0/src/filesystem/windows/SDL_sysfilesystem.c#L163

riscos: https://github.com/libsdl-org/SDL/blob/9ee6942e79a0674384d7ad948bbae16c5c16a43c/src/filesystem/riscos/SDL_sysfilesystem.c#L196

winrt: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/filesystem/winrt/SDL_sysfilesystem.cpp#L225

unix: https://github.com/libsdl-org/SDL/blob/345c161feb52f39c4ebfc1cda0cf80c05ce699fc/src/filesystem/unix/SDL_sysfilesystem.c#L318

here's an example of how the api could look
```c
typedef enum
{
    SDL_DIRECTORY_READ = 1 << 0,
    SDL_DIRECTORY_WRITE = 1 << 1,
    SDL_DIRECTORY_EXECUTE = 1 << 2,

    SDL_DIRECTORY_RW = SDL_DIRECTORY_READ | SDL_DIRECTORY_WRITE,
    SDL_DIRECTORY_RWX = SDL_DIRECTORY_READ | SDL_DIRECTORY_WRITE | SDL_DIRECTORY_EXECUTE,
} SDL_DirectoryFlags;

int SDL_CreateDirectory(const char* path, Uint32 flags);
```
I'm not sure what the return code should look like. 0 on success probably, anything negative for error, maybe a positive value for warnings such as if the dir already exists?

**Comment by ITotalJustice** [comment]
Thinking about it, it would probably make sense to also add a `SDL_RemoveDirectory(path, flags)`? flags would have something like `remove if non empty (recursively deleting files / folder`, can't think of other options, maybe thats all that's needed

**Comment by ITotalJustice** [comment]
i added a impl for mkdir platforms, this is based off https://github.com/libsdl-org/SDL/blob/345c161feb52f39c4ebfc1cda0cf80c05ce699fc/src/filesystem/unix/SDL_sysfilesystem.c#L257

```c
int SDL_CreateDirectory(const char* path, Uint32 flags) {
    char* str = NULL;
    char *ptr = NULL;
    size_t len = 0;
    int mode = 0;

    if (flags & SDL_DIRECTORY_READ)
        mode |= S_IRUSR;

    if (flags & SDL_DIRECTORY_WRITE)
        mode |= S_IWUSR;

    if (flags & SDL_DIRECTORY_EXECUTE)
        mode |= S_IXUSR;

    if (!mode) {
        return SDL_InvalidParamError("flags");
    }

    str = SDL_strdup(path);
    if (!str) {
        SDL_OutOfMemory();
        return -1;
    }

    len = SDL_strlen(str);
    if (!len) { // sanity check
        return -1;
    }

    if (str[len - 1] == '/')
        str[len - 1] = '\0';

    for (ptr = str+1; *ptr; ptr++) {
        if (*ptr == '/') {
            *ptr = '\0';
            if (mkdir(str, mode) != 0 && errno != EEXIST)
                goto error;
            *ptr = '/';
        }
    }

    if (mkdir(str, 0700) != 0 && errno != EEXIST) {
error:
        SDL_SetError("Couldn't create directory '%s': '%s'", str, strerror(errno));
        SDL_free(str);
        return -1;
    }

    SDL_free(str);
    return 0;
}
```

**Comment by AntTheAlchemist** [comment]
Can we please also have `SDL_RenameFile()` and `SDL_DeleteFile()`

**Comment by ell1e** [comment]
> No need for RemoveDirectory() to work if folder isn't empty, that can be left to the user to sort out with SDL_DeleteFile().

That is actually quite difficult to get right, because you can have race conditions particularly if you *don't* want to descend into symbolic link children that point to other folders: it is very easy to mess it up such that between your symbolic link check on the child and its actual removal right after, there is a possibility for it to have been converted to a symlink pointing to an outside folder just in between, causing you to traverse out and potentially recurse into tons of outside things you never wanted deleted. (For what it's worth, afaik the only way to avoid it is to use directory handles, and check link status & do removal on the opened dir handle rather than via the path string.) Another problem is that if you go through the multibyte conversion to utf-8 on Windows, I think children with invalid utf-16 names (with broken surrogates) may cause your recursive delete to permanently trip over as well - so the deletion loop/queue in itself should retain/use native wide strings for child access. All in all, I think it'd be very useful to solve this in SDL2 properly because it's hard to get all corner cases right.

**Comment by AntTheAlchemist** [comment]
It's always been the role of the programmer to clear out a directory before attempting to delete it. That's not something the SDL API should be getting involved with. The ethos is to provide the raw low-level functionality so that the programmer can implement the more complex higher function of clearing the directory out. Symbolic links are a moot point in this.

**Comment by PythagoRascal** [comment]
This might be outside the scope of this feature request, but I recently wished there was an SDL equivalent to [stat](https://www.tutorialspoint.com/unix_system_calls/stat.htm). I also at the time would have liked file-path manipulation functions or directory enumeration functions.

**Comment by ell1e** [comment]
> It's always been the role of the programmer to clear out a directory b

I really don't understand your point. If the SDL filesystem doesn't provide raw handles, then it is actually *impossible* to do this on top of it safely. Symbolic links are absolutely not moot, because symlink escape deletion damage is a very common significant security hole. So again, it would be useful to solve this in a safer way for everyone, IMHO.

**Comment by AntTheAlchemist** [comment]
It isn't the role of SDL to traverse directory trees. It will never happen. That's why there aren't any file handling functions already, which is why we're more likely to get the very basic ones, if any.

**Comment by baidwwy** [comment]
and openfile 
https://github.com/crazecoder/open_file
