### ISSUE TITLE
fix gamepad G-Shark GS-GP702

### ISSUE THREAD

**Issue by 64ghost** [libsdl-org/SDL#5006]
not working right stick( up and down)

SOLUTION
In  src/joystick/SDL_gamecontrollerdb.h (str138)  you need to fix righty:a4 on righty:a3

**Comment by sezero** [comment]
There are two identical entries for `G-Shark GS-GP702` in there,
at line 138 for DINPUT and at line 399 for MACOSX. (Which OS are
you on?) If one needs changing, I guess the other would need it.
@slouken?

**Comment by 64ghost** [comment]
I use win10 x64. But you need to change for all systems.

**Comment by AntTheAlchemist** [comment]
I also have the same problem (with current source code version) on Win10 with my G-Shark GS-GP702 controllers. Mine are branded Jite, model KD-890 Double Shock2. 
Product ID = 6
Vendor ID = 121
Guid = 03000000790000000600000000000000

Here are the problems I'm having:

1. They're supposed to have rumble, but SDL is reporting no rumble.

2. `SDL_GameControllerGetAxis(con, SDL_CONTROLLER_AXIS_RIGHTY)` causes error "Joystick only has 4 axes", which is very strange because SDL_CONTROLLER_AXIS_RIGHTY has a value of 3.

Also note:

`SDL_JoystickNumAxes(joy)` returns 4.

`SDL_JoystickGetAxis(joy, 3)` doesn't set an error and actually returns the y axis of the right stick. `SDL_JOYAXISMOTION` events are also produced.

**Comment by sezero** [comment]
Does the suggested change fix your issues then?

**Comment by AntTheAlchemist** [comment]
> Does the suggested change fix your issues then?

Yes, it should be a3, not a4. This change prevents the error as well.

The lack of rumble is still an issue though.

**Comment by sezero** [comment]
> > Does the suggested change fix your issues then?
> 
> Yes, it should be a3, not a4. This change prevents the error as well.

@icculus, @slouken: Can this be considered for 2.0.18?

> The lack of rumble is still an issue though.

Don't know about that part

**Comment by khibich147** [comment]
> not working right stick( up and down)
> 
> SOLUTION In src/joystick/SDL_gamecontrollerdb.h (str138) you need to fix righty:a4 on righty:a3

what does that even how i can fix it ?

**Comment by AntTheAlchemist** [comment]
This joystick doesn't have any game controller mappings. It's just a plain joystick now. I noticed the GUID has also changed:

USB Joystick
Product ID 6
Vendor ID 121
GUID 03004f8e790000000600000000000000

**Comment by CatBoat0** [comment]
Need driver, i dont have dvd.
