### ISSUE TITLE
Crash on Vulkan detection

### ISSUE THREAD

**Issue by StanleySweet** [libsdl-org/SDL#5032]
Hey there

We're experiencing some issues with Vulkan detection on Windows as it crashes the game for some AMD users on startup

Version: 2.0.12
OS: Windows

Full commit: https://github.com/0ad/0ad/commit/b61a3332c4c0946c67fb36ef442d3ca956d4f546

Sample that's crashing

```cpp
static void ReportVulkan(const ScriptRequest& rq, JS::HandleValue settings)
{
	std::string vulkanSupport = "unsupported";
	// According to http://wiki.libsdl.org/SDL_Vulkan_LoadLibrary the following
	// functionality is supported since SDL 2.0.8.
#if SDL_VERSION_ATLEAST(2, 0, 8)
	if (!SDL_Vulkan_LoadLibrary(nullptr))
	{
		void* vkGetInstanceProcAddr = SDL_Vulkan_GetVkGetInstanceProcAddr();
		if (vkGetInstanceProcAddr)
			vulkanSupport = "supported";
		else
			vulkanSupport = "noprocaddr";
		SDL_Vulkan_UnloadLibrary();
	}
	else
	{
		vulkanSupport = "cantload";
	}
#endif
	Script::SetProperty(rq, settings, "vulkan", vulkanSupport);
}
```

Crashlog varies, but it only works by commenting this code.

Initial report thread https://wildfiregames.com/forum/topic/51184-alpha-25-could-not-start/

Seems like a driver bug, anyone experiencing this?

**Comment by icculus** [comment]
Every single crash in the initial report thread is crashing in OpenGL, not Vulkan, which leads me to suspect that a) loading Vulkan either confuses something on ATI's drivers if you then end up using OpenGL instead b) UNLOADING vulkan confuses something because it removes some thing that their OpenGL drivers also need, or c) touching vulkan at all adjusts some driver or GPU state that later causes OpenGL issues.

I would definitely start with commenting out the SDL_Vulkan_UnloadLibrary() line and see if the problem goes away.

But in all three of these scenarios (if one of them is correct), this is almost certainly a driver bug, not an SDL bug.

**Comment by StanleySweet** [comment]
a) Possible
b) Removing SDL_Vulkan_UnloadLibrary() doesn't fix the problem so not b) :)
c) Possible 

I guess we need to investigate more. It's a bummer really because we can't know how much of our users really support vulkan :/

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
