### ISSUE TITLE
OpenGL: Fullscreen Prevents Any Window to Show Up in Windows

### ISSUE THREAD

**Issue by MikuAuahDark** [libsdl-org/SDL#5065]
I'm running this on Windows 10 build 19043.1348 (21H1), AMD Radeon integrated graphics.

Before started,
1. Make sure there's Task Manager window running, it's set to show "Always on Top" (in Options), and is shown before running the program.
2. If your Windows DPI scale is higher than 100%, after compiling the program, **override** the DPI scale of the program like below
![gambar](https://user-images.githubusercontent.com/7500438/144701472-30d9c30c-51e6-455c-8e6e-cb2ccfe439a7.png)

Now, compile this test simple program that displays red maroon color all over the screen.
```c
#include <string.h>

#define SDL_MAIN_HANDLED
#include "SDL2/SDL.h"

/* Please change these to your desktop dimensions */
#define DESKTOP_W 1920
#define DESKTOP_H 1080

int main()
{
	int quit = 0;

	if (SDL_Init(SDL_INIT_VIDEO) < 0)
		return 1;

	/* Note: You also can use SDL_WINDOW_FULLSCREEN_DEKSTOP instead of borderless and it will have same issue */
	SDL_Window *window = SDL_CreateWindow("Test", 0, 0, DESKTOP_W, DESKTOP_H, SDL_WINDOW_OPENGL | SDL_WINDOW_BORDERLESS);
	SDL_Renderer *render = NULL;

	for(int i = 0; i < SDL_GetNumRenderDrivers(); i++)
	{
		SDL_RendererInfo info;
		SDL_GetRenderDriverInfo(i, &info);

		if (strcmp(info.name, "opengl") == 0)
		{
			render = SDL_CreateRenderer(window, i, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
			break;
		}
	}

	if (render)
	{
		while (!quit)
		{
			SDL_Event e;

			while(SDL_PollEvent(&e) != 0)
			{
				if ((e.type == SDL_QUIT) || (e.type == SDL_KEYUP && e.key.keysym.sym == SDLK_ESCAPE))
					quit = 1;
			}

			SDL_SetRenderDrawColor(render, 0x30, 0x00, 0x00, 0xff);
			SDL_RenderClear(render);
			SDL_RenderPresent(render);
		}

		SDL_DestroyRenderer(render);
	}

	SDL_DestroyWindow(window);
	SDL_Quit();

	return 0;
}
```

If the program is run correctly, with 2 of the prerequists above, the whole screen flashes then it forcefully makes the app running in foreground, even hiding the Task Manager window that has highest priority.

Furthermore if you press Ctrl+Alt+Del then click Task Manager, the window will flash again and show the Task Manager window. Unfortunately I can't record the screen because not even OBS is able to record what's going on.

This is same as love2d/love#1750 but that's with bigger codebase. This report is a smaller test case that can be reproduced using SDL alone.

**Comment by slouken** [comment]
I believe this is Windows behavior for fullscreen OpenGL windows. Does anyone have any workaround?

**Comment by peppy** [comment]
This is expected behaviour. It is the graphics driver assuming that the user wants to be displaying the fullscreen GPU accelerated app using exclusive fullscreen, reducing latency and improving performance.

When using OpenGL, it's up to the driver to determine when to enter this state. It sounds like what you are looking for is to force the window into "borderless fullscreen", which can be done in hacky ways. The best we have found to date is making the window either 1px larger or smaller than the actual screen size. Usually larger works better, but you also need to be wary of the fact that the window will draw over potentially two displays, which can lead to [black screens](https://github.com/ppy/osu-stable-issues/issues/207) during switching modes or [reduced performance](https://github.com/ppy/osu/discussions/17291) caused by [slight changes in how you implement the hack](https://github.com/ppy/osu-framework/pull/5068).
