### ISSUE TITLE
compute backends and dx12 future direction question?

### ISSUE THREAD

**Issue by hgkamath** [libsdl-org/SDL#5077]
Filing this issue, as to understand (a) what is possible? and (b) what would it involve if a direction is considered ?

Vulkan comes in two flavors
1. shader for graphics, SPIR-V for vulkan shaders
2. compute-kernel for  SPIR-V for compute including OpenCL-2.1

I read on https://wiki.libsdl.org/CategoryVulkan that currently there is ongoing vulkan graphics development/support in SDL. I guess this is mostly the former flavor.

- Q1. is compute something that SDL will venture into?
- Q2. What may be a future direction of SDL with regard to a software that uses SDL to allow paravirtualization or passthrough of
  - q2a. win/directx-12
  - q2b. win/direct-compute-ML
  - q2c. all-arch/vulkan-compute

For windows, I believe the WDDM driver version 2.4(GPU paravirtualization support,), 2.5(directML), 2.9(GPU hw accel), 3.0(Linux hostmode drivers) matters as to what may be possible

I ask in the context of being a qemu virtual machine software user. qemu uses SDL as one of the backends. Currently through virgl it is beginning to have a opengl virtual display. Inside a guest VM, Linux Mesa, is now also able to use direct-x and vulkan backends and also transform opengl to vulkan via Zink. So both VM guests platforms are , in a sense, ready to use any of directx or vulkan as backends. I am just a user, not expert. Wondering if SDL development will lead to qemu to ever have its own /dev/dxg device or compute-gpu just as wsl2 does.

**Comment by icculus** [comment]
> I read on https://wiki.libsdl.org/CategoryVulkan that currently there is ongoing vulkan graphics development/support in SDL. I guess this is mostly the former flavor.

Yes, because Vulkan graphics need (a small amount of) platform-specific code to figure out how to get a VkInstance that can talk to the system's desktop environment, but [the API surface](https://github.com/libsdl-org/SDL/blob/423feac69b7db9b8eaca486c766a75bccea8353a/include/SDL_vulkan.h) is extremely small and is out of the way before initial setup is complete.

Vulkan compute doesn't need most of that; for maximum flexibility, you can use the existing SDL_Vulkan_LoadLibrary and SDL_Vulkan_GetVkGetInstanceProcAddr to help get a compute VkInstance up and running, but after that, it's just all direct Vulkan calls and doesn't need any SDL support infrastructure.

I can't speak to what DirectX12 compute looks like at the moment, but I suspect it is similar...but for Vulkan, what you're asking for here: you already have all you need from SDL.
