### ISSUE TITLE
SDL_RenderGeometry: try with big endian

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#5093]
Maybe we should double check RenderGeometry with big endian architecture

**Comment by slouken** [comment]
It for sure won't work right now. There's a real problem with having the API take SDL_Color and then treating them as ints. The API should take a well defined color format and internally we probably need to convert to the type used by the graphics layer. On little endian systems we can probably leave it as-is, but for big-endian systems, we need to byteswap the color inputs.

What is the underlying type that is required for the various graphics APIs? We probably want to use that rather than "int"

**Comment by slouken** [comment]
> In my opinion it would be cleanest if it was like this:
> 
> * SDL_RenderGeometry takes an array of `SDL_Vertex`, which has a `SDL_Color` member.
> * SDL_RenderGeometryRaw takes a strided array of `SDL_Color` for its colors. Therefore `SDL_RenderGeometry` doesn't do any real casting, it just sends the offset of the color field.
> * Backend code consistently takes that strided array of `SDL_Color` and copies it through to graphics driver code, telling the driver that it's a 4 component unorm8 color (since that's what `SDL_Color` is).

Agreed, this seems like the right solution.

**Comment by slime73** [comment]
Is it safe to change `SDL_RenderGeometryRaw` to take `const SDL_Color *` instead of `const int *`, or would doing so break API compatibility?

**Comment by DanielGibson** [comment]
Yeah sorry, I should've checked this report first, then I'd have noticed that the discussion is happening here :)
To keep discussion in one place, I'll just post my reply here as well:

How could this best be fixed?
Could you just change the function signature accordingly and quickly release 2.0.20 and deprecate 2.0.18, hoping only few people (who would need to adjust their code to pass SDL_Color) use this function so far?
I *think* the old and new versions of the function should still be binary compatible, as they take pointers to data that is supposed to be identical (and C/`extern "C"` doesn't mangle the types into the function names)?

Or would it be better to give the fixed version another name (and keep the original)?
You could still add something like `#define SDL_RenderGeometryRaw SDL_RenderGeometryRaw2` to the header so new code automatically uses the fixed version of the function, but existing binaries (and `dlsym()`) will still get the original function

**Comment by slouken** [comment]
Changing the type of the parameter wouldn't break the ABI. People would have to change their code, but if we do it for the next revision it would probably be okay.

**Comment by DanielGibson** [comment]
Sounds good, but 2.0.20 should be released pretty soon then to minimize the risk that 2.0.18 ends up in a release version of a Linux distro that doesn't update software after a distro release (like debian stable, though that one in particular shouldn't be at risk as the next debian stable is due in 2023)

**Comment by 1bsyl** [comment]
I am trying with a big endian QEMU virtual machine but I am stuck because the graphics interface isn't starting, so I am not able to run anything graphic.

the code previous to RenderGeometry, didn't care about endianess:
https://github.com/libsdl-org/SDL/blob/108bb5aabec27f41f977bdf7a4d2ed3f3a3962eb/src/render/SDL_render.c
https://github.com/libsdl-org/SDL/blob/108bb5aabec27f41f977bdf7a4d2ed3f3a3962eb/src/render/opengl/SDL_render_gl.c

So there may be no issue ...

**Comment by slouken** [comment]
We're planning on releasing 2.0.20 soon, so we can get this change out before too many people use RenderGeometryRaw with int* instead of SDL_Color*

Can anyone verify that the various libraries that would use that (DearImGui, Spine, Nuklear, Libroket, Microui, etc.) would work well with this change?

**Comment by DanielGibson** [comment]
I just checked Dear ImGui, it indeed uses `SDL_RenderGeometryRaw()` so it'll either break with 2.0.18 or 2.0.20 (you can only cast either to int **xor** to SDL_color), unless a special case with `#if SDL_VERSION_ATLEAST(2,0,20)` is added: https://github.com/ocornut/imgui/blob/4a43dcb940ea6616a28ae78e795e30f1f5f354c8/backends/imgui_impl_sdlrenderer.cpp#L181

Maybe they could live with breaking it for 2.0.18 and only support 2.0.20, once it's released?

Another thing I noticed is that it uses Uint32 in RGBA-order (or optionally BGRA-order, but that doesn't help us) for colors internally and doesn't care about endianess: https://github.com/ocornut/imgui/blob/4a43dcb940ea6616a28ae78e795e30f1f5f354c8/imgui.h#L2219-L2232
So strictly speaking their SDL Render code is wrong (on Big Endian machines), as it doesn't convert the colors. Of course this issue is independent of whether `SDL_RenderGeometryRaw()` uses int or SDL_Color for colors.

**Comment by DanielGibson** [comment]
No idea about Spine, do you mean this: http://esotericsoftware.com/ ? It appears to be closed-source so can't check..

**_Nuklear_** doesn't have an official SDL_Render example yet, but there's a PR: https://github.com/Immediate-Mode-UI/Nuklear/pull/280
I think it **won't be affected**, because it casts the pointers to `const void*` (nice solution for C, won't work in C++, so unfortunately not an option for Dear ImGUI)

**_MicroUI_**: No official example, but PR: https://github.com/rxi/microui/pull/48
**This would need to be adjusted for SDL_Color.** @1bsyl as this is also plain C, maybe you could just cast the color to `const void*` like in the Nuklear example?

**_LibRocket_**: PR with example not merged yet: https://github.com/libRocket/libRocket/pull/301/files
**This would need to be adjusted for SDL_Color.** As it's C++ this will be a bit uglier (or 2.0.20+ only) like Dear ImGui.
(The last commit in their repo is from February 2020, is this still maintained?)

If there's examples for more libs, I guess @1bsyl will know about them :)

**Comment by slouken** [comment]
Do we maybe want to officially change the type to RGBA or BGRA and not SDL_Color? Would that make the raw API easier to use for those libraries?

**Comment by slime73** [comment]
All of those libraries (Nuklear, MicroUI, and LibRocket) use individual memory-sequential bytes for colours just like SDL_Color has, their current 2.0.18-relative code is just casting to `int*`before passing those colours into SDL. Dear ImGui is the only API I know of that passes around int-packed colours on its own rather than memory-sequential byte components.

Or in other words, I don't think using an int-packed type as input makes it easier for those libraries to use SDL_RenderGeometryRaw (aside from the pointer type change affecting whether those pull requests compile). An integer interface would make it confusing when endianness is involved, too.

**Comment by slouken** [comment]
Fair enough, just wanted to think this through, because we're rushing 2.0.20 for this.

**Comment by 1bsyl** [comment]
@DanielGibson there is https://github.com/mikke89/RmlUi
Which replaces libRocket I guess
Spine isn't closed sources, but hard to setup. I may be not free though. There used to be an exemple in the PR for RenderGeometry.

Not sure what you try to see ? it's still ABI compatible, and when updating the compiler will tell people to cast to SDL_Color * and that's all.

**Comment by 1bsyl** [comment]
So I got a vm working with bigendian, and first thing is a illegal instruction generated .. https://github.com/libsdl-org/SDL/commit/6101499c7c1254d26858724655c3d999c7c7f4d2

**Comment by 1bsyl** [comment]
On bigendian, opengles2 backend renders with correct colors.
But SDL_RenderReadPixel, seem to read inversed values.

**Comment by 1bsyl** [comment]
I think the software renderer part is also ok, regarding the color ordering.
But I see an issue because it draws wrongly on the frame buffer (32 bits). color aren't correct there:
I simply clear the screen in white.
```
         SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
         SDL_RenderClear(renderer);
```
And it draws a yellow background

**Comment by 1bsyl** [comment]
Adding a PR https://github.com/libsdl-org/SDL/pull/5109 to cast with SDL_Vertex and SDL_VertexSolid ..

**Comment by 1bsyl** [comment]
The big endian issue was in the opengles2 driver and fixed above (it was never used).
Now: opengl is ok. opengles2 ok. software ok (with native "fb", or emulation with opengl or opengles2).

In the end, there were no specific handling to do with big-endian and render geometry.
Closing this issue about big endian ...
