### ISSUE TITLE
Differing window surface pixel formats on Mac vs Windows/linux

### ISSUE THREAD

**Issue by MyreMylar** [libsdl-org/SDL#5149]
Hello,

More of a question than a bug, but are the default surfaces created when you create a window intended to have different pixel formats on different platforms. Over at pygame we've been wrestling with issues on mac that seem to have their roots in the default mac windows surface being in an ARGB format while windows and linux are in `SDL_PIXELFORMAT_RGB888`

Here is an SDL test program I made to show the default window surface's pixel format:

```
    #define SDL_MAIN_HANDLED
    #include "SDL/SDL.h"
    #include <stdio.h>
    #include <iostream>


    int main(int argc, char* argv[]) {

        SDL_SetMainReady();
        SDL_Init(SDL_INIT_VIDEO);

        SDL_Window* window = NULL;
        SDL_Surface* winSurface = NULL;

        window = SDL_CreateWindow( "Example", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1280, 720, SDL_WINDOW_SHOWN );

        // Make sure creating the window succeeded
        if ( !window ) {
            std::cout << "Error creating window: " << SDL_GetError()  << std::endl;
            system("pause");
            // End the program
            return 1;
        }

        std::cout << "Created window!\n";

        winSurface = SDL_GetWindowSurface( window );

        SDL_PixelFormat* pixelFormat = winSurface->format;
        Uint32 pixelFormatEnum = pixelFormat->format;
        const char* surfacePixelFormatName = SDL_GetPixelFormatName(pixelFormatEnum);

        std::cout << " Window Pixel Format: " << surfacePixelFormatName  << std::endl;

        // Clean up
        SDL_Quit();

        return 0;
    }
```

On windows I get:

```
 Window Pixel Format: SDL_PIXELFORMAT_RGB888
```

But given the results we see in pygame I'm assuming that it spits out something different on Mac.

My questions are - is this intended and something we should be handling properly in pygame? Is there a reason for the ARGB surface on mac versus windows & linux (may affect how we handle it)?

**Comment by Starbuck5** [comment]
On mac I get:

```
Window Pixel Format: SDL_PIXELFORMAT_ARGB8888
```

And to clarify a bit on MyreMylar's point, we have Surfaces try to use the same pixelformat as the display, if one has been created. (So they can be blit quicker, presumably). So these Surfaces are being set up as a bunch of fully zeroed pixels (0, 0, 0, 0), instead of the (0, 0, 0, 255) we get on other platforms.

**Comment by slouken** [comment]
Yes, the window surface is intended to be in the optimal format for display and you should convert your artwork at load time or let SDL's blit capability convert at runtime for the display format.

**Comment by Starbuck5** [comment]
It seems strange to have opacity on a display surface, since it's not going to let you see through to the desktop or anything.

The format specification seems to come from here in the end: https://github.com/libsdl-org/SDL/blob/main/src/video/cocoa/SDL_cocoamodes.m#L139-L162

Perhaps it would be beneficial / possible to change the top one there into XRGB8888, since the opaque bits are theoretically useless, and maybe the blits would be faster? Since then it doesn't actually have to care about the alpha in some cases?
