### ISSUE TITLE
windows devel binary download has include path wrong

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#5173]
in http://libsdl.org/release/SDL2-devel-2.0.18-VC.zip , the SDL headers are directly in `include/`, unlike when doing e.g. a standard install on linux where they end up in /usr/include/SDL2/.
this makes it impossible to use the recommended, sdl2-config-free way of using `#include <SDL2/SDL.h>` without manually messing around with the contents.

**Comment by slouken** [comment]
The recommended way of including SDL headers is:
#include "SDL.h"

**Comment by rofl0r** [comment]
not what i recommend for people that not only want native, but also cross-compile to work: https://sabotage-linux.neocities.org/blog/5/ (hint: sdl-config breaks that, as it returns host settings)

**Comment by slouken** [comment]
Cross-compiled sdl-config returns cross-compile settings. I use this for the official SDL Windows builds, built using a cross-compiler on macOS.

Please don't recommend that people include <SDL2/SDL.h>, that's against 20 years of official SDL recommendation and documentation, specifically because of using it in lots of different environments that don't necessarily work the way you'd expect on official Linux distributions.
