### ISSUE TITLE
SDL_memcpy_REAL low performance in VS2022

### ISSUE THREAD

**Issue by An0nyMooUS** [libsdl-org/SDL#5225]
![image](https://user-images.githubusercontent.com/73304497/149559335-2f9b40d8-e9e4-4ac6-97f0-82e4fe994c49.png)

I'm using bgfx + SDL for my game engine.

However, analyzing with Intel VTUNE Profiler, I noticed that the ``SDL_memcpy_REAL`` is having a BAD performance.

6.4s to copy?! I don't know what it is, but it's the function that is using the most time according to Intel VTUNE.

How do I disable this function and use default memcpy function? 🤔

**Comment by XXxR4GALXxx** [comment]
Release:
![image](https://user-images.githubusercontent.com/73304497/149567650-ceca2fdb-59a2-44dd-a20a-4747e61b78af.png)

**Comment by XXxR4GALXxx** [comment]
...and, why ``HAVE_MEMCPY`` is 0 with MSVC 2022?! (using CMAKE)

**Comment by cgutman** [comment]
> However, analyzing with Intel VTUNE Profiler, I noticed that the SDL_memcpy_REAL is having a BAD performance.

That alone doesn't mean there's anything wrong with `SDL_memcpy()`. You have to look at where those calls are coming from. If you're copying data very frequently or copying large buffers, it's totally expected to see lots of CPU time spent doing that - it is simply doing the work you asked it to do.

If you were to replace `SDL_memcpy()` with `memcpy()` and saw the CPU overhead of memory copying go down significantly, that would be worth a look.

> ...and, why HAVE_MEMCPY is 0 with MSVC 2022?! (using CMAKE (add_subdirectory))

Because `memcpy()` is a libc function and SDL avoids libc on Windows by default to prevent a dependency on the Microsoft Visual C++ Runtime. If you want it to link to libc, you can pass `-DSDL_LIBC=ON` when to CMake when building SDL and `SDL_memcpy()` will just become a call to `memcpy()`.

**Comment by glebm** [comment]
Perhaps we can use `CopyMemory` on Windows? https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366535(v=vs.85)

**Comment by sezero** [comment]
> Perhaps we can use the `CopyMemory` function (XP+) or the `RtlCopyMemory` macro (2000+) on Windows? 

It's just a macro wrapping around memcpy.

**Comment by cgutman** [comment]
ntdll.dll exports many CRT functions (including memcpy, memmove, memset, and memcmp). I wonder if we could convince MSVC to link to ntdll.dll for those rather than vcruntime.dll. That would let us use the optimized implementations of those CRT functions (where possible), rather than being stuck with our slower C implementation.

**Comment by slouken** [comment]
Do we know that SDL's memcpy() implementation is slower than the Windows version? I haven't done benchmarks recently...

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
