### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by pionere** [libsdl-org/SDL#5230]
I made a few adjustments to SDL2 in my [fork](https://github.com/pionere/SDL/tree/dev). Please have a look at the [ChangeLog](https://github.com/pionere/SDL/blob/dev/dev_CHANGELOG.md), some of them might be relevant to you as well.

**Comment by ulatekh** [comment]
I would imagine that the volunteer SDL developers are busy, and are not going to sort through your branches to determine what contains something of value and what doesn't.

If you have something to submit, then separate them by purpose, squashing/separating commits if appropriate, and submit pull requests.

**Comment by pionere** [comment]
> If you have something to submit, then separate them by purpose, squashing/separating commits if appropriate, and submit pull requests.

I [don't](https://github.com/libsdl-org/SDL/pull/5179) care [that](https://github.com/libsdl-org/SDL/pull/5130) much [any](https://github.com/libsdl-org/SDL/pull/5183) more [.](https://github.com/libsdl-org/SDL-1.2/pull/855)

**Comment by icculus** [comment]
I'm working on detangling these commits; some of them we definitely want and some of them we definitely don't. I'll write up an explanation once I get it sorted out.

Thanks for your patience on this!

**Comment by icculus** [comment]
Okay, I've gone through all the commits in the `dev` branch, including things that weren't specifically mentioned in the changelog. Most of it is quite good!

Going forward, if we can get your fork and upstream in sync, let's figure out how to do that...if you'd rather live separately and have us pull in a few patches when appropriate, that's okay, too; whatever you are comfortable with is what we'll do...but understand that sometimes pull requests don't get handled for awhile, especially when we're crunching on the next release, and sometimes we are picky about little details, and I totally understand if that is annoying.

But also, this took a long time to sort through and I probably won't do it this way again, so let's figure out how to make this work better for everyone next time, if you want to.

With that out of the way, here are the notes on the things I skipped, and why.

- We don't want the dynamic API to be disabled through the configure/cmake scripts (https://github.com/pionere/SDL/commit/ae1585de941eb1a50ffc0402b65f9e43ae07302a, etc). It was intentional that one has to turn it off by editing a header buried deep in SDL's sources...so it can be done, but it has to be done intentionally. The goal was to make people that don't feel strongly about it not turn it off on a whim, which would make it difficult/impossible to override a build of SDL included with an app. For an embedded system where it _never_ makes sense, though, we can definitely add an `#ifdef` to remove it unconditionally, as we do for several platforms already.

- What was this change? https://github.com/pionere/SDL/commit/1882e6e93fbb6995262f85953c54349a0edc2c88 Better sound quality? These values have been there since the first revision of the CVS repository, 20+ years ago, so a little clarification would help me here before we change it. If it sounds better or fixes a bug, etc, let's definitely pull this in, though.

- Disabling assertions can't turn off the whole subsystem, because `SDL_assert_always` can't be removed (https://github.com/pionere/SDL/commit/7aa402616e2f072a96497f5a5648b739e05849e6) ... we won't remove APIs before we tear up everything in SDL3 and even there I would hesitate to remove this, personally.

- Most of https://github.com/pionere/SDL/commit/2adda5b42f4733470d0db47981b753a185c44031 seems good, but despite being in an "iphoneos" directory, SDL_mfijoystick.m is used on macOS, too (MFI devices, "Made For iOS," obviously started there, but the API was added to macOS later).

- I haven't added the dummy thread implementation (https://github.com/pionere/SDL/commit/4bf613e96b15d3087b43f10997b78d0932331e39) because there's already a weird tapdance with the "generic" stuff in SDL already, and I need to look at this more, but after looking over the whole patchset, Sam and I are of the opinion that "disabling" a subsystem _should not remove the API_, but just leave a stub there...so most of the bulk can evaporate out of a build, but the function is still available (even if that function just returns immediately with a failure)...which is to say we're probably going to want this patch once I research more.

- The other consensus we had after looking at this patchset is that "disabling" subsystems is a giant mess of preprocessor checks and inconsistencies in the configure script, and a lot of your work _improves_ the code about that, but we really want to rip a lot of this out and simplify it all at some point. But in the meantime, most of your patches are moving towards making this problem suck less, so in they go.

- This cleanup patch (https://github.com/pionere/SDL/commit/f8a63d295d1ed6c36d5a4180542dc4730ad3fd12) is mostly good, but it needs to be broken down into separate commits, I think. Just making a note here so I remember to come back and do that. I'll move this to a separate issue so it isn't forgotten.

- We think (perhaps incorrectly!)  that these sort of patches are unnecessary, as (we hope) the RWops calls will correctly fail and not need a special `#ifdef` to get the right results: https://github.com/pionere/SDL/commit/6c3e1e8106bb048bfcc5e5d8d93d5bdb53e5e1a4  ...if that isn't the case, we would rather SDL be fixed to work that way instead of adding these `#ifdef` checks.

- We would rather logging not be removed entirely in any circumstance (https://github.com/pionere/SDL/66fcc1a70cf7af2dc6554071e8993e168dd48d810)

- Disk/dummy audio should not default to off (https://github.com/pionere/SDL/commit/f2c73a7fb0c445074562a504b3badeea22a38568), as it's useful for these to be available to end users in some cases, and they don't take much space.

- Likewise for virtual joysticks (https://github.com/pionere/SDL/commit/2821272508d9fdf65db274ec314bf4323e03ed4f), which can be useful to some apps.

- I absolutely want the "upload build artifacts" patch (https://github.com/pionere/SDL/commit/bf08b8f89ea2e37dee0d7e63386116e763f5eff6) but there are some other GitHub Actions changes I want to make before I apply this. I'll move this to a separate issue so it isn't forgotten.

- We may expose descriptions for video/audio, so I'm opting to not apply https://github.com/pionere/SDL/commit/5718be3ca3c8c20f74c7ff4fbe853dc8b67cb2ac for now.

- The IME work is probably good (https://github.com/pionere/SDL/commit/31b4db8b5a1712d4b6b4986dc78ea16eca5964f8 and https://github.com/pionere/SDL/commit/2cbbe764846df85fc0646827302370999c3200ac) but I need to read it more carefully before I apply it.

**Comment by icculus** [comment]
Ok, PR #5248 has the stuff I definitely want to merge (minus a few commits that landed in @pionere's patch today that I haven't looked at yet). Going to let people pick through that for a little bit and then merge it.

**Comment by pionere** [comment]
@icculus : thanks for your time and effort you spent on reviewing my changes.

I would definitely prefer to stay as close to the upstream as possible, but at the moment I'm still exploring the code and would like to apply changes (even though minor ones) faster than the speed of the PR acceptance process. That said most probably I'm going to slow down soon, so this might change in the near future.

About the skipped changes:
- Dynamic API: yes, I saw the long comment about the reasoning behind your solution. The problem I see with dynamic API is that it prevents optimizations and as sdl2 starts to gain size (maybe I'm doing something wrong, but it grow from 900kb to 1200kb recently), I think it is important that unused features and code can be eliminated.
- pionere@1882e6e93fbb6995262f85953c54349a0edc2c88 : I don't see a reason why the original change (from 0xFF to 0xFE) was necessary. If you apply the logic of 456a0431482c78519fa8d671e68901fa9fd99a40 to U8, then 0xFF should be used.
- pionere@7aa402616e2f072a96497f5a5648b739e05849e6 : the problem is that if you set SDL_DEFAULT_ASSERT_LEVEL to zero, its value is not propagated to the config file with `#cmakedefine`. Maybe standard `#define SDL_DEFAULT_ASSERT_LEVEL @SDL_DEFAULT_ASSERT_LEVEL@` should be used?
- pionere@2adda5b42f4733470d0db47981b753a185c44031 : so you would prefer a different name for `SDL_JOYSTICK_IOS`, or are there other concerns?
- pionere@6c3e1e8106bb048bfcc5e5d8d93d5bdb53e5e1a4 : without the `#ifdef`s the FILE subsystem wont be really disabled, since the `file/*.c` sources are added unconditionally.
- dummy/virtual objects: I think that only a minority of the users would use them and they can turn them on if they want. As an application developer I would like to see if a real entity is available or not. But obviously that is up to you to decide...

About future changes, here is what I planned:
- make audio capture optional
- move driver specific fields of SDL_VideoDevice to union/SDL_*DriverData/new entity (?)
- make driver specific API optional (?)
- add any changes/adjustments while working on the two points above (I already have a few SDL_InvalidParamError/SDL_SetError + SDL_bool vs int changes)

What are your opinions about the above points?

The other question is how to do the smaller changes. I might create a separate issue for those small changes, but they might become dependent on each other soon and not sure how you like to be bombarded by minor changes.
Alternatively I could collect the really minor changes in a single PR and extend it if necessary. You could review/merge it from time to time and then I one open a new PR for the next changes?

**Comment by icculus** [comment]
Okay, I think I have all the unresolved issues split out into separate bugs, so once we merge #5248, we can close this MegaIssue.   :)

**Comment by pionere** [comment]
Could you please answer the questions at the end of [my comment](https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019446075)?

**Comment by icculus** [comment]
> @icculus : Could you please answer the questions at the end of [my comment](https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019446075)?

Oh, right, sorry!

> Dynamic API: yes, I saw the long comment about the reasoning behind your solution. The problem I see with dynamic API is that it prevents optimizations and as sdl2 starts to gain size (maybe I'm doing something wrong, but it grow from 900kb to 1200kb recently), I think it is important that unused features and code can be eliminated.

I think the growth was that hidapi is now built into SDL, as of 2.0.18; before it was a separate library. We did this so we could expose it as a stable API, since SDL's version has diverged from the mainline (or it can be built to be binary incompatible and that caused us problems? It was something like that.).

The lowest hanging fruit, for binary size, is probably disabling that and the software blitters/converters, which were like a third of the library size when I looked at this a few years ago. Granted, there's a million subtle places you might need them, but if you have an embedded device where you _know_ you have all your data in the right format, it could be worth chopping it out.

> pionere/SDL@7aa4026 : the problem is that if you set SDL_DEFAULT_ASSERT_LEVEL to zero, its value is not propagated to the config file with #cmakedefine. Maybe standard #define SDL_DEFAULT_ASSERT_LEVEL @SDL_DEFAULT_ASSERT_LEVEL@ should be used?

I've added a bug to remember to look at this further.

> make audio capture optional

How much space would this actually save? In most audio backends, this is usually a small function and a few more conditionals during device open. I don't really want to litter `#ifdef` lines everywhere to save a few bytes here and there.

> move driver specific fields of SDL_VideoDevice to union/SDL_*DriverData/new entity (?)

There isn't a lot of this (a few Metal things, etc), and there's never more than one of these objects alive per process, so I suspect this isn't worth your time, or the added preprocessor clutter.

> make driver specific API optional (?)

There isn't a _lot_ of this, but there are a few of these scattered around (like the OpenGL texture binding stuff in the render API, etc), but again: if the goal is reducing library size, these are not big pieces of code.

> I already have a few SDL_InvalidParamError/SDL_SetError + SDL_bool vs int changes

This specific thing is thankless work, but I'm glad someone is doing these specific cleanups.


I think everything I didn't reply about here got opened as a separate bug, which is to say we intend to either apply the patch soon or talk about them more over at those issue pages. Let me know if I missed something, though!

**Comment by pionere** [comment]
> I think the growth was that hidapi is now built into SDL, as of 2.0.18; before it was a separate library. We did this so we could expose it as a stable API, since SDL's version has diverged from the mainline (or it can be built to be binary incompatible and that caused us problems? It was something like that.).
> 
> The lowest hanging fruit, for binary size, is probably disabling that and the software blitters/converters, which were like a third of the library size when I looked at this a few years ago. Granted, there's a million subtle places you might need them, but if you have an embedded device where you _know_ you have all your data in the right format, it could be worth chopping it out.

Great, thanks for the info.
- software blitters/converters: you mean the src/render/software part? In the game I'm working on we only do whole blits and nothing fancy...
- hidapi: I saw there is a configuration flag to use hidapi for joystick or not. So hidapi is completely optional? What is the consequence if the joystick does not use hidapi?

> > make audio capture optional
> 
> How much space would this actually save? In most audio backends, this is usually a small function and a few more conditionals during device open.

No idea, I thought it makes about half of the audio code. But I haven't even checked yet how much space is used by the audio code.

> I don't really want to litter `#ifdef` lines everywhere to save a few bytes here and there.

Right, that is not the plan. If it takes too many `#ifdef` then I just skip it.

> There isn't a lot of this (a few Metal things, etc), and there's never more than one of these objects alive per process, so I suspect this isn't worth your time, or the added preprocessor clutter.
> There isn't a _lot_ of this, but there are a few of these scattered around (like the OpenGL texture binding stuff in the render API, etc), but again: if the goal is reducing library size, these are not big pieces of code.

Noted. Thanks for the insight.

> Let me know if I missed something, though!

Just one thing: Do you prefer a collector PR, or many one-by-one?

**Comment by 1bsyl** [comment]
@pionere there are variables to reduce the library size, inside SDL_internal.h 
https://github.com/libsdl-org/SDL/blob/main/src/SDL_internal.h#L59

**Comment by pionere** [comment]
@1bsyl : thanks for the tip, I'm going to have a look at it.
@icculus : just to be clear, I do not intend to make an application specific sdl2, just looking for generic ways to reduce the footprint.
btw: you might want to add some of the changes from saturday to the big one:
- e9d327dcac6ffb7e5033539933e029b8fc99e9ba : makes open_audio_device much more readable.
- 0f84fa0b4391ee174cba02d3f8b496fdec86600a : simplifies SDL_DUMMY/OFFSCREEN_CreateWindowFramebuffer
- 2b389c5133a0151a73ca6a4af6f4e26722a2abe6: updates SDL_CreateRGBSurface* interface
- f87cf70137d6c457bdf750a42eebd95dfdd12214, 6b849add37cffa2ff8f135cbbb8be65ad7d77518:  error-handling fixes
- 5516e9c45441eed189d5b5b1a59e2171a3f98120: sync D3D_RenderReadPixels with D3D11_RenderReadPixels

**Comment by icculus** [comment]
> software blitters/converters: you mean the src/render/software part? In the game I'm working on we only do whole blits and nothing fancy...

Mostly SDL/src/video/SDL_blit*, generated by sdlgenblit.pl

>  hidapi: I saw there is a configuration flag to use hidapi for joystick or not. So hidapi is completely optional? What is the consequence if the joystick does not use hidapi?

`--disable-hidapi` from the configure script.

It'll work through standard interfaces, like /dev/event or XInput, but hidapi talks directly to devices, so they don't need specific drivers, etc. It gives a significant increase in device support.

> Just one thing: Do you prefer a collector PR, or many one-by-one?

A PR with multiple related things is welcome, but feel free to put unrelated things in separate PRs.  :)

**Comment by icculus** [comment]
Skipping this one: https://github.com/libsdl-org/SDL/commit/2b389c5133a0151a73ca6a4af6f4e26722a2abe6

Don't want to change the docs that say "we don't use it *but you must still set this to zero*" in case we _do_ use it later.

Still looking at https://github.com/libsdl-org/SDL/commit/e9d327dcac6ffb7e5033539933e029b8fc99e9ba but after that, I _think_ everything mentioned here is resolved, and we should close this MegaIssue.  :)

**Comment by icculus** [comment]
> Still looking at https://github.com/libsdl-org/SDL/commit/e9d327dcac6ffb7e5033539933e029b8fc99e9ba

I think I'm going to pass on this one.

This was the last thing pending for this issue, so I'm closing.
