### ISSUE TITLE
mingw (and cygwin) builds don't use alloca()

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5234]
In configure.ac and CMakeLists.txt, we specifically do not check
for `alloca` for mingw/cygwin targets:
https://github.com/libsdl-org/SDL/blob/main/configure.ac#L323
https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L858
As a result, `HAVE_ALLOCA` is never defined. On the other hand,
SDL_config_windows.h and SDL_config_winrt.h do define `HAVE_ALLOCA`
by themselves.  Is there a specific reason for this weirdness?
Some historical issue???

**Comment by sezero** [comment]
Looks like it began with this which I don't fully understand the reason for: https://github.com/libsdl-org/SDL-1.2/commit/2013951be47a92c321100afb72b3cee32d4560ef

**Comment by okuoku** [comment]
I guess it's just a oversight; On GCC/Clang, we should have `HAVE_ALLOCA` regardless of LIBC since they have `__builtin_alloca`. (But anyway, GCC will generate call into [`memcpy` etc during optimization](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56888) thus I think we need `HAVE_LIBC` anyway on Gcc platforms.)

> Looks like it began with this 

It's from https://github.com/spurious/SDL-mirror/commit/391d73e37b26614e2e343ca8e9d4334e07380896 .

**Comment by sezero** [comment]
> It's from [spurious/SDL-mirror@391d73e](https://github.com/spurious/SDL-mirror/commit/391d73e37b26614e2e343ca8e9d4334e07380896) .

That was some bad patch: A bad workaround for lacking alloca.h resulting in disabling alloca..
The whole situation looks like an oversight.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL/commit/a575e2cf5eeb8775cdf30ee85a4eda70d2fa4f24 and did the same to SDL-1.2
