### ISSUE TITLE
DualShock 4 custom LED settings are discarded when SDL2 applications are launched

### ISSUE THREAD

**Issue by maxigaz** [libsdl-org/SDL#5243]
I use [this solution](https://gaming.stackexchange.com/questions/336934/how-to-set-default-color-and-brightness-of-leds-of-the-dualshock-4-controller-on/336936#336936) for setting the LED colours and brightness on my DualShock 4 system start. (I use the value `000001` for dimmed blue, so that it doesn't drain the battery that much.)

This setting is discarded when any of the following applications are launched, so the default bright blue is set as a colour:

- DOSBox Staging 0.78.1 ([bug report](https://github.com/dosbox-staging/dosbox-staging/issues/1248))
- DOSBox-X 0.83.21 SDL2 version
- DevilutionX v1.3.0

OS: Manjaro Linux x86_64
SDL version: 2.0.18.

**Comment by eloj** [comment]
Just to be clear, this is not a problem for applications that do not change the LED color to begin with, which I've verified myself using `testjoystick`.

The issue seems to be that there is no API for an application to query the pre-existing LED colors from the device, such that they can be restored say when the application exits.

I've tried to determine if this is even possible to do, i.e is there actually a way to get this information from the controller? Going by [this comment in the linux kernel](https://github.com/torvalds/linux/blob/d569e86915b7f2f9795588591c8d5ea0b66481cb/drivers/hid/hid-sony.c#L2168), it is not.

In that case, it would be necessary to retrieve this information from the operating system, which is quite a hacky solution IMO. I personally wouldn't consider it unless maybe someone could demonstrate how to do it on Windows too, so it's not just a linux thing.

Unfortunately I think the best thing an SDL application can do at the moment, is to turn off the LEDs when exiting.

**Comment by slouken** [comment]
Yes, unfortunately it's not possible to query the previous LED value. It would be possible to add a brightness hint, if that's something you're still interested in.

I'll go ahead and close this for now, feel free to reopen it if you'd like.
