### ISSUE TITLE
Pionere's IME patches

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5249]
> The IME work is probably good (https://github.com/pionere/SDL/commit/31b4db8b5a1712d4b6b4986dc78ea16eca5964f8 and https://github.com/pionere/SDL/commit/2cbbe764846df85fc0646827302370999c3200ac) but I need to read it more carefully before I apply it.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5230#issuecomment-1019428704_

**Comment by pionere** [comment]
@icculus: I just found an issue with 2cbbe764846df85fc0646827302370999c3200ac. In IME_ShowCandidateList when it reallocates the ime_candidates the returned value of realloc is NULL if the memory is not modified.
b4c676f1330ee26ad1128b55c93dec0fd5030160 fixes the mistake.

**Comment by pionere** [comment]
sorry, it is me again: 9e90098180427e37ba98d346d0498262cd944eac

**Comment by icculus** [comment]
I have to confess that I have no idea what LANG_CHT is or why we explicitly check Korean here, or what didn't work about any of that to comment it out.

That code came in from here originally: https://github.com/libsdl-org/SDL-historical-archive/commit/ef79a3536dce3a21c7a7aa1261dc63882af51c69

Once I understand that, we can merge these commits.

**Comment by pionere** [comment]
As far as I understood a language code consist of a primary part and a secondary part. The primary part (PRIMLANG) speficies the language 'group'.
It can be korean (LANG_KOREAN) or chinese(LANG_CHINESE) or english(LANG_ENGLISH), while the whole language is more specific: traditional chinese(LANG_CHT) or simplified chinese(LANG_CHS).
This means PRIMLANG() must be checked against the language group (LANG_KOREAN, LANG_CHINESE, etc), while LANG() can be one of LANG_CHT, LANG_CHS, etc..
That is why checking PRIMLANG() against LANG_CHT is wrong and always fails since PRIMLANG is created with mask 0x3FF, while LANG_CHT is (1024 | 4) == (0x400 | 0x04).

As for the check against Korean to disable the preselection, I have no clue. My only guess is that the pre-selection might not look right/expected in case the options are displayed horizontally...

**Comment by icculus** [comment]
Okay, sounds good to me.
