### ISSUE TITLE
2.0.18+ Exception thrown in Windows.Gaming.Input.dll during SDL_Quit() (Windows 10; Visual Studio 2019).

### ISSUE THREAD

**Issue by LucidSigma** [libsdl-org/SDL#5270]
This appears to be similar to [this issue](https://github.com/libsdl-org/SDL/issues/4488).  

When `SDL_Quit()` is called with a game controller connected, `Windows.Gaming.Input.dll` will throw an exception if the application is open for about thirty seconds. This started happening in my application after upgrading from 2.0.16 to 2.0.18. It still occurs in 2.0.20.  

Other information:
* Windows 10.
* Visual Studio 2019.
* 64-bit application (haven't tested if it happens in 32-bit).
* Occurs in both Debug and Release mode.
* I am using a PS4 controller.
* Does not occur if there aren't any game controllers connected to the PC.
* This only happens if the application is open for about 30+ seconds.
* The exception occurs during `WIN_CoUninitialize` in `SDL_windows.c`.
* I am closing all of the game controllers before calling `SDL_Quit()`.
* I am loading the game controller database from [here](https://github.com/gabomdq/SDL_GameControllerDB) during application startup (not sure if this is actually relevant to the issue).
* It will consistently occur every time I run the application for more than thirty seconds with a controller plugged in.

Please let me know if there is anything else I can provide.  

Call stack during exception:  
![Call stack.](https://user-images.githubusercontent.com/39696157/151514154-a85e7450-17f7-4064-a306-08689ff0254f.png)

**Comment by walbourn** [comment]
COM initialization is ref-counted, so you need to balance all calls to CoUninitialize with CoInitialize.

That said, for `Windows.Gaming.Input` you actually need to initialize the Windows Runtime (which itself initializes COM). For UWP with C++/CX, this is done by the C/C++ Runtime, but that is not true of Win32 desktop or UWP with C++/WinRT.

```
#include <roapi.h>

::Windows::Foundation::Initialize(RO_INIT_MULTITHREADED);
```

```
::Windows::Foundation::Uninitialize();
```

Make sure SDL_Init and SDL_Quit use these *instead of or in addition to* calling CoInitializeEx/CoUnitialize whenever building with WGI support.
