### ISSUE TITLE
Rumble doesn't work with XBox 360 controller on Windows

### ISSUE THREAD

**Issue by DaMarkov** [libsdl-org/SDL#5351]
```
SDL_Init(SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK | SDL_INIT_HAPTIC);
auto gGameController = SDL_JoystickOpen(0);			
SDL_JoystickRumble(gGameController, 0xFFFF, 0xFFFF, 1000);
```

Doesn't work. Same code works under Linux with a different controller.
For some reason `ctx->xinput_correlated` get set to `SDL_FALSE` and hence `SDL_JoystickRumble` doesn't even try to make it rumble.

Microsoft's API works without any problems with this controller (`XInputSetState()`).

**Comment by slouken** [comment]
Have you pressed a button on the controller? That's how it gets correlated...

**Comment by DaMarkov** [comment]
I tested that, still doesn't work. I am calling `SDL_JoystickRumble` every frame.
Every button on the controller works fine with SDL, but still no rumble.

**Comment by slouken** [comment]
In that case, you'll need to find out why xinput_correlated isn't getting set to true.

**Comment by AntTheAlchemist** [comment]
I can confirm this isn't working. Very strange.

This does work though (which might hint as to what's going wrong):

```
auto gGameController = SDL_GameControllerOpen(0);
SDL_JoystickRumble(SDL_GameControllerGetJoystick(gGameController), 0xFFFF, 0xFFFF, 1000);
```

**Comment by slouken** [comment]
In normal application usage, you wouldn't have a constant continuous rumble, so eventually the controller would be correlated and new rumble after that would take effect. I've made a change so that even if you don't change the values, once correlation happens the rumble will begin on the next call to SDL_JoystickRumble().

Please let me know if this isn't what you're seeing.
