### ISSUE TITLE
Wayland: Fractional scaling issues

### ISSUE THREAD

**Issue by Kontrabant** [libsdl-org/SDL#5437]
Wayland seems to be in decent shape overall, but there are a couple of sticking points when using a desktop with fractional scaling:

1. The scaled desktop size, such as reported by SDL_GetDesktopDisplayMode(), is not reported correctly.  SDL uses wl-output to get the native resolution and divides it by the integer scale factor, which works when dealing with pure integer scaling, but fails when the desktop is scaled by a fraction.  For example, a 4k display with 150% scaling has a virtual desktop size of 2560x1440, however SDL reports it as 1920x1080 since it's 3840x2160 / 2.  The solution is to use the xdg-output protocol, if available, to retrieve the desktop dimensions, as it reports the transformed dimensions instead of the raw values.

2. Backing surfaces when using the DPI aware flag and fractional scaling are scaled up by the scale factor reported by wl-output, which means they are considerably larger than they need to be.  This results in significant overdraw (a 4k monitor running fullscreen at 150% scaling will have a 5k backbuffer), an image that needs to be downscaled and may inhibit direct scanout.  The workaround for this seems to be using the wp_viewporter extension, with the backbuffer and source region set to the display's native resolution and the destination set to the size of the virtual desktop.  This should result in an output image that is 1:1 unscaled and makes it possible for the compositor to potentially use a direct scanout path (see [GNOME Mutter #2126](https://gitlab.gnome.org/GNOME/mutter/-/issues/2126) and [XWayland #861](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/861)).

**Comment by Kontrabant** [comment]
#5438 is the pull request for fairly trivial xdg-output patch.

I have a rough version of the second part involving wp_viewporter working, but it's more involved and will take some additional time to make sure that nothing is broken and things behave as they should.

**Comment by flibitijibibo** [comment]
Cleared the Wayland plate as much as I could... if a WIP for part 2 drops in over the weekend I think I'll be able to give it enough testing to squish it into the release candidate.

**Comment by Kontrabant** [comment]
It's in progress, but time-wise, this weekend probably isn't realistic.  Plus, as this is a feature/enhancement as opposed to a bugfix, and it requires re-plumbing some existing, working, code in the window logic to make everything work, I'd really prefer it to have a longer testing period.

**Comment by flibitijibibo** [comment]
Sounds good, will leave this issue as-is then!

**Comment by Kontrabant** [comment]
I did manage to get part 2 knocked out sooner than expected:  #5450

**Comment by flibitijibibo** [comment]
I've run into something really odd while working on this... on GNOME it seems like xdg_output does not actually scale for logical size. In Super Hexagon the viewport is twice as large as it should be; the fix was to scale these two xdg_output dimensions as well:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c#L490-L491

Based on the order of events I'm seeing, it seems like we should check the wl_output current mode (which it gives us), then compare against the xdg_output logical size for consistency with scale_factor.

**Comment by flibitijibibo** [comment]
Had to wedge in something for GNOME, Plasma was fine from what I could tell:

https://github.com/libsdl-org/SDL/commit/40417b188a5dbfdd04297204caa77a3dabe8d7fd

Because we're using scale_factor inside the xdg_output callback this likely broke fractional scaling - would be great to know if I'm just missing something obvious here...

**Comment by flibitijibibo** [comment]
Second half resolved by #5450
