### ISSUE TITLE
PSP: Audio resampling is very slow.

### ISSUE THREAD

**Issue by isage** [libsdl-org/SDL#5493]
Continuing from https://github.com/libsdl-org/SDL/pull/5105

Resampling small (<1sec, 10kb) file from S16 44100 to S16 44100*5 takes around 16 seconds (15877 sdl ticks). Same conversion with sdl1 takes zero ticks.

Core of the problem, i think, lies in SDL2 converting samples to FLOAT32 for resampling, and then converting back to target format after.

I've attached simple testcase for both sdl1 and sdl2
[cvttest.zip](https://github.com/libsdl-org/SDL/files/8425007/cvttest.zip)

**Comment by isage** [comment]
Tried porting libsamplerate and compiling SDL2 with support for it. Conversion time still same.

**Comment by isage** [comment]
Digging deeper: conversion to float isn't a culprit. Most time is spent in kaiser_and_sinc, namely in calls to bessel

**Comment by icculus** [comment]
I'll take a look at this but probably not before 2.0.22 ships, in case anyone else beats me to it.

**Comment by ccawley2011** [comment]
> Digging deeper: conversion to float isn't a culprit. Most time is spent in kaiser_and_sinc, namely in calls to bessel

If I'm understanding the code correctly, `kaiser_and_sinc` is only called once, and the table generated by it is reused until `SDL_AudioQuit` is called. It also looks like it would always generate the same results for `ResamplerFilter` and `ResamplerFilterDifference`, so one approach could be to use pre-calculated tables instead of calculating them at runtime, which could potentially improve performance at the cost of adding an extra 20KB to the executable size.

> Same conversion with sdl1 takes zero ticks.

Is SDL 1.2 actually converting anything here? It only seems to resample audio when `hi_rate = lo_rate*2^x`, and the [code for handling other sample rates](https://github.com/libsdl-org/SDL-1.2/blob/main/src/audio/SDL_audiocvt.c#L1478) is disabled.

**Comment by isage** [comment]
> If I'm understanding the code correctly, `kaiser_and_sinc` is only called once, and the table generated by it is reused until `SDL_AudioQuit` is called. It also looks like it would always generate the same results for `ResamplerFilter` and `ResamplerFilterDifference`, so one approach could be to use pre-calculated tables instead of calculating them at runtime, which could potentially improve performance at the cost of adding an extra 20KB to the executable size.

Actually no, it's re-populated every time conversion is requested
> 
> > Same conversion with sdl1 takes zero ticks.
> 
> Is SDL 1.2 actually converting anything here? It only seems to resample audio when `hi_rate = lo_rate*2^x`, and the [code for handling other sample rates](https://github.com/libsdl-org/SDL-1.2/blob/main/src/audio/SDL_audiocvt.c#L1478) is disabled.

It's not disabled. It converts to closest pot value. What's disabled is conversation to precise samplerate

**Comment by isage** [comment]
Main problem (and difference with sdl1 that uses fixed-point math in resampler) is usage of doubles. mips just can't handle that in hardware.

**Comment by uyjulian** [comment]
I wonder if it's fine to use SDL 1.2's resampler in SDL 2 as is, enabled for specific platforms.

**Comment by slouken** [comment]
> I wonder if it's fine to use SDL 1.2's resampler in SDL 2 as is, enabled for specific platforms.

In general, if you want good quality, the answer is no.

Here's an interesting thread that might be relevant:
https://linux-audio-dev.linuxaudio.narkive.com/4iRMuZ97/looking-for-fast-integer-resampling-code

**Comment by icculus** [comment]
> I wonder if it's fine to use SDL 1.2's resampler in SDL 2 as is, enabled for specific platforms.

It's quality is terrible and it will corrupt memory if not converting between powers of two sample rates, so 100% no.

**Comment by icculus** [comment]
> Actually no, it's re-populated every time conversion is requested

I don't think that's correct, fwiw, but even if it's one time, adding 16 seconds to ones startup time (or worse: when you accidentally play the wrong sound mid-game) is completely unacceptable.

Try the pull request and see if it fixes your problem. If it does, and if we get some consensus that this is a correct thing to do, we'll either merge it for 2.0.22 or right after it ships.

**Comment by isage** [comment]
That seems to have knocked down resampling time from 15 seconds to 1.5, which is awesome, but still pretty slow.

**Comment by isage** [comment]
> I don't think that's correct, fwiw
Strange, because when i did "printf debugging" it definitely called kaiser_and_sinc multiple times.

**Comment by icculus** [comment]
> Strange, because when i did "printf debugging" it definitely called kaiser_and_sinc multiple times.

I could be wrong, idk.

Anyhow, if we merge the PR, that point is moot, but let's see what else we can do in here to speed this up.

**Comment by icculus** [comment]
I guess the question is: is all floating point bad, or is the doubles that are specifically the problem here?

If it's the doubles, can you just replace all the doubles with floats in SDL_ResampleAudio and see if it helps?

Using float still gives acceptable output here, so let's see if that helps on the PSP.

If that _doesn't_ help, we're probably either going to have to put a lousy integer linear resampler in here for the PSP or just add a note to the README that you need to have your audio data in the right format for this platform.

**Comment by isage** [comment]
Note won't really help. Well, atleast in my case, because engine allows playing sounds from scripts with arbitrary samplerate. Yeah, I'll test with floats.

**Comment by fjtrujy** [comment]
> I guess the question is: is all floating point bad, or is it the doubles that are specifically the problem here?
> 
> 
> 
> If it's the doubles, can you just replace all the doubles with floats in SDL_ResampleAudio and see if it helps?
> 
> 
> 
> Using float still gives acceptable output here, so let's see if that helps on the PSP.
> 
> 
> 
> If that _doesn't_ help, we're probably either going to have to put a lousy integer linear resampler in here for the PSP or just add a note to the README that you need to have your audio data in the right format for this platform.
> 
> 

PSP has 32 bits float, however if we try to do doubles with 64 bits, they are being calculated using "soft floats" operations which are slower....

**Comment by isage** [comment]
Yup, converting to float with dirty `#define double float` hack helped. That got the conversion time in testcase down to 34 ticks (and in my game from several minutes to less than a minute)

**Comment by fjtrujy** [comment]
> Yup, converting to float with dirty `#define double float` hack helped. That got the conversion time in testcase down to 34 ticks (and in my game from several minutes to less than a minute)

This is good know!

**Comment by icculus** [comment]
Updated my PR with more optimizations, including the "use floats instead of doubles" change. Even on desktop, I'm probably close to twice as fast with these patches, but it's yet to be seen what sort of audio artifacts we're risking by dropping precision from double to float...but the speed boost is so attractive, I think it's worth merging it after 2.0.22 ships and seeing what happens.

I'm not sure if there's much low-hanging fruit left after this for the PSP, beyond just dropping in a low-quality, integer-only linear resampler.

**Comment by icculus** [comment]
I renamed the branch which caused GitHub chaos. The PR you want to test is #5508 now, sorry about that!

**Comment by ccawley2011** [comment]
I did some testing on RISC OS with the test program that isage posted, and the optimizations provide some noticable speed boosts, especially in soft-float builds:

| System | Build type | Old time | New time |
|-|-|-|-|
| Raspberry Pi 1 | ARMv3 | 2410 ticks | 140 ticks |
| Raspberry Pi 1 | VFP | 320 ticks | 80 ticks |
| Pinebook | ARMv3 | 1340 ticks |  90 ticks |
| Pinebook | VFP | 140 ticks | 30 ticks |
 
I don't have any RiscPC stats yet, but this looks promising.

**Comment by fjtrujy** [comment]
Really good investigation! Thanks guys!

**Comment by icculus** [comment]
So are we good on PSP at this point? We'll leave this open until we merge the PR, which I think we will after 2.0.22 ships, but I'm wondering if there's more work needed still.

**Comment by isage** [comment]
I'll test latest PR tomorrow (instead of my local hacks), but yeah, looks good

**Comment by isage** [comment]
With #5508 testcase got down to 31 tick. (and my game loading time to 15secs instead of 15 minutes, although i optimized some things on my side too).

**Comment by ccawley2011** [comment]
I've updated my earlier post with RiscPC and Raspberry Pi 3 test results.

**Comment by icculus** [comment]
Okay, the resampler optimizations are merged! I'm closing this bug now. If there's more work to be done, please say so and we'll reopen!
