### ISSUE TITLE
audio issue with wasapi and Intel Display Audio devices

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#5571]
This was reported to me by @j4reporting for quakespasm at
https://github.com/sezero/quakespasm/issues/23 - any insights?

Quoting as is:

---

Audio is not initialized on WIndows if 'Intel display audio'  is the only available audio device AND a modeset is issued.
This is a known issue with Intel Drivers (see [Intel document](https://www.intel.com/content/www/us/en/support/articles/000035049/intel-nuc/intel-nuc-kits.html) ).  

```
Sound Initlalisation
Coundn't opem SDL audio:  WASAPI can't find requested audio endpoint: Element not found.
```

I could fix this by simply retrying again 2 seconds later. 

Unfortunately audio device is also lost later in the game when switching to another video resolution or  switching from vid_fullscreen 0 <-> 1.
What is needed is some kind of   snd_restart  command  and ideally a check if the audio device is available  and if not,  an automatic restart of the audio device.

the same issue can be observed with [vkQuake](https://github.com/Novum/vkQuake), [Ironwail](https://github.com/andrei-drexler/ironwail) and probably with other forks.

Why had  that worked for me all this years?  I had a headphone connected to the system (realtek HD audio) and Quakespasm would find the headphone, initialize audio  and when Intel Display Audio re-apperared,  SDL/ WASAPI  would switch back to the default audio device!

---

**Comment by icculus** [comment]
This is wild! So for up to 8 seconds after changing the display resolution, the audio device goes missing...? Wow.

This feels like something we should look for by vendor id and add some special case code for.

**Comment by sezero** [comment]
If I'm reading the linked docs correctly, Intel says they are innocent and blame apps. Never heard this kind of an issue though, until today - so I'm not 100% sure about who to blame - quakespasm or intel drivers or SDL.

**Comment by eloj** [comment]
The suggestion[0] that you should retry for more than 8 seconds after a modeset just seems baffling. How is that an OK user experience?

**Comment by icculus** [comment]
Yeah, this is 100% Intel's fault but we can probably handle this as a special case. I'll look into it.

**Comment by icculus** [comment]
I'm just noting, having messed around with HDMI audio more recently, that it's extremely common for it to take a few seconds to get audio going when switching to such an audio device; I've seen this on Windows, Linux and macOS...the difference is that the OS level device doesn't vanish or fail, it just doesn't make any sound until it's ready, and I think that's the crux of the issue here.

For now, I'm going to pass on trying to workaround this in SDL, as it seems to be an older hardware issue, and we're continuing to push towards people using fullscreen_desktop instead of changing the resolution, which should avoid this bug.

I'm not closing this as WONTFIX yet, in case it's more widespread than I assume, but I'm bumping from the milestone.

**Comment by icculus** [comment]
(Following up from #7044, we should be good here, too, but please let me know if this issue still persists!)
