### ISSUE TITLE
SDL_SetWindowFullscreen(SDL_WINDOW_FULLSCREEN_DESKTOP) does not cause a SDL_WINDOWEVENT_RESIZED on KDE

### ISSUE THREAD

**Issue by tau-dev** [libsdl-org/SDL#5593]
After upgrading SDL2 from 2.0.20 to 2.0.22 on KDE Plasma on Arch Linux, toggling fullscreen mode (specifically, in the [lite](https://github.com/rxi/lite) editor) does not trigger a SDL_WINDOWEVENT_RESIZED, so the window only draws to a part of the screen.

**Comment by tau-dev** [comment]
Consulting [the wiki](https://wiki.libsdl.org/SDL_WindowEventID), it seems lite should have been using SDL_WINDOWEVENT_SIZE_CHANGED all along. Sorry!

**Comment by tau-dev** [comment]
... except SDL_WINDOWEVENT_SIZE_CHANGED, too, is only generated on leaving fullscreen mode.

**Comment by sulix** [comment]
This appears to be because of [x11: when waiting on fullscreen changes, not window position _and_ size. ](https://github.com/libsdl-org/SDL/commit/8bae343f252128147d97912c89fa2b40380158e6) — we now set the window size directly within the X11 SDL_SetWindowFullscreen() implementation, which means that the resize event [is filtered out](https://github.com/libsdl-org/SDL/blob/5394238cdc93669dd5d7696f8d4460a0b85289da/src/events/SDL_windowevents.c#L120).

Note though, that there is an ``SDL_WINDOWEVENT_SIZE_CHANGED`` event, but the lite editor still ends up squished into a corner. That's more likely an issue with SDL_GetWindowSurface() on wayland, though.

**Comment by flibitijibibo** [comment]
Just ran into this as well, Super Hexagon is a good test case.

**Comment by jgmdev** [comment]
Confirming this issue also reproducible on the lite fork [lite-xl](https://github.com/lite-xl/lite-xl) by pressing f11 to enter fullscreen and not just a kde issue since I'm using the wayfire window manager which uses wlroots.

Tested on sdl 2.0.22 and reproducible on both SDL_VIDEODRIVER wayfire and x11.

**Comment by slouken** [comment]
@icculus, can you look at this? It definitely seems like a 2.0.22 regression.

**Comment by icculus** [comment]
Yeah, I'm checking it.

**Comment by stsp** [comment]
Same problem after recent fedora
update. It is not a big deal to "fix" in
an app if the change is intentional
and won't be reverted in the future.

**Comment by stsp** [comment]
As already pointed above, its
caused by 8bae343f.
https://github.com/libsdl-org/SDL/commit/8bae343f252128147d97912c89fa2b40380158e6#diff-4d617e5c2011238b8ec8564c68b8a4bf491d9500c1cfc2d2660ceaa39d56c4f7R1400-R1401

After that change, the check
in SDL_SendWindowEvent():120
```
        if (data1 == window->w && data2 == window->h) {
            return 0;
        }
```
returns 0, as if the window was
already resized. And SDL_OnWindowResized(window)
is never called.

I was wrong saying the work-around
on an app side is possible. It isn't, the
window is in an inconsistent state.

**Comment by slouken** [comment]
Oh, good point. @icculus, can you check this? What was the purpose of directly setting window w/h there?

**Comment by stsp** [comment]
> Oh, good point.

Thanks but I only verified
and repeated what was already
said in the beginning of this thread. :)
Just a note to not take other's credits.

**Comment by cgutman** [comment]
Is sending `SDL_WINDOWEVENT_RESIZED` part of the API contract? I would expect only `SDL_WINDOWEVENT_SIZE_CHANGED` for a full-screen transition since it's initiated by the application rather than externally.

If `SDL_WINDOWEVENT_SIZE_CHANGED` alone is fine, it seems like we could just unconditionally call `SDL_OnWindowResized()` there.

**Comment by stsp** [comment]
To me that sounds like a good
simplification, especially because
of the very nasty nature of
SDL_SendWindowEvent().
Instead of just sending a specified
event, it calls other functions (like
SDL_OnWindowResized()), which
themselves call SDL_SendWindowEvent()
again (recursively) to send other events...
Calling such functions directly may
be a good step at simplifying such design.

**Comment by icculus** [comment]
> Oh, good point. @icculus, can you check this? What was the purpose of directly setting window w/h there?

I don't have the bug number handy, but the problem was that calling GetWindowSize right after another SDL call would return wrong values because the Configure event hadn't arrived yet due to lack of PumpEvents, but since we had already directly queried the X server while waiting for the window to map or something.

The solution appears to be a) force a PumpEvents after this wait, so the window state gets updated _and_ the event arrives or b) generate the event right there.

**Comment by slouken** [comment]
Generating the events right there should be fine if the window data is in a consistent state. On Windows, the Win32 API window calls dispatch into the event loop under the hood and do the same thing. Typically we use events instead of changing window state directly, so that SDL can do other work as needed on various platforms.

**Comment by slouken** [comment]
@icculus, can we prioritize this? I can confirm that Super Hexagon is completely broken right now, and probably a bunch of other games are as well.

**Comment by icculus** [comment]
Working on this.

**Comment by stsp** [comment]
Works for me, thanks.

**Comment by slouken** [comment]
I confirmed Super Hexagon is working again as well. Thanks!

**Comment by icculus** [comment]
My test case was the lite editor, and ddnet (which I couldn't reliably trigger but definitely can't now), so I think we covered it.
