### ISSUE TITLE
Use-after-free in METAL_DestroyRenderer?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5630]
This is a possibly dumb question, but I'm still feeling around in the dark on Objective-C memory management, so it might be totally fine.

This is, I think, where this METAL_RenderData's retain count drops to zero:

https://github.com/libsdl-org/SDL/blob/8cd908e0b987d3de26052bb16d9065541a30d23d/src/render/metal/SDL_render_metal.m#L1571-L1588

...but we access `data` right afterwards.

@slime73, do we need to move the `CFBridgingRelease` call to the end of this block?

**Comment by slime73** [comment]
With Objective-C's ARC, `CFBridgingRelease` decrements the reference count on the object and also adds a new reference via the objc value it returns, which in this case will be decremented when the `data` variable goes out of scope.

So it should work fine when ARC is used, but... I don't remember what happens when ARC is off. I think SDL on macOS still doesn't use ARC yet, right? IMO it really should move to ARC instead of manual objective-c memory management.

**Comment by slime73** [comment]
I think in non-ARC, if the value returned by `CFBridgingRelease` is marked as autoreleased it should work out fine, but if it's not then there's a memory leak there. I'm not sure which of those two options its implementation does.

**Comment by icculus** [comment]
> IMO it really should move to ARC instead of manual objective-c memory management.

I agree, there's a bunch of ugly `#ifdef`s and--more importantly--a lot of brain powered wasted on things like this.

Does anyone know why haven't we required ARC? Is it to maintain compatibility with older build tools or something?

**Comment by slouken** [comment]
> Does anyone know why haven't we required ARC? Is it to maintain compatibility with older build tools or something?

Yes, that's why.

I'm not seeing the use after free? Where do we reference data after the bridging release?

**Comment by icculus** [comment]
>  Where do we reference data after the bridging release?

The line right after it: 

```c
 if (data.mtlcmdencoder != nil) { 
```

(Objective-C does magic with pointers and uses `.` instead of `->` when it does.)

**Comment by icculus** [comment]
As for older build tools: is it time to dump them?  Like, if it's for PowerPC compat or something...? I don't know the details.

**Comment by slime73** [comment]
> Does anyone know why haven't we required ARC? Is it to maintain compatibility with older build tools or something?

I believe ARC on macOS requires 64 bit macOS 10.7+ at runtime. That's been the minimum runtime requirement of my own software that uses SDL for almost a decade now, but I think official SDL releases have had their minimum runtime target set to macOS 10.6 since 2013 or so.

https://developer.apple.com/library/archive/releasenotes/ObjectiveC/ObjCAvailabilityIndex/
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtVersionsPlatforms.html#//apple_ref/doc/uid/TP40008048-CH106-SW1

**Comment by slouken** [comment]
10.6 was for 32-bit x86 macOS systems, but I think at this point it's reasonable to drop support for those. @sezero, what's your opinion?

**Comment by sezero** [comment]
I'm one of the dinosaurs facing extinction with an i686 Macbook + 10.6 OS.
But I don't care much.

As for metal support: it strictly requires 64 bit OS, and what, 10.11
and newer?? So, is weak linking not possible to continue to support 10.6?
Or, is weak linking with ARC is not possible if minimum target is 10.6?
In any case, I won't be standing in the way.

**Comment by slime73** [comment]
Now that you mention it, I remember experimenting with enabling ARC just for the Metal-related files in SDL a while ago... but I didn't figure out how to do it in a manner that still let the rest of the project build for 10.6/x86, via Xcode. I wasn't doing a super deep-dive investigation at the time though, so maybe there is a way, but overall I'd still prefer moving to ARC for everything instead.

I'll see about throwing together a pull request for ARC soon.
