### ISSUE TITLE
Get name associated with SDL_AudioDeviceID

### ISSUE THREAD

**Issue by lucmans** [libsdl-org/SDL#5658]
When opening an audio device using SDL_OpenAudioDevice(), SDL automatically selects the "most reasonable" choice if NULL is passed as the first parameter.
Currently, there is no way to get the name associated with the opened audio device.

I would suggest a function similar to SDL_GetAudioDeviceName(), only instead of taking an index, it would take a SDL_AudioDeviceID (Uint32).
Alternatively, passing index=-1 (or a macro for the value) to SDL_GetAudioDeviceName() could return the name of the "most reasonable" audio device.

This is useful in case you want to choose the most reasonable audio device, but still want to give users the option to change it.
Now, there is no way to visually show what the default choice of SDL was, and by extension, what the current audio devices is.

**Comment by icculus** [comment]
Gonna mark this early-in-milestone: for the most part, this is easy. The only part that takes effort is what to return when a NULL device is opened, and I'll need to go through all the drivers to make sure these report something reasonable.

For example, on some platforms, NULL means "the first thing in the list of names we already enumerated", on CoreAudio, NULL means "the system default output, even if it changes to a completely different piece of hardware while your app is running" and ALSA means the device named "default" but I have to fill in the code to find out that means "SoundBlaster Pro" ... others might have other quirks.

Also worth noting that since NULL is a magic value here, there is _never_ a way to say "this is the audio device that NULL _will_ open" because there are reasonable scenarios where _it will not be in the list of devices we report_ and we can't know what's going to happen until we actually open it. I would recommend if you want to show it in a UI where the user can pick a device from a list, you just call it "[system default]" or "[you decide for me]" or something.

Once it's opened, I can usually produce a reasonable name (that may or may not be in the list of devices we reported).

**Comment by icculus** [comment]
> ALSA means the device named "default" but I have to fill in the code to find out that means "SoundBlaster Pro"

Comically, on Ubuntu, asking ALSA for the proper name of the default device reports "PulseAudio".  🤪

**Comment by icculus** [comment]
Actually, having gone through all the audio backends now, almost all of these are going to return some variation on "System default playback device" or something similarly not useful. Especially in the more modern APIs--which you're likely to be using--the default will move to a new device if necessary (user unplugs the current default, user plugs in headphones, user chooses a different device in System Preferences, etc).

I'm inclined to close this as WONTFIX. The non-default info is already available to the app, and the default info often isn't useful.

**Comment by lucmans** [comment]
Thank you for looking into this so quickly.
> Actually, having gone through all the audio backends now, almost all of these are going to return some variation on "System default playback device" or something similarly not useful
It would be nice to know the systems default is being selected compared to the first entry in the list. It's some extra information we do not have available right now. I would say that information is pretty useful.

> Also worth noting that since NULL is a magic value here, there is never a way to say "this is the audio device that NULL will open"
> Once it's opened, I can usually produce a reasonable name (that may or may not be in the list of devices we reported).
I hoped that was the case. That is why I proposed getting the device name by specifying the SDL_AudioDeviceID given by SDL_OpenAudioDevice(). This way, it is possible to report to the user what audio device is currently being used. As far as I saw, the SDL_AudioDeviceID is the only device specific handle exposed to the program/SDL library users.

> Especially in the more modern APIs--which you're likely to be using--the default will move to a new device if necessary (user unplugs the current default, user plugs in headphones, user chooses a different device in System Preferences, etc).
Doesn't this generate a SDL_AudioDeviceEvent? Because in that case, it would be especially useful to be able to retrieve the name of the new audio device.

Lastly, maybe the wiki page on SDL_OpenAudioDevice() should reflect your findings on what happens when you pass NULL instead of a name. "The most reasonable default" is a bit vague and not even true, as no high level reasoning is performed to estimate the best choice. This is especially useful if a function like SDL_GetAudioDeviceNameByID() is not going to be added.
