### ISSUE TITLE
Dynamic API vs Watcom (and/or calling conventions in general)

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5669]
> Something with dynapi... If I do the following to disable dynapi (the second part
in order to workaround calling convention differences), then `showimage logo.svg`
works:
>
> [... see diff in original bug report...]
>
> Can anyone see what's wrong with dynapi being enabled for os/2?

_Originally posted by @sezero in https://github.com/libsdl-org/SDL/issues/5667#issuecomment-1128111986_

**Comment by icculus** [comment]
(Sticking this in 2.0.24 so it doesn't get lost, but no promises if the workload gets too large.)

**Comment by ccawley2011** [comment]
I've noticed that when building for Windows with OpenWatcom, SDL doesn't link at all unless dynapi is disabled or it's built with `-ecc` to force it to use `__cdecl` calling conventions everywhere, as otherwise it can't resolve any of the `_REAL` functions. I wonder why OS/2 doesn't have this problem.

**Comment by sezero** [comment]
> I've noticed that when building for Windows with OpenWatcom

So you _can_ build SDL2 for windows using watcom? Send me your makefile so
I can test and see what is missing.

**Comment by ccawley2011** [comment]
It's a bit of a mess so far, but everything I've got so far is in this branch: https://github.com/ccawley2011/SDL/tree/watcom-win32. I'll try and split the changes up into something more manageable.

Notes:
- open-watcom/open-watcom-v2#868 is needed for this to build. Some of the D3D9 changes are also things that should be fixed in OpenWatcom's headers instead of here.
- `dxgi.h`, `windows.gaming.input.h`, `d3d11.h`, `roapi.h`, `mmdeviceapi.h`, `audioclient.h`, `tpcshrd.h` and `sensorsapi.h` are unavailable, so any features that depend on these headers have been disabled.
- The MSVC-style assembler in `src/cpuinfo/SDL_cpuinfo.c` causes a crash on Windows, but it presumably doesn't affect OS/2 for some reason.
- `SDL_qsort()` and `SDL_bsearch()` don't specify the calling conventions used by the callbacks, and fixing it may or may not cause an ABI breakage on OS/2 (Windows shouldn't be affected since IIRC both MSVC and MinGW use `__cdecl` by default, and other platforms should always use the default calling conventions).
- `SDL_DYNAMIC_API` is disabled for now.
- SDL2main isn't built yet.
- It's possible to use the standard SDL2.lib development library for MSVC (but not SDL2main.lib) from the official website, however the SDLCALL fixes are likely to still be necessary for `SDL_qsort()` and `SDL_bsearch()` to work correctly.

**Comment by sezero** [comment]
>  this branch: https://github.com/ccawley2011/SDL/tree/watcom-win32.

Taking it now, will try building 

>  The MSVC-style assembler in `src/cpuinfo/SDL_cpuinfo.c` causes a crash on Windows, but it presumably doesn't affect OS/2 for some reason.

Hasn't cause issues so far, but it would be better if we had a watcom-style aux pragma

>   `SDL_qsort()` and `SDL_bsearch()` don't specify the calling conventions used by the callbacks, and fixing it may or may not cause an ABI breakage on OS/2 (Windows shouldn't be affected since IIRC both MSVC and MinGW use `__cdecl` by default, and other platforms should always use the default calling conventions).

Fixing that would possibly cause breakage. The difference we have is
`__cdecl` (or `_System` in os/2 case) vs watcom's default `__watcall`

A note about exports:
For correctly exporting symbols, see either this:
https://github.com/libsdl-org/SDL-1.2/blob/main/Watcom-Win32.zip
.. or these:
https://github.com/libsdl-org/sdl12-compat/blob/main/src/Makefile.w32
https://github.com/libsdl-org/sdl12-compat/blob/main/src/SDL12.exports
In essence, you define DECLSPEC as an empty macro on the cmdline and
then use an exports file to describe which actual symbol is exported
as what. Otherwise, well running `gendef` will show you what's wrong, i.e.
all of the exported symbols are prefixed with an underscore.

**Comment by sezero** [comment]
> > SDL_qsort() and SDL_bsearch() don't specify the calling conventions used by the callbacks, and fixing it may or may not cause an ABI breakage on OS/2 (Windows shouldn't be affected since IIRC both MSVC and MinGW use __cdecl by default, and other platforms should always use the default calling conventions).
> 
> We should just fix that, if it's only going to affect (Watcom) Windows and OS/2 builds.

It's a mess: default calling convention is `__cdecl` for windows, but watcom's crt
doesn't define a calling convention for qsort's `compar`, meaning that it takes watcom's
default `__watcall` calling convention.

I won't touch this, if you do then be my guest.

**Comment by ccawley2011** [comment]
> It's a mess: default calling convention is `__cdecl` for windows, but watcom's crt doesn't define a calling convention for qsort's `compar`, meaning that it takes watcom's default `__watcall` calling convention.
> 
> I won't touch this, if you do then be my guest.

In PR #5683, I simply disabled the system versions of `qsort()` and `bsearch()` on OS/2, which should avoid that issue.

How are the `_System` calling conventions defined? If the issue with the Dynamic API on OS/2 is the same issue I had on Windows, it's possible that `_System` and `__watcall` are similar enough that the ABI might remain the same after PR #5683 is merged, considering that the non-math functions seem to work anyway.

**Comment by sezero** [comment]
> How are the `_System` calling conventions defined?

See the `32-bit topics` -> `Auxiliary pragmas` in cguide.pdf of open watcom:
```
#pragma aux __syscall "*" \
parm caller [] \
value struct struct caller [] \
modify [eax ecx edx]

Notes:
1. Symbols names are not modified, that is, they are not adorned with leading
   or trailing underscores.
2. Arguments are pushed on the stack from right to left. That is, the last
   argument is pushed first. The calling routine will remove the arguments
   from the stack.
3. When a structure is returned, the caller allocates space on the stack. The
   address of the allocated space will be pushed on the stack immediately
   before the call instruction. Upon returning from the call, register EAX
   will contain address of the space allocated for the return value.
   Floating-point values are returned in 80x87 register ST(0).
4. Registers EAX, ECX and EDX are not saved and restored when a call is made.
```

**Comment by sezero** [comment]
> > The MSVC-style assembler in `src/cpuinfo/SDL_cpuinfo.c` causes a crash on Windows,
> > but it presumably doesn't affect OS/2 for some reason.
> 
> Hasn't cause issues so far, but it would be better if we had a watcom-style aux pragma

This one seems like a open watcom v2 bug: I built sdl12-compat with
ow2 from git (Jan 15 2022 17:48:13), testplatform.exe does seem to crash,
but not if I build sdl12-compat using ow1.9. (Maybe it's fixed in newer
git revisions, don't know.)

**Comment by sezero** [comment]
> This one seems like a open watcom v2 bug

Does seem to be fixed in their 'Last CI build' (original bug possibly
was https://github.com/open-watcom/open-watcom-v2/issues/805)

**Comment by ccawley2011** [comment]
> > How are the `_System` calling conventions defined?
> 
> See the `32-bit topics` -> `Auxiliary pragmas` in cguide.pdf of open watcom:
> 
> ```
> #pragma aux __syscall "*" \
> parm caller [] \
> value struct struct caller [] \
> modify [eax ecx edx]
> 
> Notes:
> 1. Symbols names are not modified, that is, they are not adorned with leading
>    or trailing underscores.
> 2. Arguments are pushed on the stack from right to left. That is, the last
>    argument is pushed first. The calling routine will remove the arguments
>    from the stack.
> 3. When a structure is returned, the caller allocates space on the stack. The
>    address of the allocated space will be pushed on the stack immediately
>    before the call instruction. Upon returning from the call, register EAX
>    will contain address of the space allocated for the return value.
>    Floating-point values are returned in 80x87 register ST(0).
> 4. Registers EAX, ECX and EDX are not saved and restored when a call is made.
> ```



> 

It seems that the only noticeable difference between `__syscall` and `__watcall` (stack calling convention) is related to how the x87 registers are used, which would explain why most functions seem to work fine but the maths functions don't. It also explains why OS/2 is able to link anyway but Windows isn't - `__cdecl` prefixes all symbol names with underscores, but both `__syscall` and `__watcall` leave them as-is.

**Comment by sezero** [comment]
Looks like it. @icculus is onto things in 5667 too: https://github.com/libsdl-org/SDL/issues/5667#issuecomment-1130722509

**Comment by sezero** [comment]
Closing this after https://github.com/libsdl-org/SDL/commit/f0566702c5e4c3522148fca6c65e83fb57326ddb (#5687)
