### ISSUE TITLE
Fix macOS CMake builds after f4fc471

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#5707]
Sure enough, stuffed this at the bottom of CMakeLists.txt and the problem goes away:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2ce31aba8..0a77db641 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -3122,3 +3122,6 @@ endif()
 if(SDL_TEST)
   add_subdirectory(test)
 endif()
+
+set(CMAKE_OBJC_FLAGS "${CMAKE_OBJC_FLAGS} ${CMAKE_C_FLAGS}")
+
```

Not that I'm recommending that, as it feels like a nuclear option.

But also: it might be the correct approach. I don't know.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/5642#issuecomment-1133763981_

**Comment by slouken** [comment]
I did the nuclear option for now. Maybe @madebr has an idea of the recommended approach for this?

**Comment by madebr** [comment]
Ideally, you don't even need to use/modify `CMAKE_C_FLAGS` and use `add_compile_options`, `target_compile_options`, `target_compile_definitions`.
CMake should be smart enough to pass it through to all enabled languages.

Of course, there are (were?) valid cases where you need to modify ´CMAKE_C_FLAGS´, e.g. for MSVC/Watcom to modify the C runtime library where you want to modify the default.
I wrote *were* because more recent versions of CMake has functionality to modify e.g. the MSVC runtime library: [`MSVC_RUNTIME_LIBRARY`](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html).

**Comment by icculus** [comment]
> But I'll reserve some time for combing through the SDL cmake build script :)

Please do! Even just notes like "here's a list of 20 bad mistakes" is useful content, since this thing was written when CMake was pretty new and it was probably a line-for-line conversion of the autoconf script.

For SDL3, we want to write it from scratch.
