### ISSUE TITLE
SDL cmake support for non-CMake builds

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#5713]
We have a number of requests from customers for SDL and SDL related libraries to have CMake support for the binary distributions. This includes autotools builds, Visual Studio DLLs, and Xcode frameworks. It would be great to solve this in a consistent way across libraries and platforms.

What do we need to do this properly? Is there a standard foo.cmake that we drop into the release archives? If so, where is the standard location for these, relative to the headers and shared libraries?

I'd like to solve this across SDL and the related libraries for the next release.

Reference:
https://github.com/libsdl-org/SDL/issues/5373
https://github.com/libsdl-org/SDL/issues/4858
https://github.com/libsdl-org/SDL/issues/3608
https://github.com/libsdl-org/SDL/issues/2947
https://github.com/libsdl-org/SDL_image/issues/182#issuecomment-1135808483
https://github.com/libsdl-org/SDL_ttf/issues/141

**Comment by sezero** [comment]
I don't do cmake much, and much less on windows and mac, so I don't think that I can be of much help here.

**Comment by slouken** [comment]
@madebr, I'm adding you to a bunch of SDL CMake bugs for review. Feel free to close them if they're already resolved, or move them out of the 2.24.0 milestone if that's not appropriate for them.

**Comment by smcv** [comment]
The way this works in Autotools-land is that the development files (same package as the headers, static library and `sdl2.pc`) include a CMake "config package" consisting of `sdl2-config.cmake` and `sdl2-config-version.cmake`, installed into `${libdir}/cmake/SDL2/`. I assume Windows and Mac users have to either unpack all their dependencies into the same prefix, or tell CMake a list of directories to look in. CMake's `find_package(SDL2)` automatically looks for this naming convention.

For example, the Debian package has this: https://packages.debian.org/testing/amd64/libsdl2-dev/filelist

At the moment the version installed by an Autotools build hard-codes an absolute path (`set(prefix "/usr")`), but it could equally well use a relative path starting with `${CMAKE_CURRENT_LIST_DIR}/../..` or similar. The only absolute path in Debian's Autotools build is `prefix` itself, so that's probably a small change for someone who is good at CMake.

I think this would also work equally well if they were named `SDL2Config.cmake` and `SDL2ConfigVersion.cmake` like the CMake build produces - CMake looks for both naming conventions. dbus' Autotools build produces `.../cmake/DBus1/DBus1Config.cmake` and `.../cmake/DBus1/DBus1ConfigVersion.cmake`, and that works fine for `find_package(DBus1)`.

**Comment by smcv** [comment]
https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure is the exact search path for "config packages". Briefly: continue to use `${libdir}/cmake/SDL2` on non-Apple Unix, but use a different location on Windows or Apple.

**Comment by slouken** [comment]
I can help with the Apple side of things as well.

**Comment by madebr** [comment]
> I can help with the Apple side of things as well.

Thanks!

I've downloaded `SDL2-2.0.22.dmg` and opened it with 7zip.
Because 7zip does not completely understand the dmg filetype, I'm left with some questions.
- Are the root items `Headers`, `Resources` and `SDL2` symbolic links to files/folders in `SDL2.framework/Versions/A`?
- Does the dmg only ship the main SDL2, so no SDL2test or SDL2main?
- I think `SDL2.framework/Versions/A/SDL2` is a Mach-O universal binary.
What does it contain? I could find out it supports armv8+amd64. But Is it a dylib? I don't see any extension. How are you supposed to use it (with CMake)?
Can you link against it by adding it to the link arguments? (e.g. passing `SDL2.framework/Versions/A/SDL2` to the linker)

Would the following work?
```cmake
add_executable(main main.c)
target_include_directories(main PRIVATE SDL2.framework/Versions/A/Headers)
target_link_libraries(main PRIVATE SDL2.framework/Versions/A/SDL2)
```

The CMake configuration script of VC will support a shared `SDL2::SDL2`, a static `SDL2;;SDL2main` and static `SDL2::SDL2test`.
Does this mean the apple dmg will only support `SDL2::SDL2`?
Neither of both `SDL2::SDL2-static`?

**Comment by slouken** [comment]
> I've downloaded `SDL2-2.0.22.dmg` and opened it with 7zip. Because 7zip does not completely understand the dmg filetype, I'm left with some questions.
> 
> * Are the root items `Headers`, `Resources` and `SDL2` symbolic links to files/folders in `SDL2.framework/Versions/A`?

Yes.

> * Does the dmg only ship the main SDL2, so no SDL2test or SDL2main?

That's correct.

> * I think `SDL2.framework/Versions/A/SDL2` is a Mach-O universal binary.
>   What does it contain? I could find out it supports armv8+amd64. But Is it a dylib? I don't see any extension. How are you supposed to use it (with CMake)?

Yes, it's a dylib. You add -F <framework path> and you're able to include the headers, and you link against it with -framework SDL2.

Since most people also include headers as `#include "SDL.h"`, we should add the private include path:
```
target_include_directories(main PRIVATE SDL2.framework/Headers)
```
 
> The CMake configuration script of VC will support a shared `SDL2::SDL2`, a static `SDL2;;SDL2main` and static `SDL2::SDL2test`. Does this mean the apple dmg will only support `SDL2::SDL2`? Neither of both `SDL2::SDL2-static`?

That's correct.
