### ISSUE TITLE
RFE: API for managing window decorations?

### ISSUE THREAD

**Issue by stsp** [libsdl-org/SDL#5726]
Hi guys.

You already have `SDL_SetWindowBordered()`
to enable/disable all window decorations at
once. In most cases however, this is too rough.
If you want to disable some window button, and
you disable entire border, then you get unmovable
window as a side effect.

You already use `_MOTIF_WM_HINTS`.
Its more careful use allows you to control
every aspect of a window decorations:
https://github.com/dosemu2/dosemu2/pull/1641/commits/499d99323f29d642155297c83e4ad9bc104502a5#diff-31ac4a849e8c559b71f6591e8bfdb5e84701d62f178c8c202bb453c15abc1fb0R393-R422

Would you like to consider some more
"granular" API than the stray and hardly
useful SDL_SetWindowBordered()`?

**Comment by slouken** [comment]
Sure, we'd need support for Windows, X11, Wayland, and macOS. Feel free to submit a PR.

**Comment by stsp** [comment]
I don't think I can do
anything for these OSes.
All I can do, I can do for
X11. In particular, for those
WMs that do support motif
hints.

But its not the point.
I was hoping to discuss the
API that you may want to
have. Its too early to assign
this to me: the API is not yet
defined.

**Comment by slime73** [comment]
Which buttons do you want to toggle? SDL_SetWindowResizable should already toggle the maximize button I think.

**Comment by stsp** [comment]
I'd like to toggle all 3
buttons but still leave
the border to drag wnd.

**Comment by slime73** [comment]
Ah, so you want the buttons and most decoration to be entirely hidden, but the drag-to-resize functionality (in resizable windows) to still work?

**Comment by stsp** [comment]
Indeed.
This is the problem with
SetWindowBordered():
it removes too much.

**Comment by slime73** [comment]
I think most apps that use borderless but still allow users to move the window will use SDL_SetWindowPosition (combined with SDL_GetGlobalMouseState) while the cursor is within a specific area in the window, to accomplish that.

If that isn't quite what you want (e.g. you want the Window Manager's window title bar to still be visible), I'm curious if there are examples of non-SDL apps on different platforms that do what you want?

**Comment by stsp** [comment]
> I think most apps that use borderless but still allow users to move the window will use
> SDL_SetWindowPosition (combined with SDL_GetGlobalMouseState)

Unless the app uses mouse
itself. :)

> examples of non-SDL apps on different platforms that do what you want?

I don't really know.
I think the question is more
of "is there any way of doing
that on those platforms". If
there is, then there are the
examples for sure, and no
reason why SDL should not
do that. But if on most platforms
this is simply not possible...

**Comment by slime73** [comment]
> I think the question is more of "is there any way of doing that on those platforms".

I was more trying to figure out if different platforms have a certain idiomatic way of presenting roughly the same end result for users – which is pretty dependent on the desired outcome and other specifics.

**Comment by stsp** [comment]
It seems people are finding some undocumented
ways on other platforms:
https://www.codeproject.com/Articles/20379/Disabling-Close-Button-on-Forms
Here he found a way to control close button.

**Comment by ell1e** [comment]
I've thought about this since it's more common now to put custom buttons on title bars, and also some of the libdecoration title bars seem a little lacking (in my opinion).

The main blocker for an app just doing a custom decoration inside the regular canvas area and using a window with no frame seems to be that under Wayland, the window can apparently only be moved in some callback that I'm assuming isn't currently available to SDL2 apps easily. Possibly, the same is true for resizing/maximize/restore.

**Suggestion:** I think one great way of doing that would be to have a maximum flexible decoration API to be able to set "drag rectangles" and to set "resize rectangles" inside the canvas, and when the user clicks inside those then SDL2 handles it to make the window drag or resize accordingly. This also would mean SDL2 doesn't need any more specialized handling like hiding title bar buttons etc., since the policy could be "if you want to do anything special with the title bar, use the drag and resize rectangles to control how your buttons work and then just use a no frame window to handle everything yourself". This would both be the most flexible for apps and possibly the easiest to deal with from SDL2's side.

**Comment by ell1e** [comment]
@Kaktus514 it needs to be inside a specific callback, apparently called `xdg_toplevel_listener`, which probably isn't met by `SDL_SetWindowHitTest`. Second of all, `SDL_SetWindowPosition` will error out which means it just won't let the user do it: https://github.com/libsdl-org/SDL/blob/509f3a42d7e67f85b4684ca487e3c166a269e534/src/video/wayland/SDL_waylandwindow.c#L2556 Third of all, `SDL_SetWindowPosition` appears to do extra logic like flushing event queues which it probably shouldn't do in this specific use case. Taking all of this combined, a specific callback just to handle resize and window movement that actually is called from the right wayland handlers and calls the right wayland functions as instructed without any unwanted event delays might be needed.

**Comment by Kontrabant** [comment]
An interactive move on Wayland is initiated by calling xdg_toplevel_move(), which the hit test API currently does. Resizes work in the same way with xdg_toplevel_resize(), which the hit test API also currently does. These functions take the serial of the input event that started them, so if passed the serial of an event that correlates with a mouse button being pressed, the operation will automatically end when that button is released. The toplevel callbacks only inform clients of configuration changes, such as maximized, fullscreen, or a new size.

The existing hit test API seems to be exactly what you are asking for.

**Comment by ell1e** [comment]
Ah cool, I didn't know `SDL_HitTestResult` was an enum (rather than a hit vs pass-through), the wiki is a bit spare. I checked the code now. You're correct that it seems to be exactly what I asked for, thanks so much for explaining. In that case, I wonder if this issue can be closed, since this effectively seems to offer full custom decoration control?

**Comment by slouken** [comment]
Yep!

**Comment by slouken** [comment]
FYI, the SDL3 documentation is much better:
https://wiki.libsdl.org/SDL3/SDL_HitTestResult
