### ISSUE TITLE
Jittery audio in games using SDL

### ISSUE THREAD

**Issue by TheMagicJesus** [libsdl-org/SDL#5735]
Have experienced jittery audio in games that use SDL. The games are Wargroove and  Super Hexagon. Thought it was an issue with Virtual Audio Cable but it might be Windows 7? no clue.

**Comment by icculus** [comment]
Can you record it so I can hear what "jittery" means in this case? Even just like a voice memo on your phone while Super Hexagon is playing would be helpful.

Thanks!

**Comment by TheMagicJesus** [comment]
https://www.file.io/oLwQ/download/zdpq4tGaI1Q6
Sorry about the external site. Github doesn't like .MKVs.
2022-05-30 14-51-27.mkv shows off what it sounds like in previous versions and in the current version with a launch argument
2022-05-30 14-52-06.mkv shows off what it sounds like in the current version without a launch argument

**Comment by flibitijibibo** [comment]
Linking the SupHex report, just in case https://github.com/TerryCavanagh/super-hexagon-neo-issues/issues/6

DirectSound works around it, so it's some interaction between VAC and WASAPI.

**Comment by icculus** [comment]
I'm going to roll a Win7+VAC install later, but for now:

Launch the Control Panel:

![image](https://user-images.githubusercontent.com/673562/172052223-29029f8e-5eee-4ccf-b56c-c548ac841245.png)

Launch System:

![image](https://user-images.githubusercontent.com/673562/172052272-a83f009d-131e-4896-bfa3-8f2bb76cf0f3.png)

Then Advanced System Settings:

![image](https://user-images.githubusercontent.com/673562/172052325-0d82f685-ec00-4e82-8450-6074bd53f57b.png)

Advanced tab, Environment Variables...

![image](https://user-images.githubusercontent.com/673562/172052370-3ac27c54-58f3-4da8-9a05-dbde3d9991ae.png)

New System Variable:

![image](https://user-images.githubusercontent.com/673562/172052415-81cd3ccb-eefd-4a21-89d1-e6d07fb1bedc.png)

Add SDL_AUDIODRIVER and directsound and click OK

![image](https://user-images.githubusercontent.com/673562/172052441-583964f3-6a85-41b7-9167-7532c2e62427.png)

Click OK to close out of all these windows and *REBOOT* and then SDL will use DirectSound instead of WASAPI for all games. Until we fix this better, this _should_ get you up and going everywhere.

**Comment by TheMagicJesus** [comment]
No luck with the system variable fix. Either a mistake on my part to open this as a SDL issue or something else.
![image](https://user-images.githubusercontent.com/47431830/172054523-92917c38-424c-4faf-930a-fc80a7ef8047.png)

**Comment by flibitijibibo** [comment]
Looks right to me, might just need a reboot.

**Comment by TheMagicJesus** [comment]
reboot occurred but audio issues remained

**Comment by icculus** [comment]
So the Super Hexagon command line that fixed this just forces that variable inside the game, as far as I know. Maybe Steam or whatever strips it out?

Anyhow, I'll know more when I do a Win7 install over here soon.

**Comment by icculus** [comment]
I threw together a Win7 install last night in preparation to look into this issue; just making sure, this is the Virtual Audio Cable we're talking about, right?

https://vac.muzychenko.net/en/

**Comment by flibitijibibo** [comment]
Yep, that's the one.

**Comment by TheMagicJesus** [comment]
I was using the VB Audio Cable from https://shop.vb-audio.com/en/12-win-apps, https://shop.vb-audio.com/en/ and Voicemeeter Potato from the same person.
Unable to continue describing the error now as I have built a new PC and swapped OS

**Comment by icculus** [comment]
(That's why I asked, VB Audio Cable is the first hit on Google for "Virtual Audio Cable")

@TheMagicJesus No worries, I'll try and reproduce the issue here if I can! Enjoy the new PC!  :)

**Comment by icculus** [comment]
Okay, so my results are:

- With Super Hexagon, this segfaults inside the game (not SDL) as soon as the voice tries to say "Super Hexagon!" at the title screen. I don't have symbols, so I don't have more to say here and I don't think this is worth the Super Hexagon developers spending more time on.
- Firefox won't play sound at all, but doesn't crash.
- The original report was jittery audio in some games.

I'm willing to decide this is memory corruption, or whatever...a bug in the virtual audio cable or some quirk of Windows 7, but I don't think it's our bug and I don't think it's worth spending more time on, especially if the original reporter has moved on to a new system build-out and doesn't suffer this issue any more and no one else is triggering it.

If it pops up again from another report, we'll revisit, but for now, this is getting closed.

**Comment by flibitijibibo** [comment]
So, good news - we have someone on Windows 7 with VAC on the system and it has this bug, so we can probably try investigating this again.

Bad news: It's actually the _opposite_ backends having the issue, WASAPI is fine and DirectSound is not. I'll have them post here with more information soon.

**Comment by michaelarts** [comment]
Hey everyone!

The machine I'm experiencing this on is an HP EliteBook 8760w and I'm using all of the default audio hardware that came with it. Windows says the audio drivers are up to date. Here's a screenshot of the sound device info:

![sounddevice](https://user-images.githubusercontent.com/8358280/188656885-3beba66d-7246-482b-ba6e-50cd4324469b.jpg)

**Comment by icculus** [comment]
(Saw this was still open while sorting through old milestones.)

I still think this is a Virtual Audio Cable bug, so for now I'm going to close this again. If it still presents when Virtual Audio Cable is uninstalled, or if the VAC people say "ah, we tried to debug this on our end and SDL is doing _this stupid thing_ instead of a more correct behavior," (_which is always possible!_) we can revisit this.
