### ISSUE TITLE
SDL_PollEvent hanging on Wayland, SDL_Window is not showing

### ISSUE THREAD

**Issue by a20eac1d** [libsdl-org/SDL#5746]
I am trying to run an SDL2 game on Linux Fedora 35 with an AMD 6700 XT GPU under Wayland. When I execute this code, I can see a window icon on the taskbar, but it is nowhere to be found. When I hover over the icon it seems like the window is not actually there, or it is invisible / fully transparent. It also seems like SDL2 is unable to poll for events because the loop hangs around there.

```c
#include <iostream>

#include "SDL2/SDL.h"

static SDL_Window *window;

static void init()
{
    if(SDL_Init(SDL_INIT_VIDEO) != 0)
    {
        std::cerr << "SDL2 failed to initialize: " << SDL_GetError() << "\n";
        abort();
    }

    window = SDL_CreateWindow
    (
        "Game", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1280, 720, SDL_WINDOW_SHOWN | SDL_WINDOW_OPENGL
    );

    if(!window)
    {
        std::cerr << "SDL2 failed to open a window: " << SDL_GetError() << "\n";
        abort();
    }

    bool running = true;

    while(running)
    {
        SDL_Event e;

        while(SDL_PollEvent(&e) != 0)
        {
            std::cout << "Polling events ... ";

            if(e.type == SDL_QUIT)
            {
                running = false;
            }

            std::cout << "done. Errors: " << SDL_GetError() << "\n";
        }
    }

    SDL_DestroyWindow(window);
    SDL_Quit();
}

int main(int argc, char** argv)
{
    SDL_version compiled;
    SDL_VERSION(&compiled);

    SDL_version linked;
    SDL_GetVersion(&linked);

    printf("SDL2 compiled version: %d.%d.%d\n",
           compiled.major, compiled.minor, compiled.patch);
    printf("SDL2 linked version:   %d.%d.%d\n",
           linked.major, linked.minor, linked.patch);

    init();
    
    return 0;
}
```

Output:

```
./game1 
SDL2 compiled version: 2.0.22
SDL2 linked version:   2.0.22
Polling events ... done. Errors: 
Polling events ... done. Errors:
(no more output until the process is killed)
```

**Comment by a20eac1d** [comment]
After playing around with it, the window works fine on X11 so this is a Wayland issue.

**Comment by flibitijibibo** [comment]
This looks very similar to the invisible window behavior - does this happen if you present the window in some way?

**Comment by a20eac1d** [comment]
> This looks very similar to the invisible window behavior - does this happen if you present the window in some way?

Can you tell me what you mean by "present"? SDL_RenderPresent(renderer)? If so, please let me know and I will try it out!

**Comment by flibitijibibo** [comment]
Anything that updates the window contents- this can be RenderPresent, GL_SwapWindow, vkQueuePresentKHR, or even UpdateWindowSurface (I think).

**Comment by OtherCannon** [comment]
Another thing to note is that this window is not resizable. Enabling SDL_WINDOW_RESIZABLE and then trying to drag the window handles or hit the maximize button does nothing.

**Comment by flibitijibibo** [comment]
> I'm on default GNOME, so the window should not look like that...

Can confirm that this is the actual, real decoration that GNOME Wayland wants and presents for SDL applications - you want https://gitlab.gnome.org/jadahl/libdecor/-/merge_requests/43 for that.

Overall from what I'm seeing this is the same issue we've seen before, where the program does not have a full framework yet - Wayland expects a fully working loop with event handling and presentation. The compositor will not present, update the titlebar or window properties, etc until you have the _full_ loop in place, since the protocol requires regular communication between the client and server to function. We can only replicate the X behavior by actively invading your program's data (for example, ShowWindow would have to intercept your EGL context or Vulkan swapchain and manually present a frame behind your back, even if you were technically in the middle of rendering at the moment ShowWindow was called).

**Comment by icculus** [comment]
Closing this as not our bug.

**Comment by felix-u** [comment]
Would it be possible to get clarification on how this can be worked around? My window renders through Wayland until I implement SDL's event loop, and from then on it'll only use X through XWayland.

This renders a native Wayland window:
```c
    while (SDL_TRUE) {
        SDL_SetRenderDrawColor(renderer, 255, 0, 0, SDL_ALPHA_OPAQUE);
        SDL_RenderClear(renderer);
	SDL_RenderPresent(renderer);
    }
```

While this results in the window only rendering through XWayland:
```c
    SDL_bool done = SDL_FALSE;
    while (!done) {
        SDL_Event event;

        SDL_SetRenderDrawColor(renderer, 255, 0, 0, SDL_ALPHA_OPAQUE);
        SDL_RenderClear(renderer);
	SDL_RenderPresent(renderer);

        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_QUIT) {
                done = SDL_TRUE;
            }
        }
    }
```

**Comment by slouken** [comment]
> Adding `SDL_WINDOW_ALLOW_HIGHDPI` to my `SDL_CreateWindow()` flags did the trick! Perhaps these options should be documented somewhere as being needed on Wayland (at least for now)?

@flibitijibibo, how is that even possible? I don't understand why that would fix the issue here.

**Comment by flibitijibibo** [comment]
Yeah, I'm not sure myself - all HIGHDPI does is make a `1.0f` value something else, the code paths are identical otherwise.

**Comment by icculus** [comment]
> While this results in the window only rendering through XWayland:

I don't want to be nitpicky, but I don't understand how this code makes a difference either; it's either decided to use Wayland or X11 at this point and does not fall back to the other.

**Comment by felix-u** [comment]
This gives me a native Wayland window:
```c
    int32_t window_flags =
        SDL_WINDOW_ALLOW_HIGHDPI |
        SDL_WINDOW_INPUT_FOCUS |
        SDL_WINDOW_SHOWN;
	SDL_Window* window = SDL_CreateWindow(
        "nbody", // title
        100, 100, // co-ordinates
        SCREEN_WIDTH, SCREEN_HEIGHT, // dimensions
        window_flags
    );
```
and this does **not**:
```c
    int32_t window_flags =
        // SDL_WINDOW_ALLOW_HIGHDPI |
        SDL_WINDOW_INPUT_FOCUS |
        SDL_WINDOW_SHOWN;
	SDL_Window* window = SDL_CreateWindow(
        "nbody", // title
        100, 100, // co-ordinates
        SCREEN_WIDTH, SCREEN_HEIGHT, // dimensions
        window_flags
    );
```
**NOTE:** I use fractional scaling. I've just discovered that if I set my scale to 1 instead of my usual 1.3, I seem to get a native Wayland window even without `SDL_WINDOW_ALLOW_HIGHDPI`. 
I suppose this behaviour somewhat makes sense, considering the name of this flag. Though I was under the impression that Wayland (or at least wlroots) provided scaled screen coordinates (resolution divided by scale factor) rather than absolute ones. Evidently, my impression was incorrect.

Is there an SDL log I can toggle somehow? I would've saved lots of time had I seen something along the lines of:
`Wayland compositor refused connection with [message], reverting SDL_VIDEODRIVER to fallback x11`

**Comment by icculus** [comment]
> I would've saved lots of time had I seen something along the lines of:
Wayland compositor refused connection with [message], reverting SDL_VIDEODRIVER to fallback x11

But what I'm saying is _it doesn't do that_. Once SDL decides to use Wayland (during SDL_Init()), it literally can not switch over to use x11.

**Comment by felix-u** [comment]
All I know is:

Comment out `HIGHDPI` flag --> `make && ./nbody` --> X window through Xwayland
Add back `HIGHDPI` flag --> `make && ./nbody` --> native Wayland window

I don't know how `SDL_Init()` works, but what other than SDL could be handling this scenario?

**Comment by slouken** [comment]
@felix-u, can you open a separate issue for getting an X11 window vs Wayland window, depending on window flags? Please include a small test program if you can.

Thanks!

**Comment by felix-u** [comment]
Done! :)
https://github.com/libsdl-org/SDL/issues/6028

**Comment by slouken** [comment]
Thanks!
