### ISSUE TITLE
Switching back from fullscreen not resizing game properly

### ISSUE THREAD

**Issue by zorgiepoo** [libsdl-org/SDL#5925]
SDL is no longer switching back to windowed mode properly when [my game](https://github.com/zorgiepoo/Sky-Checkers) is in fullscreen and I toggle (using opt+enter) to windowed mode (this uses `SDL_SetWindowFullscreen()` passing 0 instead of prior `SDL_WINDOW_FULLSCREEN_DESKTOP` from a `SDL_KEYDOWN` event). It looks like, visually, there is a lack of a resize update event. If I resize the window afterwards, the game properly resizes.

<img width="629" alt="Screen Shot 2022-07-16 at 6 39 40 AM" src="https://user-images.githubusercontent.com/857267/179360197-cc45ffc7-7d54-4c59-8e56-237631e0ea3f.png">

I'm on Ubuntu 20.04.4 LTS and should be using X11 (not Wayland).

This reproduces on top of main (a09d62e4d81522a04e5bd04346d1b22f02ade890 as of now) and SDL 2.0.22. This does not reproduce on SDL 2.0.20 or 2.0.12 (which I was using earlier). So I only noticed this issue after I tried upgrading SDL. (On earlier 'bad' SDL builds actually, the issue was that going to fullscreen didn't make my game resize to the full screen but this seems to have been fixed at some point.. but there seems to be two issues present in the commit log)

When my game receives `SDL_WINDOWEVENT_RESIZED` it essentially does:
```
SDL_GL_GetDrawableSize(ZGWindowHandle(renderer->window), &renderer->drawableWidth, &renderer->drawableHeight);
glViewport(0, 0, renderer->drawableWidth, renderer->drawableHeight);
updateGLProjectionMatrix(renderer);
```
I'm currently trying to bisect where things regressed in SDL but if I were to take a wild guess it's related to some wayland or x11 fullscreen commits.

**Comment by zorgiepoo** [comment]
This seems to be the first commit where fullscreen behavior went wrong (#5233). In this case going to fullscreen doesn't render the game to the full screen size though (cc @icculus)

```
commit 8bae343f252128147d97912c89fa2b40380158e6 (HEAD, refs/bisect/bad)
Author: Ryan C. Gordon <icculus@icculus.org>
Date:   Tue Apr 5 22:19:25 2022 -0400

    x11: when waiting on fullscreen changes, not window position _and_ size.
    
    This makes sure the window doesn't have outdated values if you try to access
    them (or call something that does, like SDL_SetWindowMinimumSize).
    
    Fixes #5233.
```

If I try to comment/revert these changes on top of `main`, fullscreen toggling behavior (both entering/exiting) works in my game again:

```
diff --git a/src/video/x11/SDL_x11window.c b/src/video/x11/SDL_x11window.c
index f7ec281b9..ed1f279e2 100644
--- a/src/video/x11/SDL_x11window.c
+++ b/src/video/x11/SDL_x11window.c
@@ -1314,7 +1314,7 @@ X11_SetWindowFullscreenViaWM(_THIS, SDL_Window * window, SDL_VideoDisplay * _dis
         Window childReturn, root, parent;
         Window* children;
         XWindowAttributes attrs;
-        int orig_w, orig_h, orig_x, orig_y;
+        int orig_x, orig_y;
         Uint64 timeout;
 
         X11_XSync(display, False);
@@ -1322,8 +1322,6 @@ X11_SetWindowFullscreenViaWM(_THIS, SDL_Window * window, SDL_VideoDisplay * _dis
         X11_XGetWindowAttributes(display, data->xwindow, &attrs);
         X11_XTranslateCoordinates(display, parent, DefaultRootWindow(display),
                                   attrs.x, attrs.y, &orig_x, &orig_y, &childReturn);
-        orig_w = attrs.width;
-        orig_h = attrs.height;
 
         if (!(window->flags & SDL_WINDOW_RESIZABLE)) {
             /* Compiz refuses fullscreen toggle if we're not resizable, so update the hints so we
@@ -1396,10 +1394,12 @@ X11_SetWindowFullscreenViaWM(_THIS, SDL_Window * window, SDL_VideoDisplay * _dis
                     window_changed = SDL_TRUE;
                 }
 
+                /*
                 if ((attrs.width != orig_w) || (attrs.height != orig_h)) {
                     SDL_SendWindowEvent(data->window, SDL_WINDOWEVENT_RESIZED, attrs.width, attrs.height);
                     window_changed = SDL_TRUE;
                 }
+                */
 
                 if (window_changed) {
                     break;  /* window changed, time to go. */
```

I should note I'm running Ubuntu in a VM and it does look like there are two (or at least more than one) resize-changes that happen when I exit fullscreen in my game.

**Comment by icculus** [comment]
Just typing this in before my laptop battery dies so I don't lose it:

- SDL_GL_GetDrawableSize calls (on X11) SDL_GetWindowSize() since there isn't any DPI magic in X11.
- SDL_GetWindowSize() literally just reports window->x and window->y.
- Maybe there's some race condition between the SDL_SendWindowEvent in X11_SetWindowFullscreenViaWM and what the window finally lands at, and the app gets the wrong size because of it.
- The ConfigureNotify event caches the previous event and won't send a new resize event if it matches, but in this case the window might have a different size than that event (why _are_ we caching this? We'll already filter out resize events if the window is already there in SDL_SendWindowEvent...)

**Comment by icculus** [comment]
Ok, I reproduced this here and this is what's happening:

- user hits alt-enter to go fullscreen_desktop (fine)
- user hits alt-enter again to go back to window
- Then, in X11_SetWindowFullscreenViaWM, we're waiting for the X server to report changes to the window before we return, we do this because every other OS generally blocks here so apps will have a sane SDL_Window state when they return, whereas X11 is async and you might get window events reporting the final results later, and we're trying to mitigate that a little.
- If it reports a window resizing, we call `SDL_SendWindowEvent(data->window, SDL_WINDOWEVENT_RESIZED, attrs.width, attrs.height);` ... we do this with SDL_WINDOWEVENT_MOVED if the window moves, too; and assume the fullscreening work is done.
- SDL_SendWindowEvent() adds a RESIZED event to the queue, and also calls SDL_OnWindowResized(), which adds a SIZE_CHANGED event, too.
- Further down the stack, there's a call to SDL_UpdateFullscreenMode() that started this work. One of the last things it does is call SDL_OnWindowResized().
- SDL_OnWindowResized() generates a second SDL_WINDOWEVENT_SIZE_CHANGED event, but also filters any previous RESIZED or SIZE_CHANGED events from the queue so there's no chance of overflow if we're changing rapidly.
- The game only checks for RESIZED events and not SIZE_CHANGED, so it never sees an event when going back to windowed mode to tell it to resize its GL viewport.

There was a good reason we added that event to the X11 code recently, but now I can't remember what it is. Either this was meant to be a SIZED_CHANGED event and I used RESIZED, or we shouldn't filter out both in SDL_OnWindowResized, or something else.

(For SDL3, we should probably change this to not have separate SIZE_CHANGED and RESIZED events, though, because this turned out to be kinda confusing.)

Going to look at a few more things and decide what to do here, but the cause is totally known now.

**Comment by slouken** [comment]
The SDL_WINDOWEVENT_RESIZED should be sent when the window is resized but the application didn't trigger the change. SDL_WINDOWEVENT_SIZE_CHANGED is sent regardless of why the window resized.

**Comment by slouken** [comment]
I'm guessing this was meant to be SDL_WINDOWEVENT_SIZE_CHANGED

**Comment by slouken** [comment]
I think the original intent was for applications to be able to react to SDL_WINDOWEVENT_RESIZED by changing window size or video mode without going recursive. :)

**Comment by icculus** [comment]
Changing the SDL_WINDOWEVENT_RESIZED in Sky-Checkers here...

https://github.com/zorgiepoo/Sky-Checkers/blob/main/src/window_sdl.c#L160

...to SDL_WINDOWEVENT_SIZE_CHANGED definitely fixes the problem here, but I'm still not sure SDL should filter _both_ events in SDL_OnWindowResized and only add one back; maybe it should notice if it filtered both and add both back in at the new size?

**Comment by slouken** [comment]
Yes, that seems reasonable.

**Comment by zorgiepoo** [comment]
Oops. I will probably change my game to use `SDL_WINDOWEVENT_SIZE_CHANGED` because that seems to be what I really want. Thanks for debugging this.

I think part of the confusion that I see is that the [documentation](https://wiki.libsdl.org/SDL_WindowEventID) for `SDL_WINDOWEVENT_RESIZED` doesn't specify when it doesn't happen or that it's only specifically for the user resizing the window. Also `SDL_WINDOWEVENT_SIZE_CHANGED` doesn't reference `data1xdata2` (although there's a code sample).

**Comment by icculus** [comment]
> Oops. I will probably change my game to use SDL_WINDOWEVENT_SIZE_CHANGED because that seems to be what I really want.

We're going to fix the issue in SDL, too, but yes, you should probably make this change regardless.

I've opened an issue to visit the documentation, and I'll resolve this issue soon as well.

**Comment by icculus** [comment]
Ok, this is fixed in SDL, and Sky-Checkers works correctly now (even without changes to listen for SIZED_CHANGED events instead of RESIZED).
