### ISSUE TITLE
Within SDL_MOUSBUTTONDOWN SDL_PRESSED behaves like SDL_RELEASED

### ISSUE THREAD

**Issue by NikNagedo** [libsdl-org/SDL#5931]
Hello,

within the event SDL_MOUSBUTTONDOWN the value SDL_PRESSED behaves normally like a persistent signal. That means as long as the mousebutton is pressed the value SDL_PRESSED is given and retrievable. So it is in SDL2 2.0.9, 2.0.10 and 2.0.12, may be also in the following versions (not tested).

In SDL2 2.0.22 and 2.0.23 the value SDL_PRESSED behaves like an onetime signal. Although the mousebutton is still pressed the value SDL_PRESSED is sended or received only once. Hence, SDL_PRESSED behaves like SDL_RELEASED.

I have tested this issue on Windows 10 64 bit and Linux Mint (only SDL2 2.0.10).

Here is a demo program illustrating the topic:

```

#include <stdio.h>
#include <stdlib.h>

#include "include\SDL2\SDL.h"

#define SDL_main main 

int main(int argc, char*argv[])
{

SDL_Event event;
int go_out;
go_out=0;

if(SDL_Init(SDL_INIT_VIDEO|SDL_INIT_JOYSTICK) !=0)
{
        printf("SDL can not be initialized: %s\n", SDL_GetError());

}

printf("Leave by clicking right mousebutton! \n");


SDL_CreateWindow("Click Demo",SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 400, 400, SDL_WINDOW_SHOWN);

while(go_out==0)
{
	SDL_PollEvent(&event);
        
		
    switch(event.type)
    {
				
		case SDL_MOUSEBUTTONDOWN:
		
		printf("down \n \n");
		
		             
		if(event.button.button==SDL_BUTTON_LEFT && event.button.state==SDL_PRESSED) 
		{ 
						
			printf("pressed \n \n");
			
			
		}
		if(event.button.button==SDL_BUTTON_LEFT && event.button.state==SDL_RELEASED) 
		{
		
			printf("released \n \n");
		}
		break;
		
		case SDL_MOUSEBUTTONUP:
		
		printf("up \n \n");
		
		if(event.button.button==SDL_BUTTON_RIGHT)
		{
			go_out=1;
		}
		
		break;
		
		
	}
}


atexit(SDL_Quit);


return 0;
}


```
Please find attached ZIP with source and a WIN 64bit program.

[click_demo.zip](https://github.com/libsdl-org/SDL/files/9132031/click_demo.zip)

**Comment by NikNagedo** [comment]
That is the behaviour of SDL2 2.0.22 and 2.0.23. The behaviour of 2.0.9, 2.0.10 and 2.0.12 is a repeating signal of "down" and "pressed" as long as the left mousebutton is pressed

https://user-images.githubusercontent.com/109514964/180297205-ba17b761-6761-41db-b013-7e7a472512fd.mp4

.

**Comment by sridenour** [comment]
It has only ever supposed to have been a one-off event. You get `SDL_MOUSEBUTTONDOWN` once when the mouse button is pressed, and `SDL_MOUSEBUTTONUP` when the button is released.

The reason your code appears to work with old versions of SDL is because it (incorrectly) isn't checking the return value of `SDL_PollEvent()`. The event struct is only valid if `SDL_PollEvent()` returns >0 (meaning there are new events to handle). Old versions of SDL apparently left the event struct unchanged if `SDL_PollEvent()` was called when no events had occurred; it seems that at some point `SDL_PollEvent()` was changed to clear the event struct instead.

If you want a persistent flag for whether or not the mouse button is down/up, either set one yourself inside the event handling code or use `SDL_GetMouseState()` every time you want to check it.

**Comment by icculus** [comment]
Closing because this was a bug in the test case, not SDL.
