### ISSUE TITLE
supertuxkart displays only a quarter of its content on wayland

### ISSUE THREAD

**Issue by lilydjwg** [libsdl-org/SDL#5941]
![screenshot-2022-07-21_11:39:53](https://user-images.githubusercontent.com/440661/180126150-f23ca2b5-7507-4659-8f5e-3b3e72bdb013.png)

This is only the left-bottom quarter of content.

I'm running Wayfire (wlroots-based) on Arch Linux. sdl2 2.0.20-2 is good and 2.0.22-1 is bad. `git bisect` gives that 4d76c9cb46491064b1817bd69f78d59783546ee5 is the first bad commit.

I'm running with dual monitors (1920x1080 and 3840x2160) and both reports scale=2 to wayland clients (my compositor scales down the former).

**Comment by slouken** [comment]
@Kontrabant, can you look at this?

**Comment by Kontrabant** [comment]
> @Kontrabant, can you look at this?

Sure, I can replicate this on Gnome if I have my primary display with a scale of 1 and my secondary display with a scale of 1.25.  What's happening is that SuperTexKart is taking the highest scale value in a multimonitor setup and (incorrectly) applying that scale across all displays.

Ultimately it boils down to [SuperTuxKart not properly handling multimonitor and mixed-DPI setups](https://github.com/supertuxkart/stk-code/blob/d85c1e3ee748b2ac7e0936301ade8c0d3e92b271/lib/irrlicht/source/Irrlicht/CIrrDeviceSDL.cpp#L167).  It uses a hack to query the scale by creating a hidden window, comparing the window size with the backbuffer, and applying that scale to all displays.  The problem is that the SDL `Wayland_CreateWindow()` function initially sets the scale value to the highest of all connected displays, and it's only updated with the 'true' value once the window is displayed, and since the window they use to calculate the scale is never shown, it's never updated.  I'm surprised this problem didn't manifest before, as this has been the standard behavior since [the Wayland backend initially got high-DPI support](https://github.com/libsdl-org/SDL/commit/797b28133c9441384b1870f49b1fe91d5e214a9f#diff-d7981dffd4e10c93a60470c43124a2dcd1c56e6483f58937b347c0febbe8af12R642).

We could try to work around this on the SDL side by setting the initial window scale value to that of the primary display (is it guaranteed to always be display 0 on Wayland?) instead of using the largest value of all the connected displays, but ultimately this is their bug as this is fundamentally incorrect behavior on their end on any platform that allows mixed-DPI setups.
