### ISSUE TITLE
`SDL_MOUSEMOTION` events aren't sent when dragging from inside the window to outside with Wayland

### ISSUE THREAD

**Issue by Guldoman** [libsdl-org/SDL#6010]
With X11 `SDL_MOUSEMOTION` events are sent when dragging from the inside of the window to outside.
With Wayland the events aren't fired when the mouse is outside the window.

Comparison of what happens in X11 (horizontal scroll in the Lite XL editor):

https://user-images.githubusercontent.com/2798487/183216141-ffdd4731-132b-48eb-a8bb-007c4465c479.mp4

And Wayland:

https://user-images.githubusercontent.com/2798487/183216151-3c40b73b-1846-45c7-9fa2-f12c06beb6d3.mp4

I suspect this happens because of this check:
https://github.com/libsdl-org/SDL/blob/17b329d199899da4bc328632f852e3c96f98c665/src/events/SDL_mouse.c#L285

Normally on mouse press the mouse is "captured", but with the Wayland backend there is no `(SDL_Mouse *)mouse->CaptureMouse`, so the `(window->flags & SDL_WINDOW_MOUSE_CAPTURE) == 0` check is always true.

**Comment by icculus** [comment]
Wayland won't emit motion events when outside the window, even if dragging, which is why CaptureMouse() isn't implemented, and probably why this won't ever work.

@flibitijibibo Can you confirm this is true real fast before I close this issue?

(Also, is there some way to convince the Wayland devs to add a protocol for this? It's ridiculous that we can see the mouse outside the window on every platform that has existed since the concept of a mouse and window were invented, except for Wayland.)

**Comment by Guldoman** [comment]
> Wayland won't emit motion events when outside the window, even if dragging, which is why CaptureMouse() isn't implemented, and probably why this won't ever work.

Just inverting the check like this `(window->flags & SDL_WINDOW_MOUSE_CAPTURE) != 0` is enough to make it work (even if not really the correct solution), so it seems like (at least in GNOME) the events are sent in the "dragging" case.

**Comment by icculus** [comment]
Huh, you're right...Just tried this with xeyes under XWayland, and it'll keep working if you drag from inside the window.

Okay, I'll make a fix.

**Comment by icculus** [comment]
Okay, this works (mostly) like you'd expect now. It's not really a full CaptureMouse support, but it's enough that auto capture and SDL_CaptureMouse() works for dragging outside the window like you'd expect.

**Comment by Guldoman** [comment]
Works great, thanks!
