### ISSUE TITLE
SDL controller type for Joy-Cons?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6017]
Now that we have good support for Joy-Cons, it might make sense to add an official controller type for them to the API.

The question is, should we? If so, should we have separate types for JOYCON_L, JOYCON_R, JOYCON_PAIR? Should JOYCON_PAIR instead be treated like SWITCH_PRO? Should JOYCON_L, JOYCON_R be conflated into just JOYCON, and you can check the VID/PID to see which it is?

Or should we just punt and let people figure this out on their own? One complicating factor is that the Nintendo Online NES controllers show up as JOYCON_R but have a different name and don't actually have all the inputs of a Joy-Con controller.

Thoughts? @icculus, @cgutman, @flibitijibibo?

**Comment by flibitijibibo** [comment]
This is something we basically do for actual Switch support anyhow - without disclosing too much, the styles explicitly shown on Nintendo hardware are Left, Right, Dual, Handheld, and Pro. There are special queries on official hardware, for PC it's just the flags that we already have to detect, and I would absolutely put each of those in its own category like we did for GameCube since there are countless third-party adapters and such that would make use of those types.

**Comment by slouken** [comment]
Great feedback, thanks. What is "Handheld"?

**Comment by flibitijibibo** [comment]
Handheld refers to the joycons when the console is undocked (they're ignored when docked). Dual refers to unplugged controllers in either mode.

**Comment by slouken** [comment]
Got it, thanks.

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/878259722f60976ed5e9e74c2d311e8c15fe5da9
