### ISSUE TITLE
Sync documentation in docs/ with the wiki?

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL#6026]
It might be useful to have some of the files in the docs/ directory synced with the wiki, to avoid having to write things like installation instructions more than once.

**Comment by icculus** [comment]
Good idea!

**Comment by icculus** [comment]
This is definitely getting bumped out of 2.26.0 because we're way behind, but let's discuss what we want this to look like for later.

Right now docs/* has README-subject.md. The wiki already supports Markdown format, so we literally just need to copy these over from one to the other when they change. Do we want them at `https://wiki.libsdl.org/README-subject` or somewhere else? We can't just do `/subject` because in theory we want to look for things originating on the wiki and create them in the docs/ folder as well (although perhaps we should not).

Technically GitHub will show MediaWiki formatting, like it does for Markdown, but it does a poor job of it and its less human-readable if someone just opens a local copy in a text editor, so I think if someone tries to add a .mediawiki thing we ignore it and only bridge Markdown files in this case.

The code to bridge these will be pretty trivial, we just need to make some basic decisions before I execute on it.

**Comment by icculus** [comment]
Okay, this is up and running now for SDL2 and SDL3.

It puts everything called README-*.md without any content changes (except endline conversion) into the wiki and vice-versa.

So docs/README-linux.md shows up on the web at https://wiki.libsdl.org/SDL3/README/linux

Just going to https://wiki.libsdl.org/SDL3/README will show a list of all READMEs available.

Editing the page on the wiki will commit it to the source's docs directory and vice-versa.

We'll see if this is useful. If this sucks, we'll just redirect requests for this directory to the equivalent page on GitHub and call it a day, but it'll be nice if this is a low-barrier path for people to submit edits to these files.
