### ISSUE TITLE
considering webgpu in SDL?

### ISSUE THREAD

**Issue by mreinstein** [libsdl-org/SDL#6099]
I realize it's early days since no browsers are yet shipping an unflagged implementation, but I think it's coming soon, and offers some really nice advantages over GL.

I'm just curious if any thought has been given to this yet, or if it's completely off of SDL's radar at this point?

**Comment by icculus** [comment]
I'm working on a new GPU API that will map nicely to it. Explanation of the overall idea is here: https://www.patreon.com/posts/58563886

Stay tuned for more on that!

No one is currently writing a WebGPU backend for the existing 2D API, because WebGL is widely available and covers all of the functionality needed there.

**Comment by mreinstein** [comment]
This is amazing!
