### ISSUE TITLE
sort: unknown option -- V

### ISSUE THREAD

**Issue by 0-wiz-0** [libsdl-org/SDL#6106]
The configure script uses 'sort -V' which is not supported by NetBSD's sort(1).

**Comment by slouken** [comment]
That's used to sort by version. Is there another alternative on NetBSD?

**Comment by 0-wiz-0** [comment]
Not in sort(1). I guess one would have to write an awk script or something.

**Comment by slouken** [comment]
I tried some simple awk and couldn't come up with anything viable. You're welcome to submit a PR to fix this.

**Comment by 0-wiz-0** [comment]
If I understood the code correctly, the line
```
        lib=[`ls -- $path/$1 2>/dev/null | sed 's,.*/,,' | sort -V -r | $AWK 'BEGIN{FS="."}{ print NF, $0 }' | sort -n -s | sed 's,[0-9]* ,,' | head -1`]
```
can be replaced with (in shell, please add quoting for m4):
```
ls -- $path/$1 | awk -f 'BEGIN { max = -1; len = -1;}
{
    linelen = length($0);
    parts = split($0, p, ".so.");
    if (parts > 1) {
        parts = split(p[2], a, ".");
        major = a[1];
        if (major > max || (major == max && linelen < len)) {
                max = major;
                len = linelen;
                line = $0;
        }
    }
}

END {
    print line;
}'

I tested by putting this awk script in a file and using
```
libneon.so.2
libneon.so.2.5.2
libneon.so.2.17.2
libneon.so.27
libneon.so.27.5.2
libneon.so.27.28.2
```
as input:
`awk -f script.awk data` which gave me `libneon.so.27`, which I think is the wanted output.

**Comment by slouken** [comment]
It doesn't handle this case though:
```
lrwxrwxrwx 1 Sam Lantinga None 13 Aug 22 16:56 libjxl.so -> libjxl.so.0.6
lrwxrwxrwx 1 Sam Lantinga None 15 Aug 22 16:56 libjxl.so.0.6 -> libjxl.so.0.6.1
-rw-r--r-- 1 Sam Lantinga None  0 Aug 22 16:56 libjxl.so.0.6.1
lrwxrwxrwx 1 Sam Lantinga None 15 Aug 22 16:56 libjxl.so.0.7 -> libjxl.so.0.7.1
-rw-r--r-- 1 Sam Lantinga None  0 Aug 22 16:56 libjxl.so.0.7.1
```

**Comment by 0-wiz-0** [comment]
Hm, that's two very different cases :)
How about this one:
```
BEGIN { max[1] = -1; }
{
    if (split($0, p, " -> ") > 1) next;
    if (split($0, p, ".so.") > 1) {
        n = split(p[2], v, ".");
        for (i=1; i<=n; i++) {
            if (v[i] < max[i]) next;
            if (v[i] == max[i]) continue;
            break;
        }
        if (max[1] != v[1]) base = "";
        if (length(v) == 1) base = $0;
        delete max;
        for (i=1; i<=n; i++) {
            max[i] = v[i];
        }
        line = $0;
    }
}

END {
    if (length(base) > 0) print base; else print line;
}
```
If we need to iterate, it'd be great to have a specification what actually *should* be the result. :)

**Comment by slouken** [comment]
The output should be the highest version with the shortest length. We also need to handle DLLs in this code.

**Comment by smcv** [comment]
Would it be an option to fix this by moving all the `find_lib` calls into the scope of `enable_sndio_shared` etc., and recommending that users of non-Linux Unixes use ordinary linking like `-lsndio` (`--disable-sndio-shared`) instead of `dlopen()` (`--enable-sndio-shared`)? The `--enable-foo-shared` mode is great for a copy of SDL that will be bundled with a proprietary game binary, but I'm not aware of anyone releasing relocatable game binaries for NetBSD.

Or, is it an option to just say that if you're using the GNU Autotools build system, then you'll also need GNU sort for the version-comparison; and if you don't want to use GNU tools, try the CMake build? It seems like the CMake build is increasingly the direction that SDL is going in (I'm still using Autotools to package it in Debian right now, but I've wondered whether I should be moving to CMake).

If it would help, the calls to `sort` could use `$SORT`, after an `AC_CHECK_PROGS([SORT], [gsort sort], [false])` to account for the BSD convention of prefixing GNU tools with `g` so they don't collide with the OS's own equivalents?

**Comment by 0-wiz-0** [comment]
> The output should be the highest version with the shortest length
Hm, that's not what it does. For your example input the original code returns `libjxl.so.0.7.1`, not `libjxl.so.0.7` (the second awk script I posted does the same).

@smcv 's proposals sound fine to me too.

**Comment by slouken** [comment]
Does NetBSD provide gsort by default?

**Comment by 0-wiz-0** [comment]
No, but there's a `coreutils` package that can be easily installed: `pkgin in coreutils` and then you have a gsort.

**Comment by smcv** [comment]
> The output should be the highest version with the shortest length

Well, that's an implementation detail. What we actually want is that the output should be all of these:

* a name that is preserved during ABI-compatible upgrades;
* a name that is not preserved during ABI-incompatible upgrades;
* the newest name that meets those constraints

For example, for libdbus on Linux, the ELF `DT_SONAME` field is `libdbus-1.so.3`, which is the name used by all versions that have a compatible ABI. We don't want `libdbus-1.so.2` because that's an older, incompatible ABI. We don't want to go less specific and use `libdbus-1.so`, because that has no ABI guarantees, and might point to either `libdbus-1.so.3` or `libdbus-1.so.2`; and we don't want to hard-code `libdbus-1.so.3.32.0` either, because a routine upgrade can replace that with `libdbus-1.so.3.33.0` and we don't want routine upgrades to break SDL.

If you use `--disable-sndio-shared` and so on, then the compiler/linker should do this for us, without having to do anything special; so this is work that we're creating for ourselves because we want to be able to have weak/optional dependencies via `--enable-sndio-shared` and so on. But perhaps `--enable-*-shared` doesn't really make sense on NetBSD?

**Comment by smcv** [comment]
> if you're using the GNU Autotools build system, then you'll also need GNU sort for the version-comparison; and if you don't want to use GNU tools, try the CMake build

Draft implementation of this in #6128.
