### ISSUE TITLE
Deprecate sdl2-config and AM_PATH_SDL2, at least on Unix

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#6140]
Library-specific `foo-config` scripts are increasingly discouraged, because they duplicate very similar logic across lots of projects, and tend to break cross-compiling, multilib (`gcc -m32` and so on) and Debian/Ubuntu multiarch. The direct replacement is pkg-config (or one of its compatible reimplementations like pkgconf), which relies on each library installing declarative metadata (SDL has had `sdl2.pc` since at least 2.0.0) and centralizes the logic into the pkg-config/pkgconf tool.

SDL 2 probably needs to keep `sdl2-config` for backwards-compatibility, but it would be nice to document it as deprecated/discouraged. It can be removed as part of SDL 3.

Similarly, the `AM_PATH_SDL2` macro in `sdl2.m4` relies on `sdl2-config` for some things. SDL 2 probably needs to keep it for backwards-compat, but it would be nice to document that the recommended way for Autoconf projects to use SDL is `PKG_CHECK_MODULES([SDL], [sdl2 >= 2.x.y])`. Users of a custom prefix can use one of pkg-config's standard ways to override its result if they need to: force the result by passing `SDL_CFLAGS` and `SDL_LIBS` to the configure script, or set `PKG_CONFIG_PATH`, `PKG_CONFIG_SYSROOT_DIR` and/or `PKG_CONFIG_LIBDIR`, or set `PKG_CONFIG` to point to a wrapper script.

`AM_PATH_SDL2` does have some features that `PKG_CHECK_MODULES` doesn't (macOS frameworks, and a check that the version of SDL found by the compiler is the same as the one found by sdl2-config), but the macOS framework support seems to be broken in practice, and the compile check seems fairly redundant. `sdl2.m4` seems to be based on GLib's `glib-2.0.m4`, which was deprecated a while ago.

**Comment by Conan-Kudo** [comment]
Deprecation should be in the SDL 2.x lifetime. ***Removal*** should be declared for SDL 3.0.

**Comment by sulix** [comment]
So, having tried [2.26.0 RC1](https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.25.1), the deprecation warning is already quite annoying. (Which I guess is sort-of the point, but still…)

In particular, there are a lot of existing applications and build-scripts, etc which are unlikely to get updated, and which call ``sdl2-config`` many times in their configure/build process. This is particularly ugly for people just trying to build something, when there are many, many copies of the deprecation warning spamming the screen.

(And one of these is the SDL tests: which uses it for the ``--with-sdl-prefix`` option, and spams the warning 4 times. Realising that the "solution" is having to set ``PKG_CONFIG_PATH=<sdl-prefix>/lib64/pkgconfig/`` instead is much less intuitive.)

Could we maybe forgo the deprecation warning for SDL 2, and just never have an sdl3-config? (Or at least make the deprecation warning a bit less verbose, and maybe link to a wiki page describing how to migrate, rather than having a very terse description in the warning? The commit message for the change would make a good start…)

**Comment by Conan-Kudo** [comment]
The point is that it _is_ supposed to nag you that it's going away. If it didn't, people wouldn't adapt to switch to pkgconfig now.

**Comment by sulix** [comment]
> The point is that it _is_ supposed to nag you that it's going away. If it didn't, people wouldn't adapt to switch to cmake or pkgconfig modules now.

A fair point, and I sort-of hate myself being that guy complaining about it.

My concerns are really that:
- By virtue of ``sdl2-config`` being called multiple times, it's verbose enough to actually be difficult to read the message. 
- (In fact, it'd be _really_ nice to find some way of limiting the number of times the warning printed to once. Though I can't think of a way to do it.)
- We should fix the test/configure script to not use sd2-config, or at least document how to use ``PKG_CONFIG_PATH`` instead of ``--with-sdl-prefix`` (which IMHO, was a bit easier to understand). 
- If I understand it, ``sdl2-config`` _isn't_ actually going away? We're just not going to have ``sdl3-config``?
- (And I suspect most of the actively-maintained things will switch to using SDL3 anyway, so longer-term, a pretty significant proportion of the SDL2 projects will be unmaintained, and hence trigger this warning…)

But this is all vague ramblings while I'm feeling tired — the only thing I really think is _important_ here is fixing the tests to not trigger this.

**Comment by slouken** [comment]
I agree with this feedback. We'll un-deprecate this for 2.x and won't include it in 3.x.

**Comment by slouken** [comment]
These have been reverted in https://github.com/libsdl-org/SDL/commit/769ae185d608b72d70c8caa54deeede7ddcdf7b1 and https://github.com/libsdl-org/SDL/commit/9209942949a2a7c2b117c22cf970e58bf587e109
