### ISSUE TITLE
New versioning scheme breaks some applications

### ISSUE THREAD

**Issue by Pixelnarium** [libsdl-org/SDL#6177]
Hello,

I just found out that the new versioning scheme in libSDL may break applications. It is of course a bug inside the application itself and not a bug on SDLs side. But given that libSDL tries to be compatible I just want to mention it. I tried it inside Flatpak via the flatpak-gog project with the newest runtime 22.08. This runtime ships the new libSDL 2.24.0 and so I found out about this.

When I tried to run Stardew Valley with the new libSDL library (game ships its own but can be changed with SDL_DYNAMIC_API environment variable) it just exits with the message:

`SDL 2.0.4 does not support changing resizable parameter of the window after it's already been created, please use a newer version of it`

It runs fine with libSDL before the new versioning scheme. While searching for it I found out that pygame was also affected by this: https://github.com/pygame/pygame/issues/3427

Since I could not find any news about this I want to make people aware of this. Setting SDL_DYNAMIC_API globally may break your games with the newest libSDL. 

edit: Changed link to upstream pygame issue

**Comment by cgutman** [comment]
Maybe we should create a `SDL_HINT_LEGACY_VERSION` hint that causes `SDL_GetVersion()` to return a version in the old format.

**Comment by icculus** [comment]
I sent ConcernedApe (the Stardew Valley person) a DM on Twitter to see if they want to take a look at this in the game.

If it's a handful of things that broke, and it's possible to fix them, I'd rather do that, since a hint is going to be an extra step for users to deal with and it's going be arcane knowledge on every title, but we'll see if it comes to that.

**Comment by icculus** [comment]
Actually, wait, @flibitijibibo, was Stardew Valley one of your titles?

**Comment by flibitijibibo** [comment]
Sadly no, this was done by Sickhead and is MonoGame-based. But, that means I know where the bug is:

https://github.com/MonoGame/MonoGame/blob/a9e5ae6befc40d7c86320ffdcfcd9d9b66f786a8/MonoGame.Framework/Platform/SDL/SDLGameWindow.cs#L16

CC @mrhelmut, this needs to check the minor version in addition to the patch version!

**Comment by mrhelmut** [comment]
Thanks for the ping! Going to patch that.

**Comment by slouken** [comment]
PyGame and MonoGame both have fixes on the way, I'll go ahead and close this for now.
