### ISSUE TITLE
[Question] Are point/patch releases planned?

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL#6179]
So, I noticed after 2.24.0 was released we got a new branch here: https://github.com/libsdl-org/SDL/commits/release-2.24.x

Does this means a 2.24.1 release would happen at some time?

I am asking because it's branch has commit ac44b22a24909812c50d950ba9fa02518ae177b8, which I need for building for Android on my project.

**Comment by icculus** [comment]
We collect up immediate regressions and emergency corrections in a .1 branch, in case it makes sense to ship a 2.24.1, but we don't promise to actually do so, since we now try to ship a 2.XX.0 release every 90 days or so (previously, it wasn't uncommon for us to take 6-12 months to ship a new release!).

CC'ing @slouken so he knows there is some demand for a quick .1 turnaround this time, though.

**Comment by ericoporto** [comment]
hey, cherry-picking the commit https://github.com/libsdl-org/SDL/commit/803924b2233458e4a2a7d24530e2208940ca278b on the release 2.24.x branch would be really helpful!

**Comment by madebr** [comment]
I went ahead and added it in b6661c016bba98cdeb7bea1ffa67aa0794dc2942
