### ISSUE TITLE
SDL_WaitEvent not getting SDL_USEREVENT when running with wayland + libdecor 

### ISSUE THREAD

**Issue by fernandoherreradelasheras** [libsdl-org/SDL#6204]
After this commit:

https://github.com/libsdl-org/SDL/pull/5703

some programs using `SDL_WaitEvent` stopped working when run with wayland with libdecor support.

As in `Wayland_WaitEventTimeout` the call to `libdecor_dispatch` will flush all pending events the function will block at `SDL_IOReady(WAYLAND_wl_display_get_fd(d->display)...)` and the user events won't be processed.

One example of application failing is scrcpy under latest Fedora.

here is a test case showing the problem in different scenarios:

https://gist.github.com/fernandoherreradelasheras/ec2f3cbf57f38ba876148493ca1f7cf6

- 0: start pushing events without the wayland window shown -> No events at all will be processed
- 1 and 2: push events after window is shown -> Some events will be properly processed but at some point WaitEvent will block again for a while
- 3: using SDL_PollEvent -> works fine.

**Comment by slouken** [comment]
@christianrauch, @flibitijibibo, can you take a look?

**Comment by flibitijibibo** [comment]
Part of me wants to just move the dispatch call to after our event processing, but the root of the problem is that SDL and libdecor fighting over the same events... similar to how we probably should have controlled the toplevel, I wonder if it would make sense to have libdecor hook into application event handlers so that we can pass events to libdecor so that it all happens in one loop instead of two.
