### ISSUE TITLE
Is it safe to SDL_Init some subsystems on a different thread?

### ISSUE THREAD

**Issue by TylerGlaiel** [libsdl-org/SDL#6215]
When profiling startup times I noticed that SDL_JoystickInit and SDL_HapticInit are taking a fairly significant amount of time, so I'd like to do those on the loading thread if possible (otherwise these delay the ability for me to show my loading screen for ~500ms or so), but the documentation isn't clear about whether or not it is safe to call SDL_InitSubSystem on a separate thread (for systems other than video/events)

**Comment by icculus** [comment]
We spoke about this briefly on Twitter, and I definitely want @slouken to chime in here, too, but my current take is that SDL_INIT_VIDEO _has to_ happen on the main thread, but it's extremely likely that SDL_INIT_JOYSTICK/SDL_INIT_GAMECONTROLLER does _not have to_ for most (if not all) platforms.

Since it's safe to init more than once with different flags, you can init the video in the main thread at startup, and then spin a thread that calls SDL_Init(SDL_INIT_JOYSTICK) from a background thread.

All of that being said, I _think_ that SDL sends SDL_JOYDEVICEADDED events for everything it sees connected at startup, so perhaps the correct thing to do here is fix SDL to be async internally, so joysticks can take as long as they want to warm up, and the events will arrive when they are ready, and SDL_Init shouldn't block waiting for them. This would probably have to be a hint, though, since there are likely many games that don't care if startup blocks for several hundred milliseconds and don't check for the event, and would absolutely do the wrong thing if SDL_NumJoysticks() suddenly started reporting zero for the first second of runtime.

Another option on your end: call SDL_Init(SDL_INIT_VIDEO | SDL_INIT_JOYSTICK), so this still blocks, but it blocks before there's a window at all, which looks more like normal startup processing than the loading screen pausing for awhile in-between frames. I know that's a cop-out, but it might be the easiest solution in the short term.

**Comment by slouken** [comment]
@icculus is right on the money here.

Are you able to profile and see where it's taking that time? My understanding is that most of the time is spent in Windows device enumeration code inside system DLLs, but it would be helpful to know if something else is going on here.

**Comment by slouken** [comment]
It should be safe as long as you do video initialization beforehand (so event initialization isn't done asynchronously) and you don't call any SDL joystick functions until it's complete.
