### ISSUE TITLE
Invalid keysym on Wayland when swapping escape and caps lock

### ISSUE THREAD

**Issue by quyykk** [libsdl-org/SDL#6256]
If I use the xkb option `caps:swapescape` on Wayland to swap the escape and caps lock key, SDL emits the wrong keycode for the caps lock key.

Here's the output of the `checkkeys.c` program. I pressed escape once and then caps lock:

```
INFO: Key pressed :  scancode 41 = Escape, keycode 0x40000039 = CapsLock  modifiers: CAPS
INFO: Key released:  scancode 41 = Escape, keycode 0x40000039 = CapsLock  modifiers: CAPS
INFO: Key pressed :  scancode 57 = CapsLock, keycode 0x40000039 = CapsLock  modifiers: (none)
INFO: Key released:  scancode 57 = CapsLock, keycode 0x40000039 = CapsLock  modifiers: (none)
```

Notice how the keycode for the CapsLock scancode isn't Escape. Every other program correctly recognizes the caps lock key as the new escape key. This problem doesn't occur on X11.

SDL 2.24.0 on Arch Linux, using Sway.

**Comment by flibitijibibo** [comment]
I believe this may have to do with modifiers being separate from "normal" keys - those come in separate events so we have to wedge it into the same system as the other keys:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L1193-L1198

I would expect the compositor to handle this though, but it's been a while since I've been in this part of the driver.

**Comment by Kontrabant** [comment]
The remapping mechanism requires that remapped key be in the XKB KeySym → SDL keycode table, and Escape was missing.

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L1193-L1198

The linked pull adds the Escape key to the table, so caps:swapescape will work now.  It adds NumLock as well, as there are options such as caps:numlock that can remap the NumLock key, which was also absent and caused the mapping to not be applied.
