### ISSUE TITLE
Keyup prevents autorepeat on other key in Wayland  

### ISSUE THREAD

**Issue by schauveau** [libsdl-org/SDL#6267]
When using the wayland backend, the SDL_KEYDOWN produced by the keyboard auto-repeat are not generated anymore after another key is released. 

I am on Debian, Sway with SDL 2.24.0

That behavior can be shown with this simple program  
[sdlkey.cc.txt](https://github.com/libsdl-org/SDL/files/9610674/sdlkey.cc.txt)

Steps to reproduce:

1. compile and run the program with `SDL_VIDEODRIVER=wayland`
2. press the 'a' key to generate multiple `KEYDOWN 97` events.
3. press the 'b' key to generate multiple `KEYDOWN 98` events.
4. release the 'a' key.  

A `KEYUP 97` event is generated (so far so good) but nothing else even though the 'b' key is still pressed.   

When using the X11 driver, some `KEYDOWN 98` events are still produced after the `KEYUP 97`.

I noticed that issue in Cataclysm DDA. See https://github.com/CleverRaven/Cataclysm-DDA/issues/61154

**Comment by Kontrabant** [comment]
I was able to reproduce this.  The issue is that the Wayland backend uses a boolean flag to set/unset the repeat system and it's cleared as soon as _any_ of the pressed keys are released, even if the released key isn't the one being repeated.

The repeated key needs to be tracked and the repeat flag cleared only when that particular key is released.  I'll have a patch for it soon.
