### ISSUE TITLE
Joy-Cons exhibit double inputs

### ISSUE THREAD

**Issue by MalikTH** [libsdl-org/SDL#6367]
Hi, I've been redirected here by ES-DE's maintainer from the EmuDeck Discord.

Nintendo Switch Joy-Cons exhibit double inputs. This happens with both single Joy-Cons used horizontally, and with two Joy-Cons connected as a pair.

Testing was done on a Steam Deck in gaming mode, and the Joy-Cons were managed using Steam Input.

**Comment by leonstyhre** [comment]
Just some additional information:

In the ES-DE 1.2.6 AppImage the bundled SDL library is the pretty ancient 2.0.10 and using this release the controllers work correctly, but only if plugged in after the application has already been started.

In the latest 2.0.0-alpha release which comes bundled with SDL 2.24.0 the double input has started to occur. As I don't have these controllers myself I can't test it, so not sure at what SDL release the problem was introduced.

To clarify, it's not a general issue with double input in ES-DE 2.0.0 as I've tested with a number of different controllers and other people have as well, it seems to be a specific issue with the Joy-Cons. Normally when these types of double input occurs it's with wireless controllers that register themselves twice with the application with different GUIDs. And as ES-DE auto-configures all controllers it seems as if there is double input from a single controller although that's not the case. But as I don't have access to this specific controller I can't test and confirm whether it's the same problem in this case. @MalikTH has tried to enable a setting in ES-DE to ignore input from all but the first controller, and as that seems to resolve the problem it's very likely that double devices are indeed reported by SDL.

A further comment is that as this issue has been seen on the Steam Deck, it could be that the Steam virtual controller is causing the problem somehow. I have tested 2.0.0 on the Steam Deck with other controllers though without any issues.

Input is handled by the SDL GameController API in ES-DE.

**Comment by slouken** [comment]
Thanks for the info!

**Comment by slouken** [comment]
How are you launching ES-DE? I tried using a Joy-Con with other Steam games and it works fine.

It's a known issue that desktop apps see two controllers when Steam is running, because Steam is providing an emulated controller and applications that aren't launched by Steam aren't getting the hint to ignore one of them.

**Comment by slouken** [comment]
My hypothesis is that you're not launching EmuDeck from Steam, and that if you add that as a non-Steam game and launch it from Steam that it will work correctly.

**Comment by leonstyhre** [comment]
Interesting, the only problem I had with double input when running Steam in the background while launching ES-DE outside of Steam is that by default Steam will generate both controller events and keyboard events unless you disable the "Desktop Configuration" setup. But that applies to any application, opening a text editor and moving the thumbsticks for instance will move the cursor unless you disable this functionality. I have not seen issues with the double devices being an issue otherwise.

I've just tested this with an Xbox 360 controller (on Ubuntu) and it does register as two devices when I launch ES-DE outside of Steam:
```
Oct 10 22:33:30 Info:   Added controller with default configuration: "X360 Controller" (GUID: 030000005e0400008e02000010010000, instance ID: 0, device index: 0)
Oct 10 22:33:30 Info:   Added controller with default configuration: "Steam Virtual Gamepad" (GUID: 03000000de280000ff11000001000000, instance ID: 1, device index: 1)
```

That does however not cause double inputs in ES-DE, I only see events for the 0 device (event.cdevice.which)
If I launch ES-DE via Steam then only the Steam Virtual Gamepad device is added, but the application/input behaves identically.

I think the Joy-Con issue is something else, I have heard about similar problems with some third party wireless controllers on Windows for instance, but I'm not sure if it's a lower level driver issue or problems with SDL as I don't have any such problematic devices to test with unfortunately.

In the past this similar problems occured with DualShock 4 controllers on macOS, where it registered as two devices and you had to fool it by plugging in the USB cable, turning on the controller and then unplugging the cable which disabled one of the devices. That was fixed when upgrading to Monterey so it was definitely a OS/driver issue and not an SDL issue.

Let's see what @MalikTH says regarding how he's running ES-DE (via Steam or outside Steam).

**Comment by slouken** [comment]
Also, the controller log, as you showed above for the Xbox 360 controller, would be helpful.

**Comment by leonstyhre** [comment]
Sorry, what do you mean with controller log?

**Comment by slouken** [comment]
This info:
```
Oct 10 22:33:30 Info:   Added controller with default configuration: "X360 Controller" (GUID: 030000005e0400008e02000010010000, instance ID: 0, device index: 0)
Oct 10 22:33:30 Info:   Added controller with default configuration: "Steam Virtual Gamepad" (GUID: 03000000de280000ff11000001000000, instance ID: 1, device index: 1)
```

**Comment by leonstyhre** [comment]
I just did a brief test with the closest thing I have to a Joy-Con pair and that's the Nintendo Switch Pro Controller. If I enable that as a Steam controller it does indeed generate double inputs in ES-DE if it's launched outside of Steam. But that's due to both controller and keyboard events being generated by Steam by default. If I go into Steam's Controller->DESKTOP CONFIGURATION settings and disable all button to keyboard mappings then there are no longer any double input in ES-DE.

**Comment by MalikTH** [comment]
I'm launching ES-DE from Steam, yes. I added ES-DE to Steam, went back to Gaming Mode, paired my Joy-Cons, and launched it in Gaming Mode.

Where would I find the controller log?

**Comment by leonstyhre** [comment]
The log location is mentioned in my message above, but please run ES-DE with the --debug flag to also see the individual button presses that gets registered, that would be very helpful.

**Comment by MalikTH** [comment]
[es_log.txt, controller log starts at line 508](https://cdn.discordapp.com/attachments/629448839966752783/1029181507245441124/es_log.txt)

Seems like it picks up both Steam Virtual Gamepad inputs _and_ Joy-Con inputs. This doesn't happen with either my 8bitdo Pro 2 or my Switch Pro Controller - they just show Steam Virtual Gamepad which I'm assuming is the expected behavior.

**Comment by slouken** [comment]
I'll take a look, thanks!

**Comment by slouken** [comment]
This is a Steam bug, fixed for the next update. Thanks!

**Comment by leonstyhre** [comment]
Perfect, thanks for looking into the issue and great to hear that it's getting resolved!
