### ISSUE TITLE
Green screen showns with D3D12/OPENGL while D3D11 works fine.

### ISSUE THREAD

**Issue by ivenstone** [libsdl-org/SDL#6376]
[rel.zip](https://github.com/libsdl-org/SDL/files/9755281/rel.zip)
To reproduce this.

In the command line, run "ffplay.exe -disp_device 2 your_video_file.mp4"
D3D12 is enabled and green screen showns.

In the command line, run "ffplay.exe -disp_device 3 your_video_file.mp4"
OPENGL is enabled and green screen showns.

In the command line, run "ffplay.exe -disp_device 1 your_video_file.mp4"
D3D11 is enabled and the first frame of the video showns.

**Comment by slouken** [comment]
So there are two issues here.

The first was a bug in the D3D12 code for my last fix, I needed to actually execute the pending commands in the command buffer instead of flushing them. That's fixed in https://github.com/libsdl-org/SDL/commit/df1bd07dee4e167bec5ac8b606461f2007bc7b10.

The second is more critical, you need to perform all your graphics operations in a single thread. Specifically, the main thread has the OpenGL context current, and when you try to upload the YUV texture on a separate thread, setting the OpenGL context current on that thread fails because it's already current on the main thread.

Depending on the platform, trying to do graphics operations on a separate thread could work, could fail, and could cause crashes with multi-threaded access to shared resources.

I recommend modifying ffplay to queue frames to the main thread and do the upload there before the present.
