### ISSUE TITLE
I got an error when pressing my Fn key

### ISSUE THREAD

**Issue by pacstah** [libsdl-org/SDL#6388]
I got an error when pressing ONLY my Fn key which stated I had to report it here, so here it is…

```The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 151 (143), X11 KeySym 0x1008FF2B (XF86WakeUp).```

**Comment by DanielGibson** [comment]
You're probably using a Thinkpad (or other Lenovo Laptop)?

The Fn key by itself *shouldn't* generate any key event (the keyboard controller should only generate ones when pressing it together with another key, maybe for "volume up" or whatever the combination is supposed to mean on the specific keyboard) - and on most keyboards it doesn't.
OTOH, https://bugs.launchpad.net/ubuntu/+source/hotkey-setup/+bug/287428/comments/27 argues that it's ok that this key generates XF86Wakeup, as pressing it *does* wake the machine up when it's suspended.

Anyway, IMO it would make sense for SDL to silently ignore XF86WakeUp instead of showing an error.

**Comment by pacstah** [comment]
Hi, thanks! It is actually a Thinkpad..!

Thanks for clearing it up..

Cheers!

**Comment by slouken** [comment]
The latest SDL will no longer print a message when this key is pressed, thanks!

**Comment by Dmitri-Gee** [comment]
Hey, I got an error for pressing a key.
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 248 (240), X11 KeySym 0xFFCA (F13)
I am using a Chromebook.
