### ISSUE TITLE
Test lib appears in Vulkan SDK

### ISSUE THREAD

**Issue by lunarpapillo** [libsdl-org/SDL#6406]
We're preparing for **Vulkan SDK 1.3.231.0** which will include the latest `release-2.24.1` of **SDL**.

There are a few unexpected changes that we'd just like to confirm are intended.  These files used to ship with **SDL** and no longer appear to be present.  This is correct, yes?
```
- SDL2,Include\SDL2\SDL_config_android.h
- SDL2,Include\SDL2\SDL_config_emscripten.h
- SDL2,Include\SDL2\SDL_config_iphoneos.h
- SDL2,Include\SDL2\SDL_config_macosx.h
- SDL2,Include\SDL2\SDL_config_minimal.h
- SDL2,Include\SDL2\SDL_config_os2.h
- SDL2,Include\SDL2\SDL_config_pandora.h
- SDL2,Include\SDL2\SDL_config_windows.h
- SDL2,Include\SDL2\SDL_config_winrt.h
```

And these new files appeared in **SDL**.  These are intended to be shipped with the **Vulkan SDK**, yes?  I'm particularly curious about the `SDL2_test.lib` library and the **CMake** files, which are somewhat surprising:
```
+ SDL2,Include\SDL2\SDL_guid.h
+ SDL2,Lib32\SDL2_test.lib
+ SDL2,Lib\SDL2_test.lib
+ SDL2,cmake\SDL2\SDL2testTargets-relwithdebinfo.cmake
+ SDL2,cmake\SDL2\SDL2testTargets.cmake
```

**Comment by madebr** [comment]
> We're preparing for **Vulkan SDK 1.3.231.0** which will include the latest `release-2.24.1` of **SDL**.
> 
> There are a few unexpected changes that we'd just like to confirm are intended. These files used to ship with **SDL** and no longer appear to be present. This is correct, yes?

Yes, CMake has 3 `SDL_config.h`'s:
- [`SDL_config.h.cmake`](https://github.com/libsdl-org/SDL/blob/dfbb93dd0c4bcdea2a3edc0e3cb0f5dae153d16e/include/SDL_config.h.cmake): converted into `SDL_config.h` by CMake
- [`SDL_config.h.in`](https://github.com/libsdl-org/SDL/blob/dfbb93dd0c4bcdea2a3edc0e3cb0f5dae153d16e/include/SDL_config.h.in): converted into `SDL_config.h` by autotools
- [`SDL_config.h`](https://github.com/libsdl-org/SDL/blob/dfbb93dd0c4bcdea2a3edc0e3cb0f5dae153d16e/include/SDL_config.h) used by MSBuild, XCode and Android.mk. This one includes `SDL_config_xxx.h` files for the various platforms.

Because the `SDL_config.h` generated by autotools and CMake  does not include `SDL_config_xxx.h` files, these are no longer installed.

> And these new files appeared in **SDL**. These are intended to be shipped with the **Vulkan SDK**, yes? I'm particularly curious about the `SDL2_test.lib` library and the **CMake** files, which are somewhat surprising:

`SDL2_test` is a test automation library used by SDL itself and also SDL_image.
Installation of this library has been added in the latest release. (autotools already did this)

> 
> ```
> + SDL2,Include\SDL2\SDL_guid.h
> + SDL2,Lib32\SDL2_test.lib
> + SDL2,Lib\SDL2_test.lib
> + SDL2,cmake\SDL2\SDL2testTargets-relwithdebinfo.cmake
> + SDL2,cmake\SDL2\SDL2testTargets.cmake
> ```

I _think_ this is a bug with your packaging.
You can't just overwrite `SDL2*-.cmake` of a 32-bit install prefix with a 64-bit prefix (and vice versa).
`SDL2ConfigVersion.cmake` tests for pointer size (32-bit vs 64-bit),
and the SDL2xxxTargets-relwithdebinfo.cmake` contain relative paths to the libraries.

You can check the working of the sdl2 cmake support with the [cmake test project](https://github.com/libsdl-org/SDL/blob/dfbb93dd0c4bcdea2a3edc0e3cb0f5dae153d16e/cmake/test/CMakeLists.txt):

```
> cmake -S %PATH_TO_SDL%/cmake/test -B sdl_test_32 -G "Visual Studio 17 2022" -A Win32 -DCMAKE_PREFIX_PATH="%PATH_TO_VULKAN_SDK%"
> cmake --build sdl_test_32

> cmake -S %PATH_TO_SDL%/cmake/test -B sdl_test_64 -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="%PATH_TO_VULKAN_SDK%"
> cmake --build sdl_test_64
```
On of both should fail because it cannot find an SDL2 with correct "bitness".

**Comment by lunarpapillo** [comment]
> I *think* this is a bug with your packaging.

I think you are likely correct.  We have routinely assumed that `cmake` files were not bitness-dependent.  That looks to be incorrect... we're investigating separately.  Thanks for your insights.

**Comment by madebr** [comment]
@lunarpapillo 
See https://github.com/libsdl-org/SDL/pull/6415 for a possible fix for this issue.

**Comment by lunarpapillo** [comment]
> See #6415 for a possible fix for this issue.

And thank you for this as well... :-)
