### ISSUE TITLE
Too frequent resizes under Wayland

### ISSUE THREAD

**Issue by Guldoman** [libsdl-org/SDL#6451]
According to the libdecor maintainer (https://gitlab.gnome.org/jadahl/libdecor/-/issues/37#note_1571696), throttling resizes under Wayland is needed for smooth resizing.

Limiting them to 1 per frame should be enough, but there could be problems with high refresh rate monitors, so a more complex heuristic may be needed.

For example limiting them to 1 every 16 ms results in this:

[Resize throttling](https://user-images.githubusercontent.com/2798487/198261781-398fe8e6-a73e-4c31-be9e-df3504eddd70.webm)

Bad hack:
```diff
diff --git a/src/video/wayland/SDL_waylandwindow.c b/src/video/wayland/SDL_waylandwindow.c
index 3c938bd53..3db7bbd87 100644
--- a/src/video/wayland/SDL_waylandwindow.c
+++ b/src/video/wayland/SDL_waylandwindow.c
@@ -34,6 +34,7 @@
 #include "SDL_hints.h"
 #include "../../SDL_hints_c.h"
 #include "SDL_events.h"
+#include "SDL_timer.h"
 
 #include "xdg-shell-client-protocol.h"
 #include "xdg-decoration-unstable-v1-client-protocol.h"
@@ -2084,6 +2085,11 @@ Wayland_HandleResize(SDL_Window *window, int width, int height, float scale)
     const int old_drawable_width = data->drawable_width;
     const int old_drawable_height = data->drawable_height;
 
+    static Uint32 last = 0;
+    Uint32 now = SDL_GetTicks();
+    if (!SDL_TICKS_PASSED(now, last+16)) return;
+    last = now;
+
     /* Update the window geometry. */
     window->w = width;
     window->h = height;
```

**Comment by Kontrabant** [comment]
This was fixed upstream in Mutter: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2652

It sounds like it should eventually be backported to 42, where it was originally introduced.

**Comment by flibitijibibo** [comment]
Was going to say, this sort of sounds like a compositor issue - the compositor ultimately handles all presentation, so it should also handle resize buffering as well. The application will only care about one window size per frame at most; any more would be asking the client to do extra work for no benefit. (Inversely, we on the client side _should_ be better about not doing programmatic resizes too much, but that's going to have to be fixed in SDL3...)

Marking as NOTABUG for now, would be good to get confirmation from the compositor side that we're on the right track before closing.

**Comment by Guldoman** [comment]
I can confirm that applying the upstream mutter patch on top of mutter 42.6 makes resizing much smoother.

**Comment by flibitijibibo** [comment]
Let's see if we can't push for this to be in 42.7... if not we can reopen and see what the best workaround is.
