### ISSUE TITLE
Window needs to be redrawn to update libdecor status

### ISSUE THREAD

**Issue by Guldoman** [libsdl-org/SDL#6461]
When a Wayland window that's using libdecor gains/loses focus, the decoration (active/inactive) doesn't change until the content of the window is updated.

Is this expected and the application is supposed to draw on focus gained/lost? Or should this be done by SDL automatically?

For example doing:
```diff
diff --git a/src/video/wayland/SDL_waylandwindow.c b/src/video/wayland/SDL_waylandwindow.c
index 3c938bd53..62d24e21b 100644
--- a/src/video/wayland/SDL_waylandwindow.c
+++ b/src/video/wayland/SDL_waylandwindow.c
@@ -921,6 +921,7 @@ decoration_frame_configure(struct libdecor_frame *frame,
      */
     Wayland_SetWindowResizable(SDL_GetVideoDevice(), window,
                                window->flags & SDL_WINDOW_RESIZABLE);
+    SDL_UpdateWindowSurface(window);
 }
 
 static void
```
is enough to solve the problem, but this is just a hack.

**Comment by flibitijibibo** [comment]
I believe Wayland expects the application to continue presenting, since the compositor now handles surface suspension on behalf of applications - I would think libdecor would have a way to update its surfaces separately from us but it wouldn't surprise me if they only updated when the application surface updates first.
