### ISSUE TITLE
How to include SDL in c++ executable.

### ISSUE THREAD

**Issue by Kostia06** [libsdl-org/SDL#6496]
Hello everyone, I hope you are doing great.  I am new to c++ and sdl. I try to build a simple game using sdl and when I compile it using MakeFile it works and run the executable, it works perfectly on my mac, but I transfer the same executable into another mac it says it can't find "sdl". My question is how to include sdl in my execiutable. I am sorry, if I wasn't clear enough. 

```
CC = g++
CFLAGS = -c -std=c++23 -g 
LDFLAGS = -g lib/SDL2 lib/SDL2_image lib/SDL2_ttf `sdl2-config --cflags` `pkg-config sdl2_image --cflags` `pkg-config sdl2_ttf --cflags` 

SRC = ${wildcard src/* .cpp}
HDR = ${wildcard include/* .hpp}
OBJ = ${SRC:.c=.o}
EXEC = lang

all: ${SRC} ${OBJ} ${EXEC} 

${EXEC}: ${OBJ}
	${CC} ${LDFLAGS} $^ -o $@

%.o: %.c ${HDR}
	${CC} ${CFLAGS} $< -o $@


delete:
	del /f /usr/local/bin/soy-lang

install:
	make
	cp ./lang /usr/local/bin/soy-lang

clear:
	rm src/*.o ${EXEC}

```

**Comment by vkedwardli** [comment]
You need to link to a static library (e.g. libSDL2.a).
If both libSDL2.dylib and libSDL2.a exist in the same directory, dynamic library will be linked first unfortunately

**Comment by slouken** [comment]
You can link statically as @vkedwardli mentioned, or you can include the SDL dylib with your application. In order to run on a Mac you probably need to build an application bundle, and you can include SDL as a framework in that.

This is better discussed on the SDL discourse, so other people can contribute to the discussion, so I'm closing it here for now.
https://discourse.libsdl.org/c/sdl-development/6
