### ISSUE TITLE
CommitWindowChanges

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6646]
> Throwing this out there because it's something I consistently ran into while working on Wayland, and is a consistent pain point for other backends like X: The SDL_Window API spec should be modified to make all changes **buffered**, with a CommitWindowChanges call to push everything at once.
>
> This fixes the main problem we've been having lately, which is that the order of window calls can finally stop mattering and SDL can enforce consistent behavior without having to fight the OS as much. On top of being a pretty major bugfix (see the numerous issues for this, usually it's when modifying a window size after leaving fullscreen) it's also an optimization; Wayland for example has to commit the window surface _every time a call is made_, while in reality we shouldn't have to do it more than once (or twice if you count presentation) per frame. Right now compositors _hate_ us for doing it like this, and when you actually look at the interaction at a low level it's easy to see why (see #4563).
>
> This is similar to the old SetVideoMode without _forcing_ SetVideoMode - someone could make multiple CommitWindowChanges calls if they absolutely needed to, while still knowing the consequences of not optimizing the batch of changes.

_Originally posted by @flibitijibibo in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1091891558_

**Comment by slime73** [comment]
Here's a drastic thought: if that's a good direction, should we remove all window-modifying *functions* and replace them with a new one which takes a struct containing all necessary setup? There could be an extra getter function to populate that struct when you just want to change some of it rather than all of it.

It would avoid confusion when someone forgets to call the Commit API after calling the other Set functions (since that scenario wouldn't be possible anymore).

**Comment by flibitijibibo** [comment]
I think that'd be good; the only question is how to prepare the struct... it's easy to add new functions, not so much struct members. Do we want to lean in window flags to do the heavy lifting or should we give the struct a bunch of padding just in case?

**Comment by slime73** [comment]
Maybe this is overcomplicating things but I wonder if it makes sense to combine multiple approaches: have a bunch of padding in the main struct to allow for growth, and also have something at the end to allow for extension when there's no more growth.

---

With this single function approach, there will be situations where one part of it can fail on some platforms, right? I wonder what should happen in terms of error-reporting and also with setting the rest of the state, in that case. It also might be harder to verify each backend's code is applying all the state it should be (especially if there are additions in the future), since there'd be a lot at once.

**Comment by icculus** [comment]
This is being discussed in #7907, so I'm going to close this as a duplicate.
