### ISSUE TITLE
Wayland viewport issue with fractional scaling and explicit client side fullscreen resolution 

### ISSUE THREAD

**Issue by davidedmundson** [libsdl-org/SDL#6707]
If we run an SDL wayland app under fractional scaling and a path where the client is explicitly setting a full screen mode

i.e
waylandwindow.c
GetFullScreenDimensions
93        if (window->fullscreen_mode.w != 0 && window->fullscreen_mode.h != 0) {

We get a cropped viewport with half the view offscreen. Controls under the mouse do not match up.

Test case:
Open supertuxkart, 
Under options choose fullscreen and explicitly select a resolution

Note that this happens with or without the wp-fractional-scale-v1 protocol, it exists from where we have the current inferred size.

**Comment by davidedmundson** [comment]
It was obvious once I typed it out, I rubber-ducked myself

We set the viewport source here:

```
...  if (FullscreenModeEmulation(window)...

            SetDrawSurfaceViewport(window, data->drawable_width, data->drawable_height,
                                   output_width, output_height);
```
output_width isn't necessarily the buffer size even when fullscreen.

I think the easiest fix is to not set a viewport source. If it's unset we'll use the buffer size which is what we always want.
I can confirm commenting out `wp_viewport_set_source` fixes it and we'll get to kill a few lines of code.

Unless there's a reason not to?

**Comment by flibitijibibo** [comment]
CC @Kontrabant who wrote the viewport work - the fix makes sense to me at least!

**Comment by Kontrabant** [comment]
> supertuxkart

Does it reproduce in anything else?  This sounds like #5941, which was/is a bug in supertuxkart itself.  Their handling of mixed-DPI setups is broken on basically every platform.

**Comment by Kontrabant** [comment]
Looking at the supertuxkart code, it looks like there have been some improvements since the last time this came up as they are now querying the backbuffer sizes of the window itself and updating after window event changes (good!), but they're still multiplying something by the highest scale factor of all the desktops somewhere that they shouldn't be and making their drawable surface too big, probably when creating it's Vulkan or GL render targets.

David's suggestion would fix the issue on Wayland, but supertuxkart is still doing something wrong internally.  I don't like the idea of hiding bad application behavior on one specific platform, as someone developing on Wayland might not realize that they are doing something wrong until someone runs their application on another platform and things fall apart.

**Comment by flibitijibibo** [comment]
Ah, I thought we'd seen this before... yeah if this is just the STK DPI bug then this is actually "correct", provided other apps are still okay.

**Comment by Kontrabant** [comment]
Yeah, I played around with it a bit more and it's definitely still very buggy on scaled and mixed-DPI setups.  The Vulkan driver does display correctly (in spite of telling me that the latest Nvidia drivers are too old), but according to the resolution list it's still applying the 1.25 scale from the second display to the resolution of the unscaled primary display, so it's still doing something with a global scale factor somewhere.

Like the last time, have to rule `NOTOURBUG` on this.

**Comment by slouken** [comment]
What about the rubber ducky and the reasonable change?

**Comment by flibitijibibo** [comment]
It seemed to make sense assuming valid behavior, but the issue is that the application in question is misusing DPI - so while we could patch over this ourselves it would make behavior inconsistent compared to, say, Cocoa/UIKit.

**Comment by davidedmundson** [comment]
On reflection (with a different better duck) my analysis was wrong. The source is the `drawable_width` which should be right even in this path. 

Lets consider this a dupe of 5941 until there's some evidence otherwise.
