### ISSUE TITLE
SDL_GetPowerInfo() reports wireless mouse's battery info

### ISSUE THREAD

**Issue by taep96** [libsdl-org/SDL#6835]
Osu!Lazer uses `SDL_GetPowerInfo()` to get battery percentage and show a warning if it's too low - https://github.com/ppy/osu/discussions/21640:

![image](https://user-images.githubusercontent.com/64481039/208267772-9de4a7e2-a0e1-45a3-b00c-e7f73f9e441d.png)

I'm running a battery-less PC, so this warning is incorrect. The only battery-powered device connected to my PC is a wireless mouse I checked if it's battery percentage affects it, and it does! I charged it and the warnings were gone, and when it discharged to 25% they appeared again.

![image](https://user-images.githubusercontent.com/64481039/208267541-af89d686-611c-48e1-a8b9-4f3e15968451.png)

I'm not familiar with SDL so I'm not sure about how this should be fixed, looks like `SDL_GetPowerInfo()` assumes system has only one power supply, so I guess this should be changed.

**Comment by icculus** [comment]
That's pretty funny! I'll take a look at this.

**Comment by icculus** [comment]
I pushed a possible fix for this (we were looking for the string "device" but your screenshot has it capitalized as "Device").

If that doesn't resolve the issue, I have a more aggressive patch that rejects any power devices with identifiers that start with "hidpp_" (which is logitech's HID communication protocol). We might need this if it turns out you're using our D-Bus codepath and the existing checks didn't fix it there.

**Comment by taep96** [comment]
@bdach In case your weren't subscribed

**Comment by slouken** [comment]
@icculus, are you merging fixes from SDL2 to main?

**Comment by icculus** [comment]
I'm waiting to see if this is sufficient before I merge this one.

**Comment by bdach** [comment]
Maintainer of upstream project where this came up here - I'm not entirely sure why I was tagged in here by @taep96 or what action is expected of me, but if it helps I'll ask to bump SDL on our side so that it can be verified that the fix fixes once we push out our next release.

**Comment by icculus** [comment]
> Maintainer of upstream project where this came up here - I'm not entirely sure why I was tagged in here by @taep96 or what action is expected of me, but if it helps I'll ask to bump SDL on our side so that it can be verified that the fix fixes once we push out our next release. We build the SDL binaries we ship from source anyways, so no need to get any minor release out or anything.

That would be _super_ helpful, thank you!

**Comment by taep96** [comment]
I don't think it's released in osu yet and I'm not sure how to test it manually

**Comment by bdach** [comment]
We haven't pushed out a new user-facing release of our project yet, for whatever's worth, but the change has trickled down to our [current `master`](https://github.com/ppy/osu/tree/master). If @taep96 is able to build and test that, then that should do the trick.

Otherwise probably need a while longer for us to put out a public release. Shouldn't be overly long, we aim for a release every few weeks, but I don't have a concrete timeline to give right now.

**Comment by taep96** [comment]
I was able to build and run it but will have to wait for my mouse to discharge to test it

**Comment by icculus** [comment]
If it doesn't fix the issue, don't charge the mouse, I have a second patch ready to go.  :)

**Comment by taep96** [comment]
Not getting it on 2023.524.0 (May 24th release) so I guess it's fixed?

**Comment by icculus** [comment]
I'm willing to call that Good Enough.  :)

**Comment by icculus** [comment]
Cherry-picked to SDL3, too, in 95f244598bb17455dc7651b0f588965e5c351086.
