### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by mimu5583** [libsdl-org/SDL#6848]
My make file consists of: 
all:
	g++ -I src/include -L src/lib -o main main.cpp -l mingw32 -l SDL2main -l SDL2

I copied the dll file into the root directory of my project and copied the include and lib folders into a src folder in the root directory. Every time I try to run make I get the error saying that -lmingw32 is not found.  I am running on windows 10 x64.

**Comment by madebr** [comment]
`libmingw32.a` should be part of your mingw toolchain.
A well-configured mingw toolchain should have a lib folder that contains `.a` libraries for the Windows API (e.g. `libws2_32.a` for Windows networking).
The toolchain should be able to automatically find these files.

For SDL2, you can work around the need for `-lmingw32` by replacing it with `-Wl,--undefined=_WinMain@16>` for 32-bit x86, or `-Wl,--undefined=WinMain` for 64-bit x86.

But generally, your toolchain is broken and needs to be fixed because you are going to run into bigger issues.
