### ISSUE TITLE
SDL API consistency: public struct field naming

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#6955]
Fields in public structs in SDL use different naming conventions depending on the struct, when there are multiple words or acronyms.

Some examples:

`SDL_AudioCVT`: all lowercase, underscores between words:
https://github.com/libsdl-org/SDL/blob/324c0b76a0111f0955063ac657617708208963ea/include/SDL3/SDL_audio.h#L231-L236

`SDL_PixelFormat`: A mix of different casing styles, no underscores:
https://github.com/libsdl-org/SDL/blob/324c0b76a0111f0955063ac657617708208963ea/include/SDL3/SDL_pixels.h#L318-L325

`SDL_DisplayMode`: underscores between words in one field, no underscore in another field. All lower-case. Also the struct is unnamed (just the typedef is named):
https://github.com/libsdl-org/SDL/blob/324c0b76a0111f0955063ac657617708208963ea/include/SDL3/SDL_video.h#L53-L60

`SDL_TouchFingerEvent`: `windowID` has different casing than `fingerId` (although each is consistent with other uses of the same name in other places.)
https://github.com/libsdl-org/SDL/blob/324c0b76a0111f0955063ac657617708208963ea/include/SDL3/SDL_events.h#L500-L512

`SDL_SensorEvent`: underscore between words for `sensor_timestamp`:
https://github.com/libsdl-org/SDL/blob/324c0b76a0111f0955063ac657617708208963ea/include/SDL3/SDL_events.h#L532-L539

`SDL_MouseWheelEvent`: upper-case at the start of a second word:
https://github.com/libsdl-org/SDL/blob/324c0b76a0111f0955063ac657617708208963ea/include/SDL3/SDL_events.h#L336-L339

`SDL_MouseMotionEvent`: all lowercase with no underscores between words in `xrel` and `yrel`:
https://github.com/libsdl-org/SDL/blob/324c0b76a0111f0955063ac657617708208963ea/include/SDL3/SDL_events.h#L299-L306

It'd be nice if a particular style was settled on. I don't really have strong preferences but I suppose whichever is already the most common probably makes sense to choose.

**Comment by slouken** [comment]
I agree that we can be more consistent here. @icculus, thoughts?

**Comment by icculus** [comment]
Yeah, let's fix these up.

**Comment by slouken** [comment]
What should our convention be? I think most fields are lower case with underscores, but we have to opportunity to blow up the world here, if we want. :)

**Comment by slouken** [comment]
I like `objectID` personally for ID fields.

**Comment by 1bsyl** [comment]
seems there is no SDL_WindowID type! https://github.com/libsdl-org/SDL/pull/6985

looking at SDL code, we use ID for type. but not much  for parameter / struct fields.

**Comment by stianhoiland** [comment]
I don't know where you stand on this, but since you are considering blowing up the world, I at least want to mention it:

Generally (though not entirely) struct & function names are globally prefixed with SDL_ and use PascalCase.

In the CoreFoundation and Objective-C world (which I consider have _a lot_ in common with SDL), the type & function name casing is the same as SDL but the global prefix does not have a trailing underscore, which is a combination I personally find gooder™ looking: `SDLPascalCase`. On the other hand, I also think underscores go well with snake_case: `sdl_snake_case`.

Considering this, there are some typedefs like `Uint64` and co., as well as `SDL_bool`, which could also be re-cased for consistency.

Thoughts?

**Comment by Lokathor** [comment]
Struct fields all moving to snake_case would be my vote.

I have no strong opinion on type names, since you don't need to use those as much in the body of a function anyway.
