### ISSUE TITLE
Windows 10 sleep breaks wasapi audio

### ISSUE THREAD

**Issue by RaymondGrumney** [libsdl-org/SDL#7044]
Running on a Windows 10 21H2 machine.

Found using [EmulationStation Desktop Edition](https://es-de.org/).

After device goes to sleep and wakes up, audio/sound no longer plays for the program.

This seems to break when using WASAPI specifically.

Workaround that fixed the issue was to set environment variable:
SDL_AUDIODRIVER=dsound

**Comment by icculus** [comment]
This is working for me here with USB headphones--loopwave just picks up where it left off when the system wakes up and I enter my password to access the desktop.

I'm wondering if your audio device is an HDMI display (because these can take awhile to reinitialize and/or they look like new devices on wake), but anything you can tell me about the hardware would be helpful here.

**Comment by j4reporting** [comment]
loopwave test  on  a  skylake NUC6i5SYH  system   GFX driver version 31.0.101.2111
Intel Display Audio  via DisplayPort  (the same happens with HDMI) ,  no other Audio device is connected or available (i.e  USB head phone or head phone connected to the 3.5mm audio out port (realtek HD audio))

```
C:\temp\SDL2_test>loopwave.exe

C:\temp\SDL2_test>INFO: Available audio drivers:
INFO: 0: wasapi
INFO: 1: directsound
INFO: 2: winmm
INFO: 3: disk
INFO: 4: dummy
INFO: Using audio driver: wasapi
ERROR: Couldn't open audio: WASAPI can't find requested audio endpoint: Element not found.

```

audio recovers with SDL_AUDIODRIVER=directsound 
audio does not recover with SDL_AUDIODRIVER=winmm     ( no error message is printed )

the same test  with a second audio device connected (head phone with a 3.5mm plug)  recovers audio..
the moment screen goes dark,  audio switches to the head phone  until the system finally enters  S3 Standby

**Comment by icculus** [comment]
I think this is the thing where the Intel's audio devices vanish for up to 8 seconds on HDMI changes (and perhaps DisplayPort too?).

That error string came from SDL_IMMDevice_Get, called by WASAPI_ActivateDevice.

I'm wondering if SDL_IMMDevice_Get should retry for up to 8 seconds if it can't find the endpoint on an otherwise-valid device ID, and see if it fixes things.

Outside of this bug, it's likely this _never_ blocks, and for this situation, it's better than failing...SDL_OpenAudioDevice() may block, or perhaps the audio thread freezes up until the device returns to normal.

But I don't know yet.

**Comment by j4reporting** [comment]
> I think this is the thing where the Intel's audio devices vanish for up to 8 seconds on HDMI changes (and perhaps DisplayPort too?).

Yes, it seems to be the same issue, the error string is identical.
DisplayPort is also affected, as each DP or HDMI port connected to the iGPU is assigned  an Intel Display Audio device in device manager. 


this issue is easily reproducable on any notebook with an Intel CPU ( Core  gen 6 - 10 ) ,  I reproduced this  with gen6 and gen8 CPUs on WIn10 (iGPU only). 

1. connect external display via DP, USB-C  or HDMI  and project  to the second screen only ( configure it as the main display is probably enough).
2. open sound control panel and set the intel display audio device as the default playback device
3. disable any other available playback devices   i.e.  the notebook's internal loud speakers. Intel Display Audio device should be the only enabled audio device.

**Comment by icculus** [comment]
This is an attempt at a fix; I still have to find a machine to test this on, though.

```diff
+    const Uint64 timeout = SDL_GetTicks64() + 8000;  /* intel's audio drivers can fail for up to EIGHT SECONDS after a device is connected or we wake from sleep. */
     HRESULT ret;
 
     SDL_assert(device != NULL);
 
-    if (devid == NULL) {
-        const EDataFlow dataflow = iscapture ? eCapture : eRender;
-        ret = IMMDeviceEnumerator_GetDefaultAudioEndpoint(enumerator, dataflow, SDL_IMMDevice_role, device);
-    } else {
-        ret = IMMDeviceEnumerator_GetDevice(enumerator, devid, device);
-    }
+    while (SDL_TRUE) {
+        if (devid == NULL) {
+            const EDataFlow dataflow = iscapture ? eCapture : eRender;
+            ret = IMMDeviceEnumerator_GetDefaultAudioEndpoint(enumerator, dataflow, SDL_IMMDevice_role, device);
+        } else {
+            ret = IMMDeviceEnumerator_GetDevice(enumerator, devid, device);
+        }
 
-    if (FAILED(ret)) {
-        SDL_assert(*device == NULL);
-        return WIN_SetErrorFromHRESULT("WASAPI can't find requested audio endpoint", ret);
+        if (FAILED(ret)) {
+            SDL_assert(*device == NULL);
+            if (ret == E_NOTFOUND) {
+                const Uint64 now = SDL_GetTicks64();
+                if (timeout > now) {
+                    const Uint64 ticksleft = timeout - now;
+                    SDL_Delay(SDL_min(ticksleft, 300));   /* wait awhile and try again. */
+                    continue;
+                }
+            }
+
+            return WIN_SetErrorFromHRESULT("WASAPI can't find requested audio endpoint", ret);
+        }
     }
     return 0;
 }
```

**Comment by j4reporting** [comment]
applied to the SDL2 branch
result: no audio and the audiosvc  service will use 1 cpu core  to 100%,  
no error  and it will not bail out after 8 seconds either

quakespasm  blocks at sound initialisation with this SDL2.dll

**Comment by icculus** [comment]
wait, dumb mistake in that patch, try this:

```diff
iff --git a/src/core/windows/SDL_immdevice.c b/src/core/windows/SDL_immdevice.c
index 831d9e7a0..8a398c64f 100644
--- a/src/core/windows/SDL_immdevice.c
+++ b/src/core/windows/SDL_immdevice.c
@@ -357,20 +357,34 @@ void SDL_IMMDevice_Quit(void)
 
 int SDL_IMMDevice_Get(LPCWSTR devid, IMMDevice **device, SDL_bool iscapture)
 {
+    const Uint64 timeout = SDL_GetTicks64() + 8000;  /* intel's audio drivers can fail for up to EIGHT SECONDS after a device is connected or we wake from sleep. */
     HRESULT ret;
 
     SDL_assert(device != NULL);
 
-    if (devid == NULL) {
-        const EDataFlow dataflow = iscapture ? eCapture : eRender;
-        ret = IMMDeviceEnumerator_GetDefaultAudioEndpoint(enumerator, dataflow, SDL_IMMDevice_role, device);
-    } else {
-        ret = IMMDeviceEnumerator_GetDevice(enumerator, devid, device);
-    }
+    while (SDL_TRUE) {
+        if (devid == NULL) {
+            const EDataFlow dataflow = iscapture ? eCapture : eRender;
+            ret = IMMDeviceEnumerator_GetDefaultAudioEndpoint(enumerator, dataflow, SDL_IMMDevice_role, device);
+        } else {
+            ret = IMMDeviceEnumerator_GetDevice(enumerator, devid, device);
+        }
 
-    if (FAILED(ret)) {
-        SDL_assert(*device == NULL);
-        return WIN_SetErrorFromHRESULT("WASAPI can't find requested audio endpoint", ret);
+        if (!FAILED(ret)) {
+            break;
+        } else {
+            SDL_assert(*device == NULL);
+            if (ret == E_NOTFOUND) {
+                const Uint64 now = SDL_GetTicks64();
+                if (timeout > now) {
+                    const Uint64 ticksleft = timeout - now;
+                    SDL_Delay(SDL_min(ticksleft, 300));   /* wait awhile and try again. */
+                    continue;
+                }
+            }
+
+            return WIN_SetErrorFromHRESULT("WASAPI can't find requested audio endpoint", ret);
+        }
     }
     return 0;
 }
```

**Comment by j4reporting** [comment]
this one works!  👍 

loopwave  picks up audio  after sleep -> wake cycle.   It continues playing audio after a change to desktop's  resolution or refresh rate. 

A quick test with quakespasm  was also successful.  Audio is initialized correnctly  and  will continue after every modeset.  Audio does not get out of sync.  no regression  so far.

**Comment by slouken** [comment]
Some style suggestions:
```c
if (SUCCEEDED(ret)) {
    break;
}
(remove assert)
if (ret == E_NOTFOUND) {
...
```

**Comment by icculus** [comment]
> Some style suggestions:

Yes, this is better, thanks.

Okay, this is in for SDL2 and SDL3. If anyone is bored and wants to make sure I didn't break this at the last moment, I'd appreciate it, but I'm already grateful that @j4reporting took the time to test _two_ separate patches here so quickly; this was massively helpful!
