### ISSUE TITLE
[SDL3] Make width/height-related parameters `unsigned`

### ISSUE THREAD

**Issue by TerensTare** [libsdl-org/SDL#7065]
In SDL2 (also in the current `main` branch), the parameters `w` and `h` of `SDL_Window` are marked as `int`. This causes the functions to add checks for whether these parameters are non-negative. That being said, I don't see any reason for why these parameters should be `int` in SDL3, but rather, should be `unsigned`.
I can make a PR related to this issue, but I wanted to consult with the community first to see if there's any reason for why these parameters should not change (I assume they haven't been changed before to keep backward compatibility).

Other stuff to be converted can be:
- width/height of `SDL_Renderer` and/or `SDL_Texture`
- `count` parameter of functions accepting arrays (maybe these should be `size_t` instead of just `unsigned`?)

**Comment by slouken** [comment]
@icculus, for discussion.

**Comment by madebr** [comment]
We have quite a few `-Wsign-compare` violations. Perhaps it's worth addressing these as part of signed/unsigned decisions.

**Comment by nfries88** [comment]
as a user, I have no issue with making function parameters unsigned for dimensions, because negative dimensions make no sense.

but for correct results, most of the use of those dimension variables need to use signed arithmetic - negative values *are* meaningful for coordinates, viewports, etc - so because C's integer conversion rules favor unsigned it would be a lot easier to keep them signed inside of structs and when returned by query functions.

just my two cents

**Comment by ericwa** [comment]
>  That being said, I don't see any reason for why these parameters should be int in SDL3, but rather, should be unsigned.

I'd also suggest leaving width/height signed; there's a C++ Core Guidelines entry for this: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-nonnegative

A blog post with more detail: https://hamstergene.github.io/posts/2021-10-30-do-not-use-unsigned-for-nonnegativity/

**Comment by 1bsyl** [comment]
@slouken some PR attempt

**Comment by slouken** [comment]
I think the consensus is to leave things as they are. @1bsyl has a separate PR to review other unsigned API usage.
