### ISSUE TITLE
How to set BT709 full range color conversion correctly in sdl2 ?

### ISSUE THREAD

**Issue by xfirefly** [libsdl-org/SDL#7083]
When rendering video frames with sdl2, the color is displayed incorrectly.
Even if SDL_SetYUVConversionMode(SDL_YUV_CONVERSION_BT709) is called;
the color is not displayed correctly.

Verify with yuv viewer, if the color conversion is set to BT709 Full Range, it is correct.

How to set BT709 full range color conversion correctly in sdl2 ?

---
 
<img width="795" alt="err" src="https://user-images.githubusercontent.com/475290/212476300-55b15b0b-59cb-46cd-b7c1-e1efc1ccd5dc.png">

---

<img width="775" alt="ok" src="https://user-images.githubusercontent.com/475290/212476303-3937dd9a-f029-4fa4-883d-6e5015a8c59d.png">

**Comment by Starbuck5** [comment]
If you need BT709 full range it looks like you'll need to introduce another conversion step using something like `libyuv`.

`I444ToARGBMatrix` / `I422ToARGBMatrix` / `I420ToARGBMatrix` with the "matrix" being `kYuvF709Constants` should get you the correct RGB information, you can upload that into a texture.

Alternatively you could try to add it to SDL, in `src/render` you can see the different rendering backends. The different backends all seem to have these implemented as shaders. You can see mentions of them in https://github.com/libsdl-org/SDL/blob/main/src/render/direct3d12/SDL_shaders_d3d12.h for example. It seems like it would be quite difficult to add a new conversion mode, because you'd have to update all the backends.

If you're trying to play a set video, the easiest way would be to re-encode into BT709 or BT601 non-full?

**Comment by xfirefly** [comment]
> If you need BT709 full range it looks like you'll need to introduce another conversion step using something like `libyuv`.
> 
> `I444ToARGBMatrix` / `I422ToARGBMatrix` / `I420ToARGBMatrix` with the "matrix" being `kYuvF709Constants` should get you the correct RGB information, you can upload that into a texture.
> 
> Alternatively you could try to add it to SDL, in `src/render` you can see the different rendering backends. The different backends all seem to have these implemented as shaders. You can see mentions of them in https://github.com/libsdl-org/SDL/blob/main/src/render/direct3d12/SDL_shaders_d3d12.h for example. It seems like it would be quite difficult to add a new conversion mode, because you'd have to update all the backends.
> 
> If you're trying to play a set video, the easiest way would be to re-encode into BT709 or BT601 non-full?

Many thanks , solved by using libyuv I420ToARGBMatrixFilter, but it seems a bit slow and needs to be optimized.
