### ISSUE TITLE
RenderPresent slow to return when vsync window is in background

### ISSUE THREAD

**Issue by JimmyDdotEXE** [libsdl-org/SDL#7114]
when using a window with a vsync enabled renderer, the SDL_RenderPresent function is slow to return when the window is fully behind another window

seems like maybe it's the renderer trying to limit the fps of a window that isn't being shown? but it's not an issue when the window is minimized

I'm running SDL 2.26.1 on Manjaro 22.0.0/Gnome 43.2 with Wayland

**Comment by Mangomm** [comment]
Yes, I also encountered this problem when I used:
_renderer = SDL_CreateRenderer(_window, -1,SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

After the program is minimized, the video delay will be very large. debug will get the result because SDL_RenderPresent is very time-consuming.

normal use time for SDL_RenderPresent function:
![image](https://user-images.githubusercontent.com/58781546/222626025-2689e18c-f44f-4d25-b60a-68114c5c6298.png)

abnormal use time for SDL_RenderPresent function(After the program is minimized):
![image](https://user-images.githubusercontent.com/58781546/222626136-ee3a89aa-e39b-41a1-9875-00f87af593e7.png)

My solution is, delete SDL_RENDERER_PRESENTVSYNC when call SDL_CreateRenderer.
![image](https://user-images.githubusercontent.com/58781546/222626240-19b3985c-2fff-460a-a9a0-ff91b63cb8ef.png)

I'm running SDL 2.26.1 on windows10.

**Comment by slouken** [comment]
We are scoping work for the SDL 3.2.0 release, so please let us know if this is a showstopper for you.

**Comment by Kontrabant** [comment]
This is an upstream Wayland issue that is currently being resolved with the forthcoming fifo and commit timing protocols (or maybe frog-fifo if those stall again). SDL does hack around this when the GL renderers are used to prevent presentation requests from blocking indefinitely, but, ultimately, upstream work is required for proper FIFO support on GL and Vulkan.

I think this can be closed, as SDL3 already only defaults to Wayland if the proper protocols for presentation are present, so there's really nothing more to do on the SDL side of things, as it's just a matter of waiting for upstream projects to fix things now.
