### ISSUE TITLE
SDL_GetMouseState() returns button mask of 0 on drag and drop.

### ISSUE THREAD

**Issue by kenrector** [libsdl-org/SDL#7115]
Using SDL 2.26 on Mac OSX 10.15 (Catalina) to process a drag and drop operation I find that SDL_GetMouseState() always returns 0, (buttonmask) when called after the window event SDL_WINDOWEVENT_ENTER.

That is,  the left mouse button is depressed on a selected file name in the finder window, the file name is then dragged into the SDL window, the event.type == SDL_WINDOWEVENT is reported with  window.event == SDL_WINDOWEVENT_ENTER when the drag passes the window edge.

On the SDL_WINDOWEVENT_ENTER a call to SDL_GetMouseState() always returns a button value of 0 even though the  button is depressed.

Subsequently, releasing the button causes the SDL_DROPFILE event to occur corrrectly.

On a non drag and drop button click the SDL_GetMouseState() returns the correct buttonmask value on the SDL_MOUSEBUTTONDOWN event.

**Comment by LiquidityC** [comment]
I tested this locally (on Ubuntu, Wayland, Gnome) and I'm getting different behavior from what you're getting.
In my case:

- The app reacts when the cursor enters or leaves the application window  **SDL_WINDOWEVENT_ENTER/SDL_WINDOWEVENT_LEAVE** (no buttons held)
- If any button is held down when the cursor enters the application window I don't get any event until the button is released. Upon which I get either a **SDL_DROPFILE** or **SDL_WINDOWEVENT_ENTER** depending on if I'm dropping a file or just holding the button. `SDL_GetMouseState()` returns 0 here since the button was released.
- If a button is held when leaving the window I get a **SDL_WINDOWEVENT_LEAVE** and `SDL_GetMouseState()`returns a "proper" mask.

I think SDL is very much at the mercy of the local window manager in these cases. So there might be limited options for a solution.

You can look at my test code here: [https://github.com/LiquidityC/sdl_testbed](https://github.com/LiquidityC/sdl_testbed)

**Comment by kenrector** [comment]
Linus,

<So there might be limited options for a solution.>

I'm unclear if someone is going to work on this.  Can you tell me what may happen next?

**Comment by LiquidityC** [comment]
> Linus,
> 
> I'm unclear if someone is going to work on this. Can you tell me what may happen next?


Oh. I'm labeled as a contributor but I have just recently started getting involved in SDL development (avid user for many years though) so I'm in no position to say what the next step is.

My best guess however. Is that this might be a problem that is out of scope for SDL.

Looking at the wayland implementation (my WM) for example. SDL registers a series of callback events to the cursor/pointer instance. And when these functions are called SDL triggers various `SDL_WINDOWEVENT_*`.
If wayland doesn't call the callback functions in certain cases there's not much that SDL can do about it.

Based on my experience I would assume the Mac API (which I don't know what it's called :worried:) functions in a very similar way. And if that is the case your problem might not be solvable.
I can't see that the behavior I'm seeing on wayland could be changed (fixed) at all for example.

Perhaps someone with direct knowledge could chime in here?

To fix your particular problem perhaps there's a workaround solution? If you can track the mouse position and you know where your window is perhaps you can monitor that to trigger the right code instead of expecting an 'enter/leave' event?

**Comment by slouken** [comment]
In the drop case, your application doesn't have mouse focus until the mouse button is released, at which point the button mask will be zero.

When you click on the window to give it focus, you also don't get the mouse button down, unless the hint SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH is set, to prevent accidentally triggering actions in the application when the user just wants to give it focus.

If you are relying on knowing the mouse state when the mouse is over the window but your application doesn't have mouse focus, you can use SDL_GetGlobalMouseState(), which should return the correct state of the buttons even when you don't have focus. Be careful though, you should respect the users' intentions with mouse focus and not respond to buttons held down when they don't expect it.

**Comment by kenrector** [comment]
Sam,

You said: <In the drop case, your application doesn't have mouse focus until the mouse button is released,>

In my earlier note I said: <Doing the Drag and Drop operation, I always get SDL_WINDOWEVENT_ENTER followed by the SDL_DROPFILE.> and I gave an example.

I reran that example and here are the results again.

Focus lost: 799x243 (0)
Focus gained: 733x363 (0)
Mouse enter: 733x363 (0)
Drop event!
dropped: 232x325 (0)
Mouse leave: 636x599 (0)
Focus lost: 636x599 (0)

Note that Focus gained and Mouse enter events both show the button mask is zero.  This is incorrect as the button is surely down otherwise the drop event wouldn't occur.

Then the Drop event occurs after moving the mouse further across the window.

It appears that the Focus and Enter events are not reported when the mouse crosses the frame border, that would be x coordinate 799, not 733.

I've run a lot of different sorts of test sequences using Linus's test and with printf in my application and the button mask is always zero.

**Comment by slouken** [comment]
That's correct, the button mask is always zero when the mouse enters the window. The button mask only changes for events that originate inside the application window.

**Comment by slouken** [comment]
Is there a reason you want different behavior, or is this just not what you expected?

**Comment by kenrector** [comment]
I looked for an event that originates inside the application window and SDL_MOUSEMOTION seemed like a likely prospect.  I added an event case for this to Linus's test code.  I found the following:

Focus gained: 671x119 (0)
Mouse enter: 671x119 (0)
motion: 671x119 (0)
motion: 588x203 (0)
dropped: 588x203 (0)

It appears that the button mask only changes when a button changes.   But perhaps there is a different event I could try?
 
To answer your question;  Yes and yes.  This is not what I expected, and I would like to have different behavior. 

I would like to have SDL_GetMouseState() reflect the actual current state of the mouse buttons, just as it does the position.

If that is impossible, then I'd like to see the SDL reference material more accurately describe the returned button state data and when it is not really the current state.

**Comment by slouken** [comment]
Your application doesn't have focus and doesn't receive mouse events while a drop operation is in progress. However in SDL3, there is a new event `SDL_EVENT_DROP_POSITION` that gives you the position of the drop in progress. You can also use SDL_GetGlobalMouseState() to get the state of the mouse even while you don't have focus.
