### ISSUE TITLE
Missing API to set window postion on a 2nd display

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7199]
It seems there is no API to explicitly set window position on a different display.
Like SDL_SetWindowPosition() at (x,y) and with an explicit displayId.

**Comment by slime73** [comment]
I think you can call `SDL_GetDisplayBounds` and add the resulting x and y values to what you'll use with `SDL_SetWindowPosition`. But it's probably a lot less intuitive than having an explicit display value, I suppose.

**Comment by 1bsyl** [comment]
I don't need this API specifically, but this should be provided.
Also maybe those should be removed: 
SDL_WINDOWPOS_UNDEFINED_DISPLAY()
SDL_WINDOWPOS_CENTERED_DISPLAY()

**Comment by 1bsyl** [comment]
yes, but this isn't really explicit 

something like this would make more sense:
```
SDL_SetWindowPosition(SDL_Window *window, int x, int y);
SDL_SetWindowPositionAndDisplay(SDL_Window *window, int x, int y, SDL_DisplayID displayID);
SDL_DisplayID SDL_GetWindowDisplay(SDL_Window *window);
```

**Comment by slouken** [comment]
SDL_SetWindowPosition() works in screen space, so you can move the window to any display, you just need to get the display bounds to see where it is.

SDL_SetWindowPositionAndDisplay() would take an x/y offset from the display origin, rather than working in screen space. This would be fairly easy to add, but how often are you positioning a window at a specific location on a specific display?

We already have SDL_GetDisplayForWindow()

**Comment by 1bsyl** [comment]
ok, true
