### ISSUE TITLE
SDL's __WIN32__ macro

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#7228]
As far as I can see, SDL defines `__WIN32__` for desktop platforms, and
not for WinRT or GDK:
https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_platform_defines.h#L143-L182

MinGW gcc does define `__WIN32__` :
```
$ /opt/cross_win32/bin/i686-w64-mingw32-gcc -E -dM -xc /dev/null|grep WIN32
#define _WIN32 1
#define __WIN32 1
#define __WIN32__ 1
#define WIN32 1
```

To be safe, is the following patch acceptable? If it is, I will apply an equivalent to SDL2 too.
```diff
diff --git a/include/SDL3/SDL_platform_defines.h b/include/SDL3/SDL_platform_defines.h
index 8841236..49bc3bc 100644
--- a/include/SDL3/SDL_platform_defines.h
+++ b/include/SDL3/SDL_platform_defines.h
@@ -140,7 +140,7 @@
 #define __SOLARIS__ 1
 #endif
 
-#if defined(WIN32) || defined(_WIN32) || defined(__CYGWIN__) || defined(__MINGW32__)
+#if defined(_WIN32) || defined(__CYGWIN__) || defined(__MINGW32__)
 /* Try to find out if we're compiling for WinRT, GDK or non-WinRT/GDK */
 #if defined(_MSC_VER) && defined(__has_include)
 #if __has_include(<winapifamily.h>)
@@ -163,6 +163,8 @@
 #define WINAPI_FAMILY_WINRT 0
 #endif /* HAVE_WINAPIFAMILY_H */
 
+#undef __WIN32__ /* MinGW gcc defines __WIN32__ */
+
 #if WINAPI_FAMILY_WINRT
 #undef __WINRT__
 #define __WINRT__ 1
```

**Comment by smcv** [comment]
An opposite opinion: I think ideally SDL 3 should only be defining or undefining platform-detection macros in its own namespace, and never define or redefine macros outside the SDL namespace (similar to how GLib defines `G_OS_UNIX` and `G_OS_WIN32`, but uses compiler-defined macros like `__WIN32__` on a read-only basis). Anything starting with `__` or `_` + a capital letter is toolchain territory, and is not SDL's job.

For SDL 2 that would be an incompatible change, but I don't think what you propose here would be a compatible change for SDL 2 either.

**Comment by sezero** [comment]
> An opposite opinion: I think ideally SDL 3 should only be defining or undefining platform-detection macros in its own namespace,

Sadly, that has been a long-standing truth. What I'm saying is a band-aid for the current situation.

>  I don't think what you propose here would be a compatible change for SDL 2 

In which way really?

**Comment by smcv** [comment]
> I think ideally SDL 3 should only be defining or undefining platform-detection macros in its own namespace

... which might mean `SDL_WIN32`, `SDL_WINRT` and so on.

Alternatively, people who are writing platform-dependent code can use the macros that are already predefined by their toolchain, like `__linux__`. For modern platforms and toolchains, those tend to be treated as a compiler-independent interface (for example all compilers targeting x86_64 Linux should define `__linux__` and `__x86_64__`), but their names don't follow a consistent convention between platforms (so for instance it's `__linux__` on Linux but `_WIN32` on Windows).

The approach taken in GLib, which is a C library at about the same level of the stack as SDL, is to define macros for very broad OS families (currently `G_OS_UNIX` and `G_OS_WIN32` are the only two that exist, because everything is either Unix-derived, Windows, or basically irrelevant this decade), but intentionally not define wrappers like `G_OS_LINUX` or `G_OS_WINRT` to make a finer-grained distinction between platforms (because those get surprisingly subtle, to the extent that you need to be a platform expert to name them correctly).

**Comment by smcv** [comment]
> > I don't think what you propose here would be a compatible change for SDL 2
> 
> In which way really?

People who are using MinGW gcc to compile portable code for platforms that include WinRT or GDK could be relying on the toolchain having defined `__WIN32__` on WinRT and GDK. If SDL undefines it, then their code will no longer compile its Windows code path.

**Comment by slime73** [comment]
Personally I'd consider it a bug if having `#include <SDL.h>` in my code removed or otherwise modified something that was defined externally to SDL (such as `__WIN32__`).

**Comment by slouken** [comment]
Agreed. SDL should adapt internally rather than change system headers, even if it's not what we would expect when building our code.

**Comment by sezero** [comment]
OK then. Close this ticket?

**Comment by sezero** [comment]
Should I apply the following to SDL3 and SDL2, then? (Please verify its
correctness, c.f.: https://github.com/libsdl-org/sdl2-compat/issues/40 )

```diff
diff --git a/include/SDL3/SDL_thread.h b/include/SDL3/SDL_thread.h
index 5102030..3dc89f0 100644
--- a/include/SDL3/SDL_thread.h
+++ b/include/SDL3/SDL_thread.h
@@ -35,7 +35,7 @@
 #include <SDL3/SDL_atomic.h>
 #include <SDL3/SDL_mutex.h>
 
-#if defined(__WIN32__) || defined(__GDK__)
+#if (defined(__WIN32__) || defined(__GDK__)) && !defined(__WINRT__)
 #include <process.h> /* _beginthreadex() and _endthreadex() */
 #endif
 
@@ -81,7 +81,7 @@ typedef enum {
 typedef int (SDLCALL * SDL_ThreadFunction) (void *data);
 
 
-#if defined(__WIN32__) || defined(__GDK__)
+#if (defined(__WIN32__) || defined(__GDK__)) && !defined(__WINRT__)
 /**
  *  \file SDL_thread.h
  *
```
