### ISSUE TITLE
Emulated mode switching for all video backends

### ISSUE THREAD

**Issue by mbriar** [libsdl-org/SDL#7287]
Hi,

I think it would be nice in certain situations if it was possible to force-enable the emulated mode switching also for video backends that technically don't need it, like x11.  Game changing the display mode can be unpleasant and e.g. Proton already unconditionally emulates all mode changes, so I'd appreciate if SDL on x11 could do the same.

Thank you.

**Comment by slime73** [comment]
Do all backends have that capability?

Proton controls higher levels than SDL does, I think - if its emulation is done via graphics API render targets in its code, that's not something SDL would be able to control (aside from SDL_Render, which many SDL games don't use.)

**Comment by mbriar** [comment]
I didn't look into how SDL actually emulates the mode changes on wayland, if this is something not trivially portable to other backends, feels free to close this.

**Comment by slime73** [comment]
I don't know how it works on Wayland either. :) 

On macOS, I think it might technically be possible - but it would probably have some limitations like stretching an emulated display mode that has a different aspect ratio than the display's native ratio, instead of letterboxing it. 16:10 is a pretty common aspect ratio on macOS so it might be a bigger issue there than on other platforms. I have no idea whether Windows or X11 could support something like this.

**Comment by slouken** [comment]
You can use SDL renderer logical presentation for this, or a similar mechanism in your own games that don't use the renderer. The compositor mode emulation in Wayland isn't generally applicable to other platforms.
