### ISSUE TITLE
Win10: Nintendo Switch Pro (8BitDo SN30pro) sometimes has a doppelgänger when hot-plugged

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#7304]
Latest SDL3 source (but also happened with SDL2), Windows 10. This has been happening for a while now; when hot-plugging my SN30 Pro, I sometimes (one in about every 5 times) get a duplicated SDL_EVENT_GAMEPAD_ADDED. One controller works fine, the other has random glitchy events coming through for random axis and buttons when the controller is idle. This happens when in Switch mode (holding Y down when plugging in), but I've also seen it happen in PS4 mode. It might have something to do with axis events rolling in while the controller is being added, because in Switch mode the axis are very sensitive and spam hairline events while idle.

**Comment by Balderick** [comment]
Yes i can see unwanted inputs showing in joy.cpl when Steam SDL is actively mapping controller events with 8Bit Do Pro 2 controller.   Valve seem to have "fixed" the dinput mode doing that by getting sdl to apply generic controller type instead of ps3 type controller.

Havent tested Switch mode for a while due to gyro drift being a problem which is very likely to be related what is described in op.  But iirc switch mode in joy.cpl had its own disco party going on when steam was running with sdl switched on.    Switching Steam SDL off stops the disco party in joy.cpl.   

8Bit Do Pro 2 just had firmware update to ver 3.00 which lists unwanted double input issue as fixed.   And triggers dont work well in joy.cpl even when sdl is switched off in Steam especially left trigger.

**Comment by slouken** [comment]
@AntTheAlchemist, this is fixed, thanks!
