### ISSUE TITLE
macosx  opgengl  produces a black screen

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#7320]
using latest SDL3 version, macos intel + ventura 13.2
it seems:
./testsprite --renderer opengl
 produces a black screen
(metal seems ok)

**Comment by icculus** [comment]
I'll check this on an M1 Mac and see if I can reproduce.

**Comment by icculus** [comment]
Seeing it here, too. Looking into it.

**Comment by icculus** [comment]
Haven't looked at the commit yet, but bisecting says this is where it broke:

https://github.com/libsdl-org/SDL/commit/dcd17f547324a143d66d79e3b586577a7da558ed

**Comment by icculus** [comment]
Ah, here's what's happening. This code...

https://github.com/libsdl-org/SDL/blob/main/src/render/SDL_render.c#L4007-L4015

...basically guarantees that we always have a render target bound (the new, logical render target magic) when we get to GL_RenderPresent, which calls SDL_GL_SwapWindow, which on Cocoa will fail to render to the screen if you have an FBO bound.

While I still believe this last detail might be a macOS bug, it's been happening since forever, and the solution is to not have the logical render target bound during present.

**Comment by slouken** [comment]
Ah, thanks for tracking that down!
