### ISSUE TITLE
Android.mk builds libSDL3.so in thumb node

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#7415]
[By default, the ndk-build system generates ARM target binaries in thumb mode.](https://developer.android.com/ndk/guides/android_mk#local_arm_mode)

Is this something we want and/or care about?

**Comment by slouken** [comment]
I'm not sure whether we care or not. I believe thumb mode used to be more important when phones had less space, but I don't know if it's still relevant. It's worth some research before 3.0 release.

**Comment by AntTheAlchemist** [comment]
I'll chip in and say I like to keep my .APK file size down. Google Play will punish apps that are larger because users are forced to uninstall to make room. Disabling thumb builds would double the native binaries, which will nearly double my .APK size. If speed is an issue, ARM code can be applied per-file by adding .arm on to the LOCAL_SRC_FILES list, or by adding LOCAL_ARM_MODE := arm. At least that is my understanding after doing some digging.

**Comment by madebr** [comment]
Closing, since it's a good default.
