### ISSUE TITLE
SDL_GetRendererOutputSize returns zero width/height when Windows desktop view is toggled

### ISSUE THREAD

**Issue by Wedge009** [libsdl-org/SDL#7419]
Reference: https://github.com/wesnoth/wesnoth/issues/7438#issuecomment-1459133232

This appears to be only an issue in SDL 2.24.0 onwards, and only on Windows (I couldn't replicate on KDE, for example). When an application using SDL is running and the user switches to desktop view via Windows+D (or Alt-Tab to 'Desktop' in Windows 7), calling `SDL_GetRendererOutputSize()` results in zero width and height being returned. Is this intentional?

I only ask because this function appears to return non-zero renderer dimensions even in desktop view for SDL 2.0.22.

**Comment by slouken** [comment]
No, that's not intentional. I'll take a look, thanks!

**Comment by Wedge009** [comment]
Thanks for the response. I await your investigation.

**Comment by slouken** [comment]
The issue is that the Win32 API GetClientRect() is returning an empty rectangle in this situation. I'll add a workaround, thanks!

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by Wedge009** [comment]
Thank you. What is the next release? I assume that commit will be included in it.

**Comment by slouken** [comment]
The next release will be 2.26.5, released around April 1.

**Comment by Wedge009** [comment]
Thanks for the update.

**Comment by ts-13512** [comment]
The fix for this seems to have broken the Xbox GDK build since IsRectEmpty is not defined in WinUser.h for Xbox builds (due to WINAPI_FAMILY_GAMES and WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP). I can submit a simple fix by implementing this function for Xbox builds but I'm not sure where to branch off or what's the procedure for cherry picking this to release-2.26.x branch.

The problem is the main branch is borked for the Xbox GDK build anyways, it doesn't even compile. So should I submit a PR for the release-2.26.x branch or main?

**Comment by slouken** [comment]
Go ahead and submit it for main, and we'll merge it to the other branches.

**Comment by GitAxeon** [comment]
Win10 allows a window to be resized so that it has client area height of 0.

Both SDL_GetWindowSize and SDL_GetWindowSizeInPixels report incorrect values when that happens which I believe to be caused by the fix to the previous issue.

I noticed this when following a Vulkan tutorial I attempted to skip rendering if the window had either width or height of 0 but since the functions reported the last known values rather than the "empty size" the check never succeeded. The Vulkan API reported correct dimensions for the VkSurfaceKHR (width 0, height 0). That later caused the validation layers to report an error when creating framebuffers of that size.

I checked the miminum window size using SDL_GetWindowMinimumSize which reported width 0, height 0.
