### ISSUE TITLE
built-in ManyMouse for SDL3

### ISSUE THREAD

**Issue by expikr** [libsdl-org/SDL#7498]
@icculus

**Comment by icculus** [comment]
We're starting to pile up a lot of duplicates of this:

#6724
#5663
#5927 

Let's consolidate all of these into one issue and close the others.

**Comment by slouken** [comment]
This is implemented in SDL3.

**Comment by Tovarichtch** [comment]
> This is implemented in SDL3.

Wonderful news! Can you tell which commits please? Thank you

**Comment by slouken** [comment]
It's a number of commits, but the gist is that when the mouse is in relative mode, the `which` parameter of the mouse events corresponds to the mouseID that generated it.

**Comment by slouken** [comment]
Yep!

**Comment by slouken** [comment]
> Are all "mouse" types supported, besides USB? Bluetooth, touchpad, touchscreen, trackpoint?
> 
> Joystick/Gamepad as mouse? Part-of-keyboard as mouse?

Anything that reports as a mouse to the OS should work here.

**Comment by nrs23** [comment]
> And same for keyboards too?

Sorry to necro but the response to this was 'yes' from @slouken, but this doesn't actually appear to be the case. In the current `main` branch the `SDL_KeyboardEvent` struct does not include a `which` parameter (https://github.com/libsdl-org/SDL/blob/3c142abcb2b0b0ad7e08b096ea8d9a1a1e1af1ef/include/SDL_events.h#L224), unlike the mouse motion/button/wheel events, and it's not referenced to be anywhere else in any documentation.

Is it possible to implement for keyboard?

**Comment by madebr** [comment]
@nrs23
This is one of the many new features of SDL3:
https://github.com/libsdl-org/SDL/blob/ac92af02eaf9e85f4b717b309f860822edff9f2d/include/SDL3/SDL_events.h#L332

**Comment by knn217** [comment]
I tested the multi-keyboard feature with the woodeneye demo. But the demo only works correctly on the Windows build, it couldn't tell keyboards appart on Ubuntu.
Is there a setting I need for Ubuntu? Windows need to set the hint SDL_HINT_WINDOWS_RAW_KEYBOARD to "1" for multi-keyboard, but I couldn't find anything for Linux

**Comment by icculus** [comment]
The X11 driver supports it with XInput2, but we have it disabled at the moment:

```
// This is not enabled by default because these events are only delivered to the window with mouse focus, not keyboard focus
#ifdef USE_XINPUT2_KEYBOARD
        XISetMask(mask, XI_KeyPress);
        XISetMask(mask, XI_KeyRelease);
        windowdata->xinput2_keyboard_enabled = true;
#endif
```

(That's kind of weird that this would follow _mouse_ focus, though...we should recheck that and maybe file a bug with x.org...?)

I have not tried it, but the Wayland backend appears to support it, from a cursory look at the code. If you happen to be running Wayland and not X11, you can try forcing SDL to use Wayland instead:

SDL_VIDEO_DRIVER=wayland ./examples/demo-woodeneye-008

Right now SDL will still favor XWayland over using Wayland directly for various technical reasons that will resolve themselves over time, so you'll probably have to use SDL_VIDEO_DRIVER to try it.

**Comment by knn217** [comment]
@icculus 
Thank you for the suggestion. I have check ed and my Ubuntu does use wayland
While debugging through the program, I saw that when using X11, the the program detected 3 keyboards when calling SDL_AddKeyboard, even though I only have 2 keyboards (one is the laptop's kb, another is a plugged in logitech kb):

- "Virtual core keyboard", keyboardID = 3
- "Virtual core XTEST keyboard", keyboardID = 5
- "xwayland-keyboard:15", keyboardID = 9
The event's keyboard ID is 0, I guess this make sense since X11 is disabled.

I also tried the same setup for wayland, but this one is a bit more confusing. Wayland only called SDL_AddKeyboard 1 time even though I have 2 physical keyboards:

- "Virtual core keyboard", keyboardID = 2
The event's keyboard ID is always 2 for both keyboards, so wayland also can't separate them.

**Comment by knn217** [comment]
> Maybe you have another device representing (part of) itself as a keyboard - fancy gamepad, remote control, presenter controller, phone-as-remote, etc.

Thank you, I have rechecked but my machine is not connected to these devices.
I have also tried to unplug my logitech keyboard but the keyboard count is still 3.
Here is the code I modified from "hello.c" for easier debugging:
`
#define SDL_MAIN_USE_CALLBACKS 1  /* use the callbacks instead of main() */
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <string>
#define USE_XINPUT2_KEYBOARD
#define SDL_VIDEO_DRIVER_X11_XINPUT2

static SDL_Window* window = NULL;
static SDL_Renderer* renderer = NULL;
std::string message = "Hello World!";

/* This function runs once at startup. */
SDL_AppResult SDL_AppInit(void** appstate, int argc, char* argv[])
{
    //SDL_SetHint(SDL_HINT_WINDOWS_GAMEINPUT, "1");
    //SDL_SetHint(SDL_HINT_WINDOWS_RAW_KEYBOARD, "1");
    //SDL_SetHint(SDL_HINT_VIDEO_DRIVER, "wayland");
    SDL_SetHint(SDL_HINT_VIDEO_DRIVER, "x11");
    
    /* Create the window */
    if (!SDL_CreateWindowAndRenderer("Hello World", 800, 600, SDL_WINDOW_KEYBOARD_GRABBED, &window, &renderer)) {
        SDL_Log("Couldn't create window and renderer: %s\n", SDL_GetError());
        return SDL_APP_FAILURE;
    }
    return SDL_APP_CONTINUE;
}

/* This function runs when a new event (mouse input, keypresses, etc) occurs. */
SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event)
{
    int count;

    if (event->type == SDL_EVENT_QUIT) {
        return SDL_APP_SUCCESS;  /* end the program, reporting success to the OS. */
    }
    else if (event->type == SDL_EVENT_KEY_DOWN) {
        SDL_Keycode key = event->key.key;
        SDL_KeyboardID id = event->key.which;
        SDL_KeyboardID* keyboardIDs = SDL_GetKeyboards(&count);
        message = SDL_GetKeyName(key) + std::string(" ") + std::to_string(count) + ":" + std::to_string(id);
        //std::cout << "Key Down: " << SDL_GetKeyName(key) << std::endl;
    }
    else if (event->type == SDL_EVENT_KEY_UP) {
        SDL_Keycode key = event->key.key;
        SDL_KeyboardID id = event->key.which;
        SDL_KeyboardID* keyboardIDs = SDL_GetKeyboards(&count);
        message = SDL_GetKeyName(key) + std::string(" ") + std::to_string(count) + ":" + std::to_string(id);
        //std::cout << "Key Up: " << SDL_GetKeyName(key) << std::endl;
    }
    return SDL_APP_CONTINUE;
}

/* This function runs once per frame, and is the heart of the program. */
SDL_AppResult SDL_AppIterate(void* appstate)
{
    int w = 0, h = 0;
    float x, y;
    const float scale = 4.0f;

    /* Center the message and scale it up */
    SDL_GetRenderOutputSize(renderer, &w, &h);
    SDL_SetRenderScale(renderer, scale, scale);
    x = ((w / scale) - SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE * SDL_strlen(message.c_str())) / 2;
    y = ((h / scale) - SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE) / 2;

    /* Draw the message */
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    SDL_RenderClear(renderer);
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
    SDL_RenderDebugText(renderer, x, y, message.c_str());
    SDL_RenderPresent(renderer);

    return SDL_APP_CONTINUE;
}

/* This function runs once at shutdown. */
void SDL_AppQuit(void* appstate, SDL_AppResult result)
{
}
`
If there are any setting I missed, please let me know.
Thank you!

**Comment by Kontrabant** [comment]
> I also tried the same setup for wayland, but this one is a bit more confusing. Wayland only called SDL_AddKeyboard 1 time even though I have 2 physical keyboards:

>    "Virtual core keyboard", keyboardID = 2
    The event's keyboard ID is always 2 for both keyboards, so wayland also can't separate them.


Wayland doesn't expose individual devices, it exposes "seats", which are collections of input devices. SDL has, and currently does, only support one seat, which appears as one "virtual" mouse and keyboard. Supporting multiple seats is on my todo list, but is not high priority right now as it will require a fair bit of refactoring, and, as far as I know, no compositor currently supports exposing more than one seat to clients (there was talk of working on it for KDE to expose multiple input devices separately, but I don't know if work is currently progressing).

**Comment by Daigoro96** [comment]
`event->button.which` always reports 0 for me as SDL_MouseID. I had that issue with  SDL_KeyboardID in KeyboardEvents too, but there i figured i can use `SDL_SetHintWithPriority(SDL_HINT_WINDOWS_RAW_KEYBOARD, "1", SDL_HINT_OVERRIDE);` to make it work. However i couldn't figure out how to make any mouse events report the actual mouseID, any ideas?
