### ISSUE TITLE
Give a higher priority to pipewire than alsa?

### ISSUE THREAD

**Issue by rom1v** [libsdl-org/SDL#7541]
If alsa and pipewire are both present on the system, SDL attempts to use alsa, and may fail because the device is busy:

> ALSA: Couldn't open audio device: Device or resource busy

With `SDL_AUDIODRIVER=pipewire`, it works.

Is it reasonable to give pipewire a higher priority than alsa? Or will it cause other issues?

Refs https://github.com/Genymobile/scrcpy/issues/3864

**Comment by flibitijibibo** [comment]
We're still waiting on one last feature before bumping PipeWire to the front: #5346

But PipeWire before ALSA... I guess that wouldn't be so bad; if Pulse fails but PipeWire succeeds then we could probably safely say that there's an audio session running? Wouldn't be a guarantee though, so I could go either way on this.

**Comment by slouken** [comment]
If pipewire initialization fails when pipewire isn't running, then that seems like a good change to make.

**Comment by flibitijibibo** [comment]
That's currently the one troublesome bit; it's not super obvious as to whether it's running a session for audio specifically, so it could be that PW is running a video session but not audio, which could cause the stream to go to a black hole.

We came super close to having a working patchset, but I ran out of developer resources and so was unable to finish it (SDL_ActionSet took priority):

https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1409

https://gitlab.freedesktop.org/pipewire/wireplumber/-/merge_requests/441

**Comment by Kontrabant** [comment]
Pipewire has an ALSA compatibility layer that should be used in this scenario, unless it was explicitly overridden or not built.

Venturing a guess here, but I'm guessing what happened is that SDL was built without Pulse support and Pipewire was built without ALSA compatibility enabled, so trying to use Pulse failed, then when it hits ALSA, the SDL driver tries to open the hardware directly and fails, because Pipewire already holds it.

> But PipeWire before ALSA... I guess that wouldn't be so bad; if Pulse fails but PipeWire succeeds then we could probably safely say that there's an audio session running? Wouldn't be a guarantee though, so I could go either way on this.

It would work for this case, although, as is usually the case in *nix land, a little googling reveals that there are still people out there with bespoke setups using dmix for whatever reason, and they probably won't be happy with this. Either way, it's going to be broken for someone.

**Comment by slouken** [comment]
ALSA emulation seems to be less robust than Pulseaudio over pipewire. I'm thinking that if we can't do pulse, we should hit pipewire next and then ALSA. @flibitijibibo, are things in a state where we could do that?

**Comment by flibitijibibo** [comment]
That seems reasonable to me. Really the only blocker for PW being at the top is detecting it over Pulse correctly, it should be safe to prioritize over ALSA without any trouble.

**Comment by slouken** [comment]
Done!
