### ISSUE TITLE
Feature Request: Adaptive sync/swap interval control for renderers other than OpenGL

### ISSUE THREAD

**Issue by nightmareci** [libsdl-org/SDL#7595]
I did some research into adaptive sync support in macOS, and it seems to me the only option right now is to directly use Metal, as there doesn't seem to be *any* way to use OpenGL in macOS with adaptive sync. I assume that's because there's no macOS adaptive sync extension for desktop OpenGL, nor for OpenGL ES (Google ANGLE). So I'm asking for some solution of enabling adaptive sync for SDL_render, perhaps with a new swap interval function similar to the existing one for OpenGL; I'm thinking it'd be possible to enable that feature in the Metal SDL_render backend. Alternatively, the option could be part of the new GPU API coming to SDL3. The feature would also benefit the other backends, so long as there's an adaptive sync option for the backing APIs.

**Comment by slime73** [comment]
To make sure there aren't any misunderstandings: do you mean adaptive vsync (automatic vsync-off when framerate drops below refresh rate), or Adaptive Sync (the monitor's refresh rate syncs to the game's framerate)?

**Comment by nightmareci** [comment]
"Adaptive Sync", meaning that presents are always immediate, not the automatic sync timing managed by vsync.

**Comment by slime73** [comment]
SDL2's OpenGL swap interval code on macOS explicitly supports adaptive *vsync* (automatic vsync on/off depending on whether the framerate is >= the monitor's fixed refresh rate. Setting the swap interval to -1 will activate it). Some other platforms support that as well depending on the graphics driver. But I don't know of any code in SDL to explicitly support Adaptive Sync (dynamically changing the monitor's refresh rate based on the game's FPS). Do you have an example of that in the code? Since I'm curious for my own projects.

**Comment by nightmareci** [comment]
I guess I just misjudged my tests, since even with vsync used it appears as smooth as using adaptive sync on my PC running Windows/Linux. But like for the DirectX backends of SDL_render, there's no way to enable adaptive sync. It might be possible to use a hacky solution of calling SDL_GL_SetSwapInterval when the current backend is OpenGL, on platforms with true adaptive sync, but that's not a very good solution.

**Comment by icculus** [comment]
SDL3 has SDL_SetRenderVSync, which  allows adaptive vsync ("late swap tearing," not changing the physical display refresh rate). Direct3D 9 doesn't support this, so it isn't implemented there, but I think we've wired it up everywhere else.
