### ISSUE TITLE
SDL3_DYNAMIC_API support for mixed 32/64 bit environments (eg. steam games)

### ISSUE THREAD

**Issue by 1ace** [libsdl-org/SDL#7613]
Looking at the code (`SDL_InitDynamicAPILocked()` in `src/dynapi/SDL_dynapi.c`), `SDL3_DYNAMIC_API` goes straight into `dlopen()`.

Perhaps it could support receiving a `:`-separated list instead, and try them until one is supported?

**Comment by flibitijibibo** [comment]
That would make sense to me - if Steam ever wanted to set this they'd want to include both (or all, if arm64 ever gets added) architectures in the variable.

**Comment by icculus** [comment]
This is a good idea, I'll take a run at it.

**Comment by icculus** [comment]
Putting this in 2.28.0 milestone, since I want to make sure this makes into an SDL2 release in addition to SDL3.

**Comment by icculus** [comment]
Okay, this is in for both SDL2 and SDL3.

Same environment variable, but it'll allow a _comma_ separated list of paths instead of a single path.

I didn't use a colon as the separator so there's no drama specifying a drive letter (like "C:") on Windows, or problems with the upcoming Mac OS 8 port, lol.
