### ISSUE TITLE
[elf/linux] glibc 2.34/symbol versioning

### ISSUE THREAD

**Issue by sylware** [libsdl-org/SDL#7619]
Hi,

It seems some glibc devs changed the version of the symbol libc_start_main() in glibc 2.34 which is in the libc shared object.

It would mean that all executables linked to glibc 2.34 does not load on system with a glibc <= 2.33.

The workaround would be to make SDL executables pure ELF64, namely use directly the SYSV ABI entry point (which is nearly a main()) and not glibc main(). It would mean that all system symbols should be "libdl-ed", including those from the libc.

That would be a definitive workaround of  most if not all symbol version issues.

But maybe libsdl is a pure library and is independent of the game executable.

**Comment by icculus** [comment]
I don't think we're going to do this; while we do provide optional entry points on some systems, to disguise the difference between main() and WinMain(), etc, it doesn't seem wise to try to bypass the generally agreed-upon way of starting a process for a system.

(the libc_start_main version bump is because of this, I think: https://sourceware.org/bugzilla/show_bug.cgi?id=23323 ...it's not the first time they've made glibc incompatible with previous versions, and generally the advice for portability is to build against an older glibc until these sort of changes are old enough that you can reasonably expect users to have them.)
