### ISSUE TITLE
Wayland output scaling does not affect tablet and mouse input

### ISSUE THREAD

**Issue by hrdl-github** [libsdl-org/SDL#7696]
Wayland provides input-related events are not affected by output scaling. SDL compensates for this correctly for touch input (https://github.com/libsdl-org/SDL/blob/d98bd67733e78dea88efbca2eff382f9c77b2d6a/src/video/wayland/SDL_waylandevents.c#L962-L965), but not for mouse or tablet tools (https://github.com/libsdl-org/SDL/blob/d98bd67733e78dea88efbca2eff382f9c77b2d6a/src/video/wayland/SDL_waylandevents.c#L522-L524 or https://github.com/libsdl-org/SDL/blob/d98bd67733e78dea88efbca2eff382f9c77b2d6a/src/video/wayland/SDL_waylandevents.c#L2459-L2461)

What exactly is the purpose of `pointer_scale_{x,y}`? At the moment these are only non-zero for "exclusive full-screen": https://github.com/libsdl-org/SDL/blob/d98bd67733e78dea88efbca2eff382f9c77b2d6a/src/video/wayland/SDL_waylandwindow.c#L240-L241 Should `pointer_scale_{x,y}` reflect the output scale or should an additional factor be used (e.g. one derived from `windowed_scale_factor` or the ratio between `drawable_width` and `window_width`, depending on whether or viewport is used or not)?

This affects both plasma-wayland and sway using `SDL_VIDEODRIVER=wayland`. See also https://github.com/koreader/koreader/issues/10420.

**Comment by Kontrabant** [comment]
SDL delivers mouse pointer events in screen coordinates (aka points or device independent pixels), while touch coordinates are delivered as normalized float values.

On high-DPI setups, if you want mouse coordinates relative to the backbuffer dimensions, you have to manually divide the backbuffer size in pixels (`SDL_GetWindowSizeInPixels` or `SDL_GetRendererOutputSize`) by the window size in screen coordinates (`SDL_GetWindowSize`), and multiply the resulting value by the mouse coordinates. Likewise, if you want the coordinates as normalized float values, you have to handle that yourself.

The pointer scale code you are looking at exists because Wayland doesn't support switching video modes, so non-native resolutions are emulated and scaled by the backend so the application can function as though the display mode has changed. The pointer scaling is used internally to convert coordinates from the native desktop resolution to the emulated one, otherwise, it's always 1.0 to directly pass the coordinates as received from the compositor to the application.
