### ISSUE TITLE
duet chromebook all keys being reported as numpad

### ISSUE THREAD

**Issue by goblinhack** [libsdl-org/SDL#7805]
Hey, I have an end user who reported that all the keys had the KMOD_NUM modifier set. I'm not sure if this is some quirk of the chromebook or a bug in SDL. Anyone else reported similar ?

**Comment by Susko3** [comment]
`KMOD_NUM` being set just means that num lock is on. See https://wiki.libsdl.org/SDL2/SDL_Keymod.
Is this causing any behavioural issues? 

Since the device in question doesn't even have the numpad keys, this being on or off is irrelevant. If you were to connect an full-size external keyboard to it, you'd see that the num lock LED would light up.

**Comment by goblinhack** [comment]
maybe I'll just mask out KMOD_NUM in general - feel free to close this
