### ISSUE TITLE
How to link SLD3 via FetchContent?

### ISSUE THREAD

**Issue by os-tap** [libsdl-org/SDL#7831]
for sdl2 it works fine:

```
FetchContent_Declare(
        SDL
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG release-2.26.5
)

FetchContent_MakeAvailable(SDL)

target_link_libraries(${PROJECT_NAME} PRIVATE
  SDL2
)
```

but for SDL3 writes now found

**Comment by madebr** [comment]
The targets of SDL3 are `SDL3::SDL3`, `SDL3::SDL3-shared`, and `SDL3::SDL3-static`.
They are documented [here](https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake).

SDL3 is not released yet, so you need to use the `main` branch, instead of a SDL2 release tag.

I just added [this section](https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md#help-it-doesnt-work) to the cmake documentation that should build.
