### ISSUE TITLE
Some 3D matrix math...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7906]
Passing on a tweet from https://twitter.com/albertvaka/status/1673825758941179905 for discussion...

> Can we get a way to specify a camera transformation matrix in SDL3? It's quite common to pan, zoom or rotate the whole view in a game.

**Comment by slouken** [comment]
Adding 3D matrix math is a gnarly mess we shouldn't get into. There's so much functionality that someone might want, we don't want to also become a full 3D math library. The only 3D math we should add is any we need internally, e.g. for the new GPU code.

**Comment by madebr** [comment]
I think the future SDL_gpu should just make sure its data types are compatible with other libraries.

**Comment by albertvaka** [comment]
I requested this originally. Maybe there's a way to offer camera movement/zoom without exposing the matrix math?

**Comment by albertvaka** [comment]
Assuming there's no way to rotate the camera, movement should be easy to add too: it's just an X and Y displacement.

If we want to allow both movement and rotation of the camera, then I think there's no way to do it without exposing matrices on the API (because the order in which you apply the transformations gives different results), which the authors seem to be against.

So, maybe this issue could be renamed to "Add camera zoom and movement API" to not involve matrices @slouken?

**Comment by albertvaka** [comment]
Then it seems unavoidable to add a function that takes a matrix if we want to have the concept of a "camera". I think it's still worth doing because a camera is a very useful thing to have, but up to you folks to decide.

**Comment by albertvaka** [comment]
Here goes an example:

Let's say I'm drawing a scene made of sprites. For each sprite I have an X and Y position. But my scene is bigger than my screen, so I provide a way to move through the scene. As I move my view in one direction, some sprites enter into view as others leave the screen from the other side. 

Imagine a side-scrolling game, where my character moves from left to right and my view is always centered on the character. Or a top-down strategy game where I can "scroll" in both axis through the map.

I know the X and Y position for each sprite in scene coordinates. However, to draw the sprite I now need to convert those X and Y coordinates to screen coordinates. If I'm just applying a translation, this just means subtracting the view's X and Y coordinates to each sprite X and Y coordinates before drawing it. But if I also want to zoom-i or rotate the screen then I need to do some maths for each sprite to calculate their position on screen.

I think this use case is very common. So if SDL did this coordinate transformation for me, not only would simplify the code in many applications but it would also enable running this on the GPU instead of the CPU.

When/if I want to draw things in screen coordinates (eg: a UI on top of my scene), I should be able to reset the view back to 0 before doing so.

**Comment by slouken** [comment]
We're not currently planning on adding this at the moment. @icculus can weigh in if it makes sense with the SDL GPU API though!

**Comment by icculus** [comment]
> if it makes sense with the SDL GPU API though!

My current thought is no; it could certainly be _useful_ to someone using a 3D API, but it's not useful to the API itself, and it's easy ("easy") to get matrix math code into an app from somewhere else.

However, I _do_ think this could be useful as a single-header library. I haven't looked, but I would be surprised if such as thing didn't already exist outside of SDL. I don't have time to sleep recently, though, let alone take this project on.
