### ISSUE TITLE
Implement application state for desktop applications?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#7910]
It might make application development easier to have the foreground and background application states in desktop applications as well as mobile applications.

However, there isn't really the same foreground / background concept on desktop, and if we wanted to emulate it, what should it map to?

One natural mapping would be "when the application has windows visible, it's in the foreground, and when there are no windows or they are all hidden or minimized, the application is in the background". However, implementing the logic for this would mean dispatching application state transition while creating and destroying windows, or even inside of SDL_Quit(), which could be dangerous, depending on the actions being taken by the application.

@libsdl-org/a-team, thoughts?

**Comment by icculus** [comment]
First thought: I wouldn't over-complicate it. On desktop things, you get `SDL_EVENT_WILL_ENTER_FOREGROUND` followed immediately by `SDL_EVENT_DID_ENTER_FOREGROUND` at startup, so mobile apps that want to rely on that can use the same setup code.

I'm not sure I would send enter-background events at all. On macOS, it maybe makes some sense, since _apps_ have focus in addition to specific windows, only that app has the global menu bar, etc. But on Windows and most other things, your windows from different apps just intermingle. A _window_ from an app has focus, but the app itself does not.

**Comment by icculus** [comment]
(Also, we already have window focus events, so trying to make a mapping to this is going to confuse things.)

**Comment by slouken** [comment]
> I'm not sure I would send enter-background events at all. On macOS, it maybe makes some sense, since _apps_ have focus in addition to specific windows, only that app has the global menu bar, etc. But on Windows and most other things, your windows from different apps just intermingle. A _window_ from an app has focus, but the app itself does not.

Yeah, this is different from application focus. On macOS, you want to continue rendering because even if the application doesn't have focus, the windows might be visible. The background state means that the application isn't visible and has no way of interacting with the user. It also, on mobile, means that you should reduce memory usage and release graphics contexts and might be terminated at any time.

**Comment by CodesOtakuYT** [comment]
The only use case of those events for me is to handle Android EGL surface creation and recreation. I'd suggest for other platforms to have the events trigger once at the start and end of the application.

**Comment by slouken** [comment]
We could trigger the event at the start of the application, but dispatching events inside SDL_Quit() is dangerous, and we have no other way of knowing the application is quitting in desktop environments. I think as long as you don't rely on that event for cleanup, and do your own cleanup if you return from main(), then that might work.

I'm a little concerned about the timing of the event on desktop relative to mobile platforms. If we did it inside SDL_Init(), then you wouldn't have a window for EGL surface creation, for example.

**Comment by CodesOtakuYT** [comment]
Honestly cleanup doesn't matter that much as an event, since I'll have cleanup after the event loop anyway.
The only really important thing for people like me here is receiving the FOREGROUND event at the start of the event loop or at least having a function to check if we'll even receive a FOREGROUND event or not.
Otherwise currently I have to use the macro __ANDROID__, which may be fine but less than ideal.

**Comment by 1bsyl** [comment]
Android fg/bg are quite similar of minimized / focus gained / lost events of the desktop.

So that's possible to call the same user function without the android macro, attached with those events. Just make sure to have an on/off state for save/restore not to restore/save twice in a row.


Android fg/bg also have also more functionnalities:
- there are "will_enter" events sent before the "did_enter" event.
- the event blocks by default the event loop. so that the app isn't running in background

**Comment by CodesOtakuYT** [comment]
I though to add a snippet of my use case for those events, in case if it helps:
```cpp
    std::optional<Surface> surface{};

#ifndef __ANDROID__
    surface.emplace(window, instance);
#endif
    window.show();

    for (auto should_close{false}; !should_close;) {
        for (SDL_Event event; SDL_PollEvent(&event);) {
            switch (event.type) {
                case SDL_EventType::SDL_EVENT_QUIT:
                    should_close = true;
                    break;
#ifdef __ANDROID__
                    case SDL_EventType::SDL_EVENT_DID_ENTER_FOREGROUND:
                        surface.emplace(window, instance);
                        break;
                    case SDL_EventType::SDL_EVENT_WILL_ENTER_BACKGROUND:
                        surface.reset();
                        break;
#endif
            }
        }
    }
```
it would be nice to get the FOREGROUND event near event loop start in desktop, the BACKGROUND event doesn't matter in this case for desktop, but it would be nice to get it near the end of the event loop.
Otherwise, a more general solution would be to at least add a function that can query if the underlying platform will ever emit FOREGROUND/BACKGROUND events.

**Comment by ilyas-taouaou** [comment]
any updates on this?
Here is my current usecase:
![image](https://github.com/libsdl-org/SDL/assets/146193882/2848de54-ac43-44f2-a56c-e4223b098992)
I expect SDL_EVENT_WILL_ENTER_BACKGROUND to work like SDL_EVENT_OCCLUDED and SDL_EVENT_DID_ENTER_FOREGROUND like SDL_EVENT_SHOWN for Desktop

**Comment by slouken** [comment]
These are subtly different. SDL_EVENT_WILL_ENTER_BACKGROUND means you should stop rendering entirely. SDL_EVENT_OCCLUDED means the user can't see your window, so you can reduce framerate (but should still render so if your window is shown it has updated content)

I'm going to go ahead and close this. I don't think there's a direct equivalent to these events on desktop and I don't want to mislead people thinking they're the same.
