### ISSUE TITLE
SDL_WarpMouseInWindow and SDL_WarpMouseGlobal both missing on Wayland

### ISSUE THREAD

**Issue by vanfanel** [libsdl-org/SDL#7937]
Hi there,

Some game engines use these functions, for example OpenFodder:

https://github.com/OpenFodder

Since Wayland support in SDL2 is considered more or less mature by now, why are these two functions missing?
https://github.com/libsdl-org/SDL/blob/17e95345e39b2b3ce436ce3029175055c3d48869/src/video/wayland/SDL_waylandmouse.c#L622

Is it because of what's commented here?
https://github.com/libsdl-org/SDL/blob/17e95345e39b2b3ce436ce3029175055c3d48869/src/video/wayland/SDL_waylandmouse.c#L670

**Comment by Kontrabant** [comment]
Wayland doesn't support warping the mouse cursor, either locally or globally, nor does it support retrieving the actual global cursor position as something like Xeyes would require.  We can fake retrieving the global coordinates well enough so that things like the UE5 editor works when on a display that isn't the primary, as well as faking mouse warp when in relative mode, but true warping and global positioning simply isn't supported for security reasons, so, unless this changes, there's nothing we can do.

This is documented in docs/README-wayland.md

**Comment by vanfanel** [comment]
@Kontrabant Ok, I see. Thanks for taking the time to answer this!
