### ISSUE TITLE
Review SDL_bool type

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#7957]
We should decide whether we're changing the SDL_bool type for SDL 3.0

Here's some relevant discussion:

@slouken:
> I'm wondering what we want to do with SDL_bool as an enum. Do we leave it that way? Do we make it an int and #define the values? Do we use std::bool if available?

@sezero:
> C++ bool is an 8 bit unsigned char, so I guess std::bool is too? Such change will introduce C/C++ incompatibility, no?

@icculus:
> If we're changing it, let's make it an int and not mess with std::bool. I'm not sure why it's an enum in the first place? Maybe in hopes compilers would enforce it being SDL_TRUE or SDL_FALSE?
> 
> I've gotten into the habit of typing SDL_bool a = (b < c) ? SDL_TRUE : SDL_FALSE; instead of SDL_bool a = (b < c); and that was probably because I got burnt by a really aggressive compiler at some point.
> 
> I'm not sure if C compilers promise that comparisons result in a 0 or 1 (or if it's simply promising zero and non-zero), but if so, ditching the enum would be a win and still reasonable to assume you can compare against SDL_TRUE and get a correct result.

**Comment by smcv** [comment]
If you're willing to hard-require C99, the natural representation for a boolean is `bool` from `<stdbool.h>`, which is constrained by the compiler to only be able to take values 0 and 1 (or equivalently `false` and `true`).

As far as I'm aware, there is no `std::bool` in C++, only `bool`. I *hope* C `bool` and C++ `bool` are guaranteed to have the same ABI on a given platform, but I can't point to chapter-and-verse of a standard that says so.

If SDL3 aims to support pre-C99 compilers, then an enum (like SDL 2 `SDL_bool`) or a typedef for some integer type (like GLib `gboolean`) is the best you can do. The cost of this is that its `sizeof` will usually be more than 1, and the compiler won't complain if you try to give it out-of-range values like `SDL_bool b = 42`.

If it will ever be used in a bitfield, making it `unsigned` would probably be a good idea. GLib's `gboolean` is signed, which with hindsight was a mistake, because it makes `gboolean b:1` in a struct counterintuitively take values -1 or 0 (because there's only enough space for the sign bit), and not the 0 or 1 that you'd expect.

> Do we use [bool] if available?

I think "if available" is the worst of both worlds: that would make it an ABI break to build SDL3 for the first time on a compiler that doesn't support C99, and then rebuild it on a more modern compiler that does. I would either say that the 14 year old C99 `bool` is a hard requirement, or avoid it completely, with no middle ground.

> I'm not sure why it's an enum in the first place? Maybe in hopes compilers would enforce it being SDL_TRUE or SDL_FALSE?

They might warn in C++, but certainly not in C.

> I'm not sure if C compilers promise that comparisons result in a 0 or 1

They do. [ISO/IEC 9899:201x draft N1570](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) (widely asserted to be functionally equivalent to the official C11 standard, which you have to pay for) says: "Each of the operators < (less than), > (greater than), <= (less than or equal to), and >= (greater than or equal to) shall yield 1 if the specified relation is true and 0 if it is false.".

The usual trap when emulating booleans in a way that is compatible with old compilers is to write `MyFlags flags = MOUSE|KEYBOARD|GAMEPAD`, and then `SDL_bool have_gamepad = (flags & GAMEPAD)`, which will result in `have_gamepad` being set to either 0 or `GAMEPAD` where `GAMEPAD` is probably greater than 1.

**Comment by LunarLambda** [comment]
SDL already uses C11 features like anonymous structs/unions (in syswm, rwops), so there's really no standard-related reason not to use C99 bool.

The question about whether C++ bool and C _Bool are equivalent is perhaps warranted. The standards don't really mention language interop at all, so technically this extends to all types (outside of extern "C" declarations?)

But then again, it would be downright pathological of a compiler to not make these equivalent in the eyes of the C ABI.

**Comment by smcv** [comment]
Something that has been quite useful in GLib is to [write down its assumptions about the toolchain](https://gitlab.gnome.org/GNOME/glib/-/blob/main/docs/toolchain-requirements.md), so that contributors can know what subset of C11 they can safely assume. Perhaps SDL could benefit from having something similar? (Obviously there's no reason why SDL would have to make the same choices about what is or isn't required as GLib did.)

**Comment by icculus** [comment]
Okay, moving conversation back here from #8460--which has excellent information as well--my current thinking is:

- Change the typedef to an (unsigned? probably.) int.
- change SDL_TRUE and SDL_FALSE to defines (1 and 0).
- we don't use C99's bool, because this is a public type and we don't want to foist that requirement onto apps, the same way we use `//` comments internally but not in the public headers.

I do think we should make a decision on this soon, though, whether we go with this or something else.

**Comment by slouken** [comment]
It's pretty common to want to write a structure with boolean flags that takes the minimum amount of space, e.g. you don't want this to take 12 bytes:
```
struct ABC
{
    SDL_bool a:1;
    SDL_bool b:1;
    SDL_bool c:1;
}
```

One of the annoying things about the current SDL_bool implementation is that with some compilers it's not actually equivalent to C's boolean expression, which is why we have this:
```
SDL_bool foo()
{
    const int x = 1;
    return (x > 0) ? SDL_TRUE : SDL_FALSE;
}
```

I think if nothing else, we should fix that. I'll go ahead and run some experiments with SDL_bool as unsigned int.

**Comment by slouken** [comment]
So this is promising, it compiles in C and C++ with -Wall and -pedantic and no warnings:
```
#include <stdbool.h>

typedef unsigned int SDL_bool;

#define SDL_TRUE 1
#define SDL_FALSE 0

SDL_bool foo(SDL_bool input)
{
    SDL_bool a = true;
    SDL_bool b = false;
    SDL_bool c = (a == b);
    SDL_bool d = (a != b);

    return (a || b || c || d);
}

bool bar(bool input)
{
    bool a = SDL_TRUE;
    bool b = SDL_FALSE;
    bool c = (a == b);
    bool d = (a != b);

    return (a || b || c || d);
}

int main(int argc, char *argv[])
{
    foo(1 != 2);
    foo(true);
    bar(SDL_TRUE);
    return 0;
}
```

**Comment by slouken** [comment]
In contrast, here are the C++ warnings for the same program using SDL_bool as an enum:
```
testbool.cpp:19:11: error: cannot initialize a variable of type 'SDL_bool' with an rvalue of type 'bool'
        SDL_bool a = true;
                 ^   ~~~~
testbool.cpp:20:11: error: cannot initialize a variable of type 'SDL_bool' with an rvalue of type 'bool'
        SDL_bool b = false;
                 ^   ~~~~~
testbool.cpp:21:11: error: cannot initialize a variable of type 'SDL_bool' with an rvalue of type 'bool'
        SDL_bool c = (a == b);
                 ^   ~~~~~~~~
testbool.cpp:22:11: error: cannot initialize a variable of type 'SDL_bool' with an rvalue of type 'bool'
        SDL_bool d = (a != b);
                 ^   ~~~~~~~~
testbool.cpp:25:9: error: cannot initialize return object of type 'SDL_bool' with an rvalue of type 'bool'
        return (a || b || c || d || f);
               ^~~~~~~~~~~~~~~~~~~~~~~
testbool.cpp:34:11: error: cannot initialize a variable of type 'SDL_bool' with an lvalue of type 'bool'
        SDL_bool f = a;
                 ^   ~
testbool.cpp:41:2: error: no matching function for call to 'foo'
        foo(1 != 2);
        ^~~
testbool.cpp:17:10: note: candidate function not viable: no known conversion from 'bool' to 'SDL_bool' for 1st argument
SDL_bool foo(SDL_bool input)
         ^
testbool.cpp:42:2: error: no matching function for call to 'foo'
        foo(true);
        ^~~
testbool.cpp:17:10: note: candidate function not viable: no known conversion from 'bool' to 'SDL_bool' for 1st argument
SDL_bool foo(SDL_bool input)
         ^
8 errors generated.
```

**Comment by slouken** [comment]
Wow, this is way nicer. :)

**Comment by slouken** [comment]
This turned out to be a great solution, and I've merged it to main.

**Comment by icculus** [comment]
Now someone needs to grep for `? SDL_TRUE : SDL_FALSE` and remove all my shenanigans.  :)

**Comment by smcv** [comment]
> So this is promising, it compiles in C and C++ with -Wall and -pedantic and no warnings:

This is structurally very similar to GLib's `gboolean` (which has `typedef int gboolean`, `#define FALSE (0)` and `#define TRUE (!FALSE)`), which has been quite widely used in open source.

But, even better, it fixes the one significant problem with `gboolean`: you used an unsigned type, which makes it possible to use for bitfields.

**Comment by icculus** [comment]
> Now someone needs to grep for ? SDL_TRUE : SDL_FALSE and remove all my shenanigans. :)

I see Ozkan is already on it, haha

**Comment by sezero** [comment]
> Now someone needs to grep for `? SDL_TRUE : SDL_FALSE` and remove all my shenanigans. :)

Those were necessary especially in sdl2-compat, where we validate SDL3
symbol correctness in C++ mode (see: test_sdl3_syms.cpp). I cleaned up
sdl2-compat for it, but the compiler generates identical code from *.c
in most, if not all of the cases.

Other satellite libs have a few cases of them but are they really worth
going through now?

**Comment by icculus** [comment]
> Other satellite libs have a few cases of them but are they really worth going through now?

Nope. But let's clean them out when we're changing code anyhow.
