### ISSUE TITLE
Should SDL_RENDERER_PRESENTVSYNC be set or not when adaptive vsync is supported?

### ISSUE THREAD

**Issue by fukuchi** [libsdl-org/SDL#8004]
I'm using SDL 2.28.1 on the Xorg server of Ubuntu 22.04, on Thinkpad X1 Carbon with Intel UHD graphics. As far as I tested, some OpenGL applications are well vsync-ed, including glxgears. Then I noticed the problem while developing an application that calls SDL_RenderSetVSync().

My application calls SDL_RenderSetVSync() to enable vsync, but when I examined the RendererInfo after enabling vsync, SDL_RENDERER_PRESENTVSYNC was not to be set. Then I found that the SDL_GL_GetSwapInterval() returns -1, which means the adaptive sync was enabled, and the application was well vsync-ed and produced a constant refresh rate.

Here are my questions:

1) Why SDL_RENDERER_PRESENTVSYNC is not set, even though the adaptive sync is enabled?
2) Is there any way to know if adaptive sync is enabled in an environment using a renderer other than OpenGL?

**Comment by icculus** [comment]
Okay, this is happening because of this code in X11_GL_GetSwapInterval:

https://github.com/libsdl-org/SDL/blob/c331b64d796d2abf2fd03ec72f733642483d3623/src/video/x11/SDL_x11opengl.c#L935-L937

[The GLX_EXT_swap_control_tear spec](https://registry.khronos.org/OpenGL/extensions/EXT/GLX_EXT_swap_control_tear.txt) uses some ambiguous language here (emphasis mine)...

> The application can also determine whether a particular drawable allows late unsynchronized swaps to occur by calling glXQueryDrawable with the attribute GLX_LATE_SWAPS_TEAR_EXT. **If late swaps are enabled**, <value> will be set to 1; otherwise, it will be set to 0.

Mesa (as of Ubuntu 23.04, at least) appears to interpret the bolded text to mean "if the Drawable is capable of having a negative swap interval set" and seems to always return 1 if you have a modern Mesa with the extension. Nvidia's current drivers appear to interpret it to mean "if the app has currently set a negative swap interval for this Drawable" and returns 1 or 0 based on that.

glXQueryDrawable returns values as unsigned ints...in Mesa's case, it'll return a -1 cast to an unsigned int for adaptive vsync. Nvidia will return a 1 and presumably expect you to check GLX_LATE_SWAPS_TEAR_EXT.

One of these implementations is clearly incorrect, but I don't know which.

BUT: on Mesa, setting a swap interval of 1 makes SDL_GL_GetSwapInterval return -1, and setting -1 returns 1, and that's wrong on our part.

**Comment by fukuchi** [comment]
As a developer working on a 2D application, understanding whether vsync is enabled is usually sufficient. Ideally, when vsync is activated, SDL_RENDER_PRESENTVSYNC should be set accurately, regardless of whether it's a kind of adaptive sync. The distinction between adaptive sync and standard vsync may not be a major concern for many developers.

On the other hand, I was curious about this because I am experimenting with vsync on SDL. Although I'm comfortable with various renderers implementing different methods to achieve the detailed information of the vsync, having a unified method would be better, particularly for developers focused on time intervals between frames seriously (if I understand the adaptive sync correctly - that's why I'm experimenting with adaptive sync).

**Comment by icculus** [comment]
Agreed, I'll see about improving this in SDL.

**Comment by icculus** [comment]
I opened a report on the Mesa bug tracker [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10193), but even if Mesa or Nvidia changes their GL, we'll have to deal with existing builds...what I'm going to do is try setting specific swap intervals and checking what values we get back, and then we'll know which behavior we're dealing with at runtime.

**Comment by icculus** [comment]
Okay, the SDL_RENDERER_PRESENTVSYNC (and SDL_GL_GetSwapInterval) should now do the right thing, in both the SDL2 and SDL3 branches!

**Comment by icculus** [comment]
Update on this issue: the Mesa team is about to merge a change to make their implementation match Nvidia's for the GLX_EXT_swap_control_tear extension: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/31655

SDL won't need any changes; newer Mesa builds with the change will land in what was the Nvidia-specific handler, and older Mesas will use what was the Mesa-specific code, so we're already good to go here.
