### ISSUE TITLE
Can't get OS shortcuts to be ignored on OS X

### ISSUE THREAD

**Issue by frranck** [libsdl-org/SDL#8007]
Hello, 
I'm using SDL2 2.28.1 on OS X. How do I get to avoid shortcuts to interrupt the game? 
I tried:
```
      SDL_SetHint(SDL_HINT_GRAB_KEYBOARD, "1");
      SDL_SetWindowGrab(window, SDL_TRUE);
```
but I still get random shortcuts like screenshots or App Exposé to get triggered when the game window is active.

**Comment by icculus** [comment]
So this is happening because of this `#ifdef` ...

https://github.com/libsdl-org/SDL/blob/08c6ac1b16eae832a2e01a5e257b2c8eafa154a1/src/video/cocoa/SDL_cocoakeyboard.m#L462-L464

...if you remove that `#ifdef` so the call to CGSSetGlobalHotKeyOperatingMode is compiled in, it successfully disables Exposé, etc.

***BUT:*** this define is there because it's not a public API and is thus forbidden in Mac App Store builds. I presume we can't even hide it behind a hint, because the App Store submission process will be upset that we linked against that symbol _at all_, whether it's called or not.

[This guy](https://stackoverflow.com/a/58012972) says you can _in theory_ cheat to use it there...

> The answer ended up involving CGSSetGlobalHotKeyOperatingMode(). This is not a public API, but there are a number of Mac App Store apps which use it by obfuscating the function name and looking it up dynamically. Apple doesn't seem to mind.

...but this is _not_ a good idea, because I'm confident Apple _does_ mind and some day will start detecting this without prior notice, and might even ban developers for evading their existing submission checks.

So I'm going to close this as WONTFIX...but if you want to ship a build of SDL with your app that uses this, remove that `#ifdef` and don't publish on the App Store.

One last note: if your app's window is SDL_WINDOW_FULLSCREEN or SDL_WINDOW_FULLSCREEN_DESKTOP, it will ignore Exposé keys without using SDL_SetWindowGrab at all, without making changes to the SDL source code, and without violating Mac App Store policies; all of this is only a problem in windowed mode. For what it's worth.

**Comment by frranck** [comment]
Thanks for the input, I actually had change to SDL_WINDOW_FULLSCREEN.
