### ISSUE TITLE
SDL_WINDOWPOS_CENTERED broken in 2.28.0 when using sdl renderer

### ISSUE THREAD

**Issue by Qwinci** [libsdl-org/SDL#8029]
Creating an sdl renderer causes the window to get moved to the top left of the screen when using SDL_WINDOWPOS_CENTERED on sdl 2.28.0/2.28.1. I bisected the exact problematic commit to aa536217b3e1a9ea4a5de9944cadbd79b134a41a. When not creating an sdl renderer the window stays centered like it should (when creating the renderer SDL_ShowWindow gets called in SDL_RecreateWindow which in turn is called from eg. GL_CreateRenderer).

**Comment by icculus** [comment]
New proposal for SDL2: let's revert this change, and instead make it so it pumps the event loop and waits up to X milliseconds for a change in SDL_GetWindowPosition/SDL_GetWindowSize if we think an async move/resize is pending (and not do that work if there's no reason to believe a response from the window manager is still outstanding).

All of these bugs happening because we're trying to coerce this to be synchronous are because the app is trying to query the result right after trying to set it, so let's move the burden to those queries and leave everyone else alone.

(and, as we're discussing in #7907, for SDL3 we should probably _just stop struggling against this completely_, but that hasn't been decided yet.)

**Comment by icculus** [comment]
Reverted in 5c3df60ec913f5b0fd04835af56f3afd42694893 for SDL2 branch and 133ad1915c4f444cb042808e4378f55bf54e8351 for release-2.28.x branch.

SDL3 will be dealt with a little later, in #7907.
