### ISSUE TITLE
Support for borderless window snapping on windows 

### ISSUE THREAD

**Issue by wobbier** [libsdl-org/SDL#8043]
I've searched all over the place for this type of support over the years ( and have recently asked our AI gods if this is supported )
I know GLFW supports this in some capacity.

I'm searching for a solution that allows native windows aero snapping using custom drag callbacks. (which would also mean supporting the FancyZones feature in PowerToys.)

I'm hoping that this ticket provides some sort of insight into this problem (if any) that could also be archived and found via search engines in the future.

I haven't found anything, but please do fill this ticket out with the relevant information for future users :) 

Thanks!

**Comment by takase1121** [comment]
Hi, I've also been there, and I found these two [**undocumented hints**](https://github.com/lite-xl/lite-xl/blob/7955fa1d367b68944a42d827e4d6ae04c0453975/src/main.c#L158) useful. They allow borderless windows to act just like a normal window with one problem - the window surface may be offsetted due to drop shadows.

These hints are undocumented - they're subjected to change and might not work at all. Use at your own risk.

**Comment by Klemmbaustein** [comment]
are there any plans on making this easier? because i need that functionality, but the weird window offset is making this difficult for me.

**Comment by slouken** [comment]
The `"SDL_BORDERLESS_WINDOWED_STYLE"` is true by default, so you get the behavior you expect. The `"SDL_BORDERLESS_RESIZABLE_STYLE"` hint is false by default because Windows doesn't render these windows correctly in some cases. They're both undocumented because changing them affects your program in ways you probably don't want.
