### ISSUE TITLE
audio test applications don't work on emscripten

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL#8101]
With `audioinfo` and `testmultiaudio`, I see this error in the console:
```
ERROR: Couldn't initialize SDL: SDL not built with thread support
```

**Comment by icculus** [comment]
So I don't know which call does it specifically, here, but the new audio code makes several mutexes, etc, even if the audio subsystem doesn't actually use a thread behind the scenes, because it doesn't know that the app won't try to access things from multiple threads...so this currently fails in src/thread/generic/SDL_syssem.c, if `SDL_THREADS_DISABLED` is defined, because SDL_CreateMutex fails.

I'm wondering if we should have a thing where these primitives succeed and run under the assumption that only a single thread ever calls them (so mutexes always successfully lock and unlock without blocking, as a no-op, etc), and the only thing that should truly _fail_ is SDL_CreateThread.

This might have ramifications I haven't considered, in which case I'll just deal with this in the audio code in some way.

**Comment by slouken** [comment]
That actually seems like a good idea.

**Comment by icculus** [comment]
Turns out it mostly works this way already; the problem is the generic RWlock code tries to create an SDL_Condition and blows up. The generic mutex code has most of its work wrapped in `#ifndef SDL_THREADS_DISABLED`, so I just need to match that in the rwlock code.

**Comment by icculus** [comment]
Okay, testaudioinfo is up and running on single-threaded Emscripten again. I assume testmultiaudio also works, but haven't tried it.

**Comment by madebr** [comment]
They all work!!
`testaudiocapture` plays back audio too fast: #8114
