### ISSUE TITLE
SDL_LogCritical Error format string

### ISSUE THREAD

**Issue by NoxFly** [libsdl-org/SDL#8130]
Using this function as follow : 
```cpp
SDL_LogCritical(SDL_LogCategory::SDL_LOG_CATEGORY_ERROR, SDL_GetError());
```
Leaves the compiler (g++ 12.3) on Ubuntu 23.04 with this error : 
```
src/main.cpp:14:32: error: format not a string literal and no format arguments [-Werror=format-security]
   14 |                 SDL_LogCritical(SDL_LogCategory::SDL_LOG_CATEGORY_ERROR, SDL_GetError());
```
The flag `-Werror=format-security` is not enabled by my own, so I guess it's by g++ default configuration.

I am using this function wrongly ? I've followed a youtube video using it like that, but on IntelliJ, and its compiler did not complain.

**Comment by madebr** [comment]
Try this:
```c++
SDL_LogCritical(SDL_LogCategory::SDL_LOG_CATEGORY_ERROR, "%s", SDL_GetError());
```

**Comment by NoxFly** [comment]
Yes, this is working. It's just a bit weird to do that but it's okay.

**Comment by icculus** [comment]
Yeah, the problem is if SDL_GetError() were to return a string that says "This is a security hole! %s" then SDL_LogCritical would then look for an string argument that isn't there, possibly crashing the program. This is why the compiler warns about this. By explicitly saying "%s" here, it doesn't matter what SDL_GetError() contains, because you've told it your format is exactly one string variable.
