### ISSUE TITLE
SDL3 migration information lacking SDL_SendKeyboardKey changes

### ISSUE THREAD

**Issue by DominusExult** [libsdl-org/SDL#8172]
SDL_SendKeyboardKey now needs three arguments` (Uint64 timestamp, Uint8 state, SDL_Scancode scancode)` while it previously needed only two `(Uint8 state, SDL_Scancode scancode)`.
If you pass only two arguments in your code, it doesn't throw a warning or a failure, maybe it should.
And the migration guide does not mention it (AFAICT).

**Comment by sezero** [comment]
It's not a public api but a private one. Do you have issues with it in maintaining a port of SDL??

**Comment by DominusExult** [comment]
So I guess we should use it different for our port of Exult for iOS, right?

https://github.com/exult/exult/blob/master/ios/ios_utils.mm

With this we add an overlay button  to be able to press ESC on the screen.

**Comment by sezero** [comment]
@slouken to your rescue

**Comment by DominusExult** [comment]
I mean I can make this code work again by adding the new first argument.
Just wondering now whether it is really not the way we should do it to begin with. This was done 8 years ago ;)

**Comment by sezero** [comment]
> Just wondering now whether it is really not the way we should do it to begin with. This was done 8 years ago ;)

Using private apis is never the the way it should be done :)

**Comment by slouken** [comment]
The migration guide only documents API changes, not internal changes. If you're including src/events/SDL_keyboard_c.h you should have gotten a compiler warning, since the prototype changed.

You can fix it just by adding the new timestamp argument. :)

However, an even better way to fix it, for a one-off case like this, is to just to create and send the keyboard event directly, using the public API `SDL_PushEvent()`

**Comment by DominusExult** [comment]
Thanks, I'll open an issue on our tracker to unuse the private API.
