### ISSUE TITLE
Joystick regression since SDL 2.0.16, Windows 11

### ISSUE THREAD

**Issue by KingOfIce77** [libsdl-org/SDL#8227]
Some time after SDL 2.0.16, some game devices disappeared (pedals and 2 of my 3 button boxes).

Here are the results for the pygame code :

```
pygame.joystick.init()
ljoysticks = [pygame.joystick.Joystick(x) for x in range(pygame.joystick.get_count())]
print([j.get_name() for j in ljoysticks])

```
SDL 2.0.16 with pygame 2.4.0 result :

- ['FANATEC Podium Wheel Base DD2', 'DSD CSW Panel', 'DSD CSW Panel', 'FANATEC ClubSport Pedals V3', 'DSD uBox Type One', 'FANATEC Podium Wheel Base DD2']

SDL 2.28.0 with pygame 2.5.1 result :

- ['FANATEC Podium Wheel Base DD2', 'FANATEC Podium Wheel Base DD2']

pygame issue here : [https://github.com/pygame/pygame/issues/3942]

**Comment by Starbuck5** [comment]
Pygame on Windows 2.4.0 uses SDL 2.26.4, pygame 2.5.1 uses SDL 2.28.2, and pygame 2.5.0 uses SDL 2.28.0. Tested by installing those versions and checking the support prompt.

So as far as I can tell this issue should read joystick regression between 2.26.4 and 2.28.0.

**Comment by Starbuck5** [comment]
Looks like it could be this commit on SDL's end: https://github.com/libsdl-org/SDL/commit/d42c303b2499a3c3451fbabcbb2b78b0d99e57d4

**Comment by IOBYTE** [comment]
This commit https://github.com/libsdl-org/SDL/commit/d42c303b2499a3c3451fbabcbb2b78b0d99e57d4 also breaks my pedals on Windows 10 and linux because they have axes but no buttons.  Button boxes will also break because they have buttons but no axes.  The right way to fix the problem this commit is trying to fix is to add the problem device to the black list.  This commit should be reverted.

**Comment by IOBYTE** [comment]
Linux is broken for my pedals but that must be a different problem.

**Comment by IOBYTE** [comment]
The linux problem is similar. SDL_EVDEV_GuessDeviceClass assumes a joystick with 3 axes but no buttons is an accelerometer.  My pedals have 3 axes and no buttons so it's ignored.

**Comment by TheFloatingWidget** [comment]
Also seeing this problem with 2.28.3, don't think we had it when using 2.24.1 (which easily pre-dates the suspicious commit you've called out). Is it worth putting up a merge request that reverts that commit?

**Comment by IOBYTE** [comment]
I think https://github.com/libsdl-org/SDL/commit/d42c303b2499a3c3451fbabcbb2b78b0d99e57d4 should be reverted. There is code elsewhere that already solves the same problem. 

The linux problem is more complicated.  One way would be to add a PEDALS joystick type and add a whitelist for known devices or add a blacklist for known accelerometers.  Both are maintenance nightmares keeping the lists up to date.

**Comment by TheFloatingWidget** [comment]
I've rolled back to v2.26.5 and all controllers are working again.

**Comment by smcv** [comment]
> The linux problem is more complicated. One way would be to add a PEDALS joystick type and add a whitelist for known devices or add a blacklist for known accelerometers. Both are maintenance nightmares keeping the lists up to date.

Right, there's really no good answer to this: evdev doesn't tell us what a device is, only what capabilities it has, but evdev capabilities are not enough to distinguish between a 3-axis accelerometer and 3-axis pedals because both are simply reported as (X, Y, Z).

I think the best long term answer would be for the kernel (which has better information) to report what a device is. There is already a way for it to report that a device is definitely an accelerometer, by setting `INPUT_PROP_ACCELEROMETER`, but there is currently no way for it to report that a device is definitely a joystick; and even if there was, SDL would need to do *something* (a heuristic involving axes, buttons, and a denylist or allowlist) for ambiguous devices that have neither property.

**Comment by IOBYTE** [comment]
Yes.  There are 2 separate bugs. One is in Windows and one is in linux specific code.  They both make assumptions for the joystick type using the number of buttons and axes that are wrong.  The result is the same for windows and linux. The same problem probably exists in other interface code. Extending the existing platform independent whitelist/blacklist code to handle this problem is probably the correct way to fix this.  Adding the ability for the application to add to the device lists would help work around bugs like this for unknown hardware.

**Comment by IOBYTE** [comment]
I reverted https://github.com/libsdl-org/SDL/commit/d42c303b2499a3c3451fbabcbb2b78b0d99e57d4 locally and my pedals were recognized and worked on Windows 10.

**Comment by slouken** [comment]
Reverted, thanks!

**Comment by IOBYTE** [comment]
I managed to get my pedals working on linux by adding a udev rule that set the permissions properly and changed the device type from ACCELEROMETER to JOYSTICK.

**Comment by KingOfIce77** [comment]
Why reopen and reapply the bug?

**Comment by slouken** [comment]
Because this fix caused a bunch of other bugs. As noted in the commit, we need to find a better way to distinguish between gaming mice and pedals.

**Comment by KingOfIce77** [comment]
Ah ok... I guess it's a matter of point of view because for me everything worked perfectly before this modification (and I have a lot of "game components" as simracer)

**Comment by KingOfIce77** [comment]
mouse is a game component !?

**Comment by IOBYTE** [comment]
You need to add the devices to ignore to SDL_ShouldIgnoreJoystick.  Hard coded lists are not future proof but that's a whole other issue.  You could add more hard coded lists for pedals and button boxes.

You shouldn't be making assumptions like this in driver/os dependent code so reverting the revert is wrong no matter how it eventually gets fixed.

The hard coded lists should be moved to a file in the future to fix this problem.
