### ISSUE TITLE
Migrate default audio device

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8330]
If the audio driver doesn't support default audio devices, we should migrate the default device ourselves when an audio device is connected and disconnected. Otherwise you're stuck in a situation where on some platforms the application doesn't need to think about it, and on other platforms it's stuck with no audio if an audio device is unplugged and then plugged back in.

If all audio devices are disconnected, we should probably get an audio removed event for the default audio device (output or capture appropriately), and if we don't have any audio devices, we should probably get an audio added event for the default audio device.

**Comment by icculus** [comment]
Working on this, and it's easy to say "something new got plugged in and this platform doesn't have any better guidance, so let's make it the new default," but what are we meant to do if someone unplugs the current default device? Do we leave it as a zombie until something new is plugged in, or do we pick a different device that's still available? And of the devices still available, how do we choose one?

My workstation's motherboard has a whole bunch of things, like headphone jacks for headphones, and a bunch more for plugging in a bunch of speakers for surround sound, then an S/PDIF port...and all of these are unused, because it's actually sending audio to my monitor via the DisplayPort connector on the GPU, so choosing any of them would be disastrous.

I'm wondering if the real problem here is not that we should fake this, but that ALSA doesn't offer it.

The only backends that can detect a default device change are Pulse, PipeWire, WASAPI, DirectSound, and CoreAudio. Almost everything else only offers a single system output, or they're ancient APIs like /dev/dsp where no one is demanding dynamic device management.

The only odd duck in there is ALSA. Maybe we can coerce this backend to work better instead?

**Comment by slouken** [comment]
If the only odd duck here is ALSA, then let's leave this alone for now. Steam Link uses it's own logic to pick the next audio device, and I'm thinking ALSA will be deprecated in favor of pipewire in the long run.
