### ISSUE TITLE
Operations in an audio event filter

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8331]
Some things an application might want to do in a filter function processing audio device events:
* Look up what devices are bound to open streams
* Open or close audio devices

These should probably be supported and tested in automated tests.

**Comment by icculus** [comment]
We're probably going to need to put in an SDL hint or something to tell the system to fake a disconnect event at the right moment, since we can't automate a physical device unplug, and pushing an event won't be enough, we'll need this to wreak havoc from the PulseAudio hotplug thread to actually test the thing that's most likely to explode.

Or maybe a simple script that can tell the OS level "destroy this device" so SDL has to react to actual device losses/format changes/whatever, if that's possible.

In the short term, I'm just going to manually unplug things to shake out the initial bugs.

**Comment by icculus** [comment]
Okay, so the easiest (and arguably, most correct) solution is to destroy the disconnected devices before sending the event, which would match what this looks like when the event is retrieved in the normal event loop and prevents shenanigans...but SDL_GetAudioStreamDevice() will return 0, since it would no longer be bound to a device when the event filter runs. It's still safe to destroy the stream in the filter, and if you didn't do this from an event filter, the device ID would be zero when you get the event.

But if you _absolutely_ need that device ID and can't just react to the stream being bound to nothing in the filter's SDL_EVENT_AUDIO_DEVICE_REMOVED code, we can add a flag to the device to say "we're disconnecting and running an event filter, don't actually do anything with this device until the filter returns."

**Comment by slouken** [comment]
I think having the state be the same as when the event would normally be processed in the event loop makes sense. If necessary I can cache off the device ID or treat getting an ID of 0 as meaning that the stream was disconnected.

**Comment by icculus** [comment]
Give the latest a try and see if it works for you.

**Comment by slouken** [comment]
Works great, thanks!

**Comment by icculus** [comment]
@slouken: just pushed a change to how disconnect events behave in event filters (devices continue to exist, streams continue to be bound, etc, and the device acts like it still works until you explicitly close it).

Once you update, make sure this still works for you.
