### ISSUE TITLE
Error cleanliness

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8421]
We frequently get bug reports saying there is an SDL error message when the API returns success. In the past we've mentioned that you should only check the error if a function fails.

Because it happens so frequently, maybe we should change this for SDL3?

The basic idea would be that we change SDL internals to clear the error state when an error is handled, and change the automated tests to verify that there is no error message when an API succeeds.

Relevant issues:
https://github.com/libsdl-org/SDL/pull/8419
https://github.com/libsdl-org/SDL/issues/8420

@libsdl-org/a-team, thoughts?

**Comment by icculus** [comment]
> when an error is handled

What does this entail? Clear it when SDL_GetError() is called?

**Comment by 1bsyl** [comment]
From, a user point of view, I think it's nice to see there was at some point an error, even if it's not because of the last SDL function call. So you can at some point print the errors. an see if something goes wrong while not checking it.

But, if a SDL function succeed, it should not set an error, nor clear any previous error.
(so if an error happens, because of a sub SDL call failing, we should store any previous error, an re-set it afterwards..)

**Comment by icculus** [comment]
We _could_ just go for quick-and-dirty, and add a github issue template that prefills bug reports with the text "SDL_GetError only means something if the last API call reported an error. If you didn't check the return value, please close this browser tab."   :)

Alternately, there are a handful of tactical places where we could clear the error message before returning success and solve 90% of the problem: SDL_Init, SDL_CreateRenderer, etc...places that might set several errors as it tries various platform-level APIs before it finds one that works, and where people are likely to misuse SDL's API like this because they're still banging out Hello World apps...this wouldn't need any major code changes and might be Good Enough.

**Comment by slouken** [comment]
I'm tempted to add something like:
```
return SDL_ClearError(); // Always returns 0
```
