### ISSUE TITLE
3rd Party controller is not being detected

### ISSUE THREAD

**Issue by idrkwhattoput** [libsdl-org/SDL#8455]
It appears that SDL2 is not detecting my 3rd party controller, however older versions of SDL actually detects my controller and i can configure its input maps perfectly. (Regression issue maybe?)

(assuming I'm using an emulator)

**Comment by slouken** [comment]
What controller are you using, what operating system is SDL running on, and what is the correct mapping for the controller?

**Comment by idrkwhattoput** [comment]
> What controller are you using, what operating system is SDL running on, and what is the correct mapping for the controller?

well its a generic usb joystick controller, the SDL is "running" (SDL2.DLL) in windows 10 (ryujinx emulator), i didn't get the "correct mapping" where you asked for it but i think you are asking about this? 
![0uiwkwj9](https://github.com/libsdl-org/SDL/assets/146492894/34260324-3e29-409e-99fa-b845bb4a55f2)
![8jm2lhod](https://github.com/libsdl-org/SDL/assets/146492894/32519427-c4b2-4cea-b8f1-3e5c0ade4a72)

**Comment by slouken** [comment]
Ah, yes, the mapping for this controller was explicitly removed because there are a bunch of different controllers with different mappings that all use the same identical circuit board. Since we can't tell which mapping to use, we removed the mapping entirely, and rely on the application (emulator in this case) to allow you to remap the controller.

If your application doesn't allow mapping controllers, you can create a mapping with testcontroller in the SDL3 source code or [AntiMicroX](https://sourceforge.net/projects/antimicrox/) and set the mapping string in the `SDL_GAMECONTROLLERCONFIG` environment variable.

FYI, a valid mapping string looks like this (as an example from a PS4 controller)
```
030000004c050000c405000000010000,PS4 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,platform:Mac OS X,
```
