### ISSUE TITLE
Always call `SDL_CleanupEvent()`

### ISSUE THREAD

**Issue by namandixit** [libsdl-org/SDL#8476]
Currently, the [documentation](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_eventsh) states that the `SDL_CleanupEvent()` must only be called after specific events. This is problematic, since a future ABI compatible version of SDL may add more such events that wouldn't be handled by the compiled application.

So, is it safe to `SDL_CleanupEvent()` always, after each event? If no, I'd recommend to have it that way; and if yes, then it should be documented and mandated to preserve SDL's forward-compatibility guarantees.

**Comment by Kaktus514** [comment]
The [documentation comments](https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_events.h#L920) for `SDL_CleanupEvent()` says:
> It is safe, but not necessary, to call this function for other event types.

As a user it seems like a good idea to always call this function for all events because I might not care or be aware of all the event types and, as you said, new event types that require cleanup might be added in the future.

**Comment by icculus** [comment]
I agree, we should probably say it must always be called or you risk memory leaks.

**Comment by slouken** [comment]
You're right. And that's what I was hoping to avoid - having to call again into the API for every event that's processed.

Hmmm....

**Comment by slouken** [comment]
I'm working on a solution now.

**Comment by slouken** [comment]
Fixed
