### ISSUE TITLE
Destroy functions should take a pointer parameter?

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#8621]
As suggested in https://github.com/libsdl-org/SDL/issues/7799#issuecomment-1824864241, maybe the Destroy functions should take a pointer to the object they're destroying so they can set it to 0 while any locks are held?

@libsdl-org/a-team, thoughts?

**Comment by icculus** [comment]
> while any locks are held?

If you're destroying an object when anything might still care about the locks, you're in a lot of trouble.

I'm inclined to say no to this, locks or otherwise; it's a big change to do to all the SDL_Destroy* functions, and it's still going to leave you with little leaky API things like SDL_free() not doing this.

**Comment by 1vanK** [comment]
Just add `SDL_SafeDestroyProperties(SDL_PropertiesID& props)`
