### ISSUE TITLE
Android_Project Inception

### ISSUE THREAD

**Issue by Wolf1098** [libsdl-org/SDL#8680]
To get a build out of your official toolchain for android, one has to 'incept' the project as a submodule of it self in the android_project folder, can we move this to a seperate repo for the build tools, don't have to have issues there. Point in the readme over to the src repo issues here, where i've posted.

**Comment by Wolf1098** [comment]
doing so would allow optionally allow the src repo to pull in sdl_ mixins and what not on a per branch level, semi automatically, allowing semi-easy flavouring and bundling???

**Comment by slouken** [comment]
Do you have a link to your instructions and discussion?

**Comment by Ravbug** [comment]
I maintain a separate android project proof-of-concept repo. It's worked quite well for me, making it easy to open SDL projects in Android Studio and take advantage of all of the IDE features it provides. 

https://github.com/ravbug/sdl-android-builder

Maybe something like this would work as an official SDL android project?

**Comment by madebr** [comment]
In https://github.com/libsdl-org/SDL/issues/6315, we discussed adding SDL as a package to some maven repo.
We ended up not doing that because it complicates the release process: we don't want to depend on an external service.

Instead, the official release would include a android archive (=files that end with `.aar`): e.g. `SDL3-3.1.2.aar`.
An example of such an archive can be found at [the bottom of this workflow run](https://github.com/madebr/SDL/actions/runs/10518221134).
An example of a project that makes use of this archive is [sdlcross](https://github.com/madebr/sdlcross).

8Observer recently tried this out, and documented his adventure [here](https://8observer8.github.io/tutorials/deploy/sdl3-app-on-android/public/index.html).
