### ISSUE TITLE
SDL crash with X11 and nvidia drivers on linux! (OpenGL)

### ISSUE THREAD

**Issue by Cesio137** [libsdl-org/SDL#8700]
I am having a problem that SDL fails when creating a window using the NVidia and X11 drivers. I used the API GLFW to troubleshoot the problem, but GLFW performed well in the tests.

> Error:

`X Error of failed request:  GLXBadDrawable`
`Major opcode of failed request:  151 (GLX)`
`Minor opcode of failed request:  5 (X_GLXMakeCurrent)`
`Serial number of failed request:  219`
`Current serial number in output stream:  219`

> OS:

**Linux tested: Ubuntu 22.04, Fedora 39, Pop OS**
**Window manager: X11**
**Nvidia Driver: 545 and 470**

**SDL: 2.28.5**
**Glad: https://gen.glad.sh**
**HEADER: https://github.com/Cesio137/Nanometro/blob/master/Engine/Source/Runtime/Renderer/OpenGL/OpenGL.h**
**CPP: https://github.com/Cesio137/Nanometro/blob/master/Engine/Source/Runtime/Renderer/OpenGL/OpenGL.cpp**

**Comment by icculus** [comment]
Don't create a GL context with SDL_GL_CreateContext if you are also going to use the render API, since it will also create one.

**Comment by icculus** [comment]
(Although, since this code seems to want to use OpenGL directly, maybe I should say "don't call SDL_CreateRenderer" instead.)

**Comment by Cesio137** [comment]
> (Although, since this code seems to want to use OpenGL directly, maybe I should say "don't call SDL_CreateRenderer" instead.)
@icculus 

Right, it’s now working on Linux with the NVidia driver. Thanks XD. I only have two more questions!

1. But should I not use "SDL_CreateRenderer" only on linux? Is the same valid for Windows and Mac?
2. Can I use "SDL_RENDERER_ACCELERATED" in the function "SDL_CreateWindow" to use Hardware acceleration?

**Comment by icculus** [comment]
> But should I not use "SDL_CreateRenderer" only on linux? Is the same valid for Windows and Mac?

You shouldn't use it _anywhere_ if you just plan to draw by calling OpenGL functions directly. SDL_CreateRenderer gives you access to a 2D renderer that might happen to use OpenGL behind the scenes, but if you don't need that, don't create one at all, since it'll want to make it's own GL context in the window and cause problems.

If you're _only_ using OpenGL, (you draw with things like glDrawArrays(), etc, and not with things like SDL_RenderCopy()), then don't create a renderer. Do the things you already did: create the window with SDL_WINDOW_OPENGL, call SDL_GL_SetAttribute and SDL_GL_CreateContext to get OpenGL ready, then call SDL_GL_SwapWindow() to get the things you draw with OpenGL onto the screen, and don't create an SDL renderer at all. This will do the right thing on all platforms.

> Can I use "SDL_RENDERER_ACCELERATED" in the function "SDL_CreateWindow" to use Hardware acceleration?

No, that flag is only for SDL_CreateRenderer(), used to say "please don't give me a software renderer under any circumstances."

You'll get hardware acceleration by default with OpenGL, unless the user doesn't have video drivers installed or you try to configure the context in an extremely weird way. Definitely create the window with the SDL_WINDOW_OPENGL flag, though, so it's prepared for the GL context you're about to create.


This should get you going, so I'm going to close this issue; if you have further questions, I don't mind answering, but I'd strongly recommend you come talk on [our forums](https://discourse.libsdl.org/) instead, so more people can jump into the conversation and help!
