### ISSUE TITLE
Suggestion: Add a method (or other mechanism) to tell SDL whether the application uses DBus independently

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/SDL#8764]
Related to #8272, possibly others.

Since many applications that use SDL most often don't handle DBus directly, would it be possible to have SDL support some mechanism to signal that full control over DBus is left to SDL? This would avoid the memory leak as described in #8272, while still allowing apps to use DBus directly.

----------

One possible way it could work:
```c
#include <SDL3/SDL.h>

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);

    // ...

    // Anywhere before SDL_Quit(), or unloading the subsystem(s) that use DBus
    SDL_SetDBusKeepAlive(1);

    SDL_Quit();
    return 0;
}
```

Other possibilities would include passing an extra flag to either SDL_Init or SDL_Quit.

The only issue with this is that apps that already are in this situation with SDL2 now have to add an extra call, flag, or some other code for their projects to keep working. This is why I think it would be a good idea to pass this with SDL3 changes.

It would also be possible to reverse the situation and put the burden on non-users of DBus to enable the automatic shutdown of DBus by SDL. It would have the upside that someone forgetting about the flag will result only in a memory leak, which is arguably better than a crash, but I personally think it would be more intuitive to put the burden on DBus users, since they're already thinking about DBus, versus non-DBus users who might not even be aware about that it exists. Plus, a crash is an excellent safeguard against oversights ;-)

**Comment by slouken** [comment]
@smcv, we're not leaking a global system resource here, right? This would just make memory leak checkers happy?

If that's the case, I'm inclined not to do this. It's much better to have memory left around that is cleaned up by the OS when the application quits than having applications crash.

**Comment by Semphriss** [comment]
The problem is that I have to work on a program that closes SDL long before the rest of the application actually quits, and it would profit from not carrying the remaining footprint of SDL while it's not in use.

If this is done correctly, no crash would ever need to happen in any kind of application, no matter the use case, outside of the regular memory management mistakes that are general to C/C++ anyways.

**Comment by slouken** [comment]
It sounds like this would best be done as a hint, for your use case.

**Comment by Semphriss** [comment]
Would that be a good solution? If that's the best option, I can take the responsibility to write the code.

**Comment by slouken** [comment]
Sure, go for it. Please default the hint to the current behavior.

**Comment by smcv** [comment]
If this is a mechanism to make SDL call `dbus_shutdown()`, be aware that it is only safe to call `dbus_shutdown()` if you know that, out of all your dependencies, including recursive dependencies and plugins, none of them will call into libdbus after the `dbus_shutdown()` call. In practice you can't ever know that on end-user systems, because your application might be calling into (for example) third-party glibc name service switch plugins, which might (rarely) be using libdbus.

On a developer system where you're using valgrind or other memory-leak checkers, perhaps you can know that well enough to get away with it.

> we're not leaking a global system resource here, right? This would just make memory leak checkers happy?

Yes. If you close the `dbus.system_conn` and `dbus.session_conn`, then the only things remaining allocated in libdbus should be memory and mutexes.

(If SDL was using `dbus_bus_get()` then that would probably be "leaking" one file descriptor per bus per process, and the corresponding resources inside the message bus daemon, until the SDL-using process exits; but SDL doesn't do that.)

**Comment by smcv** [comment]
To clarify what I said about recursive dependencies, a very common "hidden" use of libdbus is that the Pipewire and PulseAudio client libraries will load it. As long as those client libraries are loaded, it's unsafe to `dbus_shutdown()`.
