### ISSUE TITLE
 in osx, first one or two  SDLK_LEFT .. presses delayed!

### ISSUE THREAD

**Issue by mumin16osx** [libsdl-org/SDL#8839]
in osx(sonoma), first one or two  SDLK_LEFT .. presses delayed!  then it is back to normal.

**Comment by icculus** [comment]
This is working here (macOS Sonoma 14.2.1)...

https://github.com/libsdl-org/SDL/assets/673562/03b67b91-e552-4f9d-8afa-ba6ae549c01d

That's me launching testsprite2 with the latest in the SDL2 branch and tapping left shift a few times as soon as possible; you can see it logging the shift key events in the terminal window.

If there's a reproduction case I can try, please let me know. Otherwise: maybe there's a macOS accessibility setting that's delaying keypresses, or something...?

**Comment by icculus** [comment]
Just realized this said LEFT and not left shift, retesting...

**Comment by icculus** [comment]
Nope, SDLK_LEFT is working here, too. Something else is up.

**Comment by icculus** [comment]
I'm closing this bug, as it doesn't reproduce here with the information available. If you have more information, feel free to add it here when you have a chance and we can reopen the bug if appropriate.

Thanks!
