### ISSUE TITLE
HINT_WINDOWS_DPI_SCALING + HINT_MOUSE_RELATIVE_MODE_WARP + RelativeMouseMode => crash on some Windows 11 systems

### ISSUE THREAD

**Issue by FeralChild64** [libsdl-org/SDL#8940]
See the example source code in the attachment - executing it and clicking inside the window leads to a crash on some Windows 11 systems:

[SDL-Test.zip](https://github.com/libsdl-org/SDL/files/14076528/SDL-Test.zip)

```C
SDL_SetHint(SDL_HINT_WINDOWS_DPI_SCALING, "1");
SDL_SetHintWithPriority(SDL_HINT_MOUSE_RELATIVE_MODE_WARP, "1", SDL_HINT_OVERRIDE);
SDL_SetRelativeMouseMode(SDL_TRUE);
```

According to my tests the last good (non-crashing) SDL version is 2.28.0 release. With 2.28.1, 2.28.5, 2.29.2, or 2.29.3 I can reproduce the crash in 100% cases. I have only tested the 64-bit releases.

Notes:

1. This was discovered thanks to @codeflorist who created an [issue](https://github.com/dosbox-staging/dosbox-staging/issues/3345) in the DOSBox Staging repository; if you need a real-world program to trigger the crash:
- download DOSBox Staging 0.80.1 (stable) or 0.81.0-rc2 for Windows (I have only checked 64 bit) - https://dosbox-staging.github.io/releases/windows/
- make sure the `SDL2.DLL` in the program directory is one of the affected versions; 0.80.1 was shipped with SDL 2.26.x (which is not affected), we will probably downgrade SDL in 0.81.0 from the current 2.28.5 to workaround the crash
- run the DOSBox, so that it creates a default configuration file
- open the `C:\Users\(username)\AppData\Local\DOSBox\dosbox-staging.conf` file and `set mouse_raw_input = false` (default is `true`)
- run the DOSBox again, click within it's window - depending on your system, it might crash

2. We have tried to reproduce the problem on a few different systems, only some allow to reproduce the problem. The common denominators seems to be:
- fast desktop CPU (in both cases this was a 13th generation Intel)
- Windows 11 - nobody succeeded to reproduce on Windows 10; I have tried with Windows 11 and Linux on the same machine and Linux was unaffected

**Comment by codeflorist** [comment]
> The common denominators seems to be:
> 
> * fast desktop CPU (in both cases this was a 13th generation Intel)
> * Windows 11 - nobody succeeded to reproduce on Windows 10; I have tried with Windows 11 and Linux on the same machine and Linux was unaffected

fast desktop CPU does not seem to be a common denominator, since the crash happens also on my Surface Pro 6.

**BUT i think i just found it:**
the crash only happens (on both my machines), if a dpi scaling of more than 100% is selected in the display settings of windows.

maybe with this it is also reproducable on win 10.

**Comment by weirddan455** [comment]
I was able to reproduce the bug on Windows 10 by setting scaling to 125%.  It's crashing with a stack overflow by what looks like an unbounded recursion.  I bisected the issue to de6963ea998d0ca939c0af9f5e0627b2a239c997 as the first bad commit.  It's a one liner.  Removing that line on the 2.28.x branch fixes the bug.

Funny enough, that commit was intended to fix a bug that was also raised by the DOSBox Staging team:  https://github.com/libsdl-org/SDL/issues/7855

**Comment by weirddan455** [comment]
To expand on what I found debugging, the stack trace goes like:

1. WIN_WarpMouse
2. SDL_SendMouseMotion
3. SDL_PrivateSendMouseMotion
4. Repeat until we run out of stack memory

It appears this is the problematic block of code:

https://github.com/libsdl-org/SDL/blob/release-2.28.x/src/events/SDL_mouse.c#L497-L517

It has logic that looks like "If X and Y are not centered, call `WarpMouse` with centered X and Y".  However, this logic is not expected `WarpMouse` to change X and Y which it does since https://github.com/libsdl-org/SDL/commit/de6963ea998d0ca939c0af9f5e0627b2a239c997 when DPI scaling is enabled.

I'm not familiar enough with this code to know what the proper fix is but hopefully this information is helpful to someone 😄
