### ISSUE TITLE
Autotools support

### ISSUE THREAD

**Issue by serfcity** [libsdl-org/SDL#9226]
Dear developers, could you add GNU Autotools build system again? Can you avoid being forced to install CMake?

**Comment by slouken** [comment]
We don't have any plans to add autotools support to SDL 3.0.

**Comment by serfcity** [comment]
Why? It's very simple Makefile.am file, isn't it?

**Comment by icculus** [comment]
The problem we had in SDL2 (which still uses autotools) is that there was an _enormous_ amount of complexity, and no one really had any expertise in autoconf's scripting language, so maintaining it was a difficulty. It's not just a matter of writing a simple makefile.

CMake has its share of issues too, and the complexity we experience isn't just due to the build system in any case, but we aren't going back to autotools.

**Comment by serfcity** [comment]
CMake is the worst build system for C that I know of. Please don't make users struggle with СMake. As a last resort, let's add a simple `GNUmakefile`.
