### ISSUE TITLE
SDL3 API feedback: please provide a way for the user to allocate buffer for resampling for performance reasons

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#9348]
I previously already gave some feedback on my concern around the larger amount of additional buffer copies for the regular audio playback code path for people who do their own mixing and used the callback interface (since it seems SDL3 will always run an additional SDL3 owned audio stream and/or mixer in between), and my worry about possible performance and latency implications.

In a similar vein I'm also concerned about the new `SDL_ConvertAudioSamples` resampling function:

> Code that used to look like this:
> ```
> SDL_AudioCVT cvt;
>    SDL_BuildAudioCVT(&cvt, src_format, src_channels, src_rate, dst_format, dst_channels, dst_rate);
>    cvt.len = src_len;
>    cvt.buf = (Uint8 *) SDL_malloc(src_len * cvt.len_mult);
>    SDL_memcpy(cvt.buf, src_data, src_len);
>    SDL_ConvertAudio(&cvt);
>    do_something(cvt.buf, cvt.len_cvt);
> ```
>
> should be changed to:
>
> ```
>    Uint8 *dst_data = NULL;
>   int dst_len = 0;
>    const SDL_AudioSpec src_spec = { src_format, src_channels, src_rate };
>    const SDL_AudioSpec dst_spec = { dst_format, dst_channels, dst_rate };
>    if (SDL_ConvertAudioSamples(&src_spec, src_data, src_len, &dst_spec, &dst_data, &dst_len) < 0) {
>        /* error */
>    }
>    do_something(dst_data, dst_len);
>    SDL_free(dst_data);
>  ```
It seems like the expectation is that every SDL3 `SDL_ConvertAudioSamples` invocation will call `malloc()`. However, `malloc()` is very slow. For calling resampling conversions on a whole range of audio data in a tighter loop, this at least looks to me like it could cause disastrous slowdowns. My apologies if I'm wrong or if I'm missing something.

The solution would be if like before, there is some function to let the user handle the buffer like the `src_len * cvt.len_mult` info where it can be preallocated, and if `SDL_ConvertAudioSamples` also will only allocate a buffer if it's not already allocated to a sufficient size. I'm pretty sure only the latter alone isn't be sufficient, since e.g. the app may want to use a stack buffer for smaller sizes which isn't safely possible with this interface either unless the user can safely predict before a call to `SDL_ConvertAudioSamples` whether it will be okay with the passed in buffer size or try to reallocate which for a stack buffer would cause a crash.

I don't think any of these uses including stack buffers are particularly rare, I use all of them in some places in my projects.

**Comment by slouken** [comment]
Adding @icculus for review.

**Comment by slouken** [comment]
Just FYI, this API is not designed to be called in a tight loop. It doesn't handle resampling across call boundaries, so if you're using it like that you'll get audible distortions when converting audio rates.

**Comment by slouken** [comment]
@ell1e, maybe you can explain your use case a bit more and we can provide guidance or understand your use case for this?

**Comment by ell1e** [comment]
Interesting, maybe it should handle it across call boundaries then? I don't think I ever noticed any distortion, but maybe i just didn't pay enough attention.

This is my current use of it: https://codeberg.org/Spew3D/Spew3D/src/commit/8380fe1e023fcab7ec05b2902a522e4568761d5b/implementation/spew3d_audio_resampler.c#L191

The audio chunks are relatively large (about 1 second each) so that's maybe why any sort of occasional click may not be too apparent. This is a streaming API, so I couldn't just run it on the entire file even if I wanted to.

**Comment by slouken** [comment]
You want to use the new SDL API SDL_CreateAudioStream()

**Comment by ell1e** [comment]
Does that one allow resampling without actually using it for the playback? Also forgive my caution, but the audio stream API looks like it might cause a lot more of extra copies again, so maybe that isn't ideal for this kind of use where that might add up. The all-in-one higher-level approach of SDL3 seems to make more granular use more difficult, sadly.

Look at mini audio, which has a resampling interface that seems to avoid this whole "library owns the audio stream" concept that causes all these indirections and takes user buffers like SDL2 used to do for so many things:

> 10.3. Resampling
> ----------------
> Resampling is achieved with the `ma_resampler` object. To create a resampler object, do something
> like the following:
> 
>     ```c
>     ma_resampler_config config = ma_resampler_config_init(
>         ma_format_s16,
>         channels,
>         sampleRateIn,
>         sampleRateOut,
>         ma_resample_algorithm_linear);
> 
>     ma_resampler resampler;
>     ma_result result = ma_resampler_init(&config, &resampler);
>     if (result != MA_SUCCESS) {
>         // An error occurred...
>     }
>     ```
> 
> Do the following to uninitialize the resampler:
> 
>     ```c
>     ma_resampler_uninit(&resampler);
>     ```
> 
> The following example shows how data can be processed
> 
>     ```c
>     ma_uint64 frameCountIn  = 1000;
>     ma_uint64 frameCountOut = 2000;
>     ma_result result = ma_resampler_process_pcm_frames(&resampler, pFramesIn, &frameCountIn, pFramesOut, &frameCountOut);
>     if (result != MA_SUCCESS) {
>         // An error occurred...
>     }

It would be nice if SDL3 kept such direct access API with most notably user-owned buffers around, instead of moving *purely* to this high-level model where it wants to own the stream(s). While I get it's nice as an option, it doesn't seem like the best match as the *only* way to do things.

**Comment by khiner** [comment]
Second this. I've been using miniaudio for my projects, but with a new project I thought I'd try out the SDL3 audio API to avoid pulling in another dependency. In [the migration guide](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_audioh) I see that if you want to run a simple standard audio callback, like a basic sine wave generator, you now allocate and free data _for every buffer frame_ (with `SDL_stack_alloc`/`free`)? I must be missing something since one should never allocate memory on the audio thread, or in any process with hard real-time latency requirements. What is the current recommended way to generate a good old demo sine wave in SDL3?

**Comment by slouken** [comment]
You create an audio stream with the desired src and dst formats and use `SDL_PutAudioStreamData()` to add data in the source format and `SDL_GetAudioStreamData()` to get the converted data. You can look at the other functions if you want to see how much is queued and flush the queue, etc.

**Comment by slouken** [comment]
Anyway, I'll let @icculus comment here, since he's more familiar with the details and might have more information or thoughts.

**Comment by ell1e** [comment]
(For what it's worth, the code I linked isn't running in the audio thread. Nevertheless, notable overhead isn't really desirable for that resampling stream either and I'm just worried with e.g. a dozen decoders running adding in additional copies of all the data for all of them will at some point not be too optimal. But maybe I'm too cautious.)

**Comment by slouken** [comment]
Try it and see? We're not doing continuous allocation in the audio stream, so it might work out fine for your purposes.

**Comment by khiner** [comment]
> You create an audio stream with the desired src and dst formats and use `SDL_PutAudioStreamData()` to add data in the source format and `SDL_GetAudioStreamData()` to get the converted data. You can look at the other functions if you want to see how much is queued and flush the queue, etc.

Thank you, and I suppose my concerns about allocating in each callback is unrelated to this issue, sorry for the noise!

**Comment by icculus** [comment]
My suspicion is that "malloc is very slow" and "one should not call malloc in the audio thread" are wisdom that has been passed down from times when malloc _was_ very slow and the audio thread was a hardware interrupt on a very slow CPU. In modern times, the system should be able to survive this.

The audio streams will expand their buffers as necessary, allocating in chunks, and as data is consumed, it will free chunks if there is too much excess memory allocated...for example, if it suddenly got a large input that trickled out over time.

In theory, it should hit equilibrium very quickly for normal streaming patterns and not allocate or free anything afterwards.

**Comment by ell1e** [comment]
I feel like that's not a great response for more advanced audio applications that do a lot of streams at once or that try to run at extra low latency (e.g. for MIDI keyboards). There is a difference between "maybe it will work fine anyway" and "this is a good idea to add into the API needlessly in a way that nobody can circumvent it anymore". I still hope this is changed one day, especially since this all seems to be a bit of a regression.

I think the best approach would still be to just separate the lowlevel audio and this whole audio streams and mixer idea. In that case, people who want to use this mixer infrastructure can separately invoke it in an audio callback and others can entirely bypass it. Kind of like SDL_Mixer works.

**Comment by 0x1F9F1** [comment]
Audio streams are already quite low level. They only do type conversion and resampling.
I actually did add support for writing data to them without copying it in a while ago, but removed it since it wasn't clear at the time what kind of api it should have.
(See some of the discussion here https://github.com/libsdl-org/SDL/pull/8236)

**Comment by ell1e** [comment]
Well, ideally I wouldn't ever need to write data in/out of them, and e.g. streaming resampling would just work in a user buffer and audio could be supplied directly without an audio stream. Then it doesn't matter how much extra functionality they provide for convenience for those projects which make use of it.

However, I've been considering moving to another audio library anyway. So I get the point of "you're simply not the target audience of SDL audio (anymore)". Nevertheless, I just wanted to let you know this direction doesn't seem ideal for everyone and could be considered a regression. I realize it's not possible to make everything work for everyone.

**Comment by 0x1F9F1** [comment]
You cannot reliably reample audio without keeping track of the resampler state, since you are dealing with partial audio frames.
Barring the current copy made during put (which can be fixed with minimal api/code changes), getting audio data from a stream already tries hard to minimise unnecessary copies https://github.com/libsdl-org/SDL/blob/f14fb979c1077c255a67687f91074a07e4528cd3/src/audio/SDL_audiocvt.c#L848

**Comment by ell1e** [comment]
Well, if you don't have it work on user buffers you already add another roundtrip of 1-2 copies for everything ever coming through by design, just by getting the data into some SDL-owned buffer, and then back into whatever the user actually works on. That's why the entire concept of being required to use SDL-owned audio streams seems suspect to me as the only option, at least if none of the new mixing functionality is ever touched.

**Comment by ell1e** [comment]
Looking at  the code, is `SDL_ResampleAudio` not meant to be used by outside functions? It basically seems to do what I am suggesting. Maybe making that user-facing with some usage example would be the best solution.

**Comment by 0x1F9F1** [comment]
> Well, if you don't have it work on user buffers you already add another roundtrip of 1-2 copies for everything ever coming through by design, just by getting the data into some SDL-owned buffer, and then back into whatever the user actually works on.

I agree that avoiding the copying (or more importantly allocation) during SDL_PutAudioStreamData is a good idea, but beyond that, copying data is often a necessary part of processing it, and just because it's using a stream interface, doesn't mean it is inherently inefficient.

> Looking at the code, is `SDL_ResampleAudio` not meant to be used by outside functions? It basically seems to do what I am suggesting. Maybe making that user-facing with some usage example would be the best solution.

No, because it's not designed to be a general purpose function, and would certainly be used incorrectly.
If you search SDL's closed issues for keywords like audio and resampling, you will find years of reports complaining about things like distortions/clicks when resampling audio, because SDL_AudioCVT (or any stateless API) cannot be used to correctly resample audio. You may not realise it, but your own code also suffers from those same issues.

You've pointed to miniaudio, but that uses a linear audio resampler, which is easy to implement, but doesn't produce particularly high quality audio. I can't claim to fully understand all the nitty-gritty mathematics of audio quality, but SDL's resampler is based on https://ccrma.stanford.edu/~jos/resample/ and basically does a weighted sum of a larger number of frames.

Taking a look at `ma_linear_resampler_process_pcm_frames_s16_upsample`, you will see it is doing multiple loops, branches, copies, function calls, and a division **for each audio frame**. Whilst that keeps the code simple, it is not efficient.

On the other hand, whilst SDL may technically make an extra copy or two compared to miniaudio, it is done so that the actual conversion/resampling code can be as fast as possible, including using SIMD to process multiple frames at once.

This is not to say that I think miniaudio is a bad library (I think it's great), but just to point out the differences in design goals, and that fixating on things such as "how many copies" isn't productive.

**Comment by khiner** [comment]
> My suspicion is that "malloc is very slow" and "one should not call malloc in the audio thread" are wisdom that has been passed down from times when malloc was very slow and the audio thread was a hardware interrupt on a very slow CPU. In modern times, the system should be able to survive this.

One should still not call malloc in the audio thread. I'm always one to reevaluate and question folk wisdom, but this one is an oldie but goodie that still holds. This is because even if it's usually fast in practice, it's highly variable and the worst case risks audible glitches (and all but guarantees them if you wait long enough). At 96kHz, we need a frame every ~0.01ms. Even on modern machines, `malloc` can have a long tail that goes out past 0.1 ms - that's _10x slower_ than what we can afford, assuming just a single audio thread running on a dedicated thread with nothing else going on.

This is why every major audio API is designed to avoid this and other system calls in the audio thread. Even if we ignore the long tail (which we absolutely shouldn't because even very small audio gaps are highly perceptible and a jarring user experience), even the best case `malloc` is way slower than not doing it at all. But also, isn't it just way cooler to design audio systems that _can_ comfortably run on a cpu from 1996 with a spinning disk? Put another way, why design something to be slower than it needs to be?
> "The most amazing achievement of the computer software industry is its continuing cancellation of the steady and staggering gains made by the computer hardware industry." - Henry Peteroski

I'm putting this out there with a cheeky wink - audio APIs are sacred things that are still largely exempt from this classic quote, and I don't want to live in a world where the games I play run an audio API that casually allocates buffer memory on the audio thread because it seems usually fine on modern hardware.

I really appreciate the innovations in the new API - _love_ the example application and the demo video you provided! I'll be using miniaudio for now while the API gets ironed out, documented more, etc. But I hope the final version ends up with this convenience _and_ provides solid worst-case/tail-end performance by default as well. Thanks for your hard work!

**Comment by 0x1F9F1** [comment]
After this week I should have some free time again so I can take a look at re-adding user-owned buffers, and maybe the ARM SIMD code.

**Comment by icculus** [comment]
> re-adding user-owned buffers

Is this reasonable to implement in a system where the device can change formats without warning? The risk of calling malloc--even if it causes a skip--is way better than the entire system falling over because a static buffer is suddenly too small.

Maybe a "here's a gigantic buffer I preallocated, and I promise not to send a large chunk of data down the stream ahead of time" can work, but I'm hesitant to complicate the public API over this.

The better win might be to simply be less aggressive about freeing consumed chunks in the audio queue so the system can still expand if needed but there's even less chance of allocating additional memory. But I'm not really convinced we should do anything here.

> maybe the ARM SIMD code

This I would unconditionally love, though.  :)

**Comment by 0x1F9F1** [comment]
> > re-adding user-owned buffers
> 
> Is this reasonable to implement in a system where the device can change formats without warning? The risk of calling malloc--even if it causes a skip--is way better than the entire system falling over because a static buffer is suddenly too small.

I mean just that the user passes in a buffer with their audio data, and a callback to free/discard/reuse/etc. it, rather than allocating and copying into our own buffer.

> The better win might be to simply be less aggressive about freeing consumed chunks in the audio queue so the system can still expand if needed but there's even less chance of allocating additional memory. But I'm not really convinced we should do anything here.

I'd be happy to take a look at the adjusting the free chunks limit, but then you don't really want each stream hogging lots of unused memory, plus then you are just delaying having to free even more memory all at once (but hopefully not on the audio thread).

**Comment by slouken** [comment]
> > > re-adding user-owned buffers
> > 
> > 
> > Is this reasonable to implement in a system where the device can change formats without warning? The risk of calling malloc--even if it causes a skip--is way better than the entire system falling over because a static buffer is suddenly too small.
> 
> I mean just that the user passes in a buffer with their audio data, and a callback to free/discard/reuse/etc. it, rather than allocating and copying into our own buffer.

There's going to be a copy somewhere in the pipeline anyway, if nothing else than copying from the original source data into the user buffers. The current API allows the application to skip that and pass source data directly into the stream.

**Comment by ell1e** [comment]
>       Is this reasonable to implement in a system where the device can change formats without warning?

I think the difference is when the audio device changes formats, which I assume means the speaker or something was changed, the user will expect and tolerate glitches. But when a random `malloc()` hits at some timewhere some buffer happened due to some tiny timing thing end up getting resized out of the blue (which is very avoidable with user controlled buffers, and in my experience harder to avoid with opaque library owned buffers) that's much less so the case.

Nevertheless, I still am of the opinion that audio streams and the SDL mixer are fine to work this way. But that at least, it would be nice if there was a way to just do the old audio callback but without involving streams, for people who wish to use SDL's wide device compatibility but to avoid the lower latency higher feature set mixer (which is a fair trade-off, really). Is that currently possible? I've read conflicting comments on this, and the example I saw that just copies it into an audio stream by SDL instead doesn't seem like it bypasses the whole malloc() and extra copies issue to me but maybe I'm missing something.

And it would be nice to have proper streamed resampling on user-owned buffers as well. I also think having a function for that which is relatively hard to use and e.g. requires me to do a manual float32 conversion would be fine, if it's documented well. I don't think letting the user do the format conversion manually in that case is necessarily bad, it has the benefit of making it obvious depending on how the pipeline is set up this will simply be slow.

I think most people willing to avoid malloc()'s on the audio thread will be willing to write their own mixing if needed.

**Comment by slouken** [comment]
> But I'm not really convinced we should do anything here.

Agreed. You can use `SDL_SetMemoryFunctions()` to track memory allocations and if you find that SDL is doing periodic allocations beyond the initial stream setup, that would be a bug. There shouldn't be any allocations happening in steady state conversion.

> > maybe the ARM SIMD code
> 
> This I would unconditionally love, though. :)

Same, this would be a great upgrade for applications already using this API.

**Comment by slouken** [comment]
Again, I suggest, try it and see, and if you're seeing problems, let us know!

**Comment by ell1e** [comment]
> Again, I suggest, try it and see, and if you're seeing problems, let us know!

Well the problem is if I don't understand when the allocations happen or if they can be avoided, I can't know if a test on my system with my audio card at my tested latency will still work like that for somebody else. I mean I realize that's always the case anyway, given different CPU speeds, but if you throw in unexpected opaque malloc() in the mix it just gets even worse. I think what most people will do in response is either 1. use a library that avoids malloc() if they care, or 2. use a relatively high latency (which is more acceptable in games than something like a DAW) if they don't care.

As stated above I guess for a game focused library that is fair, what I'm mainly lamenting is for non-game uses this seems like a regression. While the whole "maybe stop caring unless it really breaks badly for you" angle is fair, it doesn't really change this just makes some uses of SDL audio unattractive when previously they weren't as much.

**Comment by slouken** [comment]
> > Again, I suggest, try it and see, and if you're seeing problems, let us know!
> 
> Well the problem is if I don't understand when the allocations happen or if they can be avoided, I can't know if a test on my system with my audio card at my tested latency will still work like that for somebody else. I mean I realize that's always the case anyway, given different CPU speeds, but if you throw in unexpected opaque malloc() in the mix it just gets even worse. I think what most people will do in response is either 1. use a library that avoids malloc() if they care, or 2. use a relatively high latency (which is more acceptable in games than something like a DAW) if they don't care.
> 
> As stated above I guess for a game focused library that is fair, what I'm mainly lamenting is for non-game uses this seems like a regression. While the whole "maybe stop caring unless it really breaks badly for you" angle is fair, it doesn't really change this just makes some uses of SDL audio unattractive when previously they weren't as much.
> 
> It would probably be useful to acknowledge that, even if it doesn't end up being fixed.

Right, and what I'm saying is that memory allocation shouldn't be happening in your use case (after the initial setup), so if you're seeing that, please let me know!

It's not a matter of allocation is fast on most systems, it's that allocation shouldn't be happening, which is better in all cases.

But, we won't know for sure unless you actually try it, or provide a test case that matches your use case.

**Comment by slouken** [comment]
BTW @ell1e, I am hearing your feedback.

@0x1F9F1, some other APIs have a context that stores the window of samples needed between audio chunks and that gets passed to a function that does the actual format conversion and resampling. Do we have something like that at the core of the audiostream that makes sense to expose?

**Comment by 0x1F9F1** [comment]
> @0x1F9F1, some other APIs have a context that stores the window of samples needed between audio chunks and that gets passed to a function that does the actual format conversion and resampling. Do we have something like that at the core of the audiostream that makes sense to expose?

That basically **is** the core of audiostream. To be fair, audiostream may benefit from some more refactoring so that there is a more clear separation between conversion and resampling, and creating a resampler class could be a part of that, but I don't think exposing those APIs would be a good idea.
I could probably eliminate some additional copying, but I'm not sure if it would overly complicate the code.

**Comment by slouken** [comment]
> > @0x1F9F1, some other APIs have a context that stores the window of samples needed between audio chunks and that gets passed to a function that does the actual format conversion and resampling. Do we have something like that at the core of the audiostream that makes sense to expose?
> 
> That basically **is** the core of audiostream. To be fair, audiostream may benefit from some more refactoring so that there is a more clear separation between conversion and resampling, and creating a resampler class could be a part of that, but I don't think exposing those APIs would be a good idea. I could probably eliminate some additional copying, but I'm not sure if it would overly complicate the code.

*nod* makes sense

**Comment by ell1e** [comment]
For what it's worth since I was just thinking about this again, in my own audio lib when a malloc() is needed it happens outside of the audio thread and the audio thread if in doubt just plays silence until that's sorted out. Maybe SDL3 should consider moving to that model? Because in my experience once a glitch happens, sometimes audio APIs get "stuck" and remain glitchy from then on instead of properly catching up, although with modern sound backends maybe this is less of an issue than it used to be. I can't really tell, I just wanted to bring it up in case it's useful in this discussion.
