### ISSUE TITLE
Ability to read/write a file in chunks with storage APi

### ISSUE THREAD

**Issue by ilyachastikov** [libsdl-org/SDL#9404]
For this moment Storage API makes it possible to read/write only the entire file. But ability to read/write a file in chunks may be useful in many situations.

**Comment by icculus** [comment]
I think there were explicit reasons (cloud APIs, consoles, etc) we avoided that. @flibitijibibo could explain in more detail if that needs clarification.

There _is_ an SDL_IOStream that will write to a growing memory buffer, though, which still needs the RAM but can manage assembling chunks on behalf of the app.

**Comment by flibitijibibo** [comment]
Basically the reason we can't do partial reads is because containers expect the "streaming" part to be less streaming from the disk and more via the use of async I/O - I'd have to look at what consoles expose but there may be a way to request an offset and size with the file name, but it's definitely _not_ like FILE* - the closest _public_ example I can point to is ISteamRemoteStorage.

**Comment by ilyachastikov** [comment]
Thanks for clarification.
