### ISSUE TITLE
Audio system preference is broken in flatpak

### ISSUE THREAD

**Issue by swick** [libsdl-org/SDL#9543]
With https://github.com/libsdl-org/SDL/pull/9473 pw is supposed to preferred over pa. It checks if a specific systemd unit is running. This is broken in a lot of environments, including flatpak which is arguably the most common environment SDL will run in.

The name of services is not stable, access to the session bus is restricted. This change is overall just a really bad idea and SDL_DBus_QuerySystemdUnitRunning should be thrown away.

Checking for the pipewire socket should be much more robust and give you the same behavior. Usually if the pipewire socket exists, the pulse socket also comes from pipewire.

**Comment by icculus** [comment]
I don't think Flatpak is the most common environment, [at least at this moment in time](https://store.steampowered.com/), but without getting into that further, this issue is still valid.

The reason we didn't just try using Pipewire, with a fallback to PulseAudio, was because of this comment in #9473, afaik:

> Simply checking for sinks/sources won't work, as Pipewire can still be used to mix audio and lists sinks/sources, even if the system is also running the real Pulseaudio server.

And I guess the question here is: is this really a practical configuration? Where someone is running Pipewire but it is not the way they want to access audio hardware? And while this _can_ in theory happen, are these people not running something custom enough that we should just tell them to `export SDL_AUDIO_DRIVER=pulseaudio`?

That seems more reasonable than breaking flatpak, but it's possible I don't have the full picture here.

**Comment by Kontrabant** [comment]
> And I guess the question here is: is this really a practical configuration? Where someone is running Pipewire but it is not the way they want to access audio hardware? And while this _can_ in theory happen, are these people not running something custom enough that we should just tell them to `export SDL_AUDIO_DRIVER=pulseaudio`?

Basically old versions where Pipewire audio was still in its infancy, only found in LTS distros at this point. Given that this doesn't work with Flatpak, I still think that we could default to Pipewire as long as a sufficiently new version is present (probably 1.0 for safety), as there really isn't any compelling reason to swap back to Pulseaudio anymore (or is there?), and as far as I can tell, any newer distros have switched over the Pipewire at this point.

Worst case scenario, someone's weird setup may end up with Pipewire playing through a Pulseaudio sink, which isn't ideal, but they'll still hear something, and, like you said, if they're hacking up their audio system, they can just do `SDL_AUDIO_DRIVER=pulseaudio` to force it, like they already have to do if they want ALSA or JACK instead.

**Comment by swick** [comment]
FWIW, we're currently looking into exposing pipewire by default in flatpak.

**Comment by flibitijibibo** [comment]
It would be interesting to know if there exists any distribution that adopted PW but _didn't_ opt to use if for audio, let alone anything else...

From what I recall Flatpak has a mechanism to prioritize Wayland above X11 even given SDL2's priority list, is it possible to have a mechanism for PW v. Pulse? That would at least patch up that specific target, which I agree is an important target.

**Comment by flibitijibibo** [comment]
> FWIW, we're currently looking into exposing pipewire by default in flatpak.

Understood, ignore that part of my previous post!

**Comment by icculus** [comment]
Okay, so we're going to pull the test out and just try PipeWire first (and Pulse will be something it will fall back to naturally if PW doesn't work out), right?

I believe all that's necessary here then is a "git revert 60f26182c3a44544f78c1569906fdf58d1d69374"

**Comment by Kontrabant** [comment]
Or something like this: https://github.com/libsdl-org/SDL/commit/e65dabafe53556b19c5a3720c66c1a80ac3d6823

It only tries Pipewire first if the underlying version is high enough (currently 1.0, but open to suggestions), otherwise it falls back to Pulse. This should handle LTS distros that were/are still shipping Pulse.

**Comment by Akaricchi** [comment]
Is there a real benefit in preferring pipewire in the first place? [The FAQ still recommends using the pulseaudio API](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#what-audio-api-do-you-recommend-to-use):

> We recommend that you continue to use PulseAudio, JACK and ALSA API's for now.

**Comment by icculus** [comment]
Surely that FAQ is out of date, though...? I'll ping Wim and ask. Assuming it is out of date, I'm fine with the check-for-1.0 patch, if everyone here is in agreement.

**Comment by Kontrabant** [comment]
I think that was mainly to reassure people that "no, you won't have to rewrite everything for Pipewire, and it won't break your existing software".

As for the 'why 'issue, there is at least one example where bypassing the compatibility layer fixes a real bug for an SDL user, and, looking into the ongoing Flatpak discussions, it seems like using Pipewire natively will be preferred in containers going forward.

Just to note, I did a bit more investigating with some distros that I had concerns about:

- Selecting the KDE desktop on Debian 12 does install Pulseaudio by default, with Pipewire not being installed at all, but installing Pipewire via apt-get automatically disables it and replaces it with pipewire-pulse. Debian 12 ships Pipewire 0.3.65, but 1.0+ is available if users opt-in to backports.
- Manjaro defaults to Pipewire 1.0.3, and trying to install Pulseaudio seems to require removing the whole Pipewire meta-package, so it's all-or-nothing.

It seems to be safe to assume that anything using a modern Pipewire version is using it for audio, as trying to do otherwise requires intentionally hacking things up, and if people want to do that, it's also fair to say that they are on their own.

**Comment by nanonyme** [comment]
> FWIW, we're currently looking into exposing pipewire by default in flatpak.

Is there some ticket about this? Asking out of curiosity.

**Comment by icculus** [comment]
Okay, @Kontrabant took care of this, so the systemd check and such are gone.

PLEASE NOTE that we might tweak this further if we find out the 1.0.0 version check isn't sufficient, but the Flatpak concerns should be resolved now no matter what.

**Comment by Erick555** [comment]
Note that in case of containers like flatpak the pipewire client library may have totally different version than what pipewire server is running. For example all flatpak runtimes have version [below 1.0](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/23.08/elements/components/pipewire-base.bst#L130) currently and it won't change in few months.

I'm not sure which pipewire part version do you check, I assume it's client library.

**Comment by Kontrabant** [comment]
Good point. Yes, we've been checking the client library version, but we should use the core version for this check instead, as that's what we really care about here.
