### ISSUE TITLE
Prefer floats in SDL_ClosestAudioFormats

### ISSUE THREAD

**Issue by 0x1F9F1** [libsdl-org/SDL#9581]
Currently the format_list prefers using integer types, before using floats.
Should it more aggresively prefer floats, given that's what all the mixing/resampling/conversions are done with?

**Comment by icculus** [comment]
Most of the backend APIs either accept float or prefer it, so moving that first is probably good, as we're likely going to be working in floats no matter what the app or the backend wants.

OpenSLES needs to be fixed real quick, because it doesn't handle float at all but only checks if the data format is signed:

https://github.com/libsdl-org/SDL/blob/fb4c15319ec61d963975b47dd1ec21fae184bc04/src/audio/openslES/SDL_openslES.c#L435-L440

All the rest look okay.

**Comment by icculus** [comment]
> OpenSLES needs to be fixed real quick

This isn't true after all, it handles it correctly outside that code snippet.
