### ISSUE TITLE
readme-macosx extremely outdated

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#960]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Mac OS X (All), All

# Comments on the original bug report:

On 2013-07-13 02:26:57 +0000, Alex Szpakowski wrote:

> The readme file for Mac OS X is extremely outdated - it references Mac OS 10.2 (not officially supported), 10.4 (not officially supported), PowerPC (not officially supported), Stuffit (ah, memories), nonexistant files, etc, etc etc... I think it might need to be almost completely rewritten.

On 2013-07-13 02:55:19 +0000, Sam Lantinga wrote:

> Yup, that's really crufty, thanks for pointing that out.  Do you feel comfortable updating it with correct information?

On 2014-07-12 00:57:27 +0000, Robotic-Brain wrote:

> I think this can be closed since the readme has been updated since?

On 2014-07-12 01:10:01 +0000, Alex Szpakowski wrote:

> It's definitely more up-to-date now, but it still has references to really old concepts like Stuffit, an Xcode.tar.gz archive, SDLmain.m, etc.

On 2015-02-19 05:22:18 +0000, Ryan C. Gordon wrote:

> 
> Marking a large number of bugs with the "triage-2.0.4" keyword at once. Sorry if you got a lot of email from this. This is to help me sort through some bugs in regards to a 2.0.4 release. We may or may not fix this bug for 2.0.4, though!

**Comment by icculus** [comment]
We'll give this a looking-at for 2.0.18.

**Comment by icculus** [comment]
Took a swing at this; almost done, but need to rename this to README-macos.md still (dropping the 'x'), and need to actually walk through this on Xcode, because this probably isn't correct anymore:

## Setting up a new project by hand

Some of you won't want to use the Stationary so I'll give some tips:

* Create a new "Cocoa Application"
* Remove "main.c" from your project
* Remove "MainMenu.nib" from your project
* Add "$(HOME)/Library/Frameworks/SDL.framework/Headers" to include path
* Add "$(HOME)/Library/Frameworks" to the frameworks search path
* Add "-framework SDL -framework Foundation -framework AppKit" to "OTHER_LDFLAGS"
* Set the "Main Nib File" under "Application Settings" to "SDLMain.nib"
* Add your files
* Clean and build

**Comment by icculus** [comment]
This got renamed to README-macos.md in https://github.com/libsdl-org/SDL/commit/193ab28fe431b12c37bf67599a344b9b0e19b2bc, still need to check the "new project by hand" instructions on modern Xcode.
