### ISSUE TITLE
audio: rename "capture" devices?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#9619]
I haven't decided if we should actually do this, but I'd maybe like to rename "capture" devices to "recording" or "input" or something.

In case I decide to, I'm just leaving this here in the 3.2.0 milestone so I remember to pull the trigger before it's too late.

**Comment by icculus** [comment]
(Also of note, there's a generous amount of waffling between calling the other direction "output" and "playback" devices...)

**Comment by 1bsyl** [comment]
Input/output are too generic, that would also refer to hdmi / jack / vga hardware audio/video, or joystick. 

Since the video part is named camera, that should be consistent to call it microphone I guess.
If this is named recording, then it would make sense to have the camera api named also recording.

**Comment by slouken** [comment]
Without thinking deeply, my immediate expectation is audio "recording" and "playback". Same with camera "recording"

**Comment by flibitijibibo** [comment]
Agree with "recording/playback", input/output and source/destination can start to mean different things when you get into stuff like mix graphs (XAudio2's terminology is the main example that comes to mind for me).

**Comment by icculus** [comment]
Okay, this is done, sdl2-compat is updated and sdlwiki has the old symbols removed.
