### ISSUE TITLE
Open and Save dialogs don't work on Windows 11

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9630]
Running testdialog, the Open and Save dialog buttons show the error message:
INFO: Error: Windows error, CommDlgExtendedError: 12290

@Semphriss, can you take a look?

**Comment by Semphriss** [comment]
I'll give it a look whenever I can :+1: 

As a starting point, the error code (0x3002) is `FNERR_INVALIDFILENAME` according to [this doc page](https://learn.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-commdlgextendederror).

---

While that's on the table, I remember there were three ways to handle file dialogs on Windows: the modern way (IFileDialog) and a legacy way. I had only implemented the legacy way for maximum compatibility.

It's probably just a minor bug, but in case the problem is "not solvable" for some reason, the modern methods can act as an alternative.
