### ISSUE TITLE
[Android] Overriding `createSDLMainRunnable()` skips important SDL (de)initialisation code

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#9652]
The documentation mentions that `createSDLMainRunnable()` can be overridden. This is most useful when using SDL with non C/C++ applications (eg. C#), as the default SDLMain assumes the main can be loaded from a shared object.

https://github.com/libsdl-org/SDL/blob/8b06473a11484ddc8e27484f879837bdf54d450e/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L243-L250

Here's the code for SDLMain. It's simply doing too much, it should really only be calling `SDLActivity.nativeRunMain()`.
I'd consider that setting the thread priority and finishing logic is important (de)initialisation logic that should never be skipped, even if a custom main is provided.

https://github.com/libsdl-org/SDL/blob/8b06473a11484ddc8e27484f879837bdf54d450e/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L1946-L1974

`nativeRunMain()` is also doing too much, setting the hint callback and the `Android_JNI_SetEnv` being important (de)initialisation code.

https://github.com/libsdl-org/SDL/blob/8b06473a11484ddc8e27484f879837bdf54d450e/src/core/android/SDL_android.c#L777-L873

I might have an idea on how to fix this.

---

In my C# application, I'm overriding `createSDLMainRunnable()` to run the standard SDL event loop (like you would on a desktop platform). This skips important logic and an immediately visible side effect is that the hint `SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY` doesn't work.

**Comment by Perksey** [comment]
Definitely watching this, I'm interesting in calling `SDL_EnterAppMainCallbacks` from within a runnable implemented in C# (which has its own built-in Java interoperability) for Silk.NET. Looks like we have the same use case!

**Comment by Perksey** [comment]
I'd like to discuss resolving this. I'm happy to contribute as I'm very dependent on this for Silk.NET. We've tried looking into workarounds but I don't believe there's a way we can trick SDL into handing back off to the calling library primarily because of how .NET handles its exports on Android.

There are a number of solutions we could do here.
1. **Most Backwards Compatible, but Most Ugly**: if `library` is a null or empty string, instead of using `dlopen` we call a new JNI function `nativeCallMain`. `nativeCallMain` will then... call main... The reason this is ugly is that this is pretty obvious behaviour and adds another JNI function.
2. **Move libmain Loading to Java**: Java will load the library and retrieve the exported function, and call it using `NativeSymbol`. Initialisation logic in `nativeRunMain` is moved to `SDL_EnterAppMainCallbacks` on the Android platform. This is obviously breaking as we're removing that JNI function, hopefully we don't care as it's pre-3.2.0? This is my most preferred solution. 
3. Maybe I'll think of more...

I just want to get the green light from someone before working on this, as I don't know what the stance is wrt the JNI interface's back compatibility.

**Comment by slouken** [comment]
In SDL 3.0, we have the flexibility to change this however makes sense. @1bsyl might have ideas on which solution is best?

**Comment by slouken** [comment]
@Susko3, can you provide a PR that adjusts the functionality to match your use case?

**Comment by Susko3** [comment]
> @Susko3, can you provide a PR that adjusts the functionality to match your use case?

Sure, I've created https://github.com/libsdl-org/SDL/pull/10434. It fixes the issue with minimal changes.
