### ISSUE TITLE
Rename SDL_UpdateTexture to SDL_UpdateRGBTexture and use SDL_Surface

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL#9777]
people has always issues using SDL_UpdateTexture with correct format and pitch.
I suggest, we rename SDL_UpdateTexture to SDL_Update**RGB**Texture, since we have the YUV and NV versions.

and makes SDL_UpdateTexture use SDL_Surface has a parameter, allowing to handle anything and hiding the burden of using the variables / pitch depending on the format)

**Comment by slouken** [comment]
SDL_UpdateTexture() works with YUV and NV12 data as long as they are tightly packed. The YUV and NV versions are only needed if you have non-packed data.

Many times the data is coming from other APIs and we shouldn't require the application to create an intermediate surface for SDL_UpdateTexture(), especially since this is often critical path for performance.

**Comment by slouken** [comment]
If you want, we could add SDL_UpdateTextureFromSurface(), which would just be a quick wrapper around SDL_UpdateTexture()
